the-blue-alliance/the-blue-alliance

templates/index_buildseason.html

Per the [official FRC competition manual page](http://www.usfirst.org/roboticsprograms/frc/competition-manual-and-related-documents).

index: Update game manual link

---

tests/test_offseason_matches_parser.py

Fix class name for TestOffseasonMatchesParser.

---

consts/notification_type.py

Fix errors with schedule updated notifications

---

controllers/account_controller.py
helpers/notification_helper.py
helpers/push_helper.py
models/subscription.py
templates/mytba.html

Add the UI for subscribing to all events within a year. Uses underlying keys like ```2015*```

Subscription Firehose

---

templates/index_buildseason.html

The old one got marked private, here's a new link

Fix Broken Homepage Video

---

helpers/notification_helper.py

Original code had a few errors. This should fix them.

Fix Admin Broadcasts

---

helpers/match_manipulator.py
helpers/notification_helper.py
models/match.py
notifications/alliance_selections.py
notifications/awards_updated.py
notifications/base_notification.py
notifications/broadcast.py
notifications/district_points_updated.py
notifications/level_starting.py
notifications/match_score.py
notifications/ping.py
notifications/schedule_updated.py
notifications/upcoming_match.py
notifications/update_favorites.py
notifications/update_subscriptions.py
notifications/verification.py

This should fix a few of the things we came across this week

W1 Notification Fixes

---

notifications/broadcast.py

This should get posted by everything that can support it, if you don't specify a version number

Global Broadcasts!

---

helpers/mytba_helper.py

This is a redundant check and prevents mytba updated notifications from going out when managed from web

Remove unnecessary device_key check

---

controllers/test_notification_controller.py
notifications/base_notification.py

Don't push to firebase and don't analytics track

Webhook Docs Notification Fixes

---

helpers/notification_helper.py

Tries to send out for events ahead of schedule

Improve upcoming match notifications

---

controllers/admin/admin_event_controller.py
helpers/event_manipulator.py
models/event.py
templates/admin/event_create.html
templates/admin/event_details.html
templates/admin/event_edit.html
templates/event_details.html

Created a new field to allow events to have custom hashtags.

Add Custom Hashtag to Event

---

api_main.py
controllers/api/api_team_controller.py
helpers/cache_clearer.py
templates/apidocs.html

Fetch all the awards/events from a team's history
These two endpoints include all you need to build the team history page
Closes #1154

API Team Awards

---

helpers/district_helper.py

fix for the inverf(x) function

District inverf(x) fix

---

controllers/api/api_trusted_controller.py
static/javascript/tba_js/eventwizard.js
static/javascript/tba_js/eventwizard_apiwrite.js
templates/eventwizard.html

This fixes the bugs I found running the Event Wizard last weekend at CTSC. It also makes some minor improvements.

Event Wizard Updates

---

admin_main.py
controllers/admin/admin_offseason_spreadsheet_controller.py
datafeeds/datafeed_offseason_spreadsheet.py
datafeeds/google_sheets_datafeed_base.py
datafeeds/parsers/csv/offseason_spreadsheet_parser.py
helpers/url_opener.py
templates/admin/base.html
templates/admin/offseasons_spreadsheet.html

Can import offseason events from https://docs.google.com/spreadsheet/ccc?key=0ApfHZGrvPfuAdHVZcTczVnhQVnh1RlNEdVFmM2c3Y1E&usp=sharing#gid=4
Haven't figured out how to do duplicate declarations yet. Maybe it isn't possible without another unique ID, like FIRST EID?
Closes #1205

Import Offseason Events From Google Spreadsheet

---

controllers/api/api_trusted_controller.py
static/javascript/tba_js/eventwizard.js
static/javascript/tba_js/eventwizard_apiwrite.js

Input YT Key along with score
Closes #1213

YT Videos from EventWizard

---

tests/test_api_trusted.py

Situation introduced in 072058b64f18375f0be319d0d1e6b474b13592d6 where we don't add EventTeams via trustedapi if they don't already exist in the database. In the tests, make sure that we test with all relevent teams added. Also added a test case where we try and add some teams not already in the db and verify they don't get added.

Fix failing trustedapi tests

---

static/javascript/tba_js/eventwizard.js
static/javascript/tba_js/eventwizard_apiwrite.js
templates/eventwizard.html

Import data using the same ajax data that Pit Display uses. Can't be tested, because I don't have FMS

EventWizard import Ranks from FMS server

---

api_main.py
controllers/api/api_team_controller.py
database/robot_query.py
helpers/model_to_dict.py
templates/apidocs.html
tests/test_apiv2_team_controller.py

Still needs query cache clearing

Add team history robots apiv2 endpoint

---

tests/test_datafeed_usfirst_legacy_events.py

Fixes one test failure due to changed data on FIRST's site. Towards #1274

Fix test based on new data from FIRST.

---

tests/test_datafeed_usfirst_events.py

Skip broken tests.

---

datafeeds/datafeed_fms_api.py
helpers/notification_helper.py

Based off #1257 
Working towards #1256 
Basic ways to determine if an individual event is down (e.g. not reporting data because FMS has no internet) or if the entire FMSAPI is down (throwing 5XX errors).
How does the base look?

[RFC] Determine Event Status

---

cron_main.py
datafeeds/datafeed_fms_api.py

Little things that slipped through - fixes an import error (for a class that doesn't exist) and a type error
I don't think we can update `cron.yaml` yet because FIRST doesn't have 2016 events up on the API yet (argh), so let's roll with what we have until they fix that.

Minor FMSAPI bugfixes

---

helpers/notification_helper.py

Dump down event keys to json string

---

admin_main.py
api_main.py
controllers/admin/admin_apistatus_controller.py
controllers/admin/admin_sitevar_controller.py
controllers/api/api_status_controller.py
datafeeds/datafeed_fms_api.py
helpers/notification_helper.py
templates/admin/apistatus.html
templates/admin/base.html

Implementation for https://github.com/the-blue-alliance/the-blue-alliance/issues/1256
Closes #1256

Api Status

---

.gitignore
controllers/api/api_team_controller.py
helpers/model_to_dict.py
templates/apidocs.html
tests/test_apiv2_team_controller.py

add team motto to team model in API

add team motto to team model

---

consts/account_permissions.py
controllers/account_controller.py
controllers/admin/admin_user_controller.py
templates/admin/user_details.html
templates/admin/user_edit.html

Commandeers #757 and makes a few changes to simplify things for an initial implementation of permissions.
My current plan is to leave the "admin panel" requiring appengine admin, and move other functions out into other paths that aren't the admin panel. This will allow a piecewise conversion of functionality.

Permissions

---

consts/account_permissions.py
controllers/account_controller.py
controllers/admin/admin_user_controller.py
models/account.py
templates/admin/user_details.html
templates/admin/user_edit.html

This adds permissions to the user model, and allows admins to view and edit them. There are no callsites for it in the code yet, but I'll be implementing them soon and wanted to get in the minimum diff fast. There also aren't methods for permission checks at the moment, but I think they'll go in user bundle - I couldn't decide so I didn't implement it yet.

RFC Add basic permissions support

---

controllers/admin/admin_user_controller.py

Fixes clowny bug with editing permissions.

---

templates/admin/send_broadcast.html

Make clear that it's a version code, not a version string

Clarify admin broadcast min version

---

templates/district_details.html

More similar pull requests to come :'(

Unbreak district points ranking system URLs

---

admin_main.py
controllers/admin/admin_suggestion_controller.py
helpers/suggestions/suggestion_test_creator.py
templates/admin/index.html

Test plan:
- Create test teams, test events.
- Create test suggestions, verify counts on /admin/ go up.
- Give test user MODIFY_DATA permission.
- Visit suggestion approval pages, verify well formed suggestions.

Allow creating test suggestions to speed up development.

---

controllers/suggestions/suggest_team_media_controller.py
helpers/suggestions/suggestion_creator.py
helpers/suggestions/suggestion_test_creator.py
templates/suggest_team_media.html

Fixes #1349 
Test Plan:
- Create test teams, test events.
- Create test suggestions, verify one of each type is created on admin page by seeing counts.
- Create team media suggestion manually, verify suggestion is made.

Refactor TeamMediaSuggestion creation to be handled commonly.

---

templates/apidocs.html

Created a first run at the API Library list. I don’t have a running copy of TBA yet, so I’m running a little blind. However, this should be fairly trivial. Feel free to clean up anything I’m missing.
Closes #1315

Add API Library list to /apidocs

---

pavement.py

This makes indentation 4 spaces and converts all strings to be double quoted.

pavement: Reformat file

---

consts/media_type.py
controllers/suggestions/suggest_team_media_review_controller.py
helpers/media_helper.py
mobile_main.py
models/media.py
models/mobile_api_messages.py
renderers/team_renderer.py
templates/media_partials/image_carousel_partial.html
templates/media_partials/imgur_partial.html
templates/suggest_team_media.html
templates/suggest_team_media_review_list.html
templates/team_details.html
templates/team_partials/team_info.html
templates_jinja2/media_partials/image_carousel_partial.html
templates_jinja2/media_partials/imgur_partial.html
templates_jinja2/team_details.html
templates_jinja2/team_partials/team_info.html
tests/test_media_url_parse.py

This is the server side component for #1362
This PR basically takes all the changes from #976 and condenses them into one commit. It allows imgur suggestions everywhere, just doesn't list it as an option on the suggest page.
Closes #1362
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/the-blue-alliance/the-blue-alliance/1367)

Allow Team Media Suggestions via Cloud Endpoints

---

controllers/suggestions/suggest_team_media_review_controller.py
mobile_main.py
models/media.py
templates/suggest_team_media_review_list.html

We don't want that to be available in the API...
Adds private_json field in Media

Breakout deletehash out from mobile API suggestion

---

common/my_filters.py
controllers/match_controller.py
templates/match_partials/match_breakdown_2016.html

See http://tba.lopreiato.me/match/2016scmb_qm3 as an example

Add 2016 score breakdown

---

admin_main.py
controllers/admin/admin_user_controller.py
templates/admin/index.html

Now that accepting suggestions requires a permission, this makes things much easier.

Button for test environments to give current user all permissions

---

admin_main.py
controllers/admin/admin_user_controller.py
templates/admin/index.html
templates/base.html
templates/index_lhc.html

Moves vexPRO logo higher on home page.
Before
After

Home sidebar

---

admin_main.py
controllers/admin/admin_media_controller.py
helpers/media_manipulator.py
templates/admin/partials/admin_media_display.html
templates/admin/team_details.html

Twice recently I've been asked to delete Medias. This allows it in the admin interface.

Allow deleting references to Media. Fixes #1370

---

controllers/event_controller.py
controllers/suggestions/suggest_team_media_review_controller.py
database/media_query.py
helpers/media_manipulator.py
models/media.py
renderers/team_renderer.py
templates/admin/partials/admin_media_display.html
templates/suggest_team_media_review_list.html
templates_jinja2/media_partials/image_thumbnail_partial.html
templates_jinja2/suggest_team_media_review_list.html
templates_jinja2/team_partials/team_info.html

I stayed up watching (AlphaGo SPOILERS!!!) AlphaGo beat Lee Sedol so I worked on this...
Please play around with it and make sure it behaves as expected. The UI should be intuitive enough.
There are ugly indicators on the Admin Team page to show if a Media is preferred. We can turn those into "remove" buttons later or something.
Some screenshots.

Preferred media. Fixes #1401

---

controllers/suggestions/suggest_event_webcast_controller.py
controllers/suggestions/suggest_event_webcast_review_controller.py
controllers/suggestions/suggest_match_video_controller.py
helpers/suggestions/suggestion_creator.py
helpers/webcast_helper.py
models/suggestion.py
templates/suggest_event_webcast_review_list.html
templates_jinja2/suggest_event_webcast.html

Automatically determines channel/file for popular webcast links (Twitch, YouTube, Ustream, Livestream). If it fails, falls back to current behavior.
This should make accepting webcasts that much easier :smile:

Auto generate webcasts from sugestion url if possible

---

controllers/suggestions/suggest_event_webcast_controller.py
templates_jinja2/suggest_event_webcast.html

Disallows submitted urls with spaces and also TBA urls. I see these kind
of invalid url submitted in the queue pretty often

Add simple webcast url validation

---

templates_jinja2/suggest_match_video_playlist.html

Also accept videos that have QM<X> for qual matches

Update "magic" playlist regex

---

controllers/account_controller.py
controllers/ajax_controller.py
helpers/mytba_helper.py
mobile_main.py

- Use model_type constants to avoid event/district key conflicts
- Use symmetric_difference when seeing if the notification list changes
Fixes #1391

Avoid Collisions in MyTBAHelper

---

cron.yaml
helpers/award_manipulator.py
helpers/district_helper.py
helpers/event_manipulator.py
helpers/match_manipulator.py

* Enqueues task whenever relevant model gets updated (Award, Match, Event) instead of nightly.
* More efficient queries
Fixes #1457

District points real time

---

common/my_filters.py
controllers/mytba_controller.py
templates/live_teams_partial.html
templates/mytba_live.html

Now shows upcoming events as well!

Clean Up MyTBA Page

---

consts/notification_type.py
controllers/account_controller.py
index.yaml
main.py
templates_jinja2/match_partials/match_table_header_hot.html
templates_jinja2/match_partials/match_table_macros.html
templates_jinja2/match_partials/match_table_row_macros.html
templates_jinja2/mytba.html
templates_jinja2/mytba_add_hot_matches.html
templates_jinja2/mytba_match.html

Hot matches

---

templates/apidocs.html

https://github.com/the-blue-alliance/the-blue-alliance/blob/master/controllers/base_controller.py#L79

Updated API docs to Last-Modified, not Last-Updated

---

package.json
react/gameday2/components/BootstrapDropdownToggleItem.js
react/gameday2/components/GamedayNavbar.js
react/gameday2/components/SidePanelToggleDropdown.js

This felt better to me than using buttons as toggles. I'm open to improvements for the copy.
Small PRs <3

[GD2] Use dropdown to toggle side panels

---

static/javascript/tba_js/eventwizard.js
static/javascript/tba_js/eventwizard_apiwrite.js
templates/eventwizard.html

Some things that came up during ctsc. This definitely fixes playoff matches. And probably fixes rankings imports (I'm as confident as I can be, without being able to test with FMS).

Event Wizard Bugfixes

---

consts/account_permissions.py
controllers/account_controller.py
controllers/suggestions/suggest_event_webcast_review_controller.py
controllers/suggestions/suggest_match_video_review_controller.py
controllers/suggestions/suggest_offseason_event_controller.py
controllers/suggestions/suggest_offseason_event_review_controller.py
controllers/suggestions/suggest_review_home_controller.py
controllers/suggestions/suggest_social_media_review_controller.py
controllers/suggestions/suggest_team_media_review_controller.py
controllers/suggestions/suggestions_review_base_controller.py
helpers/suggestions/suggestion_creator.py
main.py
models/suggestion.py
templates/admin/partials/pending_suggestion_rows_partial.html
templates_jinja2/event_partials/suggest_event_info.html
templates_jinja2/suggest_offseason_event.html
templates_jinja2/suggest_offseason_event_review_list.html
tests/test_suggestion_creator.py
tests/test_suggestions_review_permission_checks.py

Add Offseason Events Via Suggestion

---

templates_jinja2/suggest_team_social_media.html

This is only to change the http for https on the facebook links.

Change Facebook http for https (minor change)

---

templates_jinja2/team_details.html
templates_jinja2/team_partials/team_info.html

Capitalized "Home" in "Home Championship."

Useless Visual Tweak(s)

---

consts/ranking_indexes.py
controllers/event_controller.py
models/event.py
templates_jinja2/event_details.html

added rankings_enhanced that uses model {"team_number": {"ranking_score_per_match": number}}
towards #1572

Add Rank Points Per Match to Rankings Table

---

consts/event_type.py
renderers/team_renderer.py
templates_jinja2/team_details.html

Closes #1549. Season WLT records no longer include offseasons, including those with the official flag set to true.

WLT record calculation fixed

---

.travis.yml

Runs the Jest JavaScript unit tests on Travis CI.
Also enables dependency caching for pip to speed up the CI process.

[WIP] Run JS tests on Travis

---

react/gameday2/components/GamedayFrame.js
react/gameday2/components/MainContent.js
react/gameday2/components/NoWebcasts.js
react/gameday2/components/VideoGrid.js
react/gameday2/containers/MainContentContainer.js
react/gameday2/containers/VideoGridContainer.js
react/gameday2/gameday2.js
react/gameday2/gameday2.less
react/gameday2/nowebcasts.less
react/gameday2/selectors/__tests__/selectors-test.js
react/gameday2/selectors/index.js
react/gameday2/sidebars.less

This displays a message if people try to visit GD2 when there aren't any active webcasts. It also includes a link to the TBA homepage. It's barebones, but it gets the job done.
There's also some behind-the-scenes refactoring that renders the main page contents (video grid, layout selector, message from this PR) as the child of another component that handles positioning when the sidebars are visible. This reduces dependencies between components and makes it easier to add different "main" views.

[GD2] Show "No webcasts" message when appropriate

---

.travis.yml
requirements.txt
tests/test_event_controller.py
tests/test_match_controller.py
tests/test_team_controller.py

Can only test things rendered with jinja2 templates, for the time being (I can't get django ones to work).
Provides some very simple tests - basically, does it render with no errors. We can build off this

Write Some Basic Controller Tests

---

controllers/event_controller.py
template_engine/jinja2_engine.py
template_engine/jinja2_filters.py
templates_jinja2/event_list.html
templates_jinja2/event_partials/event_table.html
tests/test_event_controller.py

Use jinja2 for event list

---

controllers/team_controller.py
templates_jinja2/team_list.html
tests/test_team_controller.py

Jinja2 team list

---

controllers/admin/admin_apistatus_controller.py
templates/admin/apistatus.html

Show current season in API status admin panel

---

templates/webhookdocs.html

Correct webhook docs, schedule_posted is now schedule_updated

---

react/gameday2/components/BootstrapDropdownToggleItem.js
react/gameday2/components/ChatSidebar.js
react/gameday2/components/FollowingTeamsModal.js
react/gameday2/components/LayoutSelectionPanel.js
react/gameday2/components/LayoutSelectionPanelItem.js
react/gameday2/components/MainContent.js
react/gameday2/components/SwapPanel.js
react/gameday2/components/VideoCell.js
react/gameday2/components/VideoCellOverlay.js
react/gameday2/components/VideoGrid.js
react/gameday2/components/WebcastSelectionPanel.js
react/gameday2/components/__tests__/LayoutDropdown.test.js
react/gameday2/gameday2.js

Not sure why the linter started erroring only recently; I couldn't track down any relevant changes in ESLint or the Airbnb style guide we use as our base. Regardless, with this PR, our CI builds shouldn't error any more.

Fixed ESLint prefer-const errors

---

templates/apidocs.html

Add reference to Cache-Control header in API docs

---

controllers/api/api_base_controller.py
tests/test_api_trusted.py

Thanks for the suggestions @ograff!

Minor ApiWrite Fixes

---

controllers/admin/admin_authkeys_controller.py
mobile_main.py
templates/admin/authkeys.html

Things we need to support iOS and myTBA

iOS Support in myTBA

---

admin_main.py
controllers/admin/admin_event_controller.py
templates/admin/event_details.html

Allow removing EventTeams in admin panel

---

templates/base.html
templates/index_lhc.html
templates_jinja2/base.html

* Centered items on front pane of website: 
* Also reformatted slightly.
* Changed search to have an icon in it (also changed verbiage briefly to make it fit properly.)

General Homepage UI tweak.

---

templates/apidocs.html

Closes #1653 
Closes #1655 
Also addresses concerns in pull request #1654 by adding disclaimer.

Add APIs and warnings

---

controllers/account_controller.py
controllers/base_controller.py
controllers/mytba_controller.py
controllers/notification_controller.py
controllers/suggestions/suggest_event_webcast_controller.py
controllers/suggestions/suggest_match_video_controller.py
controllers/suggestions/suggest_offseason_event_controller.py
controllers/suggestions/suggest_team_media_controller.py
controllers/test_notification_controller.py
controllers/webhook_controller.py
helpers/user_bundle.py
static/javascript/tba_js/tba_favorites.js
templates_jinja2/account_register.html

For uniformity, everything now requires registration (which is just setting a name), and requiring registration implicitly requires login (duh).
Also fixed some redirects to make flow more natural.

Login cleanup

---

app-backend-tasks-b2.yaml
app-backend-tasks.yaml
helpers/event_insights_helper.py
helpers/media_helper.py

Fix some errors, downgrade some logs.

Logging cleanup

---

controllers/main_controller.py
main.py
templates/base.html
templates/index_lhc.html
templates_jinja2/add_data.html

At /add-data, should cover most common cases

Add Instructions to Add Offseason Data

---

controllers/admin/admin_event_controller.py
database/event_query.py
database/team_query.py
datafeeds/parsers/first_elasticsearch/first_elasticsearch_event_list_parser.py
datafeeds/parsers/first_elasticsearch/first_elasticsearch_team_details_parser.py
helpers/event_manipulator.py
helpers/team_manipulator.py
models/event.py
models/team.py
templates/admin/event_details.html
templates/admin/event_edit.html
templates/admin/team_details.html
templates/datafeeds/usfirst_event_details_get.html
templates/datafeeds/usfirst_team_details_get.html
tests/test_first_elasticsearch_event_list_parser.py
tests/test_first_elasticsearch_team_parser.py

And displays them on the web. We can expose it in the API in a later PR.

Store event and team postal codes

---

controllers/suggestions/suggest_offseason_event_controller.py
controllers/suggestions/suggest_offseason_event_review_controller.py
helpers/suggestions/suggestion_creator.py
templates_jinja2/event_partials/suggest_event_info.html
templates_jinja2/suggest_offseason_event.html
templates_jinja2/suggest_offseason_event_review_list.html
tests/test_suggestion_creator.py

- Update the way we do location to fix crashes (fixes #1682)
- Error when admin doesn't enter an event short (needed for keys)
- Leave review boxes blank when fields don't exist

Offseason Suggest Fixes

---

controllers/suggestions/suggest_offseason_event_review_controller.py
templates_jinja2/event_partials/suggest_event_info.html
templates_jinja2/suggest_offseason_event_review_list.html

@gregmarra @fangeugene 
Does this seem clearer about where to put the key? I also added some validation :)

Cleaner Offseason Review Page

---

templates/apidocs.html

Fix https://github.com/the-blue-alliance/the-blue-alliance/issues/1702

Add a Java API to the list

---

consts/account_permissions.py
consts/media_type.py
controllers/suggestions/suggest_designs_review_controller.py
controllers/suggestions/suggest_review_home_controller.py
helpers/media_helper.py
helpers/suggestions/suggestion_creator.py
main.py
models/media.py
models/suggestion.py
templates/admin/partials/admin_media_display.html
templates/admin/partials/pending_suggestion_rows_partial.html
templates_jinja2/media_partials/grabcad_partial.html
templates_jinja2/media_partials/media_display_partial.html
templates_jinja2/suggest_designs_review.html
templates_jinja2/suggest_team_media.html
templates_jinja2/team_details.html
templates_jinja2/team_partials/team_info.html
tests/test_media_url_parse.py

Link CAD Models

---

react/gameday2/gameday2.js
templates/base.html
templates/gameday2.html

* Gets rid of GD dependency on jQuery
* Removed scripts and CSS files that aren't being used

Removed unused JS/CSS from GD2

---

react/gameday2/reducers/__tests__/videoGrid.test.js
react/gameday2/reducers/videoGrid.js

Some tests for the state of the video grid, which is probably one of the more brittle and complex components we have. This is by no means comprehensive, but should protect against most regressions.

[GD2] More tests!

---

controllers/cron_controller.py
cron_main.py
helpers/district_helper.py
helpers/district_manipulator.py
helpers/district_team_manipulator.py
models/district.py
templates/admin/district_list.html

Doesn't read from this anywhere yet.

Save district rankings in district model

---

controllers/admin/admin_apistatus_controller.py
controllers/api/api_base_controller.py
templates/admin/apistatus.html
tests/test_api_trusted.py

Disable it on `/admin/apistatus`

Trusted API Killswitch

---

helpers/event_details_manipulator.py
helpers/firebase/firebase_pusher.py
helpers/match_manipulator.py
notifications/base_notification.py
notifications/broadcast.py
notifications/ping.py
notifications/update_favorites.py
notifications/update_subscriptions.py
notifications/verification.py
queue.yaml
tba_config.py

To support GD and GD Lite. WIP.

New Firebase Data Structure

---

controllers/datafeed_controller.py
datafeeds/datafeed_fms_api.py

Save responses from FRC API

---

helpers/event_simulator.py
tests/test_event_simulator.py

Simulates an event over time. Useful for testing.

Event simulator

---

helpers/event_insights_helper.py
templates_jinja2/event_partials/event_insights_2017.html

2017 event insights Fixes #1773

---

tba_config.py
templates/index_competitionseason.html

Switch landing to competition season

---

templates/about.html

* Added extra sentence about new stuff TBA offers (insights + blog + CAD stuff.)
* Changed out links to be buttons.

About page style & minor wording change.

---

consts/account_permissions.py
controllers/event_controller.py
controllers/suggestions/suggest_event_media_controller.py
controllers/suggestions/suggest_event_media_review_controller.py
controllers/suggestions/suggest_review_home_controller.py
database/get_affected_queries.py
database/media_query.py
helpers/suggestions/suggestion_creator.py
main.py
models/media.py
models/suggestion.py
templates_jinja2/event_details.html
templates_jinja2/suggestions/pending_suggestion_rows_partial.html
templates_jinja2/suggestions/suggest_event_media.html
templates_jinja2/suggestions/suggest_event_media_review_list.html
tests/suggestions/test_suggest_event_media_controller.py
tests/suggestions/test_suggest_event_media_review_controller.py
tests/suggestions/test_suggestion_creator.py
tests/test_database_cache_clearer.py

Event Media Suggestions

---

controllers/cron_controller.py
cron.yaml
cron_main.py
helpers/bluezone_helper.py
helpers/firebase/firebase_pusher.py
helpers/match_time_prediction_helper.py
models/event.py

As discussed in #1779 
Continuation of #1784

TBA BlueZone

---

templates/mytba_live.html

myTBA Minor Style Change

---

controllers/admin/admin_authkeys_controller.py
helpers/firebase/firebase_pusher.py
helpers/webcast_online_helper.py
react/gameday2/components/VideoCellToolbar.js
react/gameday2/components/WebcastSelectionOverlayDialog.js
react/gameday2/reducers/webcastsById.js
tba_config.py
templates/admin/authkeys.html

If it's Twitch, we know if the webcast is live of not!

Live webcasts

---

cron.yaml
helpers/firebase/firebase_pusher.py
helpers/webcast_online_helper.py
react/gameday2/components/WebcastSelectionOverlayDialog.js
react/gameday2/gameday2.js
react/gameday2/reducers/webcastsById.js

Special webcasts now source from Firebase, stream titles are displayed for live webcasts.

Firebase special webcasts

---

notifications/upcoming_match.py
tests/test_notification_upcoming_match.py

@fangeugene can you take a look/test? I don't have all the webcast status fetcher keys set up on any local instance of mine.
Fixes #1801

Provide webcast in UpcomingMatchNotification

---

controllers/apiv3/api_event_controller.py

Now an alliance looks like this:
```
{
"backup": null, 
"declines": [], 
"name": "Alliance 1", 
"picks": [
"frc375", 
"frc1796", 
"frc806"
], 
"status": {
"current_level_record": {
"losses": 0, 
"ties": 0, 
"wins": 0
}, 
"level": "sf", 
"playoff_average": null, 
"record": {
"losses": 0, 
"ties": 0, 
"wins": 0
}, 
"status": "playing"
}
},
```

APIv3 Alliance Status

---

bootstrap.py
pavement.py
templates/admin/debug.html

Run `paver bootstrap` to load data for 2016necmp. You can also run `paver boostrap --key=<event/tea/match key>` to load a certain entity.

Bootstrap Development Instance Using APIv3

---

templates/event_partials/event_table.html

Event table formatting

---

templates/contact.html

Remove match video spreadsheet link from contact page

---

controllers/apiv3/api_base_controller.py
controllers/apiv3/api_suggest_controller.py

I don't think 400 really makes sense in this case since the team doesn't exist or isn't competing. @fangeugene @phil-lopreiato what do you guys think?

Return error code 404 if team doesn't exist or isn't competing this year instead of 400 for suggesting media

---

templates/thanks.html

Trying to cleanup some PRs here.
This one fixes #1827. You guys should be able to do a standard merge and give @tsteward his due credit.

Fix broken Firebase link

---

controllers/match_suggestion_controller.py
main.py
templates_jinja2/match_partials/match_suggestion_table_macros.html
templates_jinja2/match_suggestion.html

Match Suggestions for FIRST Champ LIVE

---

consts/playoff_type.py
controllers/event_controller.py
helpers/match_helper.py
models/match.py
templates_jinja2/event_details.html
templates_jinja2/playoff_partials/playoff_round_robin_6_team.html
tests/test_match_cleanup.py

Advancement doesn't actually match finals teams below because of bad data for sf3-2 on the FRC API staging server

Round robin support Fixes #1736

---

templates/index_lhc_offseason.html

Adds direct link to event page for FOC on templates/index_lhc_offseason.html

Link to FOC events page

---

controllers/admin/admin_main_controller.py
templates/admin/debug.html

Still a WIP.
I'm just going through a bunch of the setup things, breaking them, then updating things with the new links/information.
Fixes #1927

Update development setup docs

---

README.md

Just small changes to make the README consistent.

Use title case for README headers

---

models/media.py

This should fix #1954, though I haven't been able to test it yet.

Fix Instagram images

---

controllers/admin/admin_event_controller.py
controllers/suggestions/suggest_offseason_event_controller.py
datafeeds/parsers/fms_api/fms_api_team_details_parser.py
helpers/suggestions/suggestion_creator.py
helpers/website_helper.py
tests/test_website_helper.py

This should fix #1949 (for future cases). Haven't had a chance to fully test locally, but I'll get a chance in a couple hours.

Add website helper

---

subtrees/bootstrap/less/variables.less

I haven't tested this PR - I am still struggling getting a TBA dev env set up.  @fangeugene and @phil-lopreiato, could one of you verify that I don't break anything?

Use Roboto font family.

---

.travis.yml
ops/travis/travis-before.sh
ops/travis/travis-worker.sh

Use this: https://docs.python.org/2/library/compileall.html
This should fail on python syntax errors.

Compile Python Code in Travis

---

run_tests.py

Don't create one process per test file anymore, use a Pool of worker processes.

Bring Back Parallel Tests

---

database/database_query.py
helpers/manipulator_base.py
helpers/model_serializer.py
models/cached_query_result.py
tests/test_model_serializer.py

Serialize models to JSON instead of using Pickle.

DBQuery rework

---

.travis.yml
apiv3_main.py
controllers/admin/admin_api_controller.py
controllers/apiv3/api_admin_controller.py
controllers/apiv3/api_base_controller.py
models/api_auth_access.py
ops/gcslock.sh
ops/travis/should-deploy.sh
ops/travis/travis-deploy.sh
templates/admin/api_edit_auth.html
templates/admin/api_manage_auth.html

Use a GCS backed mutex to only allow one job to deploy at once
Add an admin API where travis jobs can post the current build info

Add Global Lock to Deploys

---

controllers/ajax_controller.py
main.py
react/eventwizard/components/infoTab/AddRemoveTeamMap.js
react/eventwizard/components/infoTab/EventInfoTab.js
react/eventwizard/components/infoTab/TeamMappingItem.js
react/eventwizard/components/infoTab/TeamMappingsList.js
react/eventwizard/constants/ApiEvent.js

Includes basic form validation.

Remap teams in EventWizard2

---

app.yaml
deploy_requirements.txt

Errors, looks like due to: https://stackoverflow.com/questions/44228959/google-python-api-tries-to-import-the-deprecated-oauth2client-contrib-multistore
Reverts the-blue-alliance/the-blue-alliance#2044

Revert "Use cloud endpoints v2"

---

admin_main.py
controllers/admin/admin_event_controller.py
helpers/location_helper.py
templates/admin/event_details.html

Admin button to re-geocode an event or to override with a given place ID

[admin] Allow Overriding Geocoded Event Locations

---

controllers/main_controller.py
tba_config.py
templates/index_buildseason.html

Update build season landing page for 2018

---

admin_main.py
consts/landing_type.py
controllers/admin/admin_main_landing_controller.py
controllers/main_controller.py
main.py
tba_config.py
templates/admin/base.html
templates/admin/main_landing.html
templates/index_buildseason.html
templates/index_competitionseason.html

Do some hacky stuff around the main landing controller to make everything controlled by a sitevar
Change the landing page without needing to redeploy the site
Run locally

Parameterize Landing Pages

---

static/swagger/api_v3.json

Update the out of date documentation for Media.type in the v3 API.
Fixes #2059
No other code was effected or anything since all I was doing was adding 2 lines to the docs to make them up to date.
N/A

Update docs for Media.type to be up to date

---

cron.yaml

Add cron job for district rankings
Add cron job for district rankings
For pre-season rankings
It hasn't

Add cron job for district rankings

---

cron.yaml

This is what happens when I'm in a rush.

Actually fix cron.yaml

---

helpers/media_helper.py
models/media.py
renderers/team_renderer.py
static/css/less_css/less/tba/tba_media.less
templates_jinja2/team_details.html
templates_jinja2/team_partials/team_info.html

#2069 imported avatars. This displays them.
In dev server

Add avatars to team pages

---

controllers/main_controller.py

So webcasts online/offline works properly

Drop buildseason landing cache time

---

controllers/main_controller.py
templates/index_buildseason.html

Show days, hours, minutes, seconds for end of build season
Local dev

Show more precise build season countdown

---

datafeeds/datafeed_fms_api.py

Fix errors when FRC API returns invalid JSON

---

controllers/match_controller.py
templates_jinja2/match_partials/match_breakdown/match_breakdown_2018.html
templates_jinja2/match_partials/match_table_cell_macros.html

Locally with partial fake data.

Add 2018 match breakdown table & RP dots

---

helpers/rankings_helper.py
models/event_details.py

Update ranking sort order and calculate total RP for 2018.
It hasn't

Update ranking sort order for 2018

---

react/liveevent/components/UpcomingMatchesTable.js

Blue alliance incorrectly showing red alliance teams
It hasn't

Fix upcoming matches showing red teams twice

---

models/event_details.py

Fix total ranking points being incorrectly calculated for 2018

---

controllers/cron_controller.py
helpers/event_insights_helper.py
templates_jinja2/event_partials/event_insights_2018.html

Add event insights for 2018. * tooltip says "Has no real meaning for Playoff matches"
With week 0 data locally.

2018 Event Insights

---

models/match.py

Closes #2113 
FIRST added this field for 2018

Don't add tba_rpEarned for 2018

---

templates/index_competitionseason.html

Avatar page not being linked to when events are going on.
Local dev

Link to avatar page when events are going on

---

controllers/main_controller.py

Fix off by one error, sort shards, reduce shards

Avatar sharding bugfix

---

templates/index_competitionseason.html

Button showing up twice
It hasn't

Remove extraneous view avatars button

---

templates/contact.html
templates/index_buildseason.html
templates/index_competitionseason.html
templates/index_lhc.html
templates/predictions.html
templates/record.html
templates/thanks.html
templates_jinja2/account_overview.html
templates_jinja2/event_details.html
templates_jinja2/nearby.html
templates_jinja2/team_details.html
templates_jinja2/team_partials/team_info.html

This will make the capitalization and punctuation standard within different elements. AKA, the most OCD PR you've seen all day. Let me know if you'd like any of these standardized in a different way or if I missed anything.
My OCD was bugging me.
N/A

Make capitalization standard

---

helpers/firebase/firebase_pusher.py
helpers/match_manipulator.py
models/match.py
react/gameday2/components/LivescoreDisplay.js
react/gameday2/components/TickerMatch.js
react/gameday2/components/VideoCellToolbar.js
react/gameday2/gameday2.js
react/gameday2/selectors/index.js
react/liveevent/components/CurrentMatchDisplay.js
react/liveevent/components/LastMatchesTable.js
react/liveevent/components/LiveEventPanel.js
react/liveevent/components/UpcomingMatchesTable.js
react/liveevent/helpers.js
tba_config.py

Use short keys and paths to reduce bandwidth. Reduced by ~60% for initial load.
Verified that LiveEventPanel & GameDay Livescore behaved the same before and after.
Verified that matches get properly deleted from Firebase.

Optimize Firebase Match Format

---

static/css/less_css/less/tba/tba_media.less

Change the cursor to show you can click on the avatar.
It's unclear that it's clickable without the cursor, and @fangeugene put in time to make it clickable with #2148.
See screenshots below.  👇 
Soon™

BONUS CURSOR (on team avatar on individual team page)

---

controllers/apiv3/api_base_controller.py

Add If-Modified-Since to list of allowed headers in Access-Control-Allow-Headers.
Fixes #2150
lol

[apiv3] Add If-Modified-Since to Access-Control-Allow-Headers

---

controllers/cron_controller.py

May fix issue with possible Firebase race condition wiping match scores.

Predict match times in a transaction

---

controllers/cron_controller.py

This reverts commit c42c19b0c21db79707fc3e10263c682d0b2c64cd.

Revert "Add match times in a transation (#2154)" [clowntown]

---

templates_jinja2/match_timeline.html

Update match timeline for new firebase format

---

helpers/firebase/firebase_pusher.py
helpers/match_manipulator.py

May fix issue with possible Firebase race condition wiping match scores.

Prevent predicted match time updates clobbering other data

---

controllers/insights_controller.py
cron.yaml

Bump max insight year and cron jobs for 2018.

Enable year insights for 2018

---

react/liveevent/components/LiveEventPanel.js

Added eta to next match.
Local dev with prod Firebase data

Clearer match upcoming state for live event panel

---

react/gameday2/components/VideoCellToolbar.js

[GameDay] Fix Set PropType

---

controllers/cron_controller.py

Fix finished events being shown as 'down'
It hasn't

Fix bug with event down detection

---

templates/index_insights.html
templates_jinja2/insights_details.html

Updated the wording on the insights page.
The current wording was confusing on what was meant.
Locally only.
None.

Updated penalty wording

---

tests/test_event_get_timezone_id.py

Geocoded location is slightly off

Fix slightly changed location test

---

templates_jinja2/team_details.html

Wasn't removed with 88b40100749dd8a914718db32c5b29e2270296db

Remove team motto from mobile

---

helpers/event_insights_helper.py

More intuitive, in line with 2017.

Calculate 2018 unicorn matches without being preconditioned on a win

---

templates_jinja2/suggestions/suggest_event_media.html
templates_jinja2/suggestions/suggest_match_video.html
templates_jinja2/suggestions/suggest_team_media.html

Added a request on suggestion pages to "help the moderators" by including relevant information, eg match score screens for match videos, or team identifying information, like bumpers, in team media. Also cleaned up a minor grammatical on the other screens.
So many videos and images in the mod queue w/ no easy way to confirm their identity (eg match number, or team number -- ev what team built the bot that is just a frame and no bumpers?)
Testing? We don't need no stinkin' testing?
(It's just a quick HTML edit, checked as valid in editor)

Suggestion Workflow Additions (HTML Templates)

---

templates_jinja2/team_details.html
templates_jinja2/team_partials/team_info.html
templates_jinja2/team_partials/team_social_media.html

* "Collapsed" separate photo/video sections on the team page and nav
* The presentation of the photos and video is still the same, but I added one extra "if" that shortly handles having no photos or videos (see screenshots below). If one or the other is present it will handle it as before.
* What is the best way to test things like this? I added a suggestion on my local copy, and logged in a different account as administrator. I found the admin page but the link the Media suggestions didn't work (http://localhost:8080/admin/suggestions/media/review 404'd)
* Removed chunk of page that held FB Like, G+, and At the Control buttons
* the team_social_media partial only created the FB Like and G+ buttons so I deleted it.
* Hid the "Add CAD Model" button near the top of the page if it would …

Make Team pages more mobile friendly (#2217)

---

renderers/team_renderer.py
templates_jinja2/team_details.html

Show district points earned and overall district ranks on team pages
We <3 data
local devserver

Show District Points on Team Pages

---

templates_jinja2/team_details.html

Change fixes a typo in the template

Fix spelling error in team details template

---

.travis.yml

This will hide the deploy stage if we are not building master.
Improves PR build time by ~80 seconds
pr: https://travis-ci.org/AustinShalit/travis-test/builds/365405661
push to branch: https://travis-ci.org/AustinShalit/travis-test/builds/365405602
push to master: https://travis-ci.org/AustinShalit/travis-test/builds/365405877

Hide the deploy stage if we are not on master

---

react/gameday2/gameday2.js

When the user hides the chat via the UI, this will set the chat URL parameter to hidden.  On page load it checks to see if the value of chat is 'hidden' and will hide the chat if it is.
closes #1448 
Manually tested

Refreshing gameday with the chat hidden will keep it hidden

---

controllers/cron_controller.py
controllers/match_suggestion_controller.py
helpers/prediction_helper.py
templates_jinja2/match_partials/match_predictions_table_header.html
templates_jinja2/match_partials/match_suggestion_table_macros.html
templates_jinja2/match_partials/match_table_cell_macros.html

For FCL.
Also implements 2018 predictions, but they're not terribly accurate.

Match suggestions 2018

---

controllers/main_controller.py
templates/index_champs.html

Update champs landing for 2018.
Will put implement 6 field livescore in a future PR.
Champs is here!!!
Local dev

2018 champs landing

---

controllers/match_controller.py
main.py
templates_jinja2/match_details.html
templates_jinja2/match_timeseries.html

Add timeseries chart on match page.
Add timeseries chart on dedicated page.  A lot of copypasta because no time to clean up right now.
GDCV everything!
Local dev

Add timeseries chart on match page

---

react/liveevent/components/LiveEventPanel.js
react/liveevent/firebaseapp.js
react/liveevent/liveevent.js
static/css/less_css/less/tba/tba_live_event_panel.less
templates/index_champs.html
templates_jinja2/event_details.html

Champs livescore

---

templates_jinja2/suggestions/suggest_match_video.html
templates_jinja2/suggestions/suggest_match_video_playlist.html

Note on the suggestion pages that we do not accept copies of match videos sourced from an official FIRST webcast, but will accept suggestions of videos on and linked to an Official FIRST channel.
Also updated Playlist page to include the "help our moderators" text from an earlier commit.
We test in production. 😀

Suggestion Workflow Additions

---

templates/index_competitionseason.html

Fixes the a none appearing when the last event of the week does not have a week number.
The landing page says "None" right now.
Has not been tested.

Do not display none when the last event does not have a week

---

backend_main.py
controllers/cron_controller.py
controllers/datafeed_controller.py
controllers/district_controller.py
datafeeds/datafeed_fms_api.py
datafeeds/parsers/fms_api/fms_api_district_rankings_parser.py
helpers/district_manipulator.py
models/district.py
templates/admin/district_edit.html
templates/admin/district_list.html
templates_jinja2/district_details.html

Show when district teams qualify for DCMP/CMP. This reads the values from the FIRST API.
locally

Show District Advancement

---

static/swagger/api_v3.json

Adds a model for `EventInsights2018`, as well as adding documentation for `unicorn_matches` to `EventInsights2017` - depends on #2269
Just documenting things that haven't been documented
Looks good in Swagger editor

Add EventInsights2018

---

templates_jinja2/district_details.html
templates_jinja2/event_list.html

As correction of GH-2280, this groups the buttons on the District event page.  Was tested and previewed identically to prior method, and overall was just an oversight on including it in the original PR.
See above.
It's required because I can't read.
Tested using local copy of TBA and actually testing both use cases properly.
See GH-2280.

Prettyfy Season / District dropdown (for real this time)

---

ops/dev/Dockerfile
static/swagger/api_v3.json

There were trailing commas in the JSON that made it invalid
The invalid JSON broke the build system for the codegen libraries.
Linted JSON on jsonlint.com, fixed all errors it gave me. JSON is now valid.

Removed trailing commas that broke JSON

---

controllers/main_controller.py

Cast the query to int so you can use search even with a leading zero.
See: https://www.chiefdelphi.com/forums/showpost.php?p=1770988&postcount=10

Cast q to int

---

bootstrap.py

`team_key_names` was not being set correctly
`youtube_videos` was no being set correctly

Fix bug with bootstrapping matches [nodeploy]

---

consts/account_permissions.py
controllers/api/api_base_controller.py
controllers/api/api_trusted_controller.py
run_tests.py
tests/test_api_trusted.py

Add a new permission, `EVENTWIZARD`, that we can grant to allow mods to import FMS reports for offseason events
I'm tired of doing it myself
Added unit tests

Add Eventwizard offseason permission

---

docs/dev-gae.md

There was a step to get the GAE testing setup to work missing from the docs, so I added it.
Because I spent half an hour trying to figure out why my deployed App Engine testing environment wouldn't work until I looked around in the Slack.
N/A, only a docs change

Documented a step to make GAE test deploys clearer

---

react/eventwizard/components/infoTab/AddRemoveTeamMap.js

(see title)
See bug #2320
Locally
N/A

Add additional layer of null checking for React eventwizard

---

templates_jinja2/add_data.html

Update add-data with easier to read formatting.
This change aims to address usability / clarity of the add-data page.
The add-data page was generally an eye-sore and made it difficult to follow at points.  It also generally didn't address more recent changes to TBA (like GrabCAD or various webcast improvements.)
Was tested locally using Inspect Element & via HTML linter.

Update add-data with easier to read formatting.

---

controllers/team_admin_controller.py
templates_jinja2/media_partials/media_display_partial.html
templates_jinja2/media_partials/team_admin_media_row.html
templates_jinja2/team_admin_dashboard.html

Give social media their own section, plus some other cleanup

[modtools] Actually support social media

---

docs/dev-container.md

Re: a conversation we had in the Slack - it can be tough to get your Vagrant/Docker images fixed if they get in to a bad state. I tried adding some more details around troubleshooting steps, especially for destroying and rebuilding.
Closes #2373

Add Docker/Vagrant troubleshooting steps

---

templates_jinja2/team_admin_dashboard.html

Adds some Frequently Asked Questions to modtools.
Cut down on common support requests.
#WeTestInProd
(HTML only change)

Add FAQs to modtools

---

controllers/team_admin_controller.py
templates_jinja2/team_admin_dashboard.html
tests/team_admin/test_suggest_team_admin_review.py

FIRST stopped allowing people to set robot names in 2019, so we can do that ourselves

[team-admin] Allow editing robot names

---

controllers/match_controller.py
datafeeds/datafeed_fms_api.py
helpers/event_insights_helper.py
helpers/rankings_helper.py
models/event_details.py
templates_jinja2/event_partials/event_insights_2019.html
templates_jinja2/match_partials/match_breakdown/match_breakdown_2019.html
templates_jinja2/match_partials/match_table_cell_macros.html

The mock data from the API doesn't have realistic data, so numbers don't necessarily add up.

Update rankings, match breakdowns, and event insights for 2019

---

models/event.py
templates_jinja2/event_details.html

Adds a badge with the Week number to an official event (or an event with a week number).
Closes #2396. If week number is not blank, adds the week number with special case for 2016.
#2396

Adds badge with week # to events

---

models/media.py

Switches ChiefDelphi direct image URLs to using a direct image link on web.archive.org.
The Android app would like to use the media URLs exposed via the API instead of generating those URLs ourselves (see [#885](https://github.com/the-blue-alliance/the-blue-alliance-android/issues/885)).
However, the existing CD media links exposed to the app include the internet archive's iframe, and end up not rendering correctly in the app (I'm really not sure how web's `background-image` CSS attributes do it properly).
The internet archive supports flags to disable this and return an image directly (the `im_` flag). Unfortunately this can only be used with a specific entry in the archive (e.g. a timestamp), but using a timestamp of "0" gives you the most recent version.
**Old:** …

Move ChiefDelphi web archive URLs to a direct image URL

---

static/swagger/api_v3.json

Should be straightforward enough - but double check my work please

Add docs for 2019 score breakdown

---

controllers/insights_controller.py
cron.yaml

Not even close to tested, but just copied #2162 so what's the worst that can happen?

Enable year insights for 2019

---

datafeeds/parsers/fms_api/fms_api_team_details_parser.py
tests/test_fms_api_team_parser.py

For all those times we go "we can nuke it from the db but it'll show back up tomorrow"

Add team parser website blacklist

---

templates/contact.html

Adds info about mod codes to try to reduce inbound emails.
We are slow replying to emails, better to have FAQ.
Local dev instance

Clean up contact screen, add note about mod codes.

---

react/gameday2/components/ChatAnalyticsTracker.js
react/gameday2/components/ChatSidebar.js
react/gameday2/components/LayoutAnalyticsTracker.js
react/gameday2/components/VideoCellAnalyticsTracker.js
react/gameday2/components/VideoGrid.js
react/gameday2/gameday2.js

Track selected layout and chat in GameDay

---

templates/apidocs_overview.html

Adds developer guidelines, light edits to rest of page.
Something to point to when we ask people to follow these guidelines.
Tested on local server

Adds v1 of developer guidelines.

---

controllers/base_controller.py
database/database_query.py
stackdriver/profiler.py
template_engine/jinja2_engine.py

Puts the API call to StackDriver tracing in a deferred task to not slow down the main response.

Defer Stackdriver Tracing

---

controllers/gameday_controller.py

Adds GameDay redirect logging for debugging

---

tbans/models/subscriptions/subscription_batch_request.py
tests/tbans_tests/models/subscriptions/test_subscription_batch_request.py

Adds a validation only mentioned in the comments, plus a test for that validation.

Add additional validation for SubscriptionBatchRequest

---

tbans/tbans_service.py

As we add methods to TBANS, doing the `if self._authenticated` check and throwing an error felt cumbersome. This changes that `_authenticated` property in to a `_validate_authentication` method that will throw an error if the request is unauthenticated.

New, DRYer validation method in TBANS

---

tbans/models/messages/fcm_message.py
tbans/models/messages/webhook_message.py
tbans/models/notifications/notification.py
tbans/models/notifications/payloads/platform_payload.py
tbans/models/subscriptions/subscription_batch_request.py
tbans/models/subscriptions/subscription_status_request.py
tbans/utils/auth_utils.py
tbans/utils/json_utils.py

Just docstring updates - fixed some formatting, fixed some wrong types. Nothing crazy.

TBANS docstring updates

---

tbans/consts/iid_error.py

Extract IID error codes to constants

---

templates/index_competitionseason.html

Fixes #2470 
Colons that do not need to be on the homepage.
See #2470 for details
Has not
See #2470 for screenshots

Removes unnecessary colons on homepage

---

tbans/models/requests/notifications/webhook_request.py
tests/tbans_tests/models/requests/notifications/test_webhook_request.py

Fixes errors we're seeing in production

Remove empty verification for webhook secrets

---

templates_jinja2/event_insights.html

Fix advanced insights chart ranges to correctly produce upper bound.

---

controllers/admin/admin_cron_controller.py
cron_main.py
tbans/models/notifications/verification.py
tbans/models/requests/notifications/webhook_request.py
templates/admin/mobile_dashboard.html
tests/tbans_tests/models/notifications/test_verification.py
tests/tbans_tests/models/requests/notifications/test_webhook_request.py

Reverts https://github.com/the-blue-alliance/the-blue-alliance/commit/d9762fbe48d837dc814cd505cec936c3a7e9b7e1 https://github.com/the-blue-alliance/the-blue-alliance/commit/52744f6e93b8a68a3ab2d9060e43673caf238eb6 and https://github.com/the-blue-alliance/the-blue-alliance/commit/ee567385489627c76167b197fb6b9543e53565b6 now that all webhooks have secrets

Revert secretless webhook code

---

bootstrap.py

When a local instance is created for development purposes, make sure to
pull down disqualification status too.
Minor addition to bootstrap.py.
See above.
Tested in my local instance with `2019cur`.
N/A

Bootstrap dqs.

---

templates_jinja2/suggestions/suggest_offseason_event.html

Grammar
Eugene said to PR it. 😄 
#WeTestInProd
(1 line HTML change)
Nope

Fix grammar on event suggest page

---

templates_jinja2/account_overview.html

Change ping sent copy

---

main.py

Closes #2523 kinda - fixes the link, not necessarily the permissions problem.

Fix BigQuery link

---

admin_main.py
controllers/admin/admin_event_controller.py
helpers/playoff_advancement_helper.py
templates/admin/event_details.html

More Event Advancement Improvements

---

app.yaml
dispatch.yaml

Save some $$$
Tasks work in local dev. Didn't test clientapi.

Recombine clientapi and tasks service into default

---

api/apiv3/api_event_controller.py
controllers/account_controller.py
controllers/admin/admin_event_controller.py
controllers/admin/admin_migration_controller.py
controllers/advanced_search_controller.py
controllers/api/api_event_controller.py
controllers/backup_controller.py
controllers/event_controller.py
controllers/insights_controller.py
controllers/nearby_controller.py
helpers/validation_helper.py
tba_config.py

Convert all 1992 references to using tba_config.MIN_YEAR

---

admin_main.py
controllers/admin/admin_event_controller.py
templates/admin/event_details.html

Make this easier to purge all unplayed matches at a level, or the entire set of matches.

Add way to delete all matches in an comp level

---

controllers/team_controller.py

Implementing a little cleanup from https://github.com/the-blue-alliance/the-blue-alliance/pull/2588/files#r330296188 - we can simplify this bit a lot by changing our constant by one

Cleanup logic in team list

---

app-backend-tasks-b2.yaml
app-backend-tasks.yaml
dispatch.yaml

My find/replace was bad because I didn't have a space in the replace. This should fix deploys 😓

Fix broken deploys by fixing yaml syntax

---

helpers/event_helper.py
tests/test_event_remapping.py

Team awards remapping wasn't correctly working.
Remapping not well tested.
Local tests pass

Add remapping tests, fix award remapping

---

clientapi/clientapi_service.py

Fix incorrect message for ClientAPI model/setPreferences subscription 500

---

controllers/main_controller.py
templates_jinja2/index/index_buildseason.html

So we can link into live ri3d streams from the homepage
Also puts some of the things we hand commented out behind config flags (in case avatars come back?)

Show Live Webcasts on Build Handler

---

controllers/datafeed_controller.py
controllers/main_controller.py
templates_jinja2/avatars.html
templates_jinja2/team_list.html

Based on https://github.com/the-blue-alliance/the-blue-alliance/commit/906f35c075ad07f777f3f0170e3e3ce69c98b409

Support avatars for 2020

---

api/apiv3/api_zebra_motionworks_controller.py
api/apiv3_main.py
controllers/api/api_trusted_controller.py
models/zebra_motionworks.py

Provide endpoint for accessing Zebra MotionWorks data:
`/api/v3/match/<match_key:>/zebra_motionworks`
Local dev

Expose Zebra MotionWorks Data in APIv3

---

templates_jinja2/event_details.html
templates_jinja2/team_partials/team_info.html

Link back to FRC Events API on official Event and Team pages

---

tests/test_notification_update_subscriptions.py

Fix class name for TestUpdateSubscriptionsNotification

---

tests/helpers_tests/test_mytba_helper.py

I wrote myTBA helper tests for https://github.com/the-blue-alliance/the-blue-alliance/pull/2674 but decided not to merge it - but the tests are still good, so here are the tests.

Add myTBA helper tests

---

.gitignore
helpers/tbans_helper.py
models/event.py
models/notifications/awards.py
models/notifications/requests/request.py
models/subscription.py
tests/helpers_tests/test_tbans_helper.py
tests/mocks/models/mock_event.py
tests/models_tests/notifications/test_awards.py
tests/models_tests/test_subscription.py
tests/test_event.py

Re-introduces reverted changes - going to do some more testing in dev to make sure these changes are safe before merging

Revert "Revert "Better Awards notifications, update webhooks docs (#2687)" (#2688)

---

ops/travis/travis-before.sh

Don't run paver make for python jobs

---

controllers/admin/admin_tbans_controller.py
helpers/award_manipulator.py
helpers/match_manipulator.py
helpers/notification_helper.py
helpers/tbans_helper.py
models/notifications/match_score.py
models/subscription.py
templates/admin/tbans_debug.html
tests/helpers_tests/test_tbans_helper.py
tests/models_tests/notifications/test_match_score.py
tests/models_tests/test_subscription.py

Adds Match Score notifications to TBANS. Will do end-to-end testing later before merging.

Add Match Score notifications to TBANS

---

deploy_requirements.txt

The new grpcio versions appear to only work with Python 3 anyways

Pin grpcio version

---

controllers/admin/admin_tbans_controller.py
helpers/match_manipulator.py
helpers/notification_helper.py
helpers/tbans_helper.py
models/notifications/event_schedule.py
templates/admin/tbans_debug.html
tests/helpers_tests/test_tbans_helper.py
tests/models_tests/notifications/test_event_schedule.py

Send Event schedule update notifications via TBANS

---

controllers/admin/admin_tbans_controller.py
helpers/event_details_manipulator.py
helpers/notification_helper.py
helpers/tbans_helper.py
models/notifications/alliance_selection.py
templates/admin/tbans_debug.html
tests/helpers_tests/test_tbans_helper.py
tests/models_tests/notifications/test_alliance_selection.py

Send Alliance Selection notifications via TBANS

---

controllers/admin/admin_tbans_controller.py
helpers/match_manipulator.py
helpers/notification_helper.py
helpers/tbans_helper.py
models/notifications/match_video.py
templates/admin/tbans_debug.html
tests/helpers_tests/test_tbans_helper.py
tests/models_tests/notifications/test_match_video.py

Send Match Video notifications via TBANS

---

controllers/admin/admin_tbans_controller.py
helpers/match_manipulator.py
helpers/notification_helper.py
helpers/tbans_helper.py
models/notifications/event_level.py
models/notifications/match_upcoming.py
templates/admin/tbans_debug.html
tests/helpers_tests/test_tbans_helper.py
tests/models_tests/notifications/test_event_level.py
tests/models_tests/notifications/test_match_upcoming.py

Dispatch Upcoming Match and Event Level notifications via TBANS

---

helpers/rankings_helper.py

Based on https://github.com/the-blue-alliance/the-blue-alliance/commit/6fe0137f9afa62fe42919d04a724f2e1dc6766f1#diff-510eb8b1695830abfa60426b7f42934d

Add support for 2020 rankings

---

helpers/event_insights_helper.py
templates_jinja2/event_partials/event_insights_2020.html

2020 event insights

---

templates_jinja2/match_partials/match_breakdown/match_breakdown_2020.html

Change "Extended" to "Exited"

---

ops/travis/travis-deploy.sh

Doing some science to see if we can deploy these or not, and if we can't, what the error message is

Deploy `queue.yaml` and `index.yaml` via deploy script

---

helpers/season_helper.py

Should remove stray error logs

Remove print from `SeasonHelper`

---

models/notifications/requests/webhook_request.py
tests/models_tests/notifications/requests/test_webhook_request.py

I think this is the right error subclass to catch

Attempt 2 at catching deadline exceeded errors from Webhook requests

---

helpers/event_helper.py

Currently we're only looking for events 4 days in advance from the start (so starting on Thursday). This includes all events that start any day before the next "week" starts

Include Events up to a week after the closest start in getWeekEvents

---

templates_jinja2/suggestions/suggest_event_media.html
templates_jinja2/suggestions/suggest_team_media.html

Some users are suggesting memes as robot media, and this change would change the verbiage to state that meme images aren't permitted.

Change suggestion text for Event/Team Media to indicate no memes permitted.

---

admin_main.py
api.yaml
api/apiv3_main.py
api_main.py
app-backend-tasks-b2.yaml
app-backend-tasks.yaml
app.yaml
appengine_config.py
backend_main.py
backend_main_b2.py
cron_main.py
deploy_requirements.txt
main.py
requirements.txt
run_tests.py
services/ndb/gae_memcache_cache.py
services/ndb/middleware.py
tests/services_tests/test_gae_memcache_cache.py
travis_requirements.txt

The first step towards migrating to the `cloud-ndb` library (https://cloud.google.com/appengine/docs/standard/python3/migrating-to-cloud-ndb)
Towards https://github.com/the-blue-alliance/the-blue-alliance/issues/2663
Before we can move to the python3 runtime, we'll need to move all our ndb interactions to be through the `cloud-ndb` library. One of the changes is that it does not automatically integrate with GAE's bundled memcache. This diff introduces a few things:
- A global cache we can provide to cloud ndb that still uses bundled memcache
- An extension of webapp's `RequestContext` that we can use to create this cache for each request
- A bit of fighting with dependency hell to make sure the new dependencies still work

Create cloud-ndb global cache backed by bundled memcache

---

react/gameday2/components/TwitchChatEmbed.js
react/gameday2/components/embeds/EmbedTwitch.js
templates/gameday.html
templates/webcast/twitch.html

As the new [Twitch update](https://discuss.dev.twitch.tv/t/twitch-embedded-player-updates-in-2020/23956), we need to include the domain in a parameter when initializing a Twitch embed.
Close #2793.

Update Twitch Embeds URL

---

src/web/jinja2_filters.py
src/web/tests/conftest.py
src/web/tests/test_jinja2_filters.py
stubs/_pytest/mark/__init__.pyi
stubs/patch/pytest.patch

Just adding some missing tests. Note - the `register_template_filters` function has changed a little bit.

[py3] Add jinja2-filter tests

---

.flake8
flake8_plugins/service_import_checker.py

For example, if importing `from backend.api.handlers.root import root` in `src/backend/web/main.py`:

[py3] Check that services don't import other services

---

src/backend/common/models/location.py
src/backend/common/models/team.py
src/backend/common/models/tests/conftest.py
src/backend/common/models/tests/location_test.py
src/backend/common/models/tests/team_test.py
src/backend/common/models/tests/util.py

Import Team model

---

docs/Developing/Development-Runbook.md
docs/Home.md
docs/Setup/Repo-Setup.md
docs/Setup/Setup.md
docs/old/Home.md

I'm not entirely sure the links to other pages will work. Also some information might be missing - we can update iteratively.

First pass at dumping a bunch of information in to the Wiki

---

src/backend/common/queries/team_query.py
src/backend/common/queries/tests/team_query_test.py
src/backend/web/handlers/team.py
src/backend/web/handlers/tests/conftest.py
src/backend/web/handlers/tests/team_detail_test.py
src/backend/web/handlers/tests/team_list_test.py
src/backend/web/jinja2_filters.py
src/backend/web/main.py
src/backend/web/templates/team_partials/team_info.html
src/backend/web/tests/test_jinja2_filters.py

Most of the interesting stuff is stubbed out here, but it does render a basic team info header

implement a minimal team detail page

---

docs/Home.md

See title.  😬
(with a bit of auto-formatting, apparently)

[py3] [nodeploy] Fix link to Py2ToPy3 docs page

---

src/backend/common/consts/webcast_type.py
src/backend/common/models/event.py
src/backend/common/models/tests/event_test.py
src/backend/common/models/webcast.py
src/requirements.txt

Introduce a `TypedDict` to define the schema of our webcast objects and write a test for those methods in the model

Strongly type webcast dicts

---

src/backend/common/models/sitevar.py
src/backend/common/sitevars/base.py
src/backend/common/sitevars/google_analytics_id.py
src/backend/common/sitevars/notifications_enable.py
src/backend/common/sitevars/tests/google_analytics_id_test.py
src/backend/common/sitevars/tests/notifications_enable_test.py
src/backend/common/sitevars/tests/website_blacklist_test.py
src/backend/common/sitevars/website_blacklist.py
src/backend/common/tests/google_analytics_test.py

This will provide some scaffolding for us to define the expected json types of our sitevars.

Add Typing to Sitevars

---

.pyre_configuration
docs/Developing/Development-Runbook.md
requirements.txt
src/backend/common/sitevars/apiv3_key.py
src/backend/web/local/blueprint.py
src/backend/web/local/bootstrap.py
src/backend/web/local/tests/blueprint_test.py
src/backend/web/local/tests/bootstrap_test.py
src/backend/web/local/tests/conftest.py
src/backend/web/local/tests/local_bootstrap_interface_test.py
src/backend/web/templates/local/bootstrap.html
src/requirements.txt

Make a pretty page for the bootstrap endpoint on the local server. Also write some tests and clean up the code.

improvements to bootstrap page

---

src/backend/common/environment.py
src/backend/common/tests/environment_test.py
src/backend/conftest.py
src/backend/web/local/blueprint.py
src/backend/web/local/tests/blueprint_test.py
tba_dev_config.json

Centralize our checking of the `GAE_ENV` variable

refactor environment helpers into own class

---

src/backend/common/models/award.py
src/backend/common/models/event.py
src/backend/common/models/match.py
src/backend/common/queries/dict_converters/district_converter.py
src/backend/common/queries/dict_converters/event_converter.py
src/backend/common/queries/dict_converters/match_converter.py
src/backend/web/local/bootstrap.py
src/backend/web/local/tests/bootstrap_test.py

More Support in Local Bootstrap

---

ops/dev/vagrant/dev_appserver.sh
src/backend/common/environment.py
src/backend/common/helpers/season_helper.py
src/backend/common/logging.py
src/backend/common/models/event.py
src/backend/common/sitevars/apistatus.py
src/backend/web/handlers/team.py
src/backend/web/handlers/tests/team_canonical_test.py
src/backend/web/renderers/team_renderer.py
src/backend/web/templates/team_details.html
tba_dev_config.json

This'll show the full team page!
Plus some other assorted bug fixes/logging tweaks that I may split out into separate commits

Migrate Team History/Detail to TeamRenderer

---

src/backend/common/queries/mobile_client_query.py
src/backend/common/queries/tests/mobile_client_query_test.py

The `only_verified` flag wasn't being respected in `MoblieClientQuery` - because it didn't have tests 🙊

[py3] Small fixes to only_verified fetches in MobileClientQuery

---

requirements.txt
src/backend/common/helpers/playoff_advancement_helper.py
src/backend/common/models/event.py
src/backend/common/models/match.py
src/backend/common/tests/future_test.py

Might be good to keep this pinned, but this will bump to the newest version and fix whatever errors came up along the way

Bump pyre version

---

.github/dependabot.yaml

This'll help us automatically keep dependencies up to date

Add Dependabot Config

---

controllers/datafeed_controller.py
cron_main.py
ops/standalone/cron-skeleton.yaml
ops/travis/travis-deploy.sh

We don't need the full set of GAE instances or cronjobs running, so let's calm down

Skeleton deploy

---

docs/Setup/WSL-Guide.md

Forgot a couple things from the WSL PR yesterday

WSL Docs - Add WSL Vagrant setup & powershell hack

---

docs/Setup/WSL-Guide.md

I accidentally goofed my WSL setup and went on an adventure to learn more about it in the meantime. Important docs so that nobody has to write code without `rsync-auto` like I did for a day.

Update WSL docs

---

src/backend/common/firebase.py
src/backend/common/tests/firebase_test.py

Pulling code from https://github.com/the-blue-alliance/the-blue-alliance/pull/2881

Add Firebase helper

---

src/backend/common/consts/account_permission.py

Pulling code from https://github.com/the-blue-alliance/the-blue-alliance/pull/2881

Move AccountPermission from py2 to py3

---

src/backend/common/models/account.py

Add better typing to the Account model

Add types to Account model

---

src/backend/common/models/favorite.py
src/backend/common/models/subscription.py

Small typing improvements to the Subscription and Favorite models

Add better typing to Subscription and Favorite

---

src/backend/web/auth.py
src/backend/web/tests/auth_test.py

Pulling some code out of https://github.com/the-blue-alliance/the-blue-alliance/pull/2881 - this adds the auth helper methods

Add auth helper methods

---

src/backend/web/templates/account_login_required.html
src/backend/web/templates/base.html

When we merged https://github.com/the-blue-alliance/the-blue-alliance/pull/2881 we did not add back in the Firebase Performance init. This adds back in the Firebase Performance setup, and bumps the Firebase versions

[py3] Re-enable Firebase Performance

---

ops/dev/vagrant/dev_appserver.sh

This PR comes out of some discussions we've had in Slack around setting up the `GOOGLE_APPLICATION_CREDENTIALS` independent of the remote datastore. This also sets up the local/remote configuration for Google Cloud Tasks.
This should also make [setting up Auth locally](https://github.com/the-blue-alliance/the-blue-alliance/wiki/Firebase-Setup#configure-authentication) easier by allowing contributors to set their `GOOGLE_APPLICATION_CREDENTIALS` without having to ssh in to the Vagrant image

[py3] Allow independent setup of GOOGLE_APPLICATION_CREDENTIALS env variable in tba_dev_config

---

src/backend/common/helpers/season_helper.py
src/backend/web/handlers/index.py
src/backend/web/templates/base.html
src/backend/web/templates/index/index_kickoff.html

[py3] Update homepage for 2021 kickoff

---

ops/dev/vagrant/dev_appserver.sh
src/backend/common/environment.py
src/backend/common/environment/__init__.py
src/backend/common/environment/environment.py
src/backend/common/environment/tasks/tasks_remote_config.py
src/backend/common/environment/tasks/tests/tasks_remote_config_test.py
src/backend/common/environment/tests/environment_test.py
src/backend/common/tests/environment_test.py
tba_dev_config.json

Reverts the previously backed out task mode, along with a new tasks remote config

Add task mode + task remote config

---

src/backend/web/templates/base.html
src/web.yaml

Matching commit on `master` https://github.com/the-blue-alliance/the-blue-alliance/commit/a22798701864a2cc98083d5f06cf1c6a476680f0

Prefix css/js url for py3

---

src/backend/common/helpers/season_helper.py
src/backend/common/helpers/tests/season_helper_test.py

See https://www.firstinspires.org/robotics/frc/blog/2021-kickoff.

Update 2021 Kickoff time

---

pytest.ini
src/backend/common/models/cached_query_result.py
src/backend/common/models/tests/event_test.py
src/backend/common/queries/award_query.py
src/backend/common/queries/database_query.py
src/backend/common/queries/district_query.py
src/backend/common/queries/event_details_query.py
src/backend/common/queries/event_query.py
src/backend/common/queries/match_query.py
src/backend/common/queries/media_query.py
src/backend/common/queries/robot_query.py
src/backend/common/queries/team_query.py
src/backend/common/queries/tests/database_query_test.py
src/backend/conftest.py
src/backend/web/handlers/event.py

No clearing yet. But this gives us the ability to read from/write to existing db queries, as long as we use the same keys as the py2 app.
We'll cut over query by query, since we need to change the base class

Implement Databse Query Caching

---

src/backend/common/middleware.py
src/backend/common/sitevars/flask_secrets.py
src/backend/common/sitevars/tests/secrets_test.py
src/backend/common/tests/middleware_test.py
src/backend/web/local/tests/blueprint_test.py

Fixes https://github.com/the-blue-alliance/the-blue-alliance/issues/3181
We'll need to make sure to do this rename in production once this gets deployed

Namespace Flask secrets

---

src/backend/web/templates/account_login_required.html
src/backend/web/templates/base.html

It looks like we forgot to change this path in https://github.com/the-blue-alliance/the-blue-alliance/pull/3193

[py3] Use py3 Javascript for Firebase auth code

---

old_py2/controllers/admin/admin_match_controller.py
old_py2/controllers/backup_controller.py
old_py2/controllers/datafeed_controller.py
old_py2/cron_main.py
old_py2/datafeeds/datafeed_first_elasticsearch.py
old_py2/datafeeds/parsers/first_elasticsearch/first_elasticsearch_team_details_parser.py
old_py2/datafeeds/parsers/fms_api/fms_api_event_list_parser.py
old_py2/dispatch.yaml
old_py2/ops/standalone/dispatch-empty.yaml
old_py2/ops/travis/travis-deploy.sh
old_py2/templates/admin/base.html
old_py2/templates/base.html
old_py2/templates/datafeeds/base.html
old_py2/templates/gameday.html
old_py2/tests/test_first_elasticsearch_team_parser.py
ops/standalone/cron-skeleton.yaml
src/backend/common/consts/event_type.py
src/backend/web/static/css/less_css/less/tba/tba_gameday.less
src/backend/web/static/css/less_css/less/tba/tba_mixins.less
src/backend/web/static/css/less_css/less/tba/tba_navbar.less
src/backend/web/templates/base.html
src/backend/web/templates/gameday2.html
src/backend/web/templates/webcast/twitch.html
src/frontend/gameday2/components/TwitchChatEmbed.js
src/frontend/gameday2/components/embeds/EmbedTwitch.js

Most changes should be isolated within `/old_py2`.

[py3] Merge master to keep things up to date

---

.github/workflows/push.yml

Adds the deploy command for the `tasks-io` service

[py3] Deploy tasks-io via GitHub Actions

---

src/backend/common/manipulators/manipulator_base.py
src/backend/common/manipulators/tests/base_manipulator_test.py
src/backend/common/queries/database_query.py
src/backend/common/queries/dict_converters/award_converter.py
src/backend/common/queries/dict_converters/converter_base.py
src/backend/common/queries/dict_converters/district_converter.py
src/backend/common/queries/dict_converters/event_converter.py
src/backend/common/queries/dict_converters/event_details_converter.py
src/backend/common/queries/dict_converters/match_converter.py
src/backend/common/queries/dict_converters/media_converter.py
src/backend/common/queries/dict_converters/robot_converter.py
src/backend/common/queries/dict_converters/team_converter.py
src/backend/common/queries/tests/database_query_test.py

Hook up `CachedDatabaseQuery` + clearing for API dicts.

Implemnt API Response Caching

---

controllers/datafeed_controller.py
datafeeds/parsers/fms_api/fms_api_team_details_parser.py
templates/datafeeds/usfirst_team_details_get.html
tests/test_fms_api_team_parser.py

Partial revert of 5bd5cc2c983a357518b1a8d5f9d8448d03eed880

Remove less code to not create a DistrictTeam when fetching teams 

---

.pre-commit-config.yaml
docs/Setup/Repo-Setup.md
ops/update_venv_deps.sh

This way, when pulling updates, we can automatically make local venvs reflect dependency updates.

Add post-checkout hook to update python deps

---

src/backend/common/decorators.py
src/backend/common/tests/decorator_test.py

This will let us cache the result of expensive internal functions in
redis. It uses the same core as the flask caching library, and this will
replace the manual "write intermediate data into memcahe" pattern we had
in the old app

Add @memoize decorator

---

src/backend/common/decorators.py
src/backend/common/helpers/event_helper.py
src/backend/common/helpers/tests/event_helper_test.py
src/backend/common/tests/decorator_test.py

This is a function that stored data in memcache in py2, so we use `@memoize` here, cached for a day.

Port EventHelper.getWeekEvents

---

src/backend/common/helpers/event_helper.py
src/backend/web/handlers/district.py
src/backend/web/handlers/tests/district_detail_test.py
src/backend/web/handlers/tests/helpers.py
src/backend/web/handlers/tests/team_list_test.py
src/backend/web/main.py
src/backend/web/templates/district_details.html

This needed some helper dependencies that were lots of code.
Tests to come.

Port District Detail Page

---

src/backend/web/handlers/account.py
src/backend/web/handlers/tests/account_overview_test.py
src/backend/web/handlers/tests/account_test.py
src/backend/web/models/tests/user_test.py
src/backend/web/models/user.py
src/backend/web/templates/account_overview.html

Support read API key add/delete in account

---

src/backend/web/handlers/account.py
src/backend/web/handlers/tests/account_overview_test.py
src/backend/web/templates/account_overview.html

Also adds a lot more testing around the account overview page that we're showing proper information

Slim down account overview template variables

---

src/backend/web/templates/account_overview.html

Fix HTML bug on connected devices page that shows extra tr elements

---

datafeeds/datafeed_fms_api.py

We're not fetching all teams for this year's season because we're stopping fetching teams for events at page 9. We should be fetching all pages while data is available.

Modify datafeed FMS API to always fetch all data

---

docs/Maintainers/Maintainer-Runbook.md

Add maintiner runbook instructions for dev container builds

---

src/backend/common/models/favorite.py
src/backend/common/models/mytba.py
src/backend/common/models/subscription.py
src/backend/common/models/tests/mytba_test.py

Pulling work of out my massive branch for the myTBA in the Account controller - having these conform to a base class makes it so we can simplify typing.

Make Favorite and Subscription conform to base MyTBA model

---

src/backend/web/handlers/account.py
src/backend/web/handlers/tests/account_overview_test.py
src/backend/web/handlers/tests/account_test.py
src/backend/web/models/mytba.py
src/backend/web/models/tests/mytba_test.py
src/backend/web/templates/account_overview.html
src/backend/web/templates/mytba.html

Migrates the `/account/mytba` route! Tested locally with all of the enumerations

Move /account/mytba route

---

src/backend/common/helpers/match_helper.py
src/backend/common/helpers/tests/match_helper_test.py

This method didn't have test coverage, so I wrote some tests

Add test for MatchHelper.natural_sorted_matches

---

src/backend/web/handlers/match.py
src/backend/web/handlers/tests/match_detail_test.py

Fix fatals from malformed incoming keys

validate match keys on detail handler

---

docs/Developing/Local-Shell.md
ops/shell/ipython_config.py
ops/shell/lib/__init__.py
ops/shell/run_user_script.sh
ops/shell/tba_shell.sh
ops/shell/user_scripts/print_event.py

This will add two concepts to make dev/admin work more maintainable.
First, an ipython environment to drop you into an interpreter that is connected to the same datastore as your dev instance (supports both local/remote).
Second, a way to commit simple scripts for admin work/maintenance/migrations that can be run under the ipython environment.
Added a wiki page with more docs, but in short...
The shell:
```bash
$ ./ops/shell/tba_shell.sh 
Python 3.9.1 (default, Jan 20 2021, 00:00:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.
Welcome to the TBA Shell!
Refer to documentation for how to use the shell at:
https://github.com/the-blue-alliance/the-blue-alliance/wiki/local_shell
In [1]: with …
```

Add ipython shell support

---

.github/workflows/pull_request.yml
.github/workflows/push.yml
.pre-commit-config.yaml
docs/Developing/Development-Runbook.md
ops/build/run_buildweb.sh
ops/dev/docker/build-container-images.sh
ops/dev/host.sh
ops/dev/print-gae-logs.sh
ops/dev/print-gulp-logs.sh
ops/dev/pull-datastore.sh
ops/dev/vagrant/bootstrap-dev-container.sh
ops/dev/vagrant/dev_appserver.sh
ops/dev/vagrant/start-devserver.sh
ops/lint_bash.sh
ops/lint_node.sh
ops/lint_py3.sh
ops/shell/ipython_config.py
ops/shell/memorystore_shell.sh
ops/shell/run_user_script.sh
ops/test_py3.sh
ops/update_venv_deps.sh
requirements.txt

We have a fair number of bash scripts, so we should have some style enforcement.

Hook up Lint/Formatting for Bash Scripts

---

ops/dev/vagrant/dev_appserver.sh

I accidentally bork'd this a while back 🤡

Fix dev_appserver.sh application when no Google credentials are set

---

src/backend/common/manipulators/manipulator_base.py
src/backend/common/manipulators/tests/base_manipulator_test.py

Deleting data is important too!

Port Delete Methods on Manipulators

---

old_py2/api/apiv3/api_event_controller.py
old_py2/controllers/admin/admin_event_controller.py
old_py2/controllers/api/api_event_controller.py
old_py2/controllers/api/api_team_controller.py
old_py2/controllers/backup_controller.py
old_py2/controllers/cron_controller.py
old_py2/controllers/district_controller.py
old_py2/controllers/event_controller.py
old_py2/controllers/mytba_controller.py
old_py2/datafeeds/parsers/fms_api/fms_api_match_parser.py
old_py2/helpers/district_helper.py
old_py2/helpers/team_helper.py
old_py2/models/notifications/awards.py
old_py2/notifications/awards_updated.py
old_py2/tests/test_notification_awards.py
src/backend/common/helpers/award_helper.py
src/backend/common/helpers/playoff_advancement_helper.py
src/backend/common/helpers/team_helper.py
src/backend/common/helpers/tests/award_helper_test.py
src/backend/common/helpers/tests/playoff_advancement_helper_test.py
src/backend/common/models/event.py
src/backend/common/models/event_details.py
src/backend/web/handlers/district.py
src/backend/web/handlers/event.py
src/backend/web/renderers/team_renderer.py

Sat down to work in the `web/handlers/event.py` file and all of the camel case method names were driving me NUTS. Doing a quick cleanup to convert some of the camel case methods to snake case

De-Java some helpers

---

README.md
docs/Home.md
docs/Setup/Contributing.md

Closes https://github.com/the-blue-alliance/the-blue-alliance/issues/3463

Update README to point to Wiki links. Add Contribuiting guidelines to Wiki

---

src/backend/common/models/event_details.py

Should be the final fix for https://github.com/the-blue-alliance/the-blue-alliance/issues/3497

Remove DQ and Played from Rankings table for 2021

---

src/backend/web/handlers/district.py
src/backend/web/handlers/tests/district_detail_test.py

Fixes https://github.com/the-blue-alliance/the-blue-alliance/issues/3496

Exclude district rankings from 2021 district details page

---

src/backend/common/sitevars/notifications_enable.py

Pulling code out of another PR

Update NotificationsEnable.enable_notifications to use more Pythonic update methods

---

old_py2/helpers/event_helper.py
old_py2/tests/test_event_remapping.py
src/backend/common/helpers/event_helper.py
src/backend/common/helpers/tests/event_helper_test.py
src/backend/common/models/award_recipient.py
src/backend/common/models/event.py

Also adding FOC test to `EventHelper` since it didn't have any tests

Add EventHelper.remapteams_awards

---

src/backend/tasks_io/datafeeds/datafeed_base.py
src/backend/tasks_io/datafeeds/tests/datafeed_base_test.py

Pulling some code out of https://github.com/the-blue-alliance/the-blue-alliance/pull/3520

Add logging tests to DatafeedBase

---

src/backend/common/helpers/mytba.py
src/backend/common/helpers/playoff_type_helper.py
src/backend/common/helpers/season_helper.py
src/backend/common/models/cached_query_result.py
src/backend/common/models/user.py
src/backend/common/sitevars/fms_api_secrets.py

Set ndb cache TTL for CachedQueryResult

---

consts/ranking_indexes.py
helpers/rankings_helper.py

We need this to support trusted API 
See https://github.com/the-blue-alliance/the-blue-alliance/issues/3493

[py2] Add ranking constants for 2021

---

.github/workflows/pull_request.yml
.github/workflows/push.yml
.gitignore
package.json

Post JS Code Coverage Info

---

src/backend/web/templates/base.html
src/backend/web/templates/event_details.html
src/backend/web/templates/team_details.html
src/backend/web/templates/team_partials/team_info.html

Expands on work done in https://github.com/the-blue-alliance/the-blue-alliance/pull/3622

Move FRC Events attribution link to remove confusion between FIRST Inspires link

---

.gitignore
Vagrantfile
docs/Developing/tba_dev_config.md
docs/common/Current-User.md
firebase.json
ops/dev/docker/Dockerfile
ops/dev/vagrant/bootstrap-dev-container.sh
ops/dev/vagrant/config.sh
ops/dev/vagrant/create_auth_emulator_accounts.py
ops/dev/vagrant/dev_appserver.sh
ops/dev/vagrant/run_datastore_emulator.sh
ops/dev/vagrant/run_firebase_emulator.sh
ops/dev/vagrant/start-devserver.sh
src/backend/common/environment/environment.py
src/backend/common/environment/tests/environment_test.py
src/backend/web/handlers/account.py
src/backend/web/handlers/tests/account_test.py
src/backend/web/static/css/less_css/less/tba/tba_base.less
src/backend/web/static/javascript/tba_js/tba_auth.js
src/backend/web/static/javascript/tba_js/tba_firebase.js
src/backend/web/templates/account_login_required.html
src/backend/web/templates/base.html

Adds the Firebase Auth emulator for easier testing of accounts locally.

Adds Firebase Auth emulator

---

src/backend/common/helpers/location_helper.py
src/backend/common/helpers/playoff_advancement_helper.py
src/backend/common/logging.py
src/backend/common/memcache.py
src/backend/common/middleware.py
src/backend/common/models/event.py
src/backend/common/run_after_response.py
src/backend/web/handlers/suggestions/suggestion_review_base.py
src/backend/web/handlers/suggestions/tests/suggest_team_media_review_controller_test.py

fix some pyre errors

---

.github/workflows/pull_request.yml

Sets up https://github.com/fastify/github-action-merge-dependabot
This way, we can automatically merge dependency updates that are green.

Add workflow for automerging dependabot PRs

---

.pyre_configuration
src/api.yaml
src/backend/api/handlers/tests/conftest.py
src/backend/api/main.py
src/backend/conftest.py
src/backend/tasks_io/main.py
src/backend/web/handlers/conftest.py
src/backend/web/handlers/tests/account_test.py
src/backend/web/main.py
src/requirements.txt
src/tasks_io.yaml
src/web.yaml

Follow https://cloud.google.com/appengine/docs/standard/python3/services/access
This will install the dependency so other pulls can start using pieces.
towards https://github.com/the-blue-alliance/the-blue-alliance/issues/3995

Add GAE builtin library

---

requirements.txt

Install hiredis-py for our redis-py library

---

ops/dev/vagrant/dev_appserver.sh
src/tasks_io.yaml

I'm attempting to track down an issue where on some branches task queues tasks are getting executed, and on some branches they're just sitting in the queues forever. This pulls some code out of one of the working branches.

Slightly more support for task queues in dev

---

src/backend/web/templates/index/index_kickoff.html

Just need to update one piece of text...

Update kickoff landing page for 2022

---

src/backend/common/models/event_details.py
src/backend/common/models/tests/event_details_test.py
src/backend/common/queries/dict_converters/event_details_converter.py

Making sure work from https://github.com/the-blue-alliance/the-blue-alliance/pull/3682 gets merged in py3
Closes https://github.com/the-blue-alliance/the-blue-alliance/issues/3691

Port non-null Event_Ranking.rankings to py3

---

src/backend/tasks_io/datafeeds/datafeed_html.py
src/backend/tasks_io/datafeeds/tests/datafeed_html_test.py

Pulling some code out of https://github.com/the-blue-alliance/the-blue-alliance/pull/3520

Rename DatafeedBase to DatafeedHTML

---

src/backend/common/flask_cache.py
src/backend/common/sitevars/turbo_mode.py
src/backend/common/tests/decorator_test.py

This lets us to dynamic cache timeouts during days of special activity.
This required the ability to do dynamic cache timeouts, which we now have!

Port TurboMode sitevar

---

src/backend/api/handlers/tests/delete_all_event_matches_test.py
src/backend/api/handlers/tests/delete_event_matches_test.py
src/backend/api/handlers/trusted.py
src/backend/api/main.py

Port API trusted delete matches

---

src/backend/common/tests/decorator_test.py

Updating tests for my yolo merge on https://github.com/the-blue-alliance/the-blue-alliance/pull/4044

Update + add tests for Flask caching with query strings

---

src/backend/common/frc_api/__init__.py
src/backend/common/frc_api/frc_api.py
src/backend/common/frc_api/tests/frcapi_test.py
src/backend/common/sitevars/fms_api_secrets.py
src/backend/common/sitevars/tests/fms_api_secrets_test.py

Split out from https://github.com/the-blue-alliance/the-blue-alliance/pull/3520/

Add base FRC API fetch class

---

src/backend/common/storage/__init__.py
src/backend/common/storage/clients/gcloud_client.py
src/backend/common/storage/clients/in_memory_client.py
src/backend/common/storage/clients/local_client.py
src/backend/common/storage/clients/storage_client.py
src/backend/common/storage/clients/tests/gcloud_client_test.py
src/backend/common/storage/clients/tests/in_memory_client_test.py
src/backend/common/storage/clients/tests/local_client_test.py
src/backend/common/storage/tests/storage_test.py

This will better prevent data leakage from tests
Also adds the `get_files` API, which we'll use when saving API responses
Split from #3520

Add InMemory Cloud Storage Client

---

src/backend/tasks_io/datafeeds/datafeed_fms_api.py
src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_root_parser.py
src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_test.py

Add base FMS API datafeed

---

.github/workflows/comment_screenshots_on_pr.yml
.github/workflows/pull_request.yml

Fixes errors with forked PRs.
Also fix missing setup steps in screenshot comment action.

[CI] Only run automerge job if the PR is by dependabot

---

old_py2/backend_main.py
old_py2/controllers/datafeed_controller.py
src/backend/common/frc_api/frc_api.py
src/backend/common/frc_api/tests/frcapi_test.py
src/backend/tasks_io/datafeeds/datafeed_fms_api.py
src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_distrct_test.py
src/backend/tasks_io/handlers/frc_api.py
src/backend/tasks_io/handlers/tests/frc_api_event_district_test.py
src/backend/tasks_io/templates/datafeeds/fms_district_list_get.html

- district list
- district advancement

Port district fmsapi endpoints to py3

---

src/backend/api/handlers/decorators.py
src/backend/api/handlers/tests/apiv3_auth_test.py
src/backend/api/handlers/tests/team_test.py
src/backend/common/consts/renamed_districts.py
src/backend/common/models/team.py
src/backend/common/queries/database_query.py
src/backend/common/queries/exceptions.py

Tried to be clever to detect keys that don't exist, but missed many edge cases. Explicitly check for keys now.
Also add more tracing

[APIv3] Fix validators

---

src/backend/api/handlers/event.py
src/backend/api/handlers/tests/event_test.py
src/backend/common/queries/database_query.py
src/backend/common/queries/dict_converters/converter_base.py
src/backend/common/queries/dict_converters/tests/converter_base_test.py
src/backend/common/queries/tests/database_query_test.py

This problem existed in py2 as well.

[Query/Converters] Fix bad conversion of None objects

---

src/backend/common/frc_api/frc_api.py
src/backend/common/frc_api/tests/frcapi_test.py

Resolution for https://usfirst.collab.net/sf/go/artf6025
Fixes https://github.com/the-blue-alliance/the-blue-alliance/issues/4159

Update frc api awards fetching to new format

---

src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_event_list_parser.py

Not a real event, messing with week numbers and whatnot

Do not import 2022ont0 for event list

---

src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_event_list_parser.py

This reverts commit 620074204707b14c0783a3faf54da2d280043de8.

Revert "Do not import 2022ont0 for event list (#4200)"

---

src/backend/web/templates/match_partials/match_breakdown/match_breakdown_2022.html
src/backend/web/templates/match_partials/match_table_cell_macros.html

2022 Match Breakdowns

---

dispatch.yaml

But like do it right this time

Dispatch API docs to py3 web

---

src/backend/common/models/match.py
src/backend/common/models/tests/match_test.py

The smallest possible change to fix match pages caused by new event key patterns.
Should fix #4300
It has not, my local environment is not working.

Simple regex change to fix match pages

---

src/backend/common/models/notifications/requests/tests/mocks/urllib/mock_http_error.py
src/backend/common/models/notifications/requests/tests/webhook_request_test.py
src/backend/common/models/notifications/requests/webhook_request.py

Tests will almost certainly fail here

Fix webhook sends not having the right data format

---

src/backend/api/handlers/decorators.py
src/backend/api/handlers/tests/apiv3_auth_test.py
src/backend/api/trusted_api_auth_helper.py
src/backend/common/helpers/tbans_helper.py
src/backend/common/helpers/tests/tbans_helper_test.py
src/backend/common/models/notifications/requests/webhook_request.py
src/backend/web/context_processors.py

All of the notifications got ported to py3 recently, and Greg flagged our logging costs are starting to get a little bit high. I'm going to remove all the non-essential logging from the notification code in order to try to decrease our logging costs.

Removed some API and notification logging

---

src/backend/common/manipulators/match_manipulator.py

Follow up to https://github.com/the-blue-alliance/the-blue-alliance/pull/4392

Removes one more line of notification logging

---

old_py2/controllers/admin/admin_cron_controller.py
src/backend/tasks_io/handlers/admin/blueprint.py
src/backend/tasks_io/handlers/admin/tasks.py
src/backend/tasks_io/handlers/admin/tests/admin_clear_eventteams_test.py
src/backend/tasks_io/handlers/admin/tests/admin_tasks_blueprint_test.py
src/backend/tasks_io/handlers/admin/tests/conftest.py
src/backend/tasks_io/handlers/conftest.py
src/backend/tasks_io/handlers/tests/conftest.py
src/backend/tasks_io/main.py

This was failing on the admin panel, due to task url routing

Port Admin EventTeam Remove to py3

---

src/backend/common/helpers/playoff_advancement_helper.py

Support 2022 Einstein Tiebreakers

---

src/backend/common/helpers/playoff_advancement_helper.py

This simplifies things a bit and makes it easier to extend year over year

Consolidate code for RR tiebreakers

---

src/backend/common/frc_api/frc_api.py
src/backend/common/frc_api/tests/frcapi_test.py
src/backend/tasks_io/datafeeds/datafeed_fms_api.py
src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_match_parser.py
src/backend/tasks_io/datafeeds/parsers/fms_api/simple_json_parser.py
src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_matches_test.py

This reverts commit da57c61306969be74f60d11d30c8ab797e5a2de9.
Let's try this again! At least now that there's not ongoing events, we can live with the 500s a bit?

Call FRC API v3 for Matches Redux

---

src/backend/web/local/bootstrap.py
src/backend/web/local/tests/bootstrap_test.py

Also switch to using manipulators to write data

[Dev] Bootstrap team media [nodeploy]

---

src/backend/common/helpers/tbans_helper.py

Pulling code out of https://github.com/the-blue-alliance/the-blue-alliance/pull/3347

Clean up TBANSHelper comments + method param types

---

old_py2/controllers/main_controller.py
old_py2/main.py

https://github.com/the-blue-alliance/the-blue-alliance/pull/4525#issuecomment-1138077291

Remove avatar list from `old_py2`

---

src/backend/web/handlers/index.py

Fixes the sorting on https://thebluealliance.com/avatars!

Fix avatar sorting

---

src/backend/common/helpers/tests/tbans_helper_test.py

I broke py3 when I merged some code and didn't update tests. Now I'm gonna slam CI to fix the tests quickly before landing a larger PR that fixes more tests.

Fix broken py3

---

src/backend/web/templates/thanks.html

Deleted the break tag on the [thanks](https://www.thebluealliance.com/thanks) page. 
The page looks better.
Has not been tested but probably doesn't need to be tested.
With break tag
Without break tag

thanks page styling

---

src/backend/web/decorators.py
src/backend/web/handlers/conftest.py
src/backend/web/handlers/suggestions/suggestion_review_base.py
src/backend/web/handlers/suggestions/tests/suggestion_review_home_test.py
src/backend/web/templates/suggestions/pending_suggestion_rows_partial.html
src/backend/web/tests/decorators_test.py

This will let admins review anything, and fixes some CSRF/ancestor queries within transaction errors

Fixes for Reviewing Webcast Suggestions

---

src/backend/web/handlers/opr.py
src/backend/web/main.py

Add the `opr` route and corresponding handler
`py3`, please.  😬 
Locally.  Does this static page need specs?  😓

Add OPR url and handler

---

src/backend/web/handlers/bigquery.py
src/backend/web/main.py

Add the `/bigquery` route and corresponding handler
More `py3`
Locally
N/A

Add bigquery url and handler

---

.github/workflows/comment_screenshots_on_pr.yml
.github/workflows/pull_request.yml
.github/workflows/push.yml
docs/Setup/Repo-Setup.md
ops/dev/docker/Dockerfile
ops/dev/vagrant/dev_appserver.sh
src/api.yaml
src/default.yaml
src/tasks_io.yaml
src/web.yaml

The GAE runtime went GA on 7/1: https://cloud.google.com/appengine/docs/standard/python3/release-notes
Changelog: https://docs.python.org/3/whatsnew/3.10.html

Update to python 3.10 runtime

---

src/backend/web/handlers/swag.py
src/backend/web/main.py

Add the `/swag` url and respective handler
More `py3`
Locally
N/A

Add swag url and handler

---

ops/check_venv_deps.py
src/backend/web/handlers/bigquery.py
src/backend/web/handlers/opr.py
src/backend/web/handlers/privacy.py
src/backend/web/handlers/swag.py
src/backend/web/main.py

Add `/privacy` url and handler
More `py3`
Locally

Add privacy url and handler

---

ops/check_venv_deps.py
src/backend/web/handlers/contact.py
src/backend/web/main.py

Add `/contact` url and handler
More `py3`
Locally

Add contact url and handler

---

src/backend/web/handlers/add_data.py
src/backend/web/main.py

Add `/add-data` url and handler
More `py3`
Locally

Add add-data url and handler

---

old_py2/controllers/admin/admin_event_controller.py
src/backend/web/handlers/admin/blueprint.py
src/backend/web/handlers/admin/event.py
src/backend/web/templates/admin/event_create.html

So we can make test events locally!

Port event create/edit admin pages

---

src/backend/web/templates/playoff_partials/playoff_round_robin_6_team.html

Removed a rogue comma in the round robin template 😆 (I assume it wasn't intentional)

Remove comma in round robin template

---

old_py2/controllers/ajax_controller.py
src/backend/common/models/favorite.py
src/backend/common/models/tests/favorite_test.py
src/backend/web/handlers/ajax.py
src/backend/web/handlers/tests/ajax_test.py
src/backend/web/main.py

We also query this on every page so port this too

Port favorite ajax endpoint

---

.pyre_configuration
src/backend/common/logging.py
src/requirements.txt

Attempting to connect our `logging.x` to the actual requests they're issued in by setting up Google Cloud Logging. We think this will give us the logs in the proper context according to https://github.com/googleapis/google-cloud-python/issues/3359

Setup Google Cloud Logging to try to get logs to connect to requests

---

src/backend/web/static/css/less_css/less/tba/tba_double_elim_bracket_table.less
src/backend/web/templates/bracket_partials/double_elim_bracket_table.html

- Fix some of the placeholder names (https://the-blue-alliance.slack.com/archives/C15SUFL92/p1664134204198169)
- Add a underscore to the alliance names to hint that there's a tooltip

Update double elim bracket

---

src/backend/web/handlers/team.py

Add support for 9xxx teams
[Someone reported it](https://www.facebook.com/groups/moardata/posts/5713396142013967/), [`frc-events` has teams over 9k](https://frc-events.firstinspires.org/2023/allteams), and, you know, those teams deserve to be seen as well.  😂
I didn't _see_ anywhere else this would need to be changed, but can make whatever additional changes are needed, if any.
It worked locally.  👀

Add support for 9xxx teams

---

src/backend/web/handlers/static.py
src/backend/web/main.py

Port /thanks to py3

---

src/backend/common/models/team_admin_access.py
src/backend/web/handlers/admin/blueprint.py
src/backend/web/handlers/admin/team_media_mod.py
src/backend/web/templates/admin/team_media_mod_add.html
src/backend/web/templates/admin/team_media_mod_edit.html
src/backend/web/templates/admin/team_media_mod_list.html

Port admin pages for managing team media mods (`/admin/media/modcodes/`) to py3
Manually

Port TeamAdminAccess admin pages to py3

---

old_py2/controllers/admin/admin_event_controller.py
old_py2/controllers/cron_controller.py
src/backend/common/helpers/event_remapteams_helper.py
src/backend/tasks_io/handlers/tasks.py
src/backend/web/handlers/admin/blueprint.py
src/backend/web/handlers/admin/event.py
src/backend/web/templates/admin/event_details.html

Port team remap to py3 admin

---

src/backend/web/handlers/admin/blueprint.py
src/backend/web/templates/admin/index.html

As title.
All the stats stuff is stubbed out and the links not-ported will 404, but at least here's something

Port admin homepage to py3

---

ops/dev/docker/Dockerfile

Pin the ubuntu version to 22.04 (which is what the currently published image uses). 
Tested that the container builds locally.

Pin docker image to ubuntu:22.04

---

docs/Maintainers/New-Season.md
src/backend/common/consts/ranking_sort_orders.py
src/backend/common/models/event_details.py
src/backend/web/templates/match_partials/match_breakdown/match_breakdown_2023.html

2023 match breakdowns & rankings

---

src/backend/common/consts/playoff_type.py
src/backend/common/helpers/playoff_type_helper.py
src/backend/common/models/match.py
src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_event_list_parser.py
src/backend/tasks_io/templates/datafeeds/usfirst_event_details_get.html
src/backend/web/handlers/index.py
src/backend/web/handlers/mytba.py
src/backend/web/templates/bracket_partials/double_elim_bracket_table.html

Fix issues not parsing 2023 matches from FRC API as double elim

2023 playoff type

---

src/backend/common/consts/playoff_type.py
src/backend/common/helpers/match_tiebreakers.py

Implement 2023 tiebreakers

---

src/backend/web/templates/bracket_partials/double_elim_bracket_table.html

Meant to include in #5010 but missed.

Add <wbr> only on 4 team alliances

---

docs/Developing/Development-Runbook.md

this ate a few minutes of my time trying to find

add link to web wiki in dev runbook

---

src/backend/web/templates/match_partials/match_breakdown/match_breakdown_2023.html

[2023] Make scoring location breakdown prettier

---

src/backend/web/handlers/mytba.py

Fix myTBA page 500-ing for live events

---

src/backend/common/consts/award_matching_strings.py
src/backend/common/consts/award_type.py
src/backend/common/helpers/tests/award_helper_test.py

Parse FIRST Impact award as chairmans, add Team Sustainability Award.
Fixes #5048

2023 awards

---

src/backend/web/handlers/event.py

Fix COPR errors on old events

---

src/backend/common/helpers/event_insights_helper.py
src/backend/web/handlers/event.py

2023 event insights fix

---

package-lock.json
package.json

Version greater than `4.17.1` errors for some reason

Pin swagger

---

src/backend/web/templates/base.html

Updated footer to have capitalized hyperlinks. 
This change makes the site look more professional and clean overall.
This has not been tested but likely does not require testing.
Old hyperlinks:
New hyperlinks:

[py3] Styling - Update footer capitalization on all pages

---

src/backend/web/templates/contact.html

The “Contact” page has been updated to add punctuation. That’s it.
This bugged me. I wanted to fix it.
This is just a bit of HTML and that’s the only change. It shouldn’t need testing as the change hasn’t happened in a “real” programming language.

fix: section header with no punctuation

---

src/backend/web/handlers/admin/tests/district_test.py
src/backend/web/handlers/admin/tests/media_test.py
src/backend/web/handlers/admin/tests/users_test.py
src/backend/web/handlers/admin/users.py
src/backend/web/templates/admin/user_list.html

write some more py3 admin panel tests

---

ops/test_ops.sh
ops/test_vagrant_startup.py
ops/tests/fullstack.test.js

reenable some fullstack test cases

---

package-lock.json
package.json
src/frontend/eventwizard/components/AuthTools.js
src/frontend/eventwizard/components/infoTab/EventInfoTab.js
src/frontend/eventwizard/components/infoTab/SyncCodeInput.js
src/frontend/eventwizard/components/teamsTab/AddRemoveSingleTeam.js
src/frontend/eventwizard/components/teamsTab/AddTeamsFMSReport.js
src/frontend/eventwizard/components/teamsTab/TeamListTab.js

This library doesn't support newer versions of node, blocking the updates in #4778
```
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: react-bootstrap-dialog@0.13.0
npm ERR! notsup Not compatible with your version of node/npm: react-bootstrap-dialog@0.13.0
npm ERR! notsup Required: {"npm":"^3.0.0","node":"^12.0.0"}
npm ERR! notsup Actual:   {"npm":"9.5.1","node":"v18.16.0"}
```

Remove react-bootstrap-dependnecy

---

src/backend/web/templates/hof.html

Chairman's -> Impact

---

old_py2/mobile_main.py
src/backend/api/api_trusted_parsers/json_matches_parser.py
src/backend/api/client_api_types.py
src/backend/api/handlers/client_api.py
src/backend/api/handlers/tests/client_api_suggestion_test.py
src/backend/api/main.py

Port ClientAPI Suggestion Creation to py3

---

old_py2/controllers/main_controller.py
old_py2/main.py
ops/prod_dispatch.yaml
src/backend/web/handlers/search.py
src/backend/web/handlers/tests/search_test.py
src/backend/web/main.py

this is the last thing we have explicitly pinned to py2

port search page to py3

---

src/backend/web/templates/admin/api_manage_auth.html
src/backend/web/templates/admin/event_details.html
src/backend/web/templates/admin/partials/api_write_table.html

Fixes for a couple issues I ran into in the admin dashboard:
* `id()` methods weren't being called properly in a few places
* event match lists were 500ing if matches didn't have times set
Local instance
None right now

Admin dashboard template fixes

---

src/tasks_cpu.yaml

Fixes insights calculations timing out at 30s

Increase cpu tasks timeout

---

.github/workflows/pull_request.yml
.github/workflows/push.yml

- Skip installing dependencies when using clowntown
- Cache fixes

Faster GH Actions Workflow

---

.github/workflows/push.yml
src/cron.yaml

Contents taken from https://github.com/the-blue-alliance/the-blue-alliance/blob/3dafb6697bd9d5511afaf7240eab733bd11b26a6/cron.yaml, which is what we have running in prod

deploy cron.yaml from py3

---

src/backend/web/templates/base.html
src/backend/web/templates/event_list.html
src/backend/web/templates/index_partials/index_lhc.html
src/backend/web/templates/team_list.html

Removing these until they are implemented.

Remove search nearby links

---

docs/Setup/Setup-Guide.md

The wiki link to the beta `docker-compose` setup doesn't work.

Correct wiki Setup-Guide beta link

---

src/backend/web/templates/insights.html

successful teamups -> most successful teamups

---

src/backend/web/handlers/ajax.py
src/backend/web/main.py

Remap teams handler

---

Vagrantfile
src/backend/api/api_trusted_parsers/json_awards_parser.py
src/backend/api/handlers/decorators.py
src/backend/web/handlers/ajax.py
src/backend/web/static/swagger/api_trusted_v1.json
src/frontend/eventwizard/components/AuthTools.js
src/frontend/eventwizard/components/EventWizardTabFrame.js
src/frontend/eventwizard/components/awardsTab/AwardsTab.js
src/frontend/eventwizard/containers/AwardsTabContainer.js
src/frontend/eventwizard/eventwizard.js

Add ability to edit awards to EventWizard.
Updated trusted API to allow specification of award type enum.

Eventwizard awards

---

.github/workflows/comment_screenshots_on_pr.yml
.github/workflows/pull_request.yml
.github/workflows/push.yml
docs/Setup/Repo-Setup.md
ops/dev/docker/Dockerfile
ops/dev/vagrant/bootstrap-dev-container.sh
src/api.yaml
src/backend/common/deferred/tests/defer_handler_test.py
src/backend/common/storage/clients/tests/gcloud_client_test.py
src/backend/tasks_io/handlers/tests/eventteam_update_test.py
src/backend/tasks_io/handlers/tests/tasks_test.py
src/default.yaml
src/tasks_cpu.yaml
src/tasks_io.yaml
src/web.yaml

Python 3.12 runtime is [GA as of 11/6](https://cloud.google.com/appengine/docs/standard/python3/release-notes#November_06_2023)
What's new: https://docs.python.org/3/whatsnew/3.12.html
[dockerpublish]

Update to python 3.12

---

src/backend/web/handlers/static.py
src/backend/web/main.py
src/backend/web/templates/about.html
src/backend/web/templates/base.html
src/backend/web/templates/donate.html
src/backend/web/templates/index_partials/index_lhc.html
src/backend/web/templates/index_partials/index_lhc_offseason.html

As title. We're long overdue for actually linking this on the site.

Add Donate Page & Links

---

src/backend/common/frc_api/frc_api.py
src/backend/common/queries/database_query.py
src/backend/tasks_io/datafeeds/datafeed_fms_api.py

This can help us monitor what's slow

Add additional profiling spans for external requests

---

ops/tests/fullstack.test.js
package-lock.json
package.json

Reverts breaking commits and fixes tests to prevent this in the future

Fix gameday

---

src/backend/web/templates/donate.html
src/backend/web/templates/thanks.html

Make donate and thanks pages cross-link

---

src/backend/web/handlers/admin/team_media_mod.py
src/backend/web/handlers/admin/tests/team_media_mod_test.py

Let's try a different approach, this time, split up the first request quickly into groups of 100, and then defer each of those individually

break up chunks of team modcodes

---

src/backend/common/consts/playoff_type.py
src/backend/common/helpers/playoff_advancement_helper.py
src/backend/common/models/event.py
src/backend/common/models/event_playoff_advancement.py

These models and functions were still untyped, so hook up some better type hints.
Existing tests pass.

Improve typing for playoff advancement

---

src/backend/common/consts/playoff_type.py
src/backend/common/helpers/playoff_advancement_helper.py
src/backend/common/helpers/tests/data/expected_advancement_2023micmp.json
src/backend/common/helpers/tests/data/expected_advancement_2023mijac.json
src/backend/common/helpers/tests/data/expected_advancement_apiv3_2023micmp.json
src/backend/common/helpers/tests/data/expected_advancement_apiv3_2023mijac.json
src/backend/common/helpers/tests/playoff_advancement_helper_test.py
src/backend/common/models/event_playoff_advancement.py
src/backend/web/jinja2_filters.py
src/backend/web/templates/admin/event_details.html

We don't have this currently, so we return a representation that assumes best-of-3 bracket, which is somewhat broken.
This diff will add proper support for representing the double elim tournament in the playoff status.
One difference is, we need to still preserve the entire bracket, because we use that to render on the event page.
Once this pushes, we'll need to do a backfill of all the 2023 events...
The API representation looks like this:
```
[
{
"extra_stats_info": [
{
"name": "Eliminated",
"precision": 0,
"type": "bool"
}
],
"level": "round1",
"level_name": "Round 1",
"rankings": [
{
"alliance_name": "Alliance 1",
"extra_stats": [
0
],
"matches_played": 1,
"record": {
"losses": 0,
"ties": 0,
"wins": 1
},
"sort_orders": [],
"team_keys": [
"frc694",
"frc1796",
"frc8159",
"frc5123"
]
}, …
```

Add playoff advancement representation for DOUBLE_ELIM

---

src/backend/web/handlers/admin/blueprint.py
src/backend/web/handlers/admin/match.py
src/backend/web/templates/admin/event_details.html

Also add csrf tokens where missing

Add admin handler to override match score breakdown

---

src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_match_parser.py
src/backend/web/templates/match_partials/match_breakdown/match_breakdown_2024.html

Closes https://github.com/the-blue-alliance/the-blue-alliance/issues/5736

Build 2024 score breakdowns

---

src/backend/web/templates/match_partials/match_table_cell_macros.html

Add 2024 RP dot calculations
Give the people what they want.
Tested locally.

Add 2024 RP dot calculations

---

src/backend/common/helpers/matchstats_helper.py

Adds 4 new component OPRs, total mic, total trap, teleop GPs, auto GPs.
Manually adding the individual components can be annoying.
Locally on `2024isde1`.

Add COPRs for total mic, total trap, teleop GPs, auto GPs

---

src/backend/web/handlers/admin/blueprint.py
src/backend/web/handlers/admin/event.py

As title. Also changes the event edit to not use `auto_merge`, and that also prevents removing webcasts.

Implement webcast add/remove in admin panel

---

src/backend/common/helpers/matchstats_helper.py

Count amplified notes in teleop note copr

---

src/backend/common/helpers/insights_helper.py

https://www.thebluealliance.com/insights/2024
Annual insights of most matches played per team includes matches that don't have scores / haven't been played, including finals 3 matches that haven't been pruned yet.

Only count played matches in matches played per team

---

src/backend/web/templates/team_admin_dashboard.html

Before (notice how lower sections aren't aligned with the margin for the `h1`)
After

Fix team admin dashboard form styling

---

src/backend/common/helpers/tbans_helper.py
src/backend/common/models/subscription.py
src/backend/common/models/tests/conftest.py
src/backend/common/models/tests/subscription_test.py

Should fix https://github.com/the-blue-alliance/the-blue-alliance/issues/5119

Async query subscriptions to speed up post-update-hooks

---

src/backend/web/templates/admin/event_details.html

Fix alignment in admin event details page

---

src/backend/web/templates/avatars.html

Added the blog post link on /avatars page
Blogs were not linked previously
Untested; Do not have environment set up. It shouldn't be able to break anything though.

Add links to 2023 and 2024 team avatar blog posts

---

src/tasks_io.yaml

This was bumped to F2 but the real solution was #5895

Downgrade tasks instance back to F1

---

src/backend/web/renderers/team_renderer.py

Fixed 500 error on team detail pages.

hotfix: check alliance name and status

---

.pyre_configuration
src/backend/common/logging.py
src/requirements.txt

Attempted fix to get logs to group properly in google cloud

Setup google cloud logging

---

.github/workflows/push.yml
ops/build/run_buildweb.sh
ops/deploy/update_env_variables_yaml.sh
src/backend/common/environment/environment.py
src/backend/common/flask_secret_key.py
src/backend/common/middleware.py
src/backend/common/tests/middleware_test.py
src/backend/web/local/tests/blueprint_test.py
src/backend/web/tests/main_test.py
src/env_variables.yaml
src/web.yaml

Realized #5991 won't work because the build artifact doesn't store the key

Use env var for flask secret key

---

.github/workflows/push.yml
src/api.yaml
src/backend/api/main.py

This is needed to bypass api auth when logged in.

Configure flask secret key in api service

---

src/backend/web/static/css/less_css/less/tba/tba_media.less

Update background colors of avatars to match the same as of the FMS [(reference)](https://firstfrc.blob.core.windows.net/fms/Avatars/AvatarSpecifications.pdf).
The current background colors are faded and provide a misleading preview for teams.

Update avatar background colors

---

src/backend/web/handlers/admin/team.py

Lets us delete social media entries

Show social media on admin team media page

---

src/backend/web/static/swagger/api_v3.json

This endpoint has been live for a while, just not documented in Swagger
more docs more good
The change was made with Swagger Editor and tested remotely on there:

Add docs for COPRs endpoint in swagger

---

ops/dev/vagrant/bootstrap-dev-container.sh

sometimes the bootstrap shell hangs on trying to install uglify for whatever reason. i don't know. this fixes it. Craig in Slack found it.

fixes occasional hang when bringing up instance

---

pwa/README.md

For folks like me starting at zero who want to look and know exactly what to run to get something up and running 😄

Add note in PWA readme about installing dependencies

---

pwa/.eslintrc.cjs
pwa/README.md
pwa/app/api/v3.ts
pwa/app/root.tsx
pwa/app/vite-env.d.ts
pwa/package-lock.json
pwa/package.json

Adds TS bindings for fetching data from TBA utilizing [oazapfts](https://github.com/oazapfts/oazapfts). During my testing I found this library to be the most robust and flexible for generating TS OpenAPI clients.

Add TS API bindings for PWA

---

.github/workflows/push.yml
pwa/package.json

Use CI build rather than GCP build

[PWA] Use CI build

---

pwa/.eslintrc.cjs
pwa/app/components/ui/button.tsx
pwa/app/components/ui/tabs.tsx
pwa/app/lib/utils.ts
pwa/app/tailwind.css
pwa/components.json
pwa/package-lock.json
pwa/package.json
pwa/tailwind.config.ts

This [initializes shadcn components](https://ui.shadcn.com/docs/installation/remix) and its settings, and adds 2 example components.

Add shadcn components

---

pwa/.eslintrc.cjs
pwa/README.md
pwa/package-lock.json
pwa/package.json
pwa/tsconfig.json
pwa/vite.config.ts

Adds icons to the stack via unplugin and iconify. These are a superset of the icons previously available to us.

Add icons library to new PWA

---

pwa/app/components/tba/allianceSelectionTable.tsx
pwa/app/components/tba/inlineIcon.tsx
pwa/app/components/ui/badge.tsx
pwa/app/components/ui/table.tsx
pwa/app/lib/utils.ts
pwa/app/routes/event.$eventKey.tsx
pwa/app/tailwind.css
pwa/package.json

Adds event page with match results + alliance table page to new PWA. Not much else.

[PWA] Add event page

---

pwa/vite.config.ts

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/the-blue-alliance/the-blue-alliance/pull/6151).
* #6152
* __->__ #6151

[PWA] Return 'unknown' git commit if git command fails

---

pwa/app/routes/privacy.tsx

[PWA] Port privacy page to tailwind

---

pwa/app/api/v3.ts
pwa/app/routes/event.$eventKey.tsx
src/backend/web/static/swagger/api_v3.json

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/the-blue-alliance/the-blue-alliance/pull/6190).
* #6195
* #6192
* #6191
* __->__ #6190

Fix undefined/null mixup in Event models in API spec

---

pwa/app/root.tsx
pwa/app/routes/event.$eventKey.tsx
pwa/app/routes/events.$year.tsx

https://remix.run/docs/en/main/guides/client-data#skip-the-hop

[PWA] Hit API directly on client

---

pwa/app/api/v3.ts
pwa/app/routes/event.$eventKey.tsx
src/backend/web/static/swagger/api_v3.json

god bless [jq](https://jqkungfu.com/)

More API spec fixes

---

.gitignore
ops/lint_py3.sh

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/the-blue-alliance/the-blue-alliance/pull/6208).
* #6207
* __->__ #6208

gitignore .venv, ignore .venv/node_modules in py3 linting

---

pwa/app/routes/thanks.tsx

Created the react thanks page
Eugene
[](https://github.com/the-blue-alliance/the-blue-alliance/issues/6168)
Local run

pwa thanks page

---

pwa/app/routes/team.$teamNumber.tsx

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/the-blue-alliance/the-blue-alliance/pull/6229).
* #6230
* __->__ #6229

[PWA] Add team page meta title/description

---

pwa/.eslintrc.cjs
pwa/app/components/tba/inlineIcon.tsx
pwa/app/components/tba/teamRobotPicsCarousel.tsx
pwa/app/components/ui/card.tsx
pwa/app/components/ui/carousel.tsx
pwa/app/routes/team.$teamNumber.tsx
pwa/package-lock.json
pwa/package.json

Autoscrolls to the right (and loops) every few sec.
The card and carousel components are stock shadcn.
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/the-blue-alliance/the-blue-alliance/pull/6230).
* __->__ #6230
* #6229

Add team header info; add team robot pics carousel

---

pwa/app/components/tba/allianceSelectionTable.tsx
pwa/app/components/tba/matchResultsTables/doubleElim.tsx
pwa/app/components/tba/matchResultsTables/quals.tsx
pwa/app/routes/team.$teamNumber.tsx

[PWA] Consistent styling

---

pwa/app/api/v3.ts
src/backend/web/static/swagger/api_v3.json

team/event fields that had nullable removed were verified against all team/event responses from prod

Fix api spec nullable fields. Fix media details type.

---

pwa/.eslintrc.cjs
pwa/app/components/ui/credenza.tsx
pwa/app/components/ui/dialog.tsx
pwa/app/components/ui/drawer.tsx
pwa/app/lib/hooks.ts
pwa/app/lib/utils.ts
pwa/app/root.tsx
pwa/app/routes/event.$eventKey.tsx
pwa/package-lock.json
pwa/package.json

On mobile, this is a drawer:
It can be dismissed by swiping.
On desktop, it's a modal:
The intent here is to put match schedule, etc. For now, its just a name.

[PWA] Test out credenza (dialog+drawer) for teams at event list

---

pwa/.eslintrc.cjs
pwa/app/components/tba/teamAvatar.tsx
pwa/app/routes/team.$teamNumber.tsx
pwa/tailwind.config.ts

Add avatar

---

pwa/app/root.tsx

[PWA] Add root error boundary

---

pwa/app/routes/contact.tsx
pwa/app/tailwind.css

pwa contact page
pwa contact page
pwa contact page
[](https://github.com/orgs/the-blue-alliance/projects/5/views/1?pane=issue&itemId=74278139)
local run

pwa contact page

---

pwa/app/routes/donate.tsx

donate page
donate page
donate page
https://github.com/the-blue-alliance/the-blue-alliance/issues/6167
local

[PWA] donate page

---

pwa/app/api/v3.ts
pwa/app/components/tba/rankingsTable.tsx
src/backend/web/static/swagger/api_v3.json

W-L-T / DQ / Played
2015 support

[PWA] More ranking columns

---

pwa/app/routes/add-data.tsx

pwa add data page
pwa add data page
pwa add data page
https://github.com/the-blue-alliance/the-blue-alliance/issues/6165
local run

pwa add data page

---

pwa/app/components/tba/globalLoadingProgress.tsx
pwa/app/components/ui/progress.tsx
pwa/app/root.tsx
pwa/package-lock.json
pwa/package.json

https://github.com/user-attachments/assets/45d11764-0978-424c-87f3-83f8e34c2040

[PWA] Add global navigation progress

---

pwa/app/lib/insightUtils.ts
pwa/app/routes/insights.($year).tsx

not the prettiest but its a start

[PWA] Add basic insights route

---

src/backend/common/helpers/insights_helper.py
src/backend/common/models/insight.py

Add most awards, most regional/district win leaderboards

---

pwa/app/lib/insightUtils.ts

[PWA] add display strings for new insights

---

pwa/app/api/v3.ts
pwa/package-lock.json
src/backend/api/handlers/event.py
src/backend/api/main.py
src/backend/common/queries/dict_converters/media_converter.py
src/backend/web/static/swagger/api_v3.json

This is needed for the frontend so that we can show team robot photos without making 40-80 requests.

Add event/key/team_media API endpoint

---

pwa/app/components/ui/accordion.tsx
pwa/app/lib/teamUtils.test.ts
pwa/app/lib/teamUtils.ts
pwa/app/routes/team.$teamNumber.tsx
pwa/package-lock.json
pwa/package.json

----
---
---
---
---
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/the-blue-alliance/the-blue-alliance/pull/6303).
* #6305
* __->__ #6303

[PWA] Add vitest; add team sponsor parsing & accordion

---

pwa/app/lib/mediaUtils.ts
pwa/app/routes/event.$eventKey.tsx
pwa/app/tailwind.css

~Performance is pretty bad. Need to figure out improvements~
<details>
</details>

[PWA] Add images to event teams tab

---

pwa/app/components/tba/teamRobotPicsCarousel.tsx
pwa/app/components/tba/teamSocialMediaList.tsx
pwa/app/components/ui/separator.tsx
pwa/app/routes/team.$teamNumber.tsx
pwa/package-lock.json
pwa/package.json

TOC isn't functional but its there.
<details>
</details>

[PWA] Add team socials to page, improve responsiveness team pg

---

pwa/app/entry.client.tsx
pwa/app/entry.server.tsx
pwa/app/root.tsx
pwa/instrumentation.server.mjs
pwa/package-lock.json
pwa/package.json
pwa/server.js
pwa/vite.config.ts

https://docs.sentry.io/platforms/javascript/guides/remix/#install

[PWA] Sentry remix

---

pwa/app/routes/about.tsx
pwa/app/routes/add-data.tsx
pwa/app/routes/thanks.tsx

Fix typos & unnecessary changes

[PWA] Make static pages match prod

---

pwa/app/lib/utils.ts
pwa/app/routes/events.($year).tsx
pwa/app/routes/insights.($year).tsx
pwa/app/routes/team.$teamNumber.tsx

[pwa] Add pluralize helper. Hide 0-0-0 offseason records

---

pwa/app/components/tba/nav.tsx
pwa/app/routes/events.($year).tsx

[PWA] Responsive navbar

---

pwa/app/lib/matchUtils.test.ts
pwa/app/lib/matchUtils.ts
pwa/app/routes/match.$matchKey.tsx

[PWA] Base match page

---

pwa/app/components/tba/matchResultsTable.tsx
pwa/app/routes/team.$teamNumber.($year).tsx

Also fixes a missing sort on match tables that was driving me crazy

[PWA] Add year support to team pages

---

.github/workflows/pull_request.yml
.github/workflows/push.yml
pwa/README.md
pwa/package-lock.json
pwa/package.json
pwa/vite.config.ts

this would have saved myself 4 minutes and @dracco1993 10 minutes
this is what happens if vars are not set properly:

[PWA] add .env validation

---

.github/workflows/pull_request.yml
.github/workflows/push.yml

Fixes regression introduced by https://github.com/actions/upload-artifact/releases/tag/v4.4.0

Include hidden files when uploading coverage

---

pwa/app/api/v3.ts
src/backend/web/static/swagger/api_v3.json

e.g. https://www.thebluealliance.com/api/v3/events/2004

Properly mark event.district as nullable in api spec

---

src/backend/web/handlers/team.py

Will merge once teams are in the DB

Support up to team 10999

---

.github/workflows/dependabot_auto_merge.yml

Based on: https://gist.github.com/xt0rted/46475099dc0a70ba63e16e3177407872

Use merge bot token for dependabot automerge

---

pwa/app/root.tsx

https://the-blue-alliance.sentry.io/issues/6042521923

[PWA] Remove in-memory LRU cache

---

pwa/app/components/tba/teamPageTeamInfo.tsx
pwa/app/lib/utils.tsx
pwa/app/routes/team.$teamNumber.($year).tsx
pwa/app/routes/team.$teamNumber.history.tsx

[PWA] Add team history page

---

pwa/app/components/tba/matchResultsTable.tsx

[pwa] fix quals being included in round1 of match tables

---

.github/workflows/pull_request.yml
pwa/.gitignore
pwa/README.md
pwa/package-lock.json
pwa/package.json
pwa/playwright.config.ts
pwa/tests/index.spec.ts

There are still some improvements to make here but this is a good first step.

[PWA] Add Playwright for e2e tests

---

pwa/app/components/tba/allianceSelectionTable.tsx
pwa/app/components/tba/awardRecipientLink.tsx
pwa/app/components/tba/links.tsx
pwa/app/components/tba/matchResultsTable.tsx
pwa/app/components/tba/teamEventAppearance.tsx
pwa/app/routes/event.$eventKey.tsx
pwa/app/routes/insights.($year).tsx
pwa/app/routes/match.$matchKey.tsx
pwa/app/routes/team.$teamNumber.($year).tsx
pwa/app/routes/team.$teamNumber.history.tsx

District points needs some UI cleanup but it's a start.
Also adds TeamLink and EventLink components to make lives easier
<details>
</details>

[pwa] clean up event statuses on event appearances, add TeamLink

---

pwa/app/api/v3.ts
pwa/app/components/tba/cards.tsx
pwa/app/lib/insightUtils.ts
pwa/app/routes/insights.($year).tsx
src/backend/web/static/swagger/api_v3.json

<details>
Year = 0:
----
Year = 2024:
</details>

[pwa] Add notables to /insights

---

src/backend/tasks_io/handlers/frc_api.py
src/backend/tasks_io/handlers/tests/frc_api_teams_test.py

Fixes failing tests https://github.com/the-blue-alliance/the-blue-alliance/actions/runs/12419002056/job/34673381033

[py3] Use days since epoch instead of day of year to ensure monotonically increasing count

---

src/backend/web/templates/admin/event_details.html

Fixes 2006ct admin page 500ing

Handle null created/updated times

---

src/backend/common/models/event_details.py
src/backend/common/models/tests/event_details_test.py

Skip empty sort orders

---

.github/dependabot.yml
pwa/package-lock.json
pwa/package.json

#6981 and #6983 are dependent on each other, so this resolves it for now and for the future.
(this is the first PR made with [jj](https://github.com/jj-vcs/jj)!)

Update vitest; create vitest dependabot group

---

src/backend/common/models/district.py
src/backend/web/local/bootstrap.py

This doesn't bootstrap district rankings because I can't figure out how. But you can kick those by visiting http://localhost:8080/tasks/math/do/district_rankings_calc/key.

Add District and DistrictTeam bootstrapping for local dev

---

pwa/app/api/v3.ts
src/backend/web/static/swagger/api_v3.json

Not final, needs cleanup and verification

2025 Score Breakdown

---

src/backend/web/static/swagger/api_v3.json

Example response from the API - our case for the breakdown locations is just wrong. This PR corrects the case of the node locations.
```
{
"MatchScores": [
{
"matchLevel": "Qualification",
"matchNumber": 1,
"winningAlliance": 1,
"tiebreaker": {
"item1": -1,
"item2": ""
},
"coopertitionBonusAchieved": false,
"coralBonusLevelsThresholdCoop": 3,
"coralBonusLevelsThresholdNonCoop": 4,
"coralBonusLevelsThreshold": 4,
"bargeBonusThreshold": 0,
"autoBonusCoralThreshold": 1,
"autoBonusRobotsThreshold": 1,
"alliances": [
{
"alliance": "Blue",
"autoLineRobot1": "No",
"endGameRobot1": "Parked",
"autoLineRobot2": "No",
"endGameRobot2": "Parked",
"autoLineRobot3": "No",
"endGameRobot3": "None",
"autoReef": {
"topRow": {
"nodeA": false,
"nodeB": false,
"nodeC": false,
"nodeD": false,
"nodeE": false, …
```

Update match breakdown autoReef and teleopReef to have proper case scoring locations. Ex: NodeA -> nodeA

---

src/backend/web/static/css/less_css/less/tba/tba_match_table.less
src/backend/web/templates/match_partials/match_table_cell_macros.html

Add third RP dot for 2025 match score row

---

src/backend/web/templates/match_partials/match_breakdown/match_breakdown_2025.html

Add level counts to auto/teleop reef in 2025 match breakdowns

---

src/requirements.txt

Bumping these dependencies got a little stuck on each other (mostly core against the other ones) - so bumping them altogether

Bump several Google deps together

---

src/backend/common/helpers/matchstats_helper.py

Add 2025 coprs

---

src/backend/web/handlers/admin/blueprint.py
src/backend/web/handlers/admin/cache.py
src/backend/web/handlers/admin/tests/event_test.py
src/backend/web/templates/admin/base.html
src/backend/web/templates/admin/cached_query_detail.html
src/backend/web/templates/admin/cached_query_info.html
src/backend/web/templates/admin/cached_query_list.html

This will let us debug stale `CachedQueryResult`s, and easily clear them

Add admin panel views 

---

src/backend/web/static/javascript/tba_js/tba.js
src/backend/web/templates/admin/base.html

I REALLY need a visual indicator to let me know if I'm in the production admin interface or a local admin interface 🤦

Change admin nav bar to green for local env

---

src/backend/common/cache_clearing/get_affected_queries.py

this seems to have been missing from the start

Add cache clearing for RegionalEventsQuery

---

src/backend/common/helpers/season_helper.py
src/backend/common/manipulators/award_manipulator.py
src/backend/common/manipulators/event_details_manipulator.py
src/backend/common/manipulators/match_manipulator.py
src/backend/common/manipulators/tests/award_manipulator_test.py
src/backend/common/manipulators/tests/event_details_manipulator_test.py
src/backend/common/manipulators/tests/match_manipulator_test.py
src/backend/common/models/regional_champs_pool.py
src/backend/tasks_io/handlers/math.py
src/backend/web/handlers/admin/blueprint.py
src/backend/web/handlers/admin/regional_champs_pool.py
src/backend/web/templates/admin/base.html
src/backend/web/templates/admin/event_details.html
src/backend/web/templates/admin/regional_champs_pool_list.html

Let's actually start computing some advancement points, now that we have real events

Enqueue regional champs points calc tasks

---

src/backend/tasks_io/handlers/math.py
src/backend/web/handlers/admin/blueprint.py
src/backend/web/handlers/district.py
src/backend/web/handlers/event.py
src/backend/web/templates/event_details.html
src/backend/web/templates/regional_details.html

Now, show the rankings on the web (we have not yet hooked up computing the advancement, but that'll come in a future diff)

Show regional CMP points on web

---

src/backend/web/static/javascript/tba_js/tba_auth.js
src/backend/web/static/javascript/tba_js/tba_firebase.js
src/backend/web/templates/base.html

Attempt to revert some Firebase changes from https://github.com/the-blue-alliance/the-blue-alliance/pull/7209 - a handful of users are reporting problems with login, but I can't repo

Revert Firebase changes

---

src/backend/common/helpers/event_insights_helper.py
src/backend/web/templates/event_partials/event_insights_2025.html

Add 2025 event insights

---

pwa/app/root.tsx

See: https://webmasters.stackexchange.com/questions/82020/seo-safe-way-to-run-beta-of-new-site-on-seperate-domain

[PWA] Add canonical URL & noindex to beta site

---

subtrees/bootstrap/less/navs.less

Reverts the-blue-alliance/the-blue-alliance#7231

Revert "Add nav bar padding; Fixes #7225"

---

pwa/app/lib/matchUtils.ts
pwa/app/lib/utils.test.ts
pwa/app/lib/utils.tsx
pwa/app/routes/event.$eventKey.tsx
pwa/tsconfig.json

[PWA] Add COPRs and basic match stats to event insights tab

---

pwa/app/routes.ts
pwa/package-lock.json
pwa/package.json
pwa/vite.config.ts

[PWA] Enable v3_routeConfig option for RR7 upgrade

---

.github/dependabot.yml
pwa/package-lock.json
pwa/package.json

Bump vitest+coverage and fix dependabot

---

src/backend/web/templates/match_partials/match_breakdown/match_breakdown_2025.html

Rename tech foul to major foul for 2025

---

src/frontend/eventwizard/components/EventSelector.js
src/frontend/eventwizard/components/EventWizardTabFrame.js
src/frontend/eventwizard/components/infoTab/AddRemoveTeamMap.js
src/frontend/eventwizard/components/infoTab/AddRemoveWebcast.js
src/frontend/eventwizard/components/infoTab/EventInfoTab.js
src/frontend/eventwizard/components/infoTab/PlayoffTypeDropdown.js
src/frontend/eventwizard/components/infoTab/SyncCodeInput.js

- Enable search on events dropdown
- Improve tabs that aren't yet implemented
- Fix styling on event info tab
- Set event info tab to be open by default so it's not just starting out with nothing
Just some small things that were getting in my way or bothering me while managing events
Tested locally via docker-compose setup

Cleanup styles on Event Wizard 2

---

pwa/app/components/tba/eventListTable.tsx
pwa/app/components/tba/inlineIcon.tsx
pwa/app/components/ui/button.tsx
pwa/app/routes/event.$eventKey.tsx

Does not show up on non-this-week events:

[pwa] add webcast links to homepage and event page

---

src/backend/common/helpers/event_insights_helper.py

Fix event insights erroring on 0 elims played

---

src/backend/common/helpers/district_helper.py
src/backend/common/helpers/regional_champs_pool_helper.py
src/backend/common/helpers/tests/district_helper_test.py
src/backend/common/helpers/tests/regional_champs_pool_helper_test.py
src/backend/common/models/regional_pool_ranking.py
src/backend/tasks_io/handlers/math.py
src/backend/tasks_io/handlers/tests/district_rankings_calc_test.py
src/backend/tasks_io/handlers/tests/regional_champs_pool_rankings_calc_test.py
src/backend/web/templates/regional_details.html

Do what the manual says in section 12.3.1, and link back an explainer in the table.
Fixes https://github.com/the-blue-alliance/the-blue-alliance/issues/7233

Handle single event teams in regional champs points

---

src/backend/common/helpers/mytba.py

Fix 500 on mytba

---

src/backend/common/cache_clearing/get_affected_queries.py
src/backend/common/cache_clearing/tests/database_cache_clearer_test.py

this was probably always a bug?

Add cache clearing across renamed district

---

src/backend/web/templates/admin/district_details.html
src/backend/web/templates/admin/regional_champs_pool_list.html

show district/regional advancement in admin panel

---

src/backend/tasks_cpu/handlers/insights.py
src/cron.yaml

Title. Also adds a default year of current season to the enqueue endpoint.

Add leaderboard calculations to cron

---

pwa/app/components/tba/eventListTable.tsx

[PWA] Hide 'Watch Now' text on mobile for gameday buttons

---

pwa/app/lib/insightUtils.ts

[PWA] add 2 more insight names

---

src/backend/common/queries/dict_converters/match_converter.py

Bump match converter subveresion

---

src/backend/common/helpers/event_insights_helper.py

Fix denominator for event insights

---

src/backend/common/helpers/insights_leaderboard_event_helper.py
src/backend/common/helpers/insights_leaderboard_match_helper.py

These are both OOMing and also not useful, so just skip them for overall year=0.

Skip certain leaderboards for year=0

---

src/backend/common/helpers/tests/insights_helper_utils_test.py
src/backend/common/manipulators/tests/base_manipulator_test.py
src/backend/tasks_io/handlers/frc_api.py

Fix format/linting errors

---

src/backend/common/helpers/insights_leaderboard_team_helper.py
src/backend/common/helpers/insights_notable_helper.py
src/backend/common/helpers/tests/insights_leaderboard_team_helper_test.py
src/backend/common/helpers/tests/insights_notable_helper_test.py
src/backend/common/models/insight.py

1. Adds DCMP winner notable
2. Adds longest Einstein streak leaderboard (does not support multiple streaks currently)
idk why it wants me to reformat those other files but it does

Add 2 new insights

---

src/backend/api/handlers/regional_advancement.py
src/backend/api/handlers/tests/regional_advancement_test.py
src/backend/api/main.py
src/backend/web/static/swagger/api_v3.json

As title, this is structured similarly to the district rankings endpoint

Add API endpoint for regional rankings

---

src/backend/common/helpers/firebase_pusher.py
src/backend/common/helpers/tests/firebase_pusher_test.py
src/backend/tasks_io/handlers/nexus_api.py

This was originally coupled to the live event update cronjob, which only runs every 5 minutes.
With this approach, we can instead patch only the keys in firebase we need (forgive the definitely incorrect, very ugly test helper) as fast as we fetch info

Update event now_queuing directly after nexus fetch

---

src/backend/common/helpers/match_time_prediction_helper.py
src/backend/tasks_io/handlers/live_events.py

Make two small changes after some chatting with @eforbes --
- update the "data is stale" check to instead look at if the most recently played match, and if nexus doesn't say the match is `ON_FIELD`, then we can assume that the data is unreliable.
- also take nexus predicted times across breaks, as this can include information from the lead queuer about when matches will resume, so the predictions can be more accurate

[nexus] tweak time predictions

---

src/backend/common/frc_api/frc_api.py
src/backend/common/frc_api/tests/frcapi_test.py
src/backend/tasks_io/datafeeds/datafeed_fms_api.py
src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_test.py

I'd eventually like to refactor this into a base class, so it'd be possible for us to have other datafeeds write to GCS as well.
But for now, consolidate all the logic into one class, instead of having reads in the API class and writes in the datafeed.

[datafeed] Move all response saving/loading into FRCAPI class

---

src/backend/api/handlers/district.py
src/backend/api/handlers/regional_advancement.py
src/backend/api/main.py
src/backend/common/models/regional_pool_advancement.py
src/backend/tasks_io/datafeeds/parsers/ra/regional_advancemnet_parser.py
src/backend/web/static/swagger/api_v3.json
src/backend/web/templates/admin/regional_champs_pool_list.html
src/backend/web/templates/regional_details.html

As title; adds API endpoints for district/regional advancement

Add API endpoints for district/regional advancement

---

src/backend/web/templates/regional_details.html

Add javascript fitering of regional advancement table

---

src/backend/web/renderers/team_renderer.py
src/backend/web/templates/admin/district_details.html
src/backend/web/templates/admin/district_list.html
src/backend/web/templates/team_details.html

Backlink to regional rankings from team page

---

pwa/app/lib/insightUtils.ts
pwa/app/routes/insights.($year).tsx

Also adds DCMP notable leaderboard name and Einstein streak leaderboard name since those were missing

[PWA] Add dropdown year selector to insights page

---

src/backend/common/helpers/tests/webcast_online_helper_test.py
src/backend/common/helpers/webcast_online_helper.py

It's available in the youtube API: https://developers.google.com/youtube/v3/docs/videos/list?

fetch viewer count for youtube streams

---

src/backend/common/helpers/firebase_pusher.py
src/backend/common/helpers/special_webcast_helper.py
src/backend/common/helpers/tests/firebase_pusher_test.py
src/backend/common/helpers/tests/special_webcast_helper_test.py
src/backend/common/models/webcast.py
src/backend/tasks_io/handlers/live_events.py
src/backend/tasks_io/helpers/live_event_helper.py
src/backend/tasks_io/helpers/tests/live_event_helper_test.py
src/backend/web/handlers/index.py

There's some lingering TODOs to do this, and it improves separation of concerns of this code a bit.

Remove unrelated helpers from firebase_pusher

---

pwa/app/api/v3.ts
src/backend/api/handlers/status.py
src/backend/api/handlers/team.py
src/backend/api/handlers/tests/status_test.py
src/backend/common/consts/teams.py
src/backend/common/sitevars/apistatus.py
src/backend/common/sitevars/tests/apistatus_test.py
src/backend/tasks_io/handlers/tests/frc_api_event_list_test.py
src/backend/web/handlers/admin/apistatus.py
src/backend/web/handlers/admin/tests/apistatus_test.py
src/backend/web/static/swagger/api_v3.json

Also formats the api_v3 spec to be more consistent with the rest of itself.

Add max_team_page to Status endpoint

---

src/backend/common/models/event.py

so we can redirect to the right thing

correct agenda link for cmp

---

src/backend/web/templates/insights.html

Changed "Most Regional & District Championship Chairman's Award Wins" to "Most Regional & District Championship Impact Award Wins".
Since the award was renamed.
Reflects the current name of the award

Update Insights page text from Chairman's to Impact

---

src/backend/tasks_io/datafeeds/datafeed_nexus.py
src/backend/tasks_io/datafeeds/tests/datafeed_nexus_test.py
src/backend/tasks_io/handlers/nexus_api.py

Since the CMP division codes follow the FIRST API

Use API short overrides with nexus

---

src/backend/web/local/bootstrap.py

When you bootstrap a district (eg `ne`), it will now bootstrap all events and rankings, as opposed to just the teams and the district object itself.
Other endpoint fetches were modified to just support the fetch_endpoint method now being a Union rather than a Dict return type

Bootstrap events and rankings when bootstrapping districts

---

pwa/app/routes/team.$teamNumber.history.tsx

Cuts down on repeated text in the UI.

[PWA] Don't repeat year multiple times in team history table

---

pwa/app/components/tba/matchResultsTable.tsx
pwa/app/routes/match_suggestion.tsx

Super hacky implementation, just trying to get this in for RSN at Champs

[PWA] Match suggestions

---

src/backend/web/templates/team_partials/team_info.html

Correct Nexus pit link in Currently Competiting section

---

src/backend/common/helpers/insights_helper.py

Fix formatting

---

pwa/app/routes/team.$teamNumber.history.tsx

Week 0 was showing out of order before.

[PWA] Correctly sort events on team history page

---

src/backend/common/helpers/insights_leaderboard_team_helper.py
src/backend/common/helpers/tests/insights_leaderboard_team_helper_test.py

These only make sense to be overall rather than per-year

Make impact/WFFA leaderboards year=0 only

---

pwa/package-lock.json
pwa/package.json
pwa/server.js

[PWA] Upgrade to Express 5

---

src/backend/web/static/javascript/tba_js/eventwizard.js
src/backend/web/static/javascript/tba_js/eventwizard_apiwrite.js
src/backend/web/templates/eventwizard.html

Maintaining report parsing is such a pain.

Update eventwizard for double elim matches

---

src/backend/web/static/javascript/tba_js/eventwizard_apiwrite.js

Update EventWizard team validation to support 5-digit team numbers
eventwizard was rejecting a valid 5-digit team (10229)

Update EventWizard team validation to support 5-digit team numbers

---

pwa/app/routes/team.$teamNumber.history.tsx

<details><summary>Screenshots</summary>
<p>
Many
One
None
</p>
</details>

[PWA] Add banners to team history page

---

pwa/package-lock.json
pwa/package.json

Fixes warning shown on npm install

[PWA] Fix npm warning

---

pwa/package-lock.json
pwa/package.json

Fixes https://the-blue-alliance.sentry.io/issues/6651804737/?query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&stream_index=0
Result of #7737
i don't know why it works in dev but not build

[PWA] Add zod as first party dependency, fix 500

---

src/backend/common/helpers/insights_helper.py
src/backend/common/helpers/tests/insights_helper_test.py

Fix einstein streak calculations
Fixes the-blue-alliance/the-blue-alliance#7323
Just through specs, as I don't have 10 years of data loaded locally.  😅
N/A

Fix einstein streak calculations

---

src/cron.yaml

Previously only done manually, now just adding to cron

Add district insights to cron

---

src/backend/common/helpers/insights_helper.py
src/backend/common/helpers/tests/insights_helper_test.py

Fix formatting CI

---

pwa/package-lock.json
pwa/package.json

Used to be used for old API client, unused now

[PWA] Remove unused dependencies

---

.github/dependabot.yml
.github/workflows/pull_request.yml
pwa/devbox.json
pwa/devbox.lock
pwa/package-lock.json
pwa/package.json
pwa/pwa.yaml

Also pins @types/node to 22.x.

[PWA] Update to node 22

---

src/backend/common/models/event.py

Code hasn't been touched in 5 years but randomly broke recently. IDEK

Fix CI formatting

---

.github/workflows/push.yml

push was missing a couple pull_request PWA-related workflows

Synchronize push and pull_request workflows (PWA runs)

---

pwa/app/api/tba/mobile/client/client.ts
pwa/app/api/tba/mobile/client/types.ts
pwa/app/api/tba/mobile/client/utils.ts
pwa/app/api/tba/mobile/core/bodySerializer.ts
pwa/app/api/tba/mobile/core/types.ts
pwa/app/api/tba/read/client/client.ts
pwa/app/api/tba/read/client/types.ts
pwa/app/api/tba/read/client/utils.ts
pwa/app/api/tba/read/core/bodySerializer.ts
pwa/app/api/tba/read/core/types.ts
pwa/app/api/tba/read/sdk.gen.ts
pwa/app/api/tba/read/zod.gen.ts
pwa/package-lock.json
pwa/package.json

[PWA] Upgrade api regen

---

pwa/app/components/ui/accordion.tsx

updates accordion component to latest shadcn mainline

[PWA] Update shadcn accordion

---

pwa/app/components/ui/popover.tsx
pwa/app/components/ui/progress.tsx
pwa/app/components/ui/scroll-area.tsx
pwa/app/components/ui/separator.tsx

updates to latest shadcn components. tested locally, looks good

[PWA] Upgrade popover, progress, scroll, and separator shadcn components

---

pwa/app/components/ui/tooltip.tsx

updating shadcn component to latest. tested locally

[PWA] Update tooltip shadcn component

---

.github/workflows/pull_request.yml
pwa/app/routes/team.$teamNumber.($year).tsx
pwa/playwright.config.ts
pwa/tests/team.spec.ts

wahoo
needs a SECRET (not env var) named
```
TBA_API_READ_KEY
```

[PWA] Enable E2E tests on CI

---

pwa/app/routes/match.$matchKey.tsx

wasn't deploying for a bit, kicking deploy with a change to pwa/

[PWA] Bump deploy

---

src/backend/common/helpers/insights_leaderboard_team_helper.py

Lol. Turns out this makes no real difference and just uses more memory.

Revert "Revert "Revert "Prefetch event data when processing insights (#7941)" (#7943)" (#7945)"

---

src/backend/common/helpers/insights_leaderboard_team_helper.py

Fix event streak insight being broken by covid

---

.github/workflows/pull_request.yml
.github/workflows/push.yml

I do not know why this is failing so just going to disable it while we work on it asynchronously

Disable PWA e2e CI

---

pwa/app/api/tba/mobile/@tanstack/react-query.gen.ts
pwa/app/api/tba/mobile/client/client.ts
pwa/app/api/tba/mobile/core/params.ts
pwa/app/api/tba/mobile/core/types.ts
pwa/app/api/tba/read/@tanstack/react-query.gen.ts
pwa/app/api/tba/read/client/client.ts
pwa/app/api/tba/read/core/params.ts
pwa/app/api/tba/read/core/types.ts
pwa/package-lock.json
pwa/package.json

[PWA] update openapi-ts & regen API

---

src/backend/common/models/notifications/requests/request.py

This didn't get updated in https://github.com/the-blue-alliance/the-blue-alliance/pull/8053 - so attempting to update it now. No idea if these keys or values are right - this call seems a little bork'd to begin with.

Update track notifications for the Google Analytics change
