the-blue-alliance/the-blue-alliance

- admin_main.py
- controllers/admin/admin_team_controller.py
- helpers/event_team/event_team_test_creator.py
- helpers/team/team_test_creator.py
- templates/admin/index.html
- tests/test_team_test_creator.py
While #1103 exists, allows creating local test teams to create test matches, events, etc.
> Adds local test team creation to bypass broken FMS list.

- models/team.py
StringProperty will truncate at 500 characters, and some teams
have names that are longer than that.
My quick read of the [docs](https://cloud.google.com/appengine/articles/update_schema) indicates that this should just work with old datastore entries but I didn't test that.
> Change Team.name to be a TextProperty (fixes #1110)

- controllers/admin/suggestions/admin_match_video_suggestions_review_controller.py
This will allow us to review matches without totally destroying a browser when there are hundreds pending.
Test plan: I tested this locally by adding a suggestion to a match, and seeing that the suggestion page loaded.
> Add limit to video suggestions review page.

- helpers/event_helper.py
- run_tests.py
- tests/test_event_get_short_name.py
Also simplify and link to the Android code to make it easier to keep them
in sync. E.g. '(.*)' is as good as '(.*)(FIRST Robotics|FRC)?' since the
"greedy quantifier" .* keeps (FIRST Robotics|FRC)? from matching any chars.
re.match() matches the start of the input string, so .* on the end of the pattern
does nothing.
> Refine the server's name shortener like the Android app's

- templates/apidocs.html
Stubbed my toe on this one a bit earlier. The docs declare `country` as being the key, when the API actually uses `country_name`.
> Update country_name key in API docs.

- helpers/notification_sender.py
Same as apiv2 (see
https://github.com/the-blue-alliance/the-blue-alliance/blob/master/controllers/api/api_base_controller.py#L60)
Fixes #1178
> Add application/json Content-Type to webhooks

- templates/apidocs.html
Changes "Type" to be "type", to match the rest of the models (and the capitalization that the key should be)
> Fix typo in Media model

- datafeeds/parsers/json/json_rankings_parser.py
- tests/test_api_trusted.py
Broken off from #1197 
Changed the trusted API to take W/L/T out of required parameters (moved to generic breakdown category) to accommodate this year's game. This will require an update to Cheesy Arena (which I'll take care of).
Closes #1115
> Trusted api updates

- consts/auth_type.py
- controllers/admin/admin_api_controller.py
- controllers/api/api_trusted_controller.py
- models/api_auth_access.py
- templates/admin/api_add_auth.html
- templates/admin/api_edit_auth.html
- templates/admin/api_manage_auth.html
- tests/test_api_trusted.py
Removes EVENT_DATA permission and splits it up so each endpoint has its own permission. 
Split from #1197
> Subdivide trusted api permissions

- .gitignore
- README.md
- pavement.py
This incorporates what I've learned so far on setting up a TBA server:
additional tool installations, updated hyperlinks, and updated
configuration steps. Thanks, Eugene.
Also, saving a personal deploy.sh file (.gitignored) avoids needing to edit
app.yaml and avoid checking in that edit.
[TIL: When the GitHub Windows app creates a PR, it defaults to the repo fork rather than the original repo.]
> Update the server setup instructions

- tests/test_apiv2_team_controller.py
- tests/test_award_type_parser.py
These don't do anything useful, and clutter tests.
> Remove unneeded prints to make tests less verbose. Towards #1275

- tests/test_datafeed_usfirst_teams.py
Towards #1274 
Need to remove or update these datafeeds. I think they're going with the move to the FIRST API entirely.
> Skip tests for broken usfirst pages.

- helpers/firebase/firebase_pusher.py
- notifications/alliance_selections.py
- notifications/awards_updated.py
- notifications/base_notification.py
- notifications/district_points_updated.py
- notifications/level_starting.py
- notifications/match_score.py
- notifications/schedule_updated.py
- notifications/upcoming_match.py
Working towards #1262
For every notification (which we currently push to the ticker firebase), also push it to an endpoint for the specific event (at event/<key>) and for the parent district, only if the event is within a district (at district/<abbrev>).
> Add Firebase feeds for events/districts

- consts/event_type.py
- controllers/datafeed_controller.py
- cron_main.py
- datafeeds/datafeed_fms_api.py
- datafeeds/parsers/fms_api/fms_api_event_list_parser.py
- helpers/event_helper.py
- test_data/fms_api/2015_event_list.json
- tests/test_fms_api_event_list_parser.py
Use FMSAPI for event list. Hits [Event Listing](http://docs.frcevents2.apiary.io/#reference/season-data/event-listings/retrieve-event-listings) endpoint. 
Current functionality maintained (e.g. skips over CMP events).
The only things missing from the API are the venue address and event website and I've submitted a feature request for them: https://usfirst.collab.net/sf/go/artf4727
This does not import EventTeams yet, that will be a separate PR
> Events From FMSAPI

- controllers/datafeed_controller.py
- cron_main.py
- datafeeds/datafeed_fms_api.py
- datafeeds/parsers/fms_api/fms_api_team_details_parser.py
- models/district_team.py
- templates/datafeeds/fmsapi_eventteams_enqueue.html
- tests/test_fms_api_team_parser.py
This is the continuation of #1270 - MERGE THAT FIRST
This PR updates the FMSAPI Team Details parser to account for paginated responses,
see f77e4b8. Otherwise, it'll add a task into the queue for each event for eventteams
after fetching event details.
Since the FMSAPI response is the same endpoint as team details, we can update & store
full Team, DistrictTeam, and Robot models from it. This might make the regular rolling
team update cronjob obsolete.
> Fetch EventTeams from FMSAPI

- app.yaml
Old Django is getting deprecated. https://cloud.google.com/appengine/docs/deprecations/django
Tested locally by browsing around to a few pages, they all worked. Tests pass.
> Bumps Django version.

- .gitignore
- admin_main.py
- controllers/admin/admin_cron_controller.py
- controllers/api/api_district_controller.py
- controllers/datafeed_controller.py
- cron_main.py
- index.yaml
Admin task to run at /admin/district_teams_update/<year> that will fetch all district events in the year,
and select the district each team competed in most often to use as the "home" district.
Closes #1231
> added admin script to generate past district teams.

- README.md
`git://` repo addresses cannot be used for pushing (https://gist.github.com/grawity/4392747)
> Updated getting started docs to use https:// repo address

- .travis.yml
It'll be removed in a later version of `pip`, so we might as well remove it now.
> travis: Remove deprecated --use-mirrors

- templates/suggest_match_video_review_list.html
- templates/suggest_team_media_review_list.html
Fixes #1328.
Moves inline javascript to execute after jquery loads.
Test Plan:
- Create test suggestions.
- Visit suggestion approval pages.
- Click 'select all' button.
- Verify all check boxes become checked.
> Fix suggestions select all by moving javascript.

- deploy.py
- pavement.py
Accepts an argument to where appcfg.py lives so that people other than Eugene can update prod :)
paver deploy -h for usage instructions.
Test plan:
- Commented out the part that actually deploys
- Ran `paver deploy /usr/local/bin`, verified expected test output, other output
- Ran `paver deploy /usr/local/bin -s`, verified skipped test out, expected other output
- Uncommented the part that actually pushes
- Ran `paver deploy /usr/local/bin`, saw confirmation site deploy
- Visited thebluealliance.com/admin, saw confirmation I was the latest deploy
> Updates deploy script to work for other install setups.

- consts/district_point_values.py
- controllers/cron_controller.py
- controllers/district_controller.py
- helpers/district_helper.py
- helpers/event_helper.py
Adds in historical district point calculations. Seems to be mostly
accurate, although we need to import some alliance data to make it
all work. Should be pretty close to accurate (only think I couldn't
do was reduced elim points for 2nd picks).
Also filters out teams that aren't associated with a DistrictTeam, which fixes #1166
We'll also have to run the admin task to build old DistrictTeams for 2009 - 2013
Closes #1060
> Implement 2009 - 2013 District Point Math

- templates_jinja2/event_details.html
- templates_jinja2/team_details.html
- templates_jinja2/team_partials/team_info.html
Some links to external sites, like team websites and all the hashtag searches, already open in new tabs. This PR adds consistency by opening all external links (or at least the ones I found by poking around the site for a bit) in new tabs.
If I missed any links, let me know and I'll add them to this PR.
First contribution to the website, woo!
> Open external links in new tab

- controllers/admin/admin_main_controller.py
- controllers/suggestions/suggest_event_webcast_review_controller.py
- controllers/suggestions/suggest_match_video_review_controller.py
- controllers/suggestions/suggest_review_home.py
- controllers/suggestions/suggest_review_home_controller.py
- controllers/suggestions/suggest_team_media_review_controller.py
- helpers/suggestions/suggestion_fetcher.py
- main.py
- templates/admin/index.html
- templates/admin/partials/pending_suggestion_rows_partial.html
- templates/suggest_event_webcast_review_list.html
- templates/suggest_match_video_review_list.html
- templates/suggest_review_home.html
- templates/suggest_team_media_review_list.html
- tests/test_suggestion_fetcher.py
1. Creates a `SuggestionFetcher` helper class to avoid duplicating code between controllers.
2. Creates `SuggestHomeReviewController` to create a standalone page to review suggestions for people with the `MUTATE_DATA` permission who can't check the /admin/ page.
3. Refactor pending suggestion partial out into separate partial.
Problem I ran into: Couldn't put this partial above the admin directory, because the admin template can't reference "up a directory". Maybe Jinja2 templates can fix this? Didn't need to fix it for this.
> Suggestion home

- helpers/event_insights_helper.py
- templates_jinja2/event_partials/event_insights.html
Things like:
- High score
- Average Score,
- Average Win Margin,
- Average {2016 score category} score
Example:
http://tba.lopreiato.me/event/2016onto2
Mobile:
> Add score-based event insights

- controllers/api/api_event_controller.py
Result looks like this (doesn't include opr/dpr/ccwm since they weren't calculated on this instance)
```
{
"year_specific": {
"C_SallyPort": [
1,
14,
7.142857142857143
],
"scales": [
3,
66,
4.545454545454546
],
"captures": [
0,
22,
0
],
"challenges": [
23,
66,
34.84848484848485
],
"A_Portcullis": [
0,
2,
0
],
"D_RockWall": [
10,
15,
66.66666666666667
],
"LowBar": [
12,
22,
54.54545454545455
],
"average_high_goals": 1.9090909090909092,
"C_Drawbridge": [
1,
8,
12.5
],
"B_Moat": [
8,
12,
66.66666666666667
],
"breaches": [
4,
22,
18.181818181818183
],
"average_boulder_score": 11.090909090909092,
"NotSpecified": [
1,
2,
50
],
"A_ChevalDeFrise": [
4,
18,
22.22222222222222
],
"average_low_goals": 1.4545454545454546,
"average_score": 45.68181818181818,
"average_win_score": 59.18181818181818, …
```
> Update API to include event insights

- templates_jinja2/team_partials/team_info.html
At The Control no longer allows deep links.
Fixes #1407
> Removes team number from ATC link. Fixes #1407

- templates_jinja2/suggest_team_media_review_list.html
The "accept all"/"reject all"/"deselect all" buttons use `href="#"`, which scrolls the page to the top when the element is clicked. This changes the javascript click handlers to prevent that default action.
> Prevent team media review page from scrolling to top

- static/css/less_css/less/tba/tba_base.less
- static/css/less_css/less/tba/tba_variables.less
- static/javascript/tba_js/tba_favorites.js
- templates/base.html
- templates_jinja2/base.html
- templates_jinja2/match_partials/match_table_cell_macros.html
- templates_jinja2/team_details.html
Currently only for Team pages, but is designed with modularity in mind to be used for other pages as well as replace GameDay's current myTBA login prompts. Only Favs (and not Subs) for now because it was way simpler and we don't make use of Subs on the website right now anyways.
Logged out:
After clicking the FAB (if logged out):
After logging in:
Clicking the FAB send an AJAX request to the server and updates the local list of Favorites stored in a cookie:
After Favoriting:
If server 500's when trying to add or delete a favorite:
> FAB for marking a team as Favorite

- templates/apidocs.html
For consistency's sake (and maybe in case html is put in other places in the future), I enclosed the .text(...).html(); around all of the JSON.stringify's used in the api docs page. 
It seemed to work okay when I put the iframe code used in #1225 in a test event.
> Escape HTML tags in API docs.

- templates_jinja2/event_details.html
Done on the github web editor, so sorry if the formatting comes out weird. Also stops the link from showing up for non-official events.
This may not work for Championship divisions, which seems to use a brand new identifier, i.e. `http://frc-events.firstinspires.org/2016/ARCHIMEDES`. Not sure I have a good enough handle on TBAs codebase to decide what to do here.
Fixes #1417 and #1224
> Fix the link to the FIRST event page

- controllers/ajax_controller.py
- controllers/suggestions/suggest_match_video_controller.py
- helpers/suggestions/suggestion_creator.py
- main.py
- templates_jinja2/event_details.html
- templates_jinja2/suggest_match_video.html
- templates_jinja2/suggest_match_video_playlist.html
Input a playlist id, and then relate match partials to each video (invalid/leave blank to ignore)
Try it out at http://tba.lopreiato.me/suggest/event/video?event_key=2016nyny with playlist ID https://www.youtube.com/playlist?list=PLLDODAGuIHqNRyZPxoHlvwMsJYP79ptCv
You'll need to add a sitevar named `youtube_api_key` with the value of a new Google API key (generated in dev console), as well as enable the YouTube Data v3 API
> Suggest Videos From YouTube Playlist

- controllers/test_notification_controller.py
- notifications/schedule_updated.py
When the event has no more unplayed matches, it broke.
Now, the test page can specify the next match outright
Here's the trace:
```
INFO     2016-03-29 04:32:00,321 test_notification_controller.py:29] Sending for 7
ERROR    2016-03-29 04:32:00,442 main_controller.py:42] list index out of range
Traceback (most recent call last):
File "/home/phil/google_appengine/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
rv = self.router.dispatch(request, response)
File "/home/phil/google_appengine/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
return route.handler_adapter(request, response)
File "/home/phil/google_appengine/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
return handler.dispatch()
File "/home/phil/google_appengine/lib/webapp2-2.3/webapp2.py", line 547, in …
```
> Fix error with test schedule update notification

- controllers/api/api_event_controller.py
- helpers/model_to_dict.py
- templates/apidocs.html
- tests/test_apiv2_event_controller.py
Exposes event timezone string (like "America/New_York") in the API event
model.
Fixes #1444
> Add event timezone to API

- templates_jinja2/event_details.html
For events 2014 and before, there's no data on
frc-events.firstinspires.org, so we can fall back to showing the old
data
> Show old Rankings page for some events

- templates/apidocs.html
The API changed name, which caused the link to change.
> Fixed API Link

- README.md
What happens when you try to launch app without said module.
Traceback (most recent call last):
File "/home/brycematsuda/google_appengine/dev_appserver.py", line 83, in <module>
_run_file(__file__, globals())
File "/home/brycematsuda/google_appengine/dev_appserver.py", line 79, in _run_file
execfile(_PATHS.script_file(script_name), globals_)
File "/home/brycematsuda/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1040, in <module>
main()
File "/home/brycematsuda/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 1033, in main
dev_server.start(options)
File "/home/brycematsuda/google_appengine/google/appengine/tools/devappserver2/devappserver2.py", line 758, in start
options.config_paths, options.app_id)
File …
> README -- Add app-backend-tasks-b2.yaml as part of module flags

- controllers/gcm/gcm.py
- notifications/alliance_selections.py
- notifications/awards_updated.py
- notifications/base_notification.py
- notifications/level_starting.py
- notifications/match_score.py
- notifications/schedule_updated.py
- notifications/upcoming_match.py
But only for the commonly used event-result pushes
See the docs: https://developers.google.com/cloud-messaging/concept-options#setting-the-priority-of-a-message
Closes #1462
> Set GCM High Priority Messages

- controllers/base_controller.py
- templates/base.html
- templates_jinja2/base.html
To help avoid some cache-based confusion (we just admit to stale data)
Suggested by @gregmarra in #1468
> Show when pages are rendered

- controllers/account_controller.py
- controllers/base_controller.py
- controllers/mytba_controller.py
- controllers/notification_controller.py
- controllers/suggestions/suggest_event_webcast_controller.py
- controllers/suggestions/suggest_match_video_controller.py
- controllers/suggestions/suggest_team_media_controller.py
- controllers/webhook_controller.py
- main.py
- static/javascript/tba_js/gameday_mytba.js
- static/javascript/tba_js/tba_favorites.js
- templates/base.html
- templates/index_lhc.html
- templates/mytba_live.html
- templates/team_list.html
- templates_jinja2/account_login_required.html
- templates_jinja2/account_register.html
- templates_jinja2/base.html
Don't merge until we have a better empty landing page for `/mytba` or Champs starts (since it won't be empty then.)
Instead of kicking a user straight to the Google login page when visiting a page that requires login, we now show the following page:
Also did a bunch of refactoring so that 
`self._require_login()` and `self._require_registration()` are much more intuitive to use.
> myTBA on Navbar & Cleanup Login Flow

- templates_jinja2/match_details.html
This makes a two-column layout for the match view as described in #1240.
> Two-column layout for match view.

- react/gameday2/actions/__tests__/actions-test.js
When I changed how the webcast adding works, I never updated the tests. We should figure out how to run JS tests on the CI server.
> Fixed tests for action creators

- controllers/suggestions/suggest_social_media_review_controller.py
- controllers/suggestions/suggest_team_media_review_controller.py
- helpers/suggestions/media_creator.py
- models/suggestion.py
- templates_jinja2/media_partials/media_display_partial.html
- templates_jinja2/media_partials/social_media_macros.html
- templates_jinja2/media_partials/social_partial.html
- templates_jinja2/suggest_team_media_review_list.html
- templates_jinja2/suggest_team_social_media.html
- templates_jinja2/suggest_team_social_review.html
- templates_jinja2/team_details.html
Try and simplify showing medias by reusing more templates.
Now, the suggestion queue and team detail pages share a template for the full size embed. Hopefully it should reduce code copy/paste
> Consolidate Media Templates

- consts/media_type.py
- helpers/media_helper.py
- tests/test_media_url_parse.py
Those urls are formed like yt.com/c/whatever. Now, TBA doesn't assume a user/ url suffix and lets youtube handle the proper redirects.
I can't come up with a case where things break because we changed the profile display url format.
Fixes #1542
> Support gapps-managed YouTube profiles

- helpers/insights_helper.py
- templates_jinja2/insights_details.html
This embeds the video(s) for the highest scoring match on the insights page for each year if it is available as described in #383. Should I also do this to the insights on the landing page?
> Embed video for highest scoring match if available

- deploy.py
- pavement.py
This addresses some of the issues raised in #1568. Specifically:
- takes the target app engine module as a parameter
- allows setting a `--reauth` flag so you can choose which account to use
when deploying
- by default checks for the travis build to have succeeded before
deploying. Bypass with `--yolo`
For example, I can deploy tba.lopreiato.me with `paver deploy -d
~/google_appengine -p tba-dev-phil`
Closes #1568
> Improve deployment pipeline

- controllers/event_controller.py
Very minor typo that broke match_offset functionality. I didn't test between changing the string format method and pushing, so the typo went undetected.
> Fixed typo: 'offset' was referenced instead of 'match_offset'

- models/team.py
- renderers/team_renderer.py
- templates_jinja2/team_partials/team_info.html
The last year a team competed is shown on team pages directly below the rookie year listing EXCEPT when that year is the current year and the team page is the current year, as requested in #1546.
> Year last competed shown on team pages

- app-backend-tasks-b2.yaml
- app-backend-tasks.yaml
- app.yaml
- app_shared.yaml
- deploy.py
- dispatch.yaml
- pavement.py
[`gcloud`](https://cloud.google.com/sdk/gcloud/reference/) is the evolution of `appcfg.py` (which is deprecated). This pull moves our deployment pipeline to use the newer command and hopefully fixes @fangeugene's deployment issues. Heads up to @gregmarra as well
It requires some changes to the module yaml files, notably you no longer provide the version and application name values (those are instead passed at the `gcloud` command line). I made the default version to be `prod`, keeping in mind that the continuous deployment stuff I'm working on in parallel will use the version `contbuild`. 
This also adds some other various options to `paver deploy` for increased flexibility.
Also, note that if your deployments are slow, try exporting the environment variable `CLOUDSDK_APP_USE_GSUTIL` to …
> Manage Deployments With gcloud Utility

- react/gameday2/selectors/__tests__/selectors-test.js
- react/gameday2/selectors/index.js
These were accidentally left in #1587, removing them for cleanliness.
> [GD2] Removed debugging logs

- controllers/admin/admin_event_controller.py
- controllers/api/api_trusted_controller.py
- controllers/backup_controller.py
- controllers/cron_controller.py
- controllers/datafeed_controller.py
- helpers/event_manipulator.py
- models/event.py
- templates/admin/event_edit.html
Merge after #1593
This PR:
After everything is working, need to:
- Delete migrated entries from Event models
- Clear database query caches
> Remove deprecated Event properties now in EventDetails

- README.md
- admin_main.py
- controllers/admin/admin_authkeys_controller.py
- controllers/gcm/gcm.py
- mobile_main.py
- models/sitevar.py
- templates/admin/authkeys.html
- templates/admin/base.html
So it's easy to keep track/add them.
This also consolidates/cleans up some of the Sitevars in use for myTBA related things, although there are a few migration steps (below).
1. Change the value in `gcm.serverKey`: make the current content the value in a dict with key "gcm_key"
2. Copy/paste the values from `appEngine.webClientId` and `android.clientId` into the panel and submit (those should be the only ones to default unfilled)
3. You can now delete the two sitevars above, they were migrated to a dict in `mobile.clientIds`
> Add Admin Panel for API Keys

- templates/apidocs.html
Per #1607, update the docs to correct the use of `official` as using the official FMS, not being an official event.
> Update event API doc to correct description of `official` property.

- react/gameday2/gameday2.js
If the Redux devtools extension wasn't installed, an undefined object would be inserted in the Redux middleware chain, which made things break. This PR properly handles the case where said extension isn't present.
> Fixed GD2 crash caused by Redux devtools not being present

- templates/apidocs.html
Cleaned up the API docs, correcting malformed HTML, bad anchors, and typos. Then added emphasis to the SSL API endpoint by adding a section atop of the page, and updating all example URLs to implicitly include `https://`. Closes #1601
> API Doc Cleanup & HTTPS Emphasis

- controllers/base_controller.py
- templates/base.html
- templates_jinja2/admin_bar.html
- templates_jinja2/base.html
Adds a bar to the bottom of all pages if the user is logged in as an admin. This bar currently allows for easier cache clearing of the page, but can be extended to do more.
If the user is an admin, none of generated HTML is cached in either memcache or edge cache. Adding the admin bar makes used of existing memcache by find/replacing an HTML comment.
I'm confident that the current setup doesn't improperly leak the admin bar to non admins (in the worst case, the button they click will still prompt for login). However, the bar may not show up for admins if the page already exists in edge cache (I'm not sure), but through experience and [this documentation](https://cloud.google.com/appengine/docs/python/how-requests-are-handled#cache-control_expires_and_vary), it seems like GAE never sets …
> Add admin bar to make tasks easier

- datafeeds/parsers/fms_api/fms_api_team_details_parser.py
- tests/test_fms_api_team_parser.py
Do the hacky find/replace fix for websites returned from `urlparse` starting with `http:///`. We were expecting it already and not caring (since it wouldn't affect browsers), but #1635 brings up a good point on other applications. Also updates tests.
Fixes #1635
> Do the hacky fix for websites starting http:///

- controllers/admin/admin_cron_controller.py
- cron_main.py
- templates/admin/tasks.html
This allows us to schedule event details scraping in advance for registration days. Adds a box on `/admin/tasks/` to do it for you.
This will schedule `/backend-tasks/get/event_list/<year>` every `<interval>` minutes for the day specified. It will also set the "turbo mode" sitevar to reduce caches matching `.*<year>.*` to 61 seconds until the end of that day (starting now).
Fixes https://github.com/the-blue-alliance/the-blue-alliance/issues/1622
> Admin Panel Interface for Registration Days

- controllers/suggestions/suggest_apiwrite_controller.py
- controllers/suggestions/suggest_apiwrite_review_controller.py
- Show the requesting user in emails to contact@
- Email contact@ when suggestions are acted upon
> Trusted API Request Email Tweaks

- controllers/ajax_controller.py
- controllers/api/api_base_controller.py
- controllers/event_wizard_controller.py
- index.yaml
- main.py
- static/javascript/tba_js/eventwizard.js
- templates/eventwizard.html
- tests/test_api_trusted.py
Yay!
When a user is logged in:
- The "Select Event" dropdown in the eventwizard will now be populated with events the user has trusted API tokens for
- The id/secret boxes will disappear (but they'll still be there for when you manually input an event key)
- The trusted API now validates that the requested event + current user have auth tokens and will count that as valid (with updated tests)
> Keyless Eventwizard

- react/gameday2/components/ChatSidebar.js
- react/gameday2/containers/ChatSidebarContainer.js
- react/gameday2/reducers/__tests__/visibility.test.js
- react/gameday2/reducers/visibility.js
- react/gameday2/sidebars.less
This makes Gameday perform better when the site is first loading. The embed kicks off an absolutely insane number of network requests, and I've noticed some (subjective) lags when the page loads. I need to learn how to do proper profiling of websites...
It looks like the twitch embed is broken on prod GD2 because it's being requested over http, not https. I'll fix that next.
> Defer loading of chat sidebar until it is opened for the first time

- templates_jinja2/admin_bar.html
The admin bar with the "clear cache" button can block player controls in Gameday. This adds a "close" button with some inline javascript that will remove the bar from the DOM.
> Close admin cache bar

- react/gameday2/components/LayoutDrawer.js
This helps keep consistency with having content on the left and "controls" on the right of a list item.
Before:
After:
> Switched sides of layout icons and checkmark

- react/gameday2/gameday2.js
Allows us to set the chat to open via a url param, and save chat state between page reloads.
If the specified chat channel isn't present in the list of twitch webcasts, this will just open the panel and default to the gameday chat.
> Sync chat sidebar state with url params

- admin_main.py
- controllers/admin/admin_district_controller.py
- controllers/datafeed_controller.py
- database/district_query.py
- database/get_affected_queries.py
- datafeeds/datafeed_fms_api.py
- datafeeds/parsers/first_elasticsearch/first_elasticsearch_event_list_parser.py
- datafeeds/parsers/fms_api/fms_api_event_list_parser.py
- datafeeds/parsers/fms_api/fms_api_team_details_parser.py
- helpers/cache_clearer.py
- helpers/district_manipulator.py
- helpers/district_team_manipulator.py
- helpers/event_helper.py
- helpers/event_manipulator.py
- models/district.py
- models/district_team.py
- models/event.py
- templates/admin/base.html
- templates/admin/district_create.html
- templates/admin/district_edit.html
- templates/admin/district_list.html
- templates/datafeeds/fms_event_list_get.html
- tests/test_database_cache_clearer.py
- tests/test_first_elasticsearch_event_list_parser.py
- tests/test_fms_api_event_list_parser.py
- tests/test_fms_api_team_parser.py
This is backend improvement towards apiv3 (a place to store district rankings).
Store one `District` model per year/region. This also gives us a persistent place to store stuff. Will deprecate the `DistrictType` constants and manage everything from the admin panel instead (this is more scalable).
This pull provides the base model and automated creation from the FMS Datafeed. The constants we'll need to parse event names that come back from elasticsearch need to be manually input. However, the code will keep the constants from the previous year, if it exists.
Migration path after merge:
1. Run some script that backfills these based on existing DCMPs and auto-fills the names from the existing constants file
2. Remove constants file, deprecate `Event.district_type_enum` and …
> Base District Model

- admin_main.py
- controllers/admin/admin_migration_controller.py
- controllers/datafeed_controller.py
- datafeeds/datafeed_fms_api.py
- datafeeds/parsers/fms_api/fms_api_event_rankings_parser.py
- helpers/event_details_manipulator.py
- helpers/rankings_helper.py
- models/event_details.py
Saves `EventDetails.rankings` to `EventDetails.rankings2`. Continues to write to both from the FRC API for now. This new format should be more future-proof and easier to use.
> New rankings format

- .travis.yml
This probably won't make very much of a difference due to caching, but it can still help with new versions of dependencies.
> travis: Use travis_retry for flakey installs

- controllers/account_controller.py
- controllers/cron_controller.py
- controllers/event_controller.py
- helpers/matchstats_helper.py
- helpers/prediction_helper.py
- queue.yaml
- templates/predictions.html
- templates_jinja2/event_insights.html
- templates_jinja2/match_partials/match_predictions_table_header.html
- templates_jinja2/match_partials/match_table_cell_macros.html
- templates_jinja2/match_partials/match_table_macros.html
- templates_jinja2/match_partials/match_table_row_macros.html
- tests/test_event_controller.py
New predictions that solve for standard OPR equations with MMSE instead of LS. Also estimates team variance for more accurate probability estimates. New graphs. Updated to support 2017.
Benchmarks:
This new prediction method results in Brier scores of:
All 2016: 0.186904972648
Champs 2016: 0.17528888034
Comparison to others:
(from https://www.chiefdelphi.com/forums/showthread.php?t=152934)
This method does not use previous years to inform current year statistics.
> Improved predictions for 2017

- controllers/cron_controller.py
- cron.yaml
- cron_main.py
- helpers/match_time_prediction_helper.py
- models/match.py
Adds a cronjob that calculates predicted times for the next 10 matches at each currently live event. The algorithms works like so:
1. Compute Cycle Time
- This is the 30% percentile of all cycle times (biased 70/30 towards the schedule) from the same day, discarding outliers.
2. Assuming that cycle time, start with the last know match start time and predict the times for the next 10 matches.
Some data:
This was an event that ran ahead of schedule, for the most part:
This was an event that was very behind, for the most part:
This was an event that was all over the place:
Overall, the predicted times are rarely more than 3 minutes late when the event is running faster than anticipated and are always more (usually very) accurate for other cases.
> Predict Upcoming Match Times

- common/my_filters.py
- controllers/admin/admin_event_controller.py
- models/match.py
- templates/admin/event_details.html
Adds tabs to the admin page detailing events to declutter it a bit. Also adds the following:
- Match scheduling details (and schedule offset)
- Match prediction times (and offset)
- Hides long match json blobs by default
- Show event media and give a button to delete references
> Admin Event Page Revamp

- react/gameday2/components/TickerMatch.js
- react/gameday2/components/VideoCell.js
- react/gameday2/components/VideoCellToolbar.js
- react/gameday2/components/WebcastSelectionOverlayDialog.js
- react/gameday2/components/WebcastSelectionOverlayDialogItem.js
- react/gameday2/containers/WebcastSelectionOverlayDialogContainer.js
- react/gameday2/reducers/chats.js
- react/gameday2/reducers/index.js
- react/gameday2/reducers/webcastsById.js
Organizes webcasts in list with BlueZone first.
Don't show BlueZone chat as an option (use GameDay chat).
Show event codes on BlueZone ticker.
> Special case GameDay for BlueZone

- controllers/gameday_controller.py
- controllers/suggestions/suggest_event_webcast_controller.py
- controllers/suggestions/suggest_event_webcast_review_controller.py
- helpers/bluezone_helper.py
- helpers/firebase/firebase_pusher.py
- helpers/suggestions/suggestion_creator.py
- models/event.py
- templates/suggest_event_webcast_review_list.html
- templates_jinja2/suggestions/suggest_event_webcast.html
- tests/suggestions/test_suggest_event_webcast_review_controller.py
- tests/suggestions/test_suggestion_creator.py
So we can show the appropriate webcast in GameDay and BlueZone when there are different webcasts for different days.
We can add a nicer date picker in the future.
> Optional "date" parameter for webcasts

- controllers/gameday_controller.py
- react/gameday2/components/VideoCell.js
- react/gameday2/components/WebcastEmbed.js
- react/gameday2/components/embeds/EmbedDacast.js
- react/gameday2/components/embeds/EmbedHtml5.js
- react/gameday2/components/embeds/EmbedIframe.js
- react/gameday2/components/embeds/EmbedLivestream.js
- react/gameday2/components/embeds/EmbedNotSupported.js
- react/gameday2/components/embeds/EmbedRtmp.js
- react/gameday2/components/embeds/EmbedTwitch.js
- react/gameday2/components/embeds/EmbedUstream.js
- react/gameday2/components/embeds/EmbedYoutube.js
- react/gameday2/gameday2.less
- react/gameday2/reducers/webcastsById.js
- react/gameday2/videojs.less
- templates/admin/partials/webcast_add_form_partial.html
- templates/admin/partials/webcast_type_select.html
- templates/gameday2.html
More work on the march towards feature parity with GD1!
* Adds streaming support for HTML5 (HLS), Livestream, Iframe, Dacast, and RTMP streams
* Migrated HLS and RTMP streams to both use [video.js](http://videojs.com/)
* Removed support for MMS streams
* Added a nice "webcast not supported" message to handle the case where we accidentally set a bad type in the sitevar
Iframes were kind of weird to get working: I either ended up with weird double-escaping if I use the `safe` keyword in the template file, or escaped html entities without it. I ended up going with the latter and just regex-replacing the escaped entities on the client. @fangeugene want to see if you can figure this one out?
> [GD2] Implemented remaining streaming providers

- templates_jinja2/suggestions/suggest_event_media.html
This changes the example youtube video on the event media page to be a video that is a good example of event media (instead of a robot reveal).
The placeholder text for the suggestion media url box was a chiefdelphi photo link. We currently don't support chiefdelphi photos for event media, so this is misleading. This changes to placeholder text to be a link for a youtube video.
> Improve event media examples

- react/gameday2/components/LayoutDrawer.js
- react/gameday2/components/LayoutSelectionPanel.js
- react/gameday2/constants/LayoutConstants.js
On some smaller (more square) screens when both the chat and social side bars are enabled, the videos are quite small in split view. This adds a horizontal split view for this situation.
This adds the horizontal split view as layout 2 and shifts the rest down. Will this be a problem for existing links to gameday? Should the new layout be 9 instead?
> add a horizontal split view to gameday

- database/dict_converters/event_details_converter.py
- models/event_details.py
Fixes #1832 
```
"extra_stats_info": [
{
"name": "Total RP", 
"precision": 0
}
], 
```
```
"extra_stats": [
13
],
```
> Serve additional ranking columns over API, add Total RP for 2017

- models/event.py
- templates/event_partials/event_table.html
This adds the status for each event to the event table to give an overview of how all of the events are progressing in one place.
> Add event status to event table

- datafeeds/datafeed_fms_api.py
- datafeeds/parsers/fms_api/fms_api_event_list_parser.py
- tests/test_fms_api_event_list_parser.py
Currently, all teams attending championship show as attending Einstein. This adds a sitevar that allows the following:
- skipping storing divisions (so they won't appear until there are actually teams)
- overriding the Einstein names (so we can render them as FIRST Champinoship until divisions are announced)
- skip changing Einstein dates
> Gracefully Handle Pre-Divisions CMP Registration Hackery

- react/gameday2/components/VideoCellToolbar.js
> [GD] Shift cell toolbar controls shadow so it doesn't overlay the embed

- react/gameday2/components/VideoCell.js
- react/gameday2/components/VideoCellToolbar.js
- react/gameday2/components/VideoGrid.js
- react/gameday2/containers/VideoCellContainer.js
- react/gameday2/containers/VideoGridContainer.js
In layouts with exactly one cell, the swap button is hidden completely.
In layouts with exactly two cells, the swap button doesn't prompt with a dialog; it just swaps with the only other view that's there.
For all other layout, the swap button functions as it did before.
> Improved how swap functions with 1 & 2 view layouts

- templates_jinja2/event_details.html
Removed "hidden-xs" property from event_details.html to allow for the stream button to display on mobile devices where browser width <768px
See: http://getbootstrap.com/css/#responsive-utilities
PR for #1867
> #1867 "Watch Now" visibility fix for Extra Small Devices (<768px)

- README.md
The numbering in the README's setup section is a bit off thanks to a recent GitHub Markdown update. This should fix that.
> Fix README setup section numbering

- templates/opr.html
This is a minor styling fix to the header of the OPR page.
> Fix OPR page header

- apiv3_main.py
- controllers/apiv3/api_base_controller.py
- controllers/apiv3/api_suggest_controller.py
This will add an API endpoint for suggesting team media. A developer would make a POST request to `/api/v3/team/<team>/suggest/media/<year>` (subject to change) with the POST data `{ media_url: "some media link" }` in order to queue a suggestion. Should resolve #1037.
I've been playing with this quite a bit, and from my tests it should be working :)
> Add team media suggestion API endpoint

- controllers/apiv3/api_base_controller.py
See [@fangeugene's comment](https://github.com/the-blue-alliance/the-blue-alliance/pull/1882/files/fae50437048384a6a12b8929c2f4d95e41d491e4#r111207897).
Error `401` means "Unauthorized: Access is denied due to invalid credentials." BTW
> Return error code 401 instead of 400 if auth header is incorrect or missing

- backend_main.py
- controllers/admin/admin_cron_controller.py
- controllers/admin/admin_event_controller.py
- controllers/event_controller.py
- database/dict_converters/event_converter.py
- database/event_query.py
- database/get_affected_queries.py
- helpers/event_helper.py
- helpers/event_manipulator.py
- models/event.py
- templates/admin/event_details.html
- templates/admin/event_edit.html
- templates_jinja2/event_details.html
- tests/test_database_cache_clearer.py
Adds keys for `parent_event` and `divisions` to the event model.
Works for Einstein(s) and MSC this year.
Closes #1895
> Store Divisional Mappings

- controllers/cron_controller.py
- models/typeahead_entry.py
- static/javascript/tba_js/tba_typeahead.js
The district search works in a manner similar to event searching, except there is only one searchable entry per district. For example, the search for "North Carolina" leads to the [events list](https://www.thebluealliance.com/events/nc) for the current year. 
Implements #1893 
Edit: typo
> Add districts to typeahead search.

- controllers/apiv3/api_team_controller.py
This should fix what @ThePlasmaGuy was talking about here: https://github.com/the-blue-alliance/the-blue-alliance/issues/1507#issuecomment-295099866
> Add last-modified header to team event status API requests

- templates_jinja2/event_insights.html
Championship prediction distributions have been off the edge of the graph. 
I think this will short-term fix it; I haven't gotten a chance to fully test it since I'm writing this PR on the drive down to St. Louis.
New numbers are based on the maximum values that I saw in Houston, rounded to the nearest 50.
Long term this should probably either be automated or parameterized; I'll think about ways to do that after season.
> Increase advanced insights prediction graph range

- templates/apidocs.html
This updates the attribution link referenced in #1913
> Update API link

- consts/award_type.py
Changes `"Chairman's Finalist Award"` to `"Chairman's Award Finalist"`, per the API description for the award:
```
{
"awardId": 659,
"eventType": "Championship",
"description": "Chairman's Award Finalist",
"forPerson": false
}
```
> Changes chairman's award to use correct name ordering

- models/event.py
Updated Event#normalized_name to take into account championship city starting in 2017.
Fixes #1922
> Include city in championship name for banners

- helpers/event_helper.py
- tests/test_event_get_short_name.py
The title pretty much explains it.  While the regex did get a little more complicated, I tried to also simplify the logic a little bit as well. 
I've also added the corresponding names to the tests: `tests/test_event_get_short_name.py`
Fixes #1937
> Update short_name regex to support numbered events

- react/gameday2/components/ChatSidebar.js
- react/gameday2/containers/ChatSidebarContainer.js
- react/gameday2/gameday2.js
It's hard to use GameDay on small/mobile screens because the chat is in the way. This will close the chat automatically if the screen size is smaller than 760px.
> Close GameDay chat on small screens

- templates/apidocs_overview.html
- templates/contact.html
Updates the contact page to fix links/references to TIMS and v2 API.
Fixes typos on the API Overview page (rolls up #1942)
Adds info on v2 API (as deprecated) to the overview
> Update Contact Page and API Docs Overview

- static/swagger/api_v3.json
This is the first doc update to the v3 spec, and bumps the version to `3.0.1` accordingly.
Aside from doc updates and clarifications, the important items are:
* Clarification of the `x-version-info` tag to note that API revisions correspond to the API as returned, not per the spec (see below why).
* The `district` property on the event models was changed to be a link to the `District_List` model. In reality the result is identical, but may result in some minor code changes for people using Swagger Codegen. The model was not renamed to minimize the effect of this change.
* The multi-line `description` atop the spec isn't JSON compliant. (unescaped `\n` is a control character and not allowed.)
* An `x-changes` property has been added to the top of the spec to track significant changes for …
> API v3 Doc Update

- tests/test_event_get_timezone_id.py
Sometimes the location tests are iffy and make the entire test fail.
> Fix iffy location tests

- static/swagger/api_v3.json
`Team_Event_Status` and `Event_Ranking` models updated to reflect actual API return values. Changes centered on W-L-T and related properties.
Fixes #1967
> Correct API Docs

- controllers/short_controller.py
- main.py
- tests/test_short_routes.py
This begins to work on some of the mentioned features in #1933.
Examples:
`thebluealliance.com/254` => `thebluealliance.com/team/254`
`thebluealliance.com/2521` => `thebluealliance.com/team/2521`
`thebluealliance.com/frc254` => `thebluealliance.com/team/254`
`thebluealliance.com/frc2521` => `thebluealliance.com/team/2521`
`thebluealliance.com/2017nytr` => `thebluealliance.com/event/2017nytr`
`thebluealliance.com/2017mndu2` => `thebluealliance.com/event/2017mndu2`
> Add short url routes

- ops/travis/travis-deploy.sh
Put `[nodeploy]` in the commit message somewhere and we'll skip deploying it
> Allow Skipping Deployment via Commit Message

- templates/webhookdocs.html
Previously, the message_type field was nested inside the message_data field in the example for the Awards Posted notification webhook. They now are both nested under the top level of the notification.
> Fixed nesting of awards_posted example

- backend_main.py
- controllers/backup_controller.py
- cron.yaml
- deploy_requirements.txt
- queue.yaml
This is the important part of #2000 - it automatically creates datastore backups and imports them into BigQuery. We can add in the csv part later, once we get this flow ironed out.
~~Still todo: add another job to set the storage class of the new backups to coldline (https://cloud.google.com/storage/docs/changing-storage-classes)~~
> Create Automated Datastore Backups

- .gitignore
- README.md
- Vagrantfile
- ops/dev/Dockerfile
- ops/dev/bootstrap-dev-container.sh
- ops/dev/start-devserver.sh
- ops/dev/vars.sh
- pavement.py
- requirements.txt
Using [`vagrant`](https://www.vagrantup.com/)+[`docker`](https://www.docker.com/).
Test it out by running `vagrant up --provider=docker && vagrant rsync-auto` and then going to `localhost:8080`.
To debug, ssh into the container using `vagrant ssh` and then run `tmux attach` to see the GAE devserver logs (use `^B-D` to detach from tmux).
> Create Container-Based Dev Environment

- api_main.py
- consts/auth_type.py
- controllers/api/api_trusted_controller.py
- helpers/event/event_webcast_adder.py
- static/swagger/api_trusted_v1.json
- tests/test_api_trusted.py
Will provide a way (eventually exposed in eventwizard2) for event managers to change some limited properties about their events. This will include:
- FIRST event code (so they can manually enable syncing)
- Webcasts
- Playoff Type
I still need to do some testing and update the docs, but feedback (as well as other fields?) is appreciated
> Add trusted API endpoint for event info

- apiv3_main.py
- consts/media_tag.py
- controllers/apiv3/api_media_controller.py
- controllers/apiv3/api_team_controller.py
- database/get_affected_queries.py
- database/media_query.py
- helpers/cache_clearer.py
- static/swagger/api_v3.json
- tests/test_database_cache_clearer.py
Adds ~~two~~ three API endpoints for querying media based on tags:
- `/api/v3/team/<team_key>/media/tag/<tag>`
- `/api/v3/team/<team_key>/media/tag/<tag>/<year:[0-9]+>`
- `/api/v3/media/tags`
> Add media tag API endpoint

- ops/dev/bootstrap-dev-container.sh
The first time this runs, the template gets renamed. So it fails the second time
> [vagrant bootstrap] Fix bug preventing provisioning multiple times

- database/dict_converters/match_converter.py
- database/match_query.py
- datafeeds/parsers/fms_api/fms_api_match_parser.py
- models/match.py
- static/css/less_css/less/tba/tba_match_table.less
- static/swagger/api_v3.json
- templates_jinja2/match_partials/match_table_cell_macros.html
- tests/test_fms_api_event_parser.py
Still need to update swagger. 
API looks like this:
```
"alliances": {
"blue": {
"dq_team_keys": [], 
"score": 160, 
"surrogate_team_keys": [], 
"team_keys": [
"frc5677", 
"frc2473", 
"frc4186"
]
}, 
"red": {
"dq_team_keys": [
"frc5027"
], 
"score": 100, 
"surrogate_team_keys": [], 
"team_keys": [
"frc5027", 
"frc2489", 
"frc2367"
]
}
}, 
```
> Store, display, and expose match DQ info. Fixes #1959

- admin_main.py
- controllers/admin/admin_migration_controller.py
- models/match.py
For #2020 
Running `/admin/migration/backfill_year_dq/<year>` enqueues tasks to backfill match DQ info for all events==official (can be pulled from FRC API). Only backfills data if match teams & scores in the DB are equal to data from the FRC API.
> Backfill DQ from FRC API

- datafeeds/parsers/json/json_matches_parser.py
- static/swagger/api_trusted_v1.json
- tests/test_api_trusted.py
Backwards compatible; `surrogates` and `dqs` are optional.
> [Trusted API] Support surrogates/dqs

- controllers/admin/admin_event_controller.py
- controllers/api/api_trusted_controller.py
- controllers/backup_controller.py
- controllers/cron_controller.py
- controllers/datafeed_controller.py
- cron_main.py
- helpers/event_helper.py
- helpers/event_manipulator.py
- models/event.py
- templates/admin/event_details.html
- tests/test_api_trusted.py
Future PR:
- Expose interface in EventWizard2
> Automatic Team Remapping. Fixes #1638

- static/swagger/api_v3.json
Currently the API v3 documentation lacks any note of the `extra_stats` property on the `Event_Ranking` model. This PR adds the necessary documentation.
> Add extra_stats and extra_stats_info to API v3 documentation

- templates/gameday2.html
Load video.js over https to remove the mixed content warning on the top right in chrome and prevent it from getting blocked.
> Remove mixed content warning in GameDay

- templates/gameday2.html
Uses minified video.js scripts instead of large original scripts. Fixes #2035.
Large reduction in GameDay page size (~133 kB).
Tested locally.
> Use minified video.js scripts

- static/swagger/api_v3.json
Update the `api_v3.json` file to comply with Swagger spec and match data actually returned.
In the `api_v3.json` file:
- Update the lines that reference `WLT_Record` in the `Team_Event_Status_playoff` object to the correct syntax.
- Move the `required` block from the root of `Event_District_Points` into the inner `additionalProperties` object to match Swagger spec and correct the formatting on the `/apidocs/v3` webpage.
- Add descriptions to the children of `Event_District_Points` as required by Swagger spec. 
- Change the `Match.video` object to fix incorrect syntax and more correctly reflect what is currently returned by the API. 
Fixes syntax errors that prevent auto-generating an API client using swagger-codegen, and fixes some formatting on the `/apidocs/v3` webpage. 
Validated …
> Update api_v3.json to match Swagger spec

- app.yaml
- deploy_requirements.txt
Followed migration guide: https://cloud.google.com/endpoints/docs/frameworks/python/migrating
According to the docs, no client updates are required
> Use cloud endpoints v2

- static/swagger/api_v3.json
Changes the data type of `first_event_id` in the API docs to match what is actually returned
Changes the data type of `first_event_id` from `integer` to `string` in the API docs
Fixes #2041, an issue where automatically-generated API clients crash when receiving data about certain offseason events. 
Linted using Swagger Editor
N/A
> Change type of first_event_id in API to match spec

- controllers/api/api_base_controller.py
- controllers/apiv3/api_base_controller.py
Throws off actual usage stats and maybe inflates APIv2 usage stats compared to APIv3.
Note: API statistics may decrease for 2018 vs. 2017 because we won't be logging "bad" calls anymore.
Tried valid and invalid API calls (v2 and v3) and verified that only valid calls called the tracking function.
> Don't track API calls with errors. Fixes #2050

- Vagrantfile
- ops/dev/Dockerfile
- ops/travis/travis-install.sh
I have updated the auto-downloaded GAE SDK to the current version, both in the `Dockerfile` as well as the Travis configuration in `ops\travis\travis-install.sh`
In addition, I have slightly tweaked the `Vagrant` configuration to what appears to be the new standard for how the calls are made, although I admittedly don't have much experience with `Vagrant`.
`Docker` and `Travis` weren't able to pull the necessary GAE SDK zip, because Google has deprecated the download.  As such, I've bumped the versions to the current version, which is `1.9.66`.
~This famously "works on my machine".  Other than someone else trying out the changes, I'm not sure of another way to test this.~
These changes should now also be reflected in the running of `Travis`.
Current version of the GAE SDK:
> Update Vagrant config

- helpers/district_helper.py
Includes teams with 0 points in district rankings.
Add all teams to team totals instead of just those that have points.
Useful for seeing teams before they have competed.
It hasn't
> Include teams with 0 points in district rankings calc

- controllers/apiv3/api_base_controller.py
Add Access-Control-Max-Age for 1 week for APIv3 OPTIONS requests
Allow caching of CORS preflight requests
In production when this gets merged.
> Add Access-Control-Max-Age header for APIv3

- templates/search.html
On the Search page, results open in a new tab
Added the `linktarget="_parent"` attribute per the documentation from [devs.google](https://developers.google.com/custom-search/docs/element)
> Opens search results in same tab

- controllers/main_controller.py
- main.py
- templates_jinja2/avatars2018.html
Added a page at `/avatars/2018` that fetches all avatars and displays them. Might get slow once more teams submit avatars, and currently only backed by memcache, but we'll see what happens.
Team number shows on hover and links to team page on click.
It would be fun to see all teams' avatars.
Load team avatars from FRC API, visit `/avatars/2018`
> Add page to display all 2018 team avatars

- templates/index_buildseason.html
- templates/index_competitionseason.html
(see PR title 😁 )
There was no actual link to the page on the site, just ~word of mouth~ Facebook links
It works locally.  See also the screenshots section.  👇 
Updated build season page:
Updated competition season page:
> Added 2018 avatars link to build season and comp season landing pages

- static/css/less_css/less/tba/tba_media.less
- templates_jinja2/avatars2018.html
Linked avatars had a visual bug that showed a line next to them on hover.
Bug reported [here](https://github.com/the-blue-alliance/the-blue-alliance/pull/2072#issuecomment-364163469)
Only locally.  See screenshots below 👇 
Before:
After:
Before:
After:
> Fixed visual bug when hovering over linked avatars

- templates_jinja2/avatars2018.html
Move avatar tooltip from anchor element to image element to prevent flickering
Hovering over an avatar at certain positions would cause tooltip to flicker because it loses focus.
Works on dev
> Move avatar tooltip to img element. Closes #2077

- controllers/datafeed_controller.py
- datafeeds/datafeed_fms_api.py
- datafeeds/parsers/fms_api/fms_api_team_avatar_parser.py
- tests/test_fms_api_team_avatar_parser.py
When parsing avatars, keep track of those with null keys to be deleted.
Currently, we do not delete a team avatar even if the FRC API stops returning one. A reason for this can be FIRST rejecting avatars that have initially been approved due to copyright violations. We should remove team avatars if the FRC API does not return one.
Closes #2085 
Verified that avatars that are Null from FRC API get deleted in dev environment
> Delete avatars if FRC API returns null

- templates_jinja2/event_insights.html
Augment existing code that defines ranges based on scores by also defining them based on 95% confidence intervals of predictions.
Also makes formerly fixed ranges fully variable, removing game dependence.
Since negative scores haven't been possible in FRC, doesn't allow lower bounds to be negative.
Ensures graphs are in range when there are matches yet to be played. Removes hacky solution from #1917 where bounds were adjusted per game to make it work out, and makes sure they make sense per event.
paver test passes in my development environment, visual testing looks reasonable.
> Base prediction graph ranges on predictions and results

- controllers/suggestions/suggest_offseason_event_review_controller.py
Suggested offseasons were being improperly set to `official = True`
Logic check for `first_code is not None` never evaluates to `False`. Should be checking for empty string.
Accept suggestion with no first_code, verify that official == False. Accept suggestion with first_code, verify that official == True.
> Fix suggestions being improperly marked as official. Closes #2082

- datafeeds/datafeed_fms_api.py
`lstrip` and `rstrip` FRC API responses
FRC API returning stuff like:
`\xef\xbb\xbf{"Schedule":[]}\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00`
Locally on dev
> Clean junk JSON from FRC API

- apiv3_main.py
- controllers/apiv3/api_event_controller.py
- controllers/apiv3/api_team_controller.py
- database/event_query.py
- database/get_affected_queries.py
- database/team_query.py
- tests/test_database_cache_clearer.py
Add two new APIv3 endpoints:
Team@Event statuses for all events for a team in one year:
`/api/v3/team/<team_key>/events/<year>/statuses`
Format: A dict of event_key: status_dict
Team@Event statuses for all teams at one event:
`/api/v3/event/<event_key>/teams/statuses`
Format: A dict of team_key: status_dict
`status_dict` is the same as what is currently available at:
`api/v3/team/<team_key>/event/<event_key>/status`
Added two new DBQueries to fetch EventTeams for 1) a specific team's year and 2) an event.
Updated cache clearing and tests to support new DBQueries
Added two new APIv3 endpoints that use the new DBQueries.
Useful for the PWA
On local dev, verified that the following two endpoints work:
`/api/v3/team/frc254/events/2017/statuses`
`/api/v3/event/2017casj/teams/statuses`
> Add Two New Team@Event Status APIv3 Endpoints

- controllers/base_controller.py
Catch `ValueError` thrown when setting memcache over 1 mb.
Avatars page 500ing
Local dev no longer 500s on avatar page
> Catch memcache ValueError

- controllers/main_controller.py
Cache all 2018 avatars in shards, since the page cannot be cached because it is too large.
Verified on local dev that RPC costs and request time are both lower.
> Cache sharded avatars

- controllers/main_controller.py
Checking whether all avatar shards were fetched was being done incorrectly.
Reproduced old bug locally, this fix makes it so that bug doesn't occur.
> Fix refetch avatar shards if missing one

- controllers/main_controller.py
- templates/index_competitionseason.html
Closes #2124 
Add a list of top (25) Favorited teams in myTBA to competition homepage, sorted by team number.
Event Teams and Favorite counts are cached for 24 hours. This could be longer, but 24 hours should be fine.
@tombot suggested it. Why not?
Local dev with actual week 1 teams and some fake Favorites.
> Add popular teams competing to homepage

- react/gameday2/components/LivescoreDisplay.js
- react/gameday2/selectors/index.js
When the current live match is played, show ETA to next match.
When the current live match mode is pre_match, show ETA to current match.
Lets users know when matches will start.
Local dev with week 0 data.
> Show ETA for next match in GameDay livescore widget

- templates/index_competitionseason.html
- templates/index_lhc.html
Moves the large team avatar button on the homepage to the left sidebar with other buttons.
Remove the avatar button from the comp season template. Add the avatar button to the lhc template.
The button is really big right now 😄
> Move avatar button to lhc for competition season

- templates/event_partials/event_table.html
Closes #2135 
Currently webcasts with unknown status are confusing
It hasn't
> Different watch button for webcasts with unknown status

- react/liveevent/components/LiveEventPanel.js
- static/css/less_css/less/tba/tba_live_event_panel.less
Adds a little more padding to the bottom of the Live Event Panel so it's not as crammed.
The Live Event Panel was looking a little crammed at the bottom, so this makes it a little more evenly spaced.
Local dev server
> Add more padding to bottom of live event panel

- controllers/suggestions/suggest_match_video_review_controller.py
- templates_jinja2/suggestions/suggest_match_video_review_list.html
- tests/suggestions/test_suggest_match_video_review_controller.py
Makes the inputs for match video suggestion reviewals radio buttons instead of checkboxes, making it consistent with other reviewals.
Consistency. Fixes #1386.
Local dev server.
> Make match video accept/reject radio inputs

- react/gameday2/livescore.less
- static/css/less_css/less/tba/tba_live_event_panel.less
Makes Power Up icons pixelated instead of being anti-aliased.
The icons look weird and fuzzy when they're not pixelated as they should be.
Local dev server.
> Make Power Up icons pixelated

- helpers/match_time_prediction_helper.py
Set match predicted time to scheduled time if no matches have been played.
Match times were no being predicted when no matches are played.
On local dev, an event with no matches played had no scheduled time. After this fix, they do.
> Fix match time predictions when no matches have been played

- react/liveevent/components/LiveEventPanel.js
- react/liveevent/components/UpcomingMatchesTable.js
Show ETA in hours if > 120 minutes
Only show current match if live score is available
Local dev with prod Firebase data.
> Live event tweaks for practice day

- static/css/less_css/less/tba/tba_media.less
- templates_jinja2/avatars2018.html
- templates_jinja2/team_details.html
- templates_jinja2/team_partials/team_info.html
Add blue background color to team page avatars with radius, so square & round icons don't look weird. Toggles to red on click.
White avatars were not showing up.
Tested toggling works on local dev, all avatars page still works too.
> Add background to team page avatars

- helpers/district_helper.py
Compute district points with `rankings2` instead of `rankings`
`rankings` is deprecated and not used anymore
Verified that district points are correctly calculated on local dev using 2018mitvr data.
> Compute district points with rankings2

- templates_jinja2/event_partials/event_table.html
https://github.com/the-blue-alliance/the-blue-alliance/commit/2cbe0446b3212c6681dbaced888d8767cb9a5e0c made this change for the home page, but not the Events page (👏 duplicate code 👏). This'll fix that.
> Use different watch button for unknown status on events page

- react/gameday2/components/VideoCell.js
- react/gameday2/components/VideoCellToolbar.js
- react/gameday2/containers/VideoCellToolbarContainer.js
Closes #2107
Make event title to event page from GameDay. Disabled for special webcasts.
Going to an event page from GameDay was clunky.
Verified events link and special webcasts don't on local dev.
> Link to event page from GameDay

- renderers/team_renderer.py
`rankings` are no longer being computed. Use `rankings2` instead.
> Use rankings2 for showing rank on team pages

- react/gameday2/selectors/index.js
Fix GameDay ticker matches being sorted incorrectly
> [GameDay] Fix ticker sort order

- controllers/cron_controller.py
- controllers/event_controller.py
- helpers/match_time_prediction_helper.py
- helpers/notification_helper.py
- templates_jinja2/event_details.html
Change event down determination to use predicted time
Maintain cycle time between predicted match times
Add alert on event page if event is down.
Fix some edge cases with match prediction times & make it more obvious to the user when an event is down.
Tested on 2018txda to ensure predicted times stay a cycle apart
Tested event offline alert
> Fixes to match time predictions and event is down detection/display

- controllers/admin/admin_user_controller.py
- models/account.py
- models/suggestion.py
- templates/admin/user_details.html
- templates/admin/user_edit.html
- tests/suggestions/test_suggestion_creator.py
Closes #2174 
Add ability to shadow ban users and autoreject their suggestions
Reduce spam
Verify on local dev that suggestions from shadow banned users don't show up in the suggestion queue, and other suggestions do.
> Shadow ban & suggestion autoreject

- templates_jinja2/team_partials/team_info.html
I changed the amount of screen each section had to work with, taking 1/12 from the left-hand side container and giving it to the right-hand side container.
There's plenty of screen reality to work with, so nothing should be overflowing.  😁 
Locally only.  See screenshots blow.  👇 
Before:
After:
> Fix "Currently competing at" panel on team page

- helpers/match_time_prediction_helper.py
Restricts the base time (time that all future match times are calculated from as `base_time + i * cycle_time` to be no older than `now - some_amount`
Fixing an edge case for match time predictions.
Tested with 2018txda, 2018vahay, and 2018ohmv with different faked current times to see that predicted match times are bounded by `current time - some amount`.
> Restrict base time for time predictions

- helpers/match_time_prediction_helper.py
Don't skip matches that are not on the same day/comp level. Set them to the scheduled time instead.
Since "is down" determination is based on predicted time vs. scheduled time, we should be predicting match times regardless.
Local dev with 2018isr1
> Explicitly set predicted match time

- helpers/insights_helper.py
- templates_jinja2/insights.html
Add insight that lists (sub)division wins
Unsure why we didn't already have it.
Local dev with partial 2017 data
> Add (sub)division wins insight

- static/swagger/api_v3.json
Updates the return value of the API call to match the actual format.
Closes #2183 
Locally tested, spec validated in Swagger editor
(Not marking Breaking Change as it fixes a broken endpoint.)
> Corrects the `/team/{team_key}/districts` return to match actual

- helpers/match_time_prediction_helper.py
Fix issue with predicted match times not being shifted if the first unplayed match is also the first match of the day.
> Shift predicted time by timedelta

- helpers/insights_helper.py
- templates_jinja2/insights.html
Add tooltip on overall insights page that displays years won on hover.
It was requested
Local dev with partial 2016/2017 data
> Show tooltip with years for championship and subdivision wins

- .gitignore
- apiv3_main.py
- app.yaml
- controllers/apiv3/api_realtime_controller.py
- database/gdcv_data_query.py
- database/get_affected_queries.py
- deploy_requirements.txt
- ops/dev/Dockerfile
- ops/dev/bootstrap-dev-container.sh
- ops/dev/start-devserver.sh
- tests/test_database_cache_clearer.py
Add an apiv3 endpoint at `/api/v3/match/<key>/timseseries` that returns a list of gdcv score objects from CloudSQL. Also adds an endpoint at `/api/v3/event/<key>/matches/timeseries` that returns a dict mapping a played match key to a list of timeseries score objects. This implementation does require that we have existing score data from the FRC API for the match (we explicitly do _not_ want this endpoint to update it real-time, it should only be retrospective).
Give the people what they want - a way to query for gdcv data
locally on the devserver
> [apiv3] Add Endpoint for GDCV Data

- ops/dev/Dockerfile
Added an apt dependency that was causing dev environment setup to fail.
This change is required to set up a new development environment correctly. It solves a mysql_config environment error on first-time setup.
Issue was discovered trying to set up a development environment, applied fixes, reran setup commands and did not get the error. This was on an Ubuntu 16.04 system.
> Fixed an unmet dependency error that caused provisioning to fail

- static/swagger/api_v3.json
Add documentation for the event and match timeseries endpoints, as well as the timeseries data model for 2018.
:+1: for good docs.
Matched against current API return and validated spec thru Swagger Editor.
> [APIv3] Add docs for Timeseries Data for 2018

- controllers/cron_controller.py
Events were being incorrectly marked as "down" if they were only behind schedule.
> Check last played match time when determining event is down

- helpers/insights_helper.py
- models/insight.py
- templates/index_insights.html
- templates_jinja2/insights_details.html
Add winning margin distribution to insights page.
@gregmarra, among others, have suggested (#2168) showing winning margin distribution on the insights page.
"Showing the distribution of win margin would give an insight into how close matches are, and how many seconds of ownership are deciding matches."
Locally only at this point.  ~When it's more complete,~ I'd like others to test.
In addition, I'm planning on adding tests, once I've fleshed out more of the functionality.
(tests coming soon, if we feel they're needed)
Week 1:
Week 2:
> Add average winning margin by week and winning margin distribution to insights page

- renderers/team_renderer.py
- templates_jinja2/team_details.html
Modify the team_details page to have an additional button that links to a youtube playlist containing all the match videos of a team for the indicated event.
I found myself having to click a lot to watch a team through the eliminations at their event and thought that was unnecessary. This button lets you sit back and watch a team's performance at an event.
I tested this on events with missing videos, no videos, videos that contain time links (don't work in playlists), and with multiple event entries for a team.
> Add automatic playlist-ing for team details page

- static/swagger/api_v3.json
Corrected the `*_played` fields documentation. CloudSQL returns booleans as 0/1 which was mistaken as a count not a boolean when writing docs.
Bad docs are bad.
Syntax checked w/ Swagger Editor
> APIv3 Docs: Timeseries model `_played` doc fix

- static/swagger/api_v3.json
I have:
* Fixed the model of /team/{team_key}/robots to match API return
* Added min and max to year parameter
* Added min to page_num parameter
* Changed { "type": "number", "format": "integer" } to { "type": "integer" }
I changed the endpoint to better show what is returned
The others are for autogenerated clients and for the online API test to not accept invalid values 
My own autogenerated [client](https://github.com/rakusan2/tba-client-generator)
I have tested it on the online Swagger Editor
> Fix model of /team/{team_key}/robots to match API return

- templates_jinja2/match_details.html
Moves Videos above Match Details on Mobile. Removes "Button to go back" since event link already present.
Addresses issues I observed using this page on an iPhone.
Tested on dev instance.
> Improves Match Details page, fixes #2213

- templates/base.html
- templates_jinja2/base.html
To be more consistent with other websites, which tend to put the "account settings" menu last, swap the order of "Swag" and "Account".
I'm fine with this diff being rejected, just a nit.
Consistency with other websites.
Dev instance.
> Move account last in nav menu

- templates_jinja2/team_details.html
Standardize references to teams as "Team 1234" on team details page. IMO, we shouldn't use #'s to refer to teams, and we should capitalize "Team" when referring to a specific team. If there is any official style guide from FIRST I would love to follow that!
Consistency.
Tested on local dev machine
> Minor cleanup to team detail pages.

- templates_jinja2/event_details.html
1. Move ongoing event block into Results tab. (@fangeugene , will this mess up any Javascript?)
2. Move OPRs into Insights tab
1. Fit better on Mobile, especially getting the tabs above the fold during current events
2. Move OPRs to somewhere you're more likely to look for them, since they are wayyyy below the fold on Mobile.
Local dev instance.
Observe addition of Insights tab, moving of "ongoing events" block.
- [ x ] New feature (non-breaking change which adds functionality)
> Event Details: More Mobile Optimization

- templates/event_partials/event_table.html
- templates_jinja2/event_partials/event_table.html
On Event List pages, the columns of the event lists don't line up.
As an example, the New England District event list([ref](https://www.thebluealliance.com/events/ne/2018)), shows tables for each week.  These tables show 1-2 events each week, with column widths varying widely between weeks.
This is simply a template change to fix a UI issue that had been bugging me.
I don't have a local environment set up to test this.  All testing was done in browser dev tools.
None
> Lining up columns across all tables.

- consts/district_point_values.py
- helpers/matchstats_helper.py
- helpers/media_helper.py
- models/media.py
- templates/about.html
- templates/admin/team_details.html
- templates/index_kickoff.html
- templates_jinja2/suggestions/suggest_team_media.html
- tests/suggestions/test_media_url_parse.py
This avoids mixed content warnings and issues.
A simple find and replace of `http://www.chiefdelphi.com` to `https://www.chiefdelphi.com`.
I noticed images weren't loading after I set one of my privacy enhancing Firefox addons to block mixed content. Further investigation showed that it was being blocked due to loading over HTTP.
To be honest, I haven't.
> Use HTTPS for chiefdelphi.com links

- static/swagger/api_v3.json
Modifies the Event Insights endpoint (`event/{event_key}/insights`) to add a year-independent model to represent the `qual` and `playoff` fields for event insights. This should be a non-breaking change for API consumers
If we're going to have Event Insights models for every year, we don't need to have models that duplicate functionality (ex: `Event_Insights_2017` and `Event_Insights_2018` used to be the same model)
Only in the Swagger editor and it *looks* right - let me know if there's code changes to be made
> Adds property safety to event/{event_key}/insights endpoint

- templates/index_lhc_offseason.html
Adds search and colorizes buttons
Adds a team/event search box and team/event buttons, similar to those on the sidebar for during season.
The buttons on the homepage were looking plain
Hasn't.
> Update offseason sidebar

- controllers/gcm/gcm.py
- templates/admin/authkeys.html
Changed the Google Cloud Messaging send URL used for notifications to the Firebase Cloud Messaging one, since GCM is now deprecated and will go offline during next season.
GCM is being deprecated, so this is migrating to its successor. If this change is not made then notifications will stop working. Solves issue #2268
I have also changed the authkeys page to reflect that it is now the FCM key, not the GCM key.
Phil tested this with a test version of the Android app and was able to send a test notification to himself with it.
> Switching notifications to FCM over (now deprecated) GCM

- app.yaml
- deploy_requirements.txt
- ops/travis/travis-deploy.sh
Followed migration guide:
https://cloud.google.com/endpoints/docs/frameworks/python/migrating
I think the problem last time was that we didn't deploy a new GAE version. So let's try that now
Closes https://github.com/the-blue-alliance/the-blue-alliance/issues/2277
Google will deprecate this in August....
yolo
> Migrate to Cloud Endpoints v2 (yet again)

- templates_jinja2/match_timeseries.html
As requested in Slack, a warning blurb below the timeseries chart as to the accuracy of the data following multiple Chief Delphi threads about it.
Teams were confusing the time series chart as a definitive source of data and minor bugs in the OCR were causing 200 point jumps in either direction (OCR'd a 1 as a 3).  This hopefully will clarify that it's an experimental feaure.
I used inspect element to check that it displayed properly and implemented it in the exact location in the jinja template creates it in.
> Add warning to timeseries about accuracy.

- consts/ranking_indexes.py
- controllers/api/api_trusted_controller.py
- helpers/rankings_helper.py
- static/javascript/tba_js/eventwizard_apiwrite.js
This allows users to import 2018 FMS Ranking Reports
#mordata
It has not been tested.
Rank | Team | RS | Endgame | Auto | Ownership | Vault | W-L-T | DQ | Played | HRS*
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 5813 | 3.20 | 375 | 167 | 1,186 | 140 | 5-0-0 | 0 | 5 |  
> Fix 2018 ranking import

- cron.yaml
Actually fetch official 2018 offseasons, start fetching 2019 official events
> Update event sync years

- bootstrap.py
- controllers/suggestions/suggest_apiwrite_controller.py
- controllers/suggestions/suggest_designs_review_controller.py
- controllers/suggestions/suggest_event_media_controller.py
- controllers/suggestions/suggest_offseason_event_controller.py
- controllers/suggestions/suggest_offseason_event_review_controller.py
- controllers/suggestions/suggest_team_media_controller.py
- docs/dev-container.md
- react/gameday2/components/AppBar.js
- react/gameday2/components/NoWebcasts.js
Update all URLs to use the www host as a stopgap measure. It will
also save the 302 redirect once #2298 gets fixed.
Due to #2298, links that resolve to thebluealliance.com are redirected
to www.thebluealliance.com without the remainder of the path intact.
4 character addition per instance, not tested.
> Expand site URL

- tests/test_event_get_timezone_id.py
I've noticed that the timezone tests are extremely inconsistent about whether or not they work and constantly fail builds for PRs that are actually perfectly fine. This pull request removes those tests so that we can see if it's the PR's code itself that's making it fail instead of having to check if errant timezone tests screwed everything up again.
Pull request builds are failing with no reason other than these tests acting up.
A test run with no changed code except for this passed.
> These tests seem to randomly fail so I deleted them

- ops/dev/Dockerfile
Added a step to the provisioning that makes using Paver in the dev container possible (fixed loading the PYTHONPATH)
It is required so that Paver bootstrap and other commands requiring the Google App Engine SDK work in the container.
Provisioning without the fix causes errors when using paver bootstrap. Provisioning with the fix does not produce the error. Tested on my Ubuntu 18.04 laptop. No other tests have issues.
> PYTHONPATH fix

- templates/apidocs_overview.html
Made the codegen libraries no longer "coming soon" but linked with a "here they are"
The codegen APIs are no longer coming soon, they are available and the documentation should reflect that.
I opened the page in Chrome and nothing was broken
https://imgur.com/a/zfSEfaf
> Added codegen API link since that's a thing now

- static/javascript/tba_js/eventwizard_apiwrite.js
- templates/eventwizard.html
- templates/react-eventwizard.html
This pull request allows the EventWizard to import spreadsheets generated by the FRC FMS.
Previously, when importing spreadsheets generated by the FMS, the Event Wizard could not find any data; however, after re-saving the spreadsheets, everything worked as intended. 
As these changes are very simple, minimal testing was required. I first tested the FMS-generated files, to ensure that my changes worked as intended. Then, to further ensure that everything was working, I tested all of the re-saved files. **(Note: It is necessary to use spreadsheets from 2018 in order for everything to work as intended. I was using 2017 spreadsheets to make sure the loading worked.)**
@tweirtx also tested these changes.
> Fixes issues when importing FMS-generated spreadsheets

- models/media.py
- static/javascript/tba_js/tba.js
Move Instagram image presentation to use the suggested (by Instagram) media embedding URLs.
Some Instagram images are broken, due to us saving media URLs that are now outdated.
This fixes #2297.
Locally.
The second image in the screenshot is from Instagram:
And the image carousel, with said Instagram image:
> Fixed Broken Instagram Images

- controllers/test_notification_controller.py
- templates/webhookdocs.html
This pull request reworks the webhook documentation page to allow test webhooks to be sent for events and matches other than those from `2014necmp` (2014 New England championship). The original test buttons have been replaced with forms that allow custom TBA keys to be specified, defaulting to `2014necmp` for consistency with the original implementation.
This is intended as a quality-of-life feature. When developing and testing applications that need to process data coming through TBA webhooks, it can be irritating to only be able to receive test data from the 2014 season, which has no FMS data available. By allowing for custom TBA keys to be used, webhook-based client testing and development can be made far easier than before.
Multiple tests were conducted, with various inputs. TBA key …
> New custom webhooks

- templates_jinja2/team_partials/team_head_tags.html
Closes #2327
Modifies the og:title attributes to 1) match the order of data in the title attribute, and 2) show the year for the team, if we're showing the non-canonical page
#2327, also it makes sense when sharing a year page for a team the social tags show the year
Tested locally
Canonical page
Non-canonical page
> Show year for non-canonical team shares (closes #2327)

- react/eventwizard/eventwizard.less
Lowered the `z-index` of the re-mapping section so that the playoff drop down would be over it.
It was annoying, and made the wizard harder to use.
See #2322
Locally
Before:
After:
> Fixed playoff type selection in React eventwizard being under other elements

- controllers/notification_controller.py
- helpers/notification_helper.py
- mobile_main.py
- models/mobile_api_messages.py
Adds a Ping endpoint to myTBA to dispatch a test notification for a user.
This is a next-step in https://github.com/the-blue-alliance/the-blue-alliance-ios/pull/345 which helps users debug information about push notifications. Allowing users to kickoff a push will help us test end-to-end that things are working as expected.
It has not ⚠️  There doesn't seem to be any `NotificationHelper` tests, and I don't believe there's documentation on how to get a push setup locally. This seems fairly low-risk, since it's adding new functionality and not modifying existing functionality.
> Add Ping endpoint to myTBA

- helpers/notification_sender.py
- notifications/base_notification.py
- notifications/update_favorites.py
- notifications/update_subscriptions.py
- tests/test_notification_base.py
Gearing up for the iOS launch, one of the things we want to do is support notifications. This wires up sending the current notifications to iOS through Firebase (which I think is still outstanding if we know if it works or not). This also DRY-s out some of the base notification code, while still allowing overriding render methods.
It has not ⚠️
> Dispatch notifications for iOS, combine notification render methods

- notifications/upcoming_match.py
- templates/webhookdocs.html
- tests/test_notification_upcoming_match.py
Fixes #2254 to properly send `predicted_time` in the `UpcomingMatchNotification`. Also updates the documentation to better clarify when these fields will or won't have data.
I updated the tests in `UpcomingMatchNotification` as well, but we never predict times for matches in our tests, so the `predicted_time` isn't really tested and will always be `None`. If anyone feels strongly about adding some way to add predictions to matches in `MatchTestCreator`, I'm more than willing to do that work.
> Fix UpcomingMatch notification to send predicted_time

- ops/travis/travis-deploy.sh
Web deploys have been stuck since https://github.com/the-blue-alliance/the-blue-alliance/commit/893056fe0f3a17ab9107d9363c18a0f4c0fbeaaf - it looks like this is a problem others using Travis have fixed via this `BOTO_CONFIG` hack
As noted in Slack, it looks like what changed is we upgraded from Cloud SDK 226.0.0 -> Cloud SDK 227.0.0 and this broke
> Attempt to fix web deploys

- app.yaml
- controllers/apiv3/api_admin_controller.py
- ops/travis/should-deploy.sh
- ops/travis/travis-deploy.sh
During the deploy phase in Travis, check if our endpoints configuration has changed, and deploy the new configuration if necessary.
We shouldn't need to specify the `ENDPOINTS_SERVICE_VERSION` - endpoints will default to using the latest deployed version https://github.com/cloudendpoints/endpoints-management-python/pull/69
Note: this does move the `should_deploy` check to later, after setting up Python and gcloud and whatnot.
Automate something that's currently manual and requires keys
> Automatically deploy endpoints config

- templates_jinja2/district_details.html
frc-districtrankings.firstinspires.org is being discontinued and replaced with frc-events. There isn't an exactly equivalent page as fair as I can tell so this will at least get to the list of districts.
On the District Rankings page, we link to the frc-districts site which is being decommissioned. That site shows this banner:
This update should link to the closest to equivalent page. 
Clicking the link gets you to an outdated page. Fine for now but will eventually be problematic.
It hasn't. Also, I don't really know what I'm doing with the {{year}} variables so if someone could check my work that would be nice.
> Updated district ranking link

- controllers/base_controller.py
- controllers/team_admin_controller.py
- models/team_admin_access.py
- templates_jinja2/media_partials/media_display_partial.html
- templates_jinja2/team_admin_dashboard.html
Give team media moderators the ability to remove/make preferred media.
Does a few things:
- skeleton out team mod dashboard
- hook up removing references/managing preferred-ness
This does not yet deal with social media or the suggestion queue. It should probably also implement a modal confirmation before doing writes. And we should also have logging for admin actions...
> [modtools] Implement Team Media Management

- .travis.yml
- mobile_main.py
- ops/travis/travis-worker.sh
https://github.com/the-blue-alliance/the-blue-alliance/commit/19034851d81767de972dd6c93a41e03a0a779768 broke deploys (well, only the last half of deploys - we're still successfully deploying to the web), because we're running in to an error when generating the endpoints configuration. That `ANDROID_AUDIENCE: True` line is the problem - the endpoints config script complains about a missing issuer
```
TypeError: Missing issuer 
```
I'm not entirely sure what it's looking for here, since from what I can tell, that `ANDROID_AUDIENCE` value isn't going to be one of the values in our issuers. Additionally, I can't find any documentation about what that line is actually doing.
Finally, I added a step to the `LINT` job that generates our endpoints configuration (and cleaned up the formatting), …
> Fix crash when generating endpoints configuration

- controllers/suggestions/suggest_designs_review_controller.py
- controllers/suggestions/suggest_social_media_review_controller.py
- controllers/suggestions/suggest_team_media_review_controller.py
- controllers/team_admin_controller.py
- helpers/suggestions/suggestion_creator.py
- templates_jinja2/team_admin_dashboard.html
A mostly-working implementation for the suggestion queue
Render pending suggestions for the mod dashboard. This does some horribly hacky things like posting to the main review controllers (and thankfully they all expect the same format of data input). Which means it _does not_ yet do permissions - you need to have the global review permission for this to work (for now)
> [modtools] Basic suggestion queue support

- database/dict_converters/event_details_converter.py
- tba_config.py
Sometimes we haven't (or can't) computed event details for certain events. In those cases we return null, but actually we should return sensible results like empty objects.
Fixes #2333
#2333 and reasonable API expectations
Locally get yourself an event, and then nuke the EventDetail record from the datastore. This matches what we have in production for an event like `1992cmp`.
`curl -H 'X-TBA-Auth-Key: {}' http://localhost:8080/api/v3/event/1992cmp/rankings`
```
{
"extra_stats_info": [], 
"rankings": null, 
"sort_order_info": null
}
```
>  Fix cases where EventDetail types API returns null 

- static/javascript/tba_js/tba_typeahead.js
Generate type ahead tokens for event keys using the same regex as the selected function.
Includes much removal of real tabs, and general whitespace cleanup.
#2332 
Many want the ability to partially type a partial event key into search and return the results. We already support matching the entire event key, but this just takes it to the next level.
General usage in Chromium 71 on debian (couldn't get local typeahead.js to work on Firefox at all which is for another day).
This makes the assumption that `TypeaheadCalcDo` will always generate event strings in a specific human readable format which may or may not be a good idea :man_shrugging:.
> Add support for event key type ahead.

- templates/base.html
- templates_jinja2/base.html
Not entirely sure why it was commented out, 51c5ebfdf0ab8b89cac7e81c9d082a61ed953e59 isn't really clear about that. This brings it back.
#2345 
:eye: chromium 71, firefox 60.4, iOS safari
> Add back Instagram links in nav bar

- templates_jinja2/team_admin_dashboard.html
- templates_jinja2/team_admin_redeem.html
Modtools docs pass.
Clarifies language from `mod` to `admin`, adds help tab to dashboard, removed broken help link and link back to redeem as per 1 redemption per account limit.
Please review and comment.
> Modtools docs pass

- deploy.py
- ops/travis/travis-deploy.sh
Attempting to fix the [failed TBANS deploy](https://travis-ci.org/the-blue-alliance/the-blue-alliance/jobs/476013831) by moving `dispatch.yaml` to be the last thing deployed
> Change order of service deploys to deploy services before dispatch

- tbans/tbans_service.py
We're seeing errors right now being thrown because of a missing import in TBANS. This code path is only executed on prod which is why I didn't catch is 😓
> Fix missing app_identity import in TBANS

- controllers/main_controller.py
- helpers/season_helper.py
- tests/test_season_helper.py
Adds dynamic stop build dates for homepage - closes #2381
I'm realizing the lifespan of this code is probably... 43 days 😓 
Prod vs Dev (somehow, one minute off?)
> Add dynamic stop-build dates for homepage

- datafeeds/parsers/fms_api/fms_api_team_details_parser.py
FIRST stopped allowing teams to add them, so we can stop fetching them
> Stop Fetching Robot Names for 2019

- templates_jinja2/match_partials/match_breakdown/match_breakdown_2019.html
The HAB Docking tooltip had an extra `{`.  Fixes the typo.
Delete the `{` character.
If the `{` was included it is probably a typo.
It has not...
> Remove extra `{`

- helpers/event_helper.py
- templates_jinja2/event_details.html
- templates_jinja2/event_partials/event_macros.html
- templates_jinja2/team_details.html
- tests/test_event_group_by_week.py
- Use `Event.week_str` in `event_helper.py` to de-dupe week string generation.
- Add link to `/events/<year>#<week>` on week badges.
- Refactor code to use same date generation logic on Event and Team pages.
Local dev.
> Add Event Week to Team Pages

- database/district_query.py
Fixes #2403
Query for equivalent codes in `DistrictHistoryQuery`
Local dev with 2018 and 2019
> Fix district history not returning equivalent code districts

- database/dict_converters/media_converter.py
The direct image URLs for YouTube videos are currently exposed as HTTP links instead of HTTPS links. This changes switches them to use HTTPS.
The Android app would like to use the media URLs exposed via the API instead of generating those URLs ourselves (see [#885](https://github.com/the-blue-alliance/the-blue-alliance-android/issues/885)). However, as of Android 9 (Pie), cleartext traffic is disabled by default. While we could enable it here, there is no compelling reason to do so instead of just getting HTTPS links to begin with.
I set up a dev environment with this change, and observed no regression on the team pages under media (which makes sense, as it does not appear as though the web site is consuming this- it is exposed for other clients).
The HTTP versions of these URLs redirect …
> Use HTTPS for YouTube image URLs

- templates_jinja2/suggestions/suggest_match_video_review_list.html
- templates_jinja2/suggestions/suggest_team_media_review_list.html
Adds a toggle using Bootstrap built-ins to hide contents_json for some suggestions, particularly Team Media, where Instagram is TOO LONG.
Mod quality of life
Screenshots below from my dev instance
Before:
After collapsed:
After expanded:
- [ x ] New feature (non-breaking change which adds functionality)
> Collapse contents_json for long metadata suggestion types

- templates/mytba_live.html
Add the event week to the date block on myTBA.
Uses the macro at `templates_jinja2/event_partials/event_macros.html` to add the event date with the week. Replaces the code for the event date with `{{ em.showEventDates(event) }}`. 
The event week is now listed next to the date in other places, so it should be listed here, too.
I _think_ I did this right but I'm not positive.
> Add event week to myTBA

- templates_jinja2/event_details.html
Corrects Google Structured Data errors for Events lacking location attributes. Fixes #2313
Improve structured data for search engines.
Compared master and this branch in the https://search.google.com/structured-data/testing-tool/ .
I did not test both codepaths for emitting event locations, since I don't know what causes one or the other to be used, but believe this change covers both.
> Add location schema.org field to Event locations

- templates/base.html
- templates/index_buildseason.html
- templates/index_champs.html
- templates/index_competitionseason.html
- templates/index_insights.html
- templates/index_kickoff.html
- templates/index_offseason.html
- templates/index_partials/schema_org_markup.html
Adds schema.org markup for:
1. `Organization` to hopefully get us a Knowledge Panel
* https://developers.google.com/search/docs/guides/enhance-site
* https://developers.google.com/search/docs/data-types/corporate-contact
2. `WebSite` to tell Google about our search box
* https://developers.google.com/search/docs/data-types/sitelinks-searchbox
Fixes #1815
Be fancy in search engines
Pasted local HTML into Google structured testing tool.
> Schema org markup for Google

- travis_requirements.txt
I don't have a great way to prove this works - unless someone wants to pull, destroy their Docker instance, and fire up a new one. 1.3.14 was the latest version that didn't error out with `dev_appserver.py`. Fixes #2398.
> Pin mysqlclient version to fix dev_appserver import error

- tbans/models/messages/fcm_message.py
- tbans/models/messages/webhook_message.py
- tests/test_tbans_webhook_message.py
Change requests to webhooks via TBANS to be async instead of sync, since we don't really care about the server's response content or response code. Surfacing those things via TBANS felt nice for monitoring/logging, but I now realize we shouldn't need to care about those things, and the original code was misguided.
We're seeing errors when calling TBANS that webhook request are timing out, because clients aren't handling requests in time (default timeout for `urlfetch` is 5s). Our protorpc request timeout to TBANS is also 5s. After digging through source, there doesn't appear to be a way to bump the protorpc request timeout.
Instead of bumping the response time down for clients, we can make calls to webhooks asynchronously and ignore their responses, since we don't care. This will speed up …
> Make async webhook calls in TBANS

- package.json
- react/gameday2/components/VideoCell.js
- react/gameday2/components/VideoCellAnalyticsTracker.js
Track how long certain webcasts are open in GameDay in Google Analytics.
Fires every minute.
Tracks in a separate GA property from the website.
> Track webcast view time in GameDay

- templates/admin/base.html
Adds modcodes to Team section of admin nav
Had to move a modcode, didn't know we had the tool already built. Now it's there!
Local dev instance
> Add modcodes to admin nav

- static/css/less_css/less/tba/tba_base.less
- templates/index_partials/apps.html
Makes the app install banner icons narrower, centered. Fixes issues on smaller screens.
They used to overlap clownily.
Local instance
Before
After
> Changes to app banners on narrower screens

- static/swagger/api_v3.json
I'm open to fixing the wording on this one - just want to make sure we call out that both fields may be null in some cases, since the current docs don't say that.
> Update Award_Recipient docs to list that awardee and team_key may be null

- templates_jinja2/match_partials/match_breakdown/match_breakdown_2019.html
Removes extraneous `}` on the tooltip.
Closes #2434
> Fixes #2434

- ops/dev/Dockerfile
- ops/dev/vars.sh
We overwrite the Docker container's `PYTHONPATH` via that `vars.sh` script, which means what we set in our `Dockerfile` isn't respected. The `PYTHONPATH` doesn't need to be set during installs/setup, and we should be fine letting it get set at the end of the script.
This change also adds the `protorpc-1.0` lib to the `PYTHONPATH`, which is something we did on CI to get the TBANS tests running, but never did in the Docker container (I usually do it locally to get the tests to run)
> Update PYTHONPATH to look for protorpc library

- app-backend-tasks-b2.yaml
- app-backend-tasks.yaml
- app.yaml
- controllers/api/api_base_controller.py
- controllers/apiv3/api_base_controller.py
- helpers/firebase/firebase_pusher.py
- helpers/manipulator_base.py
- stackdriver/profiler.py
Sets unique deferred task URLs so they show up differently in the logs.
> Set unique deferred task URLs

- app.yaml
- dispatch.yaml
- mobileapi.yaml
- mobileapi/mobile_main.py
- ops/travis/travis-deploy.sh
- pavement.py
- Duplicates the current internal mobile API at `/mobileapi/*` under a separate service.
- Adds a `test` endpoint for easier testing.
We are trying to move everything to its own service for better separation of concerns for code and ops. This allows us to test & use the existing internal mobile API with both the old and new service until everything is migrated to point to the new one.
Visiting `/_ah/api/tbaMobile/v9/test` and `/mobileapi/tbaMobile/v9/test` both work in local dev.
> Separate service for internal mobile API

- clientapi.yaml
- clientapi/clientapi_service.py
- deploy_requirements.txt
- dispatch.yaml
- mobileapi.yaml
- mobileapi/mobileapi_service.py
- ops/travis/travis-deploy.sh
- pavement.py
- Duplicates the current internal mobile API at `/clientapi/*` under a separate service.
- Adds a `test` endpoint for easier testing.
- Handles Firebase authentication ourselves.
We are trying to move everything to its own service for better separation of concerns for code and ops. This allows us to test & use the existing internal client API with both the old and new service until everything is migrated to point to the new one. The new service doesn't use managed endpoints for authentication.
Visiting `/clientapi/tbaClient/v9/test` works in local dev. Adding an `Authorization` header returns the user ID.
> Separate clientapi service attempt 2

- tbans/models/messages/fcm_message.py
- tests/tbans_tests/models/messages/test_fcm_message.py
Follow up PR for https://github.com/the-blue-alliance/the-blue-alliance/pull/2442 - removes the authentication code we use in `FCMMessage` for the new util method in `auth_utils`, since they're the same.
> Remove old auth methods from FCMMessage

- tbans/consts/fcm_error.py
- tbans/models/messages/fcm_message.py
Another follow up from https://github.com/the-blue-alliance/the-blue-alliance/pull/2442 - had an extra todo to extract the FCM error code constants in to their own file, like the other error constants now are.
> Add error class FCMError for FCM error codes

- tbans/tbans_service.py
The motivation behind this is if we're sending invalid request to TBANS, the logs look all 200. In the case we start sending invalid requests (maybe someone changes the helper methods), the logs will at least start showing up as red.
> Add helper method to log/return 400s in TBANS

- tbans/consts/platform_payload_priority.py
- tbans/consts/platform_payload_type.py
- tbans/models/subscriptions/subscription_batch_response.py
- tbans/models/subscriptions/subscription_response.py
- tbans/models/subscriptions/subscription_status.py
- tests/tbans_tests/models/subscriptions/test_subscription_batch_response.py
- tests/tbans_tests/models/subscriptions/test_subscription_response.py
- tests/tbans_tests/models/subscriptions/test_subscription_status.py
Fixed some initialization weirdness with the Instance ID model classes. `SubscriptionBatchResponse` shouldn't throw an error if we have an empty `results`, because we got back error JSON.
Additionally, this just adds another level of validation that a `SubscriptionResponse` gets initialized with either an error or a response, which means we can check for an error or a status code when looking for an error (because one or the other will be right). In it's current implementation if we init an empty object (which is currently possible) we'll get an unknown error, even though we didn't get an error back from the server.
And finally, `SubscriptionStatus` didn't have validation on the JSON and the rest of the classes do, so I added it, along with a test to make sure it can be initialized …
> Fix Subscription (Instance ID) model init errors

- templates/index_buildseason.html
- templates/index_competitionseason.html
- templates_jinja2/event_details.html
Updates the URL tied to three different buttons on the site.
- Changes the <img src="https://user-images.githubusercontent.com/22439365/54663586-02476680-4a9f-11e9-90a6-d2f01f834b27.png" width="125px"></img> button to link to `/add-data` on both `index_buildseason` and `index_competitionseason`.
- Changes the <img src="https://user-images.githubusercontent.com/22439365/54663720-7c77eb00-4a9f-11e9-93eb-284192f70e0a.png" width="125px"></img> button on `event` pages to go to the same URL as the <img src="https://user-images.githubusercontent.com/22439365/54663777-9f0a0400-4a9f-11e9-8da7-64af7e78bc0f.png" width="100px"></img> button on top of the `event` page.
Currently, the Add button on the homepage just links to the Contact page. However, once on the contact page, there is a section about …
> Modify "Add Video" buttons

- tbans/models/notifications/verification.py
- tests/tbans_tests/models/notifications/test_verification.py
Follow up on https://github.com/the-blue-alliance/the-blue-alliance/pull/2473 - we fixed the secret validation in the request but not in the notification (we need both when forming a verification request)
> Remove validation on secret for verification notification

- static/css/less_css/less/tba/tba_bracket_table.less
I have added position: static to .brackettable tr td in tba_bracket_table.less
This is in response to [issue 2481](https://github.com/the-blue-alliance/the-blue-alliance/issues/2481). The bug not only existed in Chrome on Windows, but was also in Chrome on Linux. Firefox in Linux showed no inside borders. Bracket table cells were inheriting a position: relative from the table td styling, but table cells have an undefined behavior when using relative positioning (as defined in the [CSS2.1 Standard](https://www.w3.org/TR/CSS21/visuren.html#choose-position)), so I have added overridden the .brackettable tr td to be statically positioned. The insights page problem is probably a similar issue, but is not addressed in this fix as it should probably be its own issue.
Ran local dev server in …
> fixed bracket table incomplete border issue (issue 2481)

- templates_jinja2/suggestions/suggest_match_video_review_list.html
An earlier diff removed the `suggestions` variable and replaced it with `suggestions_and_events`. This updates the count to use the new variable.
Fixes video count.
Local sandbox
Before
After
> Fix suggestion count on match video suggestions.

- controllers/base_controller.py
- controllers/webhook_controller.py
- templates/webhook_add.html
- templates_jinja2/account_overview.html
This change to the webhook controller ensures that name, url, and secret are all non-None for webhooks. Closes #2474
TBANS was assuming webhook secrets were non-None, which doesn't appear to be enforced via during webhook creation. We discussed via Slack generating secrets for users that don't specify secrets so they have a fallback for doing checksums. The next step is to migrate webhook users that don't have secrets set right now and add the validation back in to TBANS.
This also surfaces secrets in the mobile clients UI, since we don't show it right now. There's a lot of diffs, but mostly it's fixing formatting in the HTML/un-nesting the returns in the webhook controller.
Tested in dev
> Make sure webhook url, name, and secret are non-None

- cron.yaml
Increases frequency of backup cron job to publish fresher data to bigquery
People are asking for fresher data
It has not. Please verify this will work as intended. I copied the cron syntax from the "Update Team Search Indexes" job.
> Run backup to bigquery cron weekly

- notifications/alliance_selections.py
- notifications/awards_updated.py
- notifications/base_notification.py
- notifications/broadcast.py
- notifications/district_points_updated.py
- notifications/level_starting.py
- notifications/match_score.py
- notifications/match_video.py
- notifications/ping.py
- notifications/schedule_updated.py
- notifications/upcoming_match.py
- notifications/update_favorites.py
- notifications/update_subscriptions.py
- tests/test_notification_awards.py
- tests/test_notification_base.py
- tests/test_notification_level_starting.py
- tests/test_notification_ping.py
- tests/test_notification_push.py
- tests/test_notification_schedule_updated.py
- tests/test_notification_score.py
- tests/test_notification_upcoming_match.py
- tests/test_notification_update_favorites.py
- tests/test_notification_update_subscriptions.py
FCM messages are failing to send right now because we're using `message_type` which FCM uses as a reserved keyword. This changes FCM client (Android) notifications to use `notification_type` instead
> Use notification_type instead of message_type for FCM messages

- templates/about.html
Change 'anaytics' to 'analytics' in templates/about.html
N/A
Fixes a public-facing spelling error
Not tested
N/A
> Fix spelling error in about template

- controllers/admin/admin_cron_controller.py
- cron_main.py
- templates/admin/mobile_dashboard.html
Adds an endpoint and admin console button to migrate webhooks without secrets set. Will revert once migration is complete.
Follow up to https://github.com/the-blue-alliance/the-blue-alliance/pull/2476 and closes #2487 - there are currently 40 webhooks without secrets. We've added validation when creating a webhook that a webhook must have a secret set (we'll generate one by default if the user does not supply one). This will allow us to revert 52744f6e93b8a68a3ab2d9060e43673caf238eb6 and ee567385489627c76167b197fb6b9543e53565b6
Tested on a dev instance.
Before:
After:
> Migrate secretless webhooks

- docs/dev-container.md
frc-events has switched to a new api key request system on a new website. This PR changes the old link to the new link in the dev-container instructions
> Use new frc-events API key request link

- helpers/event_insights_helper.py
This allows these objectives to be recorded and analyzed for playoff matches.
On the other hand, it's a bit confusing to note RP being scored in playoff matches, so we should discuss whether that needs to be clarified in the template text.
Changed the logic for calculating rocket and hab RPs to be when the FIRST API reported RP _or_ when the match breakdown indicates RP criteria was met.
The FMS can report RPs that aren't met by match breakdown, e.g. G5/G16 for rocket RP. This differs from previous years where RP requirements would have been satisfied by the causing the component events to be scored, hence the explicit RP indications in the FIRST API.
This allows for rocket RP, hab RP, and unicorn match analysis on playoff matches, which @jaredhasenklein requested.
Fixes #2489.
Spot …
> Base RPs and unicorn matches off of match breakdowns

- helpers/insights_helper.py
- models/award.py
- templates_jinja2/team_details.html
- templates_jinja2/team_history.html
- templates_jinja2/team_partials/blue_banner_macros.html
Verified locally that only one blue banner for WFA shows up for 3847 in 2019.
Verified locally that insights counts 3 total banners for 3847 in 2019, not 4.
Before
After
> Only show & count one Championship Woodie Flowers banner

- templates_jinja2/playoff_partials/playoff_table.html
Phil's change in https://github.com/the-blue-alliance/the-blue-alliance/commit/a04fe4ad9c687ced4ec125a7f8f9b7dc4d0ae147 added a `num_played` field to the results of `generatePlayoffAdvancement2015`, but we weren't unpacking that value in the templates. This updates the templates to unpack that value and fix the 500s for 2015 events.
> Unpack num_played in 2015 advancement template

- templates_jinja2/team_admin_dashboard.html
Updated the modtools FAQ page to include a blurb on expiration of access. (Figure it may save some emails after 7/1 See https://github.com/the-blue-alliance/the-blue-alliance/blob/master/controllers/admin/admin_team_media_mod.py#L90 for current expiration setting.)
Also bumped up the `h5` tags to `h4` for the Q's on the FAQ page to make them a bit more visible.
Trying to avoid "Hey - where'd my access go?" emails & CD posts.
`#WeTestInProd`
(HTML only change)
> Update modtools FAQ for Expiration

- models/event.py
- models/match.py
- tbans/models/notifications/alliance_selection.py
- tbans/models/notifications/awards.py
- tbans/models/notifications/broadcast.py
- tbans/models/notifications/district_points.py
- tbans/models/notifications/event_level.py
- tbans/models/notifications/event_schedule.py
- tbans/models/notifications/match_score.py
- tbans/models/notifications/match_upcoming.py
- tbans/models/notifications/update_favorites.py
- tbans/models/notifications/update_subscriptions.py
- tests/tbans_tests/models/notifications/test_alliance_selection.py
- tests/tbans_tests/models/notifications/test_awards.py
- tests/tbans_tests/models/notifications/test_broadcast.py
- tests/tbans_tests/models/notifications/test_district_points.py
- tests/tbans_tests/models/notifications/test_event_level.py
- tests/tbans_tests/models/notifications/test_event_schedule.py
- tests/tbans_tests/models/notifications/test_match_score.py
- tests/tbans_tests/models/notifications/test_match_upcoming.py
- tests/tbans_tests/models/notifications/test_update_favorites.py
- tests/tbans_tests/models/notifications/test_update_subscriptions.py
This adds all existing notification models (other than `MatchVideo` and `EventMatchVideo` - those ones need more thought) to TBANS.
> Add existing notification models to TBANS

- database/match_query.py
- models/match.py
- tests/test_api_trusted.py
Correctly indicate disqualification status for eliminations.
See diff.  It's pretty minor.
We currently do not correctly indicate that elimination alliances are
disqualified together.  We currently only mark the middle team as
disqualified.
See #2507.
> Fix #2507.

- backend_main.py
- controllers/datafeed_controller.py
- sitevars/website_blacklist.py
- templates/admin/team_details.html
- tests/test_sitevar_website_blacklist.py
Adds a "Blacklist Website" button to the Team admin page to blacklist a team's current website
Blacklisting websites right now involves modifying a sitevar, which is pretty gross.
Tested on a staging instance
(Before - with the button)
(After - automatically re-scrapes the team)
(Blacklist sitevar - automatically updated)
> Add blacklist website button to Team admin page

- consts/notification_type.py
- helpers/notification_helper.py
- notifications/update_subscriptions.py
- tbans/models/notifications/update_subscriptions.py
- templates/webhookdocs.html
- tests/tbans_tests/models/notifications/test_update_subscriptions.py
- tests/test_notification_update_subscriptions.py
Stop sending `UPDATE_FAVORITES` and `UPDATE_SUBSCRIPTIONS` notifications to all non-Android clients (webhooks mostly). Also update the webhook documentation to remove references to these notifications.
Also rename `UPDATE_SUBSCRIPTION` -> `UPDATE_SUBSCRIPTIONS` for parity.
We realized we were dispatching these notifications to webhooks when they can't use them.
This hasn't been tested 🙊
> Only send update favorites and update subcriptions notifications to Android clients

- tbans/requests/webhook_request.py
- tests/tbans_tests/requests/test_webhook_request.py
Webhook verifies and pings are failing if the user doesn't get the first request on a TBANS instance. My guess is that our end-to-end requests are succeeding too fast, and the request gets killed/canceled/never executed (I'm seeing 5ms-20ms in the logs for non-first-process requests). Post-change requests look to be a more reasonable length (~100-200ms).
This reverts #2422, which made webhook reqeusts async. If a server doesn't reply to a ping or to a verification within the time allotted (it's 10s end-to-end, with a little overhead in web), showing a 500 in web seems fine. I think the real solution here is to work on some debug messaging for users, as opposed to showing a 500. But we can handle that later, once we get webhook requests working again.
> Fix TBANS webhook requests failing to deliver (revert #2422)

- helpers/match_helper.py
This allows 2019 match breakdowns to be uploaded via the write API. 
Currently, any attempts to do this result in this error:
```
Valid score breakdowns for 2019 are: set([])
```
I would like for this to be fixed before one of my upcoming events, and I'm pretty sure this is the only place that needs to change. (I'm not sure if the rankings endpoint needs to be updated or not, though.)
I haven't gotten Docker to work locally so it hasn't been. But I did run this file through the Python interpreter to make sure there aren't any syntax errors (there aren't). The field list is taken from https://www.thebluealliance.com/api/v3/match/2019micmp1_qm1, which I believe is complete.
> Update valid match breakdowns for 2019

- templates_jinja2/account_overview.html
Adds a button on `/account` to request API tokens.
Adds a "Request Tokens" button next to the API Write Key area of the account page. 
The button matches the one found [here](https://www.thebluealliance.com/request/apiwrite) and is in a similar style to the one above on read keys.
I went to my Account page, remebering that there were API keys there, trying to request write keys for an offseason. I realized on that page, I can request read keys but not write keys. I think there should be a button or link that directs to `/request/apiwrite` from there because I had to follow three links to get to the page I intended.
> Add button to request API write tokens

- consts/playoff_type.py
- helpers/playoff_advancement_helper.py
- templates_jinja2/event_details.html
Creates `PlayoffType.CUSTOM` for events that do not use any of the standard elims brackets that have already been implemented, e.g. `2019bc`.
For custom playoff types, the standard eliminations bracket is not rendered, and instead, only the elims match list is rendered.
#2540 
Tested on local instance of TBA
https://i.imgur.com/Z55pcw6.png
> Add custom playoff type

- templates/admin/debug.html
- templates/admin/tasks.html
The buttons on the admin console for launching tasks related to generating insights were broken.
I found URLs that work in `cron.yaml`, so I just replaced the 404ing URLs with the corresponding ones from there.
Makes dev lives easier
Manually tested, you should probably test it on your own as well
> Fix task enqueue URLs for insights

- static/swagger/api_v3.json
Fixes issue 
1) TBA API where get_event("2019micmp") returns with a webcast of type "direct_link" which is not an allowed type webcasts
2) TBA API where get_team("frc7") creates error because their rookie_year is None
Adds "direct_link" to the allowed types for webcasts
Removes "rookie_year" requirement from teams since many teams do not have a rookie year EG : frc326, frc7
> Added "direct_link" to webcasts type and Removed "rookie_year" as requirement for teams

- admin_main.py
- api/apiv3/api_event_controller.py
- controllers/admin/admin_event_controller.py
- controllers/admin/admin_migration_controller.py
- controllers/cron_controller.py
- controllers/event_controller.py
- cron_main.py
- datafeeds/csv_advancement_parser.py
- helpers/event_details_manipulator.py
- helpers/match_manipulator.py
- helpers/playoff_advancement_helper.py
- models/event.py
- models/event_details.py
- templates/admin/event_details.html
- templates_jinja2/bracket_partials/bracket_table.html
- templates_jinja2/playoff_partials/playoff_round_robin_6_team.html
- templates_jinja2/playoff_partials/playoff_table.html
We want to be able to support loading arbitrary data into playoff advancement (for offseason events that run their own round robin, for example), so move all this into a datastore model we can expose writes to.
This required changing the format of the bracket data to not have numeric keys (since those don't work with a round trip of json serialization).
Also haven't done cache clearing yet
> [wip] Migrate Event Playoff Advancement/Bracket into EventDetails

- static/swagger/api_v3.json
Turns out there were actually a bunch of different types that were not allowed and broke things when you called events containing them through the API.
Added a couple more webcast types that are left out in the API but present in the data set. This information was gathered by examining every webcast type across all years (1992-2019)
> Added more types to webcast types

- controllers/admin/admin_event_controller.py
- controllers/admin/admin_memcache_controller.py
- templates/admin/event_details.html
Enables clearing of pages for all teams at an event without manually clearing each team.
Locally, clicking "Clear Cache" on the event admin page also clears team page caches.
> Clear team page caches when clearing event page cache

- static/javascript/tba_js/eventwizard_apiwrite.js
This adds support for schedule reports exported from 2019 FMS. These reports dropped the "Match" column from last year and added that information to the "Description" column for playoff matches, so attempting to import them would result in a "No matches found in the file" message.
Fixes #2548
Match result reports seem to work as expected without changes.
Tested in a local instance with both qualification and playoff schedule reports from 2019MIBB and 2018MIBB, which were recognized and uploaded successfully. (I'm unsure if some people are still using 2018-style reports, so I have retained support for those as well.)
> Fix issues with importing 2019 FMS schedule reports

- helpers/match_helper.py
This fixes an issue where match times submitted in schedule reports via the event wizard would fail to parse, resulting in "?" placeholder scores being displayed instead of the scheduled match time. (`re.match` only looks for matches at the start of a string, and schedule reports contain strings such as "Sat 11:40 AM", so the weekday was causing issues here.) 
(Note that I based this on #2553 to get schedule imports to work at all, so that should probably be merged first. 0615b3c is the only new commit here.)
Tested uploading schedule reports on a local instance
Before:
After:
> Fix parsing match times in event wizard schedule import

- consts/playoff_type.py
- tests/test_playoff_type.py
Playoff type for `ROUND_ROBIN_6_TEAM` was messing up qual numbering. This wasn't caught before because Einstein doesn't have qual matches.
Short circuit `get_set_match_number` for qual matches.
Local dev on `2019pascs`
> Fix playoff type messing up qual numbering

- tests/test_event.py
Getting `week` setup on an actual object, even for testing, is pretty hard. This approach just subclasses `Event` to a `MockEvent` where we can set the `week`/`year` directly and makes sure the logic we're testing works right Closes #2401
> Add week_str tests

- api/apiv3/api_event_controller.py
- api/apiv3/api_team_controller.py
- api/apiv3_main.py
- controllers/cron_controller.py
- tba_config.py
Add `/api/v3/teams/all/(simple|keys)` and `/api/v3/events/all/(simple|keys)` endpoints that return ALL teams and events respectively.
Enables apps to download an index of all teams and events without hitting 40+ endpoints.
Local dev.
> Add APIv3 endpoints for all teams and all events

- templates_jinja2/suggestions/suggest_offseason_event.html
A bit of feedback from Slack - change the "Name" field to be "Event Name" in the offseason suggestion form
> Change Name field in Offseason suggest to be Event Name

- controllers/suggestions/suggest_apiwrite_review_controller.py
I was doing some work in a different branch and saw this file used `app_identity` - but it doesn't actually use `app_identity` or `tba_config`. Both dependencies got removed in https://github.com/the-blue-alliance/the-blue-alliance/commit/48e2c21bf82fd3a18db07c8d912bb55a148833b8#diff-7f331489138411648b1b87c7bccfc913
And it looks like we've never used `logging` in this controller
> Remove unused imports from SuggestApiWriteReviewController

- tests/test_sitevar_website_blacklist.py
Another little bit of cleanup - realized that we weren't clearing the cache between tests
> Clear nbd cache between website blacklist tests

- ops/dev/Dockerfile
This fixes the locale error issue I have when installing system-wide dependencies inside the container via pip, as well as gives us a version of Python 3.7 inside our dev container (I know we're still a little ways off from any upgrading)
> Update Docker Ubuntu version to 19.04

- controllers/team_controller.py
This adds a "8000's" tab to the team list, and hopefully makes it a bit easier to change in the future.
https://www.thebluealliance.com/teams/9 (8000s) currently 404s. This makes it work.
Locally, by importing 2020milak (which currently has 8126 registered)
> Add 8000-level page to team list

- templates_jinja2/index/index_insights.html
Failure from GCP is
```
return obj[argument]: UndefinedError: builtin_function_or_method object has no element 0
```
We should be able to fix this by calling `items()` instead of accessing `items`
> Change landing page insights items to .items()

- app-backend-tasks-b2.yaml
- app-backend-tasks.yaml
- dispatch.yaml
We're getting warnings during deploying that `module` is deprecated (which it is) and that we should use `service` instead. This doesn't require any migration or anything on our backend services, just changing the names works fine.
> Convert  keyword in service configs to

- database/event_query.py
- helpers/event_helper.py
- models/event.py
Confirmed on my staging instance that 2020 events match up properly with what's on frc-events, and that re-scraped 2019 events are still sorted properly
**Edit: Ignore this part - see https://github.com/the-blue-alliance/the-blue-alliance/pull/2584#issuecomment-536346649 - our week sorting is right**
The one exception is this Israeli DCMP which sorts as being Week 10 in our system, but shows up as Week 9 in frc-events. 99% success rate is pretty good I guess.
No tests because holy cow it takes so much setup to tests these - I can file a ticket to make sure we get tests
> Fix 2020+ event sorting

- templates_jinja2/match_details.html
Changes the match detail page.
Now, on the match details page, the title will follow (Event) (Year) rather than (Year) (Event). For example, a match will now say Beach Blitz 2019 instead of 2019 Beach Blitz.
Elsewhere on the site (such as on an [event page](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/templates_jinja2/event_details.html)), the format (Event) (Year) is followed. When clicking on a match from an event page, the inconsistency in header is clear.
It hasn't.
**Current:**
**New:**
> Match details page naming consistency

- models/event.py
Adds a case when figuring out `week` for an event to account for the empty week between Week 8 and Week 9 in 2020
Right now, 2020 events after Week 8 are shown with the wrong week.
Tested in a staging instance - made sure that `2020cmptx` (although we don't return a week for CMP events) was still being calculated as Week 8, whereas `2020iscmp`/`2020cmpmi` are being calculated as Week 9
> Fix 2020 event's weeks after Week 8 being off-by-one

- helpers/award_helper.py
Added OTHER award type to the award helper.
Allow submitting other award type from Cheesy Arena
Simple change. 
not tested.
> Add "OTHER" award type to award helper

- controllers/account_controller.py
This changes the write key table on `/account` to sort by event ID. This table is currently sorted by auth ID, which isn't as useful and makes navigating the table harder when it's large.
(This is currently just sorting by the first event ID - all of my keys just have one associated event, and I'm not sure when a key would have more than one, but hopefully this is still somewhat useful for those keys. They'll end up next to other keys from the same year, at least.)
Local instance
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
> Sort write keys by event ID

- templates_jinja2/index/index_insights.html
Changes the title on the graph from Elims to Playoffs on the insights page.
Elsewhere on the site (and even within insights), we refer to the matches after qualifications as Playoffs. This is the same terminology FIRST uses officially now.
Hasn't.
**Current (bottom of current home page):**
**Proposed:**
**Currently, [elsewhere on the site](https://www.thebluealliance.com/insights/2019):**
> Insights "Elims" --> "Playoffs"

- templates_jinja2/suggestions/suggest_team_media.html
A few minor things with the current verbiage about Onshape on the media suggestion page. F
Fixed the following:
- Uniform capitalization of "Onshape"
- Shorten sample URL. Onshape URLs are just too dang long. Followed a path similar to GrabCAD example link.
- Shortened help text about uploading Onshape video. Removed some unnecessary words.
On the suggestions page, Onshape is dominating for no good reason - it's just taking up too much room to say not a whole lot, imo.
Hasn't.
N/A
> Clean up Onshape verbiage

- templates/admin/base.html
The `/admin/suggestions/...` endpoints got removed in https://github.com/the-blue-alliance/the-blue-alliance/commit/5f4936e53452c261ef646362700ccecf1b6f6d33#diff-e5f3a0e7f1f45ee323be58e611b7d79e but the links in the admin console never got removed. This removes those dead links from the admin console sidebar.
> Removes dead suggestions links in admin console

- templates_jinja2/suggestions/suggest_team_social_review.html
Social media suggestion items don't have a year, which means all of the team links on the social media suggestion review page end up being `Team XXXX (None)`, and the links don't go anywhere. This removes the year from the link/text formatting to fix the link location.
> Fix team link under social media review

- api/apiv3/api_base_controller.py
- controllers/api/api_base_controller.py
- notifications/base_notification.py
- sitevars/google_analytics_id.py
- tests/test_google_analytics_id.py
More cleanup - adds a `GoogleAnalyticsID` sitevar
Tested both the APIv2 and APIv3 controllers - having no `GOOGLE_ANALYTICS_ID` value set properly no-ops/logs having it set does hit the GA API and returns a 200.
I can't confirm that the analytics are showing up properly, since I don't see them in my staging GA, but I don't think there's a change that would break it.
> Add Google Analytics ID Sitevar

- helpers/rankings_helper.py
The `2006nh` is throwing errors on production because we're getting an error when trying to get `sort_order_info[0]['name']`, since the `sort_order_info` for 2006 will always be None, although we do appear to have `extra_stats` for 2006 rankings. This adds a `sort_order_info` and `sort_order` for 2006.
Some old-school FRC people should probably take a look at this one and make sure things look right - I'm not entirely sure abort sort orders and whatnot for 2006. Pulling sort orders for 2006 and 2007, things looked the same, so I copied the setup for 2007 for 2006.
```
2006: u'sort_orders': [0.0, 24.11, 0.0, 0.0, 0.0, 0.0]
2007: u'sort_orders': [0.0, 32.0, 0.0, 0.0, 0.0, 0.0]
```
I'm fairly confident the Qual Scores being 0 is an issue with my local env
> Fix 2006 event pages erroring when events have rankings

- helpers/notification_sender.py
We're seeing errors in `helpers/notification_sender.py` when sending to webhooks due to `secret` being a unicode string when generating a HMAC for `X-TBA-HMAC`. This should ensure both values used to generate the HMAC are strings.
> Fix failing webhook requests due to hmac errors

- controllers/main_controller.py
- helpers/season_helper.py
- tests/test_season_helper.py
Fixes the issue we were seeing with https://github.com/the-blue-alliance/the-blue-alliance/pull/2589 - since we're now using programmatic dates for kickoff/offseason, the templates were defaulting to using the current year dates. This is wrong, since if we want to show the kickoff template in December, we'll show the wrong year. Additionally, showing the offseason template will show the current year kickoff date, not the next year kickoff date.
This figures out the "effective year" to show for the index templates - if all official events have been played for a season, the effective season is next season
> Calculate effective season when generating landing pages

- index.yaml
The changes merged in https://github.com/the-blue-alliance/the-blue-alliance/pull/2597 required us to update the index, but our indexes don't get synced from Docker back to local changes, so I missed this index change.
> Add generated index for landing page effective season

- static/swagger/api_v3.json
The `Media` object doesn't return a `key` field according to https://github.com/the-blue-alliance/the-blue-alliance/blob/d4e45cc8162baf368e74f80e6050f9f91f3e40e0/helpers/model_to_dict.py#L118 - this removes that `key` field, which should be a safe change, since no one should be consuming it since it's never coming back on any of the responses.
This also sets `foreign_key` to be a required field in the API, since it's required in the data model https://github.com/the-blue-alliance/the-blue-alliance/blob/master/models/media.py#L45
> Set Media.foreign_key to be a required field in the API, remove unused Media.key reference from API

- models/event.py
`2019iscmp` was a problematic event back when it was sorting in to Week 9. Now it's being sorted properly in to Week 6, so this `if self.year == 2020 and week > 7` is unused. Removing it just to keep the codebase tidy.
> Revert "Fix 2020 event's weeks after Week 8 being off-by-one"

- controllers/team_admin_controller.py
- templates_jinja2/team_admin_redeem.html
- tests/team_admin/test_team_admin_redeem.py
No longer fail if the user has redeemed a team admin code for a prior year
We should be checking the years in here
Fixes #2633 
added unit test
> Fix per-year bugs in redeeming team admin access

- controllers/main_controller.py
- helpers/season_helper.py
- templates_jinja2/index/index_buildseason.html
- tests/test_season_helper.py
Display countdown to the first official event of the season.
Stop build day no longer exists
Local dev
> Change build season to count down to first event

- static/css/less_css/less/tba/tba_misc.less
- templates_jinja2/media_partials/social_media_macros.html
Team social media links would sometimes have the icons and text on separate lines. This fixes that.
Local instance
Before:
After:
Small screen:
> Prevent social media links from line-breaking between icon and text

- models/notifications/requests/fcm_request.py
- models/notifications/requests/webhook_request.py
- tests/models_tests/notifications/requests/test_fcm_request.py
- tests/models_tests/notifications/requests/test_request.py
- tests/models_tests/notifications/requests/test_webhook_request.py
This is a bit in preparation for doing retries on FCM sends - if we attempt to send a notification to some mobile clients and only some of the sends succeed, we should only report the successful sends. The idea being - if we try the sends again later and they succeed, we'll report them. Otherwise we'll clean up the old clients. This should make this metric a little more clear - if we don't see any notifications being reported, or it's lower than usual, that gives us a signal something is probably wrong
> Only report successful notification sends to GA

- templates/webhookdocs.html
Final bit of cleanup from https://github.com/the-blue-alliance/the-blue-alliance/pull/2530 - we stopped sending myTBA notifications to webhooks and cleaned up the docs, but forgot to remove the links from the sidebar. This just removes the links from the sidebar on the webhooks documentation page.
> Remove notification_update_favorites and notification_update_subscriptions from webhook documentation sidebar

- consts/client_type.py
- controllers/admin/admin_mobile_controller.py
- deploy_requirements.txt
- helpers/notification_helper.py
- helpers/tbans_helper.py
- models/mobile_client.py
- models/notifications/broadcast.py
- models/notifications/requests/fcm_request.py
- templates/admin/send_broadcast.html
- tests/helpers_tests/test_tbans_helper.py
- tests/models_tests/notifications/requests/test_fcm_request.py
- tests/models_tests/notifications/test_broadcast.py
- tests/models_tests/test_mobile_client.py
Adds support for the the Broadcast notification for FCM clients, moves the Broadcast webhooks to be handled by TBANS, and consolidates Android notification calling code to exist in TBANS.
This also wires up the batch sending/retrying of FCM messages, which has through tests. Under proper failure conditions, we'll attempt to resend to failed FCM clients up to 5 additional times using exponential backoff between 1 and 32 seconds. Logging is in place for deletions, errors, and critical paths. Errors and critical logs will get alerting metrics.
> Add Broadcast notifications to TBANS

- templates_jinja2/index/index_buildseason.html
The template never got updated to use `seasonstart_datetime_utc` when we removed `endbuild_datetime_est` in https://github.com/the-blue-alliance/the-blue-alliance/pull/2637
> Fix error when showing avatar button on build page

- travis_requirements.txt
Travis deploys are failing at the end when we're updating web config information - the `httpie` version changed from underneath us. We should pin the version for now.
> Pin httpie version to fix Travis deploys

- templates_jinja2/event_details.html
Can someone (cc @phil-lopreiato) confirm we started pulling Event info from the FMS API starting in 2015? https://github.com/the-blue-alliance/the-blue-alliance/commit/3ba1a6eb94a7b1a8d31ba114fe428c89a48809f8
> Conditional the FMS API callout to Events during or after 2006

- helpers/tbans_helper.py
- tests/helpers_tests/test_tbans_helper.py
Fixing a TBANS oversight where we weren't checking to see if a webhook was verified before sending to it. Luckily we haven't used this codepath yet.
> Only send to verified webhooks via TBANS

- models/notifications/broadcast.py
- models/notifications/district_points.py
- tests/models_tests/notifications/test_broadcast.py
- tests/models_tests/notifications/test_district_points.py
Right now broadcast and district points notifications deliver somewhat silently (no vibration). Setting them to delivery at a high priority should make them act more like regular notifications.
> Change all user-facing notifications to be high priority

- tests/helpers_tests/test_tbans_helper.py
These tests are a little stronger by making sure when we're not calling sends for Android we're looking at the base notification class, and when we're calling sends we're making sure we're calling send for the proper notification class
> Assert stronger mocks for Android TBANS tests

- models/mobile_client.py
- tests/models_tests/test_mobile_client.py
Currently code like this lives in `helpers/push_helper.py` - eventually we'll kill that code, and TBANS needs to be fetching clients for users for myTBA notifications
> Add MobileClient method to fetch clients for user_id

- consts/fcm/platform_priority.py
- tests/consts_tests/fcm/test_platform_priority.py
- tests/models_tests/fcm/test_platform_config.py
It was unclear via the FCM documentation, but looking over the code, the library we're using enforces `high` and `normal` for FCM platform priorities. I've double checked the APNS and Webpush platform priorities are correct
https://github.com/firebase/firebase-admin-python/blob/00cf1d34fdd8ca3531ff3556688c2e785db17920/firebase_admin/_messaging_encoder.py#L202
> Fix FCM Android platform priority

- models/notifications/alliance_selection.py
- models/notifications/awards.py
- models/notifications/broadcast.py
- models/notifications/district_points.py
- models/notifications/event_level.py
- models/notifications/event_schedule.py
- models/notifications/match_score.py
- models/notifications/match_upcoming.py
- tests/models_tests/notifications/test_alliance_selection.py
- tests/models_tests/notifications/test_awards.py
- tests/models_tests/notifications/test_broadcast.py
- tests/models_tests/notifications/test_district_points.py
- tests/models_tests/notifications/test_event_level.py
- tests/models_tests/notifications/test_event_schedule.py
- tests/models_tests/notifications/test_match_score.py
- tests/models_tests/notifications/test_match_upcoming.py
Part of #2670 - I realized that setting the priority higher doesn't get the results I want, so we should just leave notifications to be default priority (we can always add back in higher priority, if necessary)
> Remove explicit platform priority from TBANS notifications

- api/apiv3/api_event_controller.py
- api/apiv3/api_team_controller.py
From Slack - since the `/events/all` and `/teams/all` endpoints are fairly large and don't get updated that often, we're going to bump the cache up to an hour for each
> Set /events/all and /teams/all cache time to be an hour

- app.yaml
- static/well-known/apple-app-site-association
Adds a `well-known` directory and `/.well-known` endpoint in prep for universal links, handoff, sign in with Apple, etc.
> Add well-known directory in prep for Apple-things

- helpers/notification_helper.py
- helpers/push_helper.py
- models/subscription.py
- tests/models_tests/test_subscription.py
I'm looking to pull as much code out of `PushHelper` and `NotificationHelper` when moving to FCM. The old `PushHelper.get_users_subscribed_to_event` is a little weird - it doesn't de-duplicate user IDs, although they get de-duplicated later via a ndb query to mobile clients.
The new method in `Subscription` has one less sharp corner, and tests
> Rewrite PushHelper.get_users_subscribed_to_event to Subscription.users_subscribed_to_event

- admin_main.py
- controllers/admin/admin_tbans_controller.py
- helpers/award_manipulator.py
- helpers/notification_helper.py
- helpers/push_helper.py
- helpers/tbans_helper.py
- models/mobile_client.py
- models/notifications/awards.py
- templates/admin/base.html
- templates/admin/tbans_debug.html
- tests/helpers_tests/test_tbans_helper.py
- tests/mocks/models/mock_event.py
- tests/models_tests/notifications/test_awards.py
- tests/models_tests/test_mobile_client.py
- tests/models_tests/test_subscription.py
- tests/test_event.py
Kind of a big PR - will break down each piece one by one
- Dispatch Awards notifications via TBANS to FCM clients (web and iOS) and webhooks
- Adds `/admin/tbans` endpoint to test sending notifications to currently-signed-in user's clients
- `NotificationHelper.send_award_update` will now ONLY send to Android clients - this is so we don't double send to webhooks. This code will say here for now, since the new Awards notifications will be a breaking change for Android (unlike ping and broadcast - which should not be)
- `MobileClient.clients` now takes an array of `user_id` as opposed to a single `user_id` - this should enable us to send notifications to a larger set of users. This wasn't used before, so this change should be whatever.
- Modified `PushHelper.get_client_ids_for_users` to …
> Dispatch Awards notifications to iOS, web, and webhooks via TBANS

- templates/apidocs_overview.html
It's obvious where to click now
> Make headers on API page links to docs

- models/notifications/broadcast.py
- templates/webhookdocs.html
- tests/models_tests/notifications/test_broadcast.py
This does a handful of things to the Broadcast notification
- Drops `None` values in the notification payloads - FCM wants only string values in the data payloads
- Removes `app_version` from webhook payload - not something the webhooks particularly need (unless we bump webhook versions/start targeting webhooks, which is two pretty big ifs)
The webhook docs are updated accordingly
> Update Broadcast notification

- controllers/apidocs_controller.py
- controllers/base_controller.py
- controllers/test_notification_controller.py
- helpers/tbans_helper.py
- models/notifications/awards.py
- models/subscription.py
- static/css/less_css/less/tba/tba_webhooks.less
- static/css/less_css/tba_style.main.less
- templates/webhookdocs.html
- tests/helpers_tests/test_tbans_helper.py
- tests/mocks/models/mock_event.py
- tests/models_tests/notifications/test_awards.py
- tests/models_tests/test_subscription.py
A bit of "two PRs in one" because things got a little out-of-hand
* Update Awards notifications to send more-specific Team and Event notifications - Team notifications will have a more detailed description of the Awards a team won, Event notifications are unchanged
(Will get screenshots from mobile apps hopefully)
* Update docs (starting with Awards, working my way through them all as I update the endpoints) to provide clearer descriptions of the fields and conditions under which we'll send notifications
* Only show notification testing boxes if the user is logged in
* Add sending to TBANS for Awards notification debugging
* Update Awards notification documentation for new behavior
> Better Awards notifications, update webhooks docs

- controllers/admin/admin_match_controller.py
- controllers/match_controller.py
- models/match.py
- static/swagger/api_v3.json
- templates/admin/match_edit.html
- templates_jinja2/match_partials/match_breakdown/match_breakdown_2020.html
- templates_jinja2/match_partials/match_table_cell_macros.html
- Added derived `tba_shieldEnergizedRankingPointFromFoul` field to indicate whether the shieldEnergizedRankingPoint was earned normally or awarded due to a foul.
- Added 2020 breakdown table
Local dev
(scores are fake and may not add up)
> 2020 Match Breakdowns

- templates_jinja2/event_partials/event_insights_2020.html
Changes `Init Line` to `Initiation Line`
On the 2020 insights page, changes the words "Init Line" to "Initiation Line."
There is enough room for it (some lines are much longer) and it seems clearer to me not to abbreviate it. I know it's trivial, but I checked the discussion on Slack slightly too late to give feedback.
It hasn't. It's just changing some text.
> Init Line --> Initiation Line (2020 insights) 

- templates_jinja2/match_partials/match_breakdown/match_breakdown_2020.html
2020 match breakdown SVG appearance change
Changes the fill color of the SVGs from white to none, creating transparency. 
Doesn't match anything by having a white background. Looks a bit weird on the page.
Hasn't.
> Make SVGs transparent

- subtrees/bootstrap/less/tooltip.less
Autofit tooltips to size of contents
Max-width isn't what we're concerned with here. It is the (currently undefined) `width` attribute that, when set to 100%, will fit the size of content.
@gregmarra brought up a good point on #2713.
> Changes tooltip widths

- templates_jinja2/match_partials/match_breakdown/match_breakdown_2020.html
Adds tooltips to the 2020 match breakdown.
On the 2020 match breakdown page, this PR will add tooltips over initiation line and end game actions, attributing it to the teams.
On [Chief](https://www.chiefdelphi.com/t/the-blue-alliance-endgame-data/377891), someone was asking if endgame data was in the order of the schedule (e.g. is "Red Robot 1" the same as "Red 1" on the schedule). I thought it was fairly obvious but also it definitely makes sense to add these tooltips because if someone is scrolled down to the match breakdown, they shouldn't have to scroll back up to the schedule (so much work!).
Inspect element 🤣
> Team attribution tooltips

- queue.yaml
A lot of our datafeed and cache-clearing tasks are failing nightly. This setups up a system to give them a little bit more time to execute, along with executing them slower to try to process more of them successfully
> Set retry params for cache-clearing and datafeed queues, lower rate

- templates_jinja2/team_partials/team_info.html
A small change - it's a little bit weird to click an old team and see the "Data from FRC Events" when we for sure did not get that data for that team from FRC Events (like ~2002 teams or something). This is kinda a middle-ground best effort to only show the link when it's appropriate on a Team page (we do something similar for Events)
> Add conditional for 2015+ Team information from FRC API

- models/notifications/requests/webhook_request.py
- tests/models_tests/notifications/requests/test_webhook_request.py
Explicitly catch `DeadlineExceededError` so we can emit a warning log instead of an error log to prevent alerting on non-actionable issues for webhooks. GAE has several `DeadlineExceededError`, but I think this is the right one to catch. We'll know if we get alerted again, and we can fix accordingly.
> Catch DeadlineExceededError in webhook request in TBANS, warning log

- models/notifications/requests/webhook_request.py
- tests/models_tests/notifications/requests/test_webhook_request.py
It looks like https://github.com/the-blue-alliance/the-blue-alliance/pull/2722 didn't work - going to revert that commit and add some logging so we can try to track down exactly what exception is getting thrown that we're not catching
> Revert deadline exceeded catch, log error class for uncaught errors

- templates_jinja2/match_partials/match_breakdown/match_breakdown_2020.html
Follow up on #2713
Changes tooltips to only include the team number, rather than team key.
Was always the intention not to include `frc` in the tooltip.
Hasn't.
> Match breakdown tooltip fix

- static/swagger/api_v3.json
JSON does not support trailing commas
It broke TBA-API/generator
JSON Linter and Swagger validater
N/A
> Fix invalid JSON

- templates_jinja2/event_partials/event_opr_table.html
On the event insights page, adds `<abbr>` tags to "OPR(s)" spelling out "Offensive Power Ranking(s)."
Sometimes you just want to know what it stands for and don't want to click the `?` and visit the `/opr` explanation page. Also #190 (found while searching for something else), lol.
Hasn't.
Cursor isn't in the screenshot but this is what happens when you mouse over the underlined portions.
> Add <abbr> tags to "OPR"

- templates_jinja2/match_partials/match_breakdown/match_breakdown_2020.html
On the 2020 match breakdown, there is currently a bug caused by the new tooltips. When hovering over red end game, the content shifts over one `<td>`. When I originally created these tooltips in #2713, I added `rel="tooltip" title=team_number` to the entire `<td>` out of laziness and to make the code shorter. That is what causes the glitch.
This PR instead wraps each of the possible contents of the cell in their own `<span>` tags and adds `rel="tooltip" title=team_number` to each of them. Also, the glyphicon representing no action is already in a `<span>` so this just adds the tooltip attributes to it.
Closes #2732
Inspect. Element. As. Always.
See #2732 for current behavior.
> Another tooltip fix

- templates_jinja2/index/index_competitionseason.html
This changes the links from being ndb Keys to event name
> Fix event links on competition season homepage

- models/notifications/requests/webhook_request.py
- tests/models_tests/notifications/requests/test_webhook_request.py
Okay - re: [this question](https://stackoverflow.com/questions/26106358/httpexception-deadline-exceeded-while-waiting-for-http-response-from-url) - it looks like the stack trace for this exception (in `gae_override/httplib.py`) is catching our timeout from `urllib2` and throwing a pretty generic `HTTPException`, which is why catching those deadline exceeded exceptions isn't working.
The original answer seems promising, where setting an explicit deadline will work. We need to make sure GAE doesn't timeout our request though (10s?). Catching this in a kinda dumb way will fix our error logs while I work on a proper fix.
> Third attempt at catching deadline exceeded errors from webhooks

- helpers/match_helper.py
This adds support for 2020 playoff tiebreakers as described in https://firstfrc.blob.core.windows.net/frc2020/Manual/HTML/2020FRCGameSeasonManual.htm#PlayoffMatchesSection
Fixes #2738. 2020isde1_qf2m2 was treated as a tie by TBA, so the playoff schedule and bracket for that event aren't being calculated correctly.
Local instance. Haven't tested all tiebreakers, but the field names should be right (copied from the breakdown JSON for that match). Breakdown contains `  "winning_alliance": "blue"`
> Add support for 2020 playoff tiebreakers

- index.yaml
Should be the same - the `pull-datastore` script is just moving them around, so... checking in these changes so I don't get a dirty repo when I pull
> Update index.yaml from pull datastore

- queue.yaml
We're seeing timeouts when approving a lot of match videos - my guess is once we hit prime time where a lot of events are going on we're going to get slammed with notifications and they'll start timing out. This lowers the queue rate in an attempt to fix that.
We might slowly start bringing this back up as weeks go on, if we notice the queue isn't draining fast enough (we have a monitoring dashboard for this).
> Lower `push-notifications` queue rate

- templates_jinja2/event_details.html
Adds "in your timezone" to the verbiage about predicted times on the event details page.
Sometimes, it is obvious that they are in local time (e.g. upcoming Israel matches at 4:00 am are obviously in my timezone rather than event) but other times it is somewhat of an unknown (think mid-day matches looking between Eastern and Pacific). Knowing that these times are automatically converted is an easy, and I believe helpful, factoid.
Hasn't.
> Adds "in your timezone" verbiage

- helpers/event_helper.py
- helpers/season_helper.py
- models/event.py
- tests/test_season_helper.py
This change calculates weeks for events starting on the first day of the competition season, moving forward. We consider the first day of competition season to be the first Monday after stop build day for 2018+. Pre-2018, we consider the first *Wednesday* after stop build day to be the first day of competition season.
2016 is special-cased in order to support `2016scmb` being Week 0.5. Official events that start before the first day of competition season are rounded up to start during the first week of competition season. This should also fix some event weeks being wrong in 2019/2018 (closes #2454).
tl;dr - `SeasonHelper` has a new `competition_season_start_date` which calculates the start date for a given season. Event weeks are determined based on their offset from this day.
Our week …
> Calculate Event weeks starting from beginning of competition season

- database/event_query.py
- helpers/season_helper.py
- models/event.py
- tests/test_season_helper.py
Thinking in a vacuum about just 2020 - we consider `2020isde1` a Week 1 event because it's *close* to Week 1, even if it doesn't technically start in Week 1. This change introduces code to find the *closest* start weekday to the first event. In the case of a year where Monday is the start of week, we look for the closest Monday to the first event. In 2020, this is Feb 24th, as opposed to Feb 17th. The difference from Feb 23rd being 1 and -6, we take the -1 situation. In other years, this might be the closest Wednesday.
The current "offset from season start" method of assigning week numbers is problematic because old years (1996-2004) the events are several weeks after the "start of season" date we're calculating. This removes that problematic code and reverts to a slightly modified method …
> Assign week numbers using the closest season start weekday (closest Monday/Wednesday) to the first event

- templates_jinja2/match_partials/match_breakdown/match_breakdown_2020.html
On the 2020 Match Breakdown, adds a "none" option if no stages were activated. Currently, the cell is blank unless stages 1, 2, or 3 are activated.
The match breakdown without stage activation data looks kind of empty/missing.
Hasn't. And I probably screwed up by trying to code again.
> Adds "none" to activation stages

- templates_jinja2/event_partials/event_insights_2020.html
> Fix "energzied" typo

- helpers/tbans_helper.py
- models/notifications/requests/request.py
- notifications/base_notification.py
As part of lightening the load on `default`, this moves tasks in the `push-notification` queue (and their associated API-tracking calls) to be executed by `backend-tasks`
> Execute push notifications on backend-tasks

- models/notifications/requests/fcm_request.py
See https://github.com/firebase/firebase-admin-python/issues/413 - should fix the warnings in our logs when sending to FCM
> Silence positional argument warnings from FCM multicast sends

- backend_main.py
- controllers/datafeed_controller.py
- cron.yaml
- cron_main.py
- templates/admin/event_details.html
- templates/admin/tasks.html
In an effort to move all non-HTML rendering tasks to other services, this moves some `datafeed` tasks to execute on `backend-tasks`
> Run all datafeed tasks on backend-tasks

- datafeeds/datafeed_fms_api.py
Another attempt to fix our cascading timeouts in GAE - setting a 5s deadline for the FRC API should allow us to bail-quick on requests that we're not going to get a response from the FRC Events API so we can move on faster.
The other option here is to remove that `raise ndb.Return(None)` and just hard-fail (allow the `context.urlfetch` to raise) in order to bail on the request even faster
> Set 5s timeout to FRC API

- backend_main.py
- controllers/datafeed_controller.py
- cron.yaml
- cron_main.py
- datafeeds/datafeed_fms_api.py
- dispatch.yaml
- helpers/award_manipulator.py
- helpers/district_team_manipulator.py
- helpers/event_details_manipulator.py
- helpers/match_manipulator.py
- templates/admin/event_details.html
- templates/admin/tasks.html
Several reverts to run the tasks we moved from `backend-tasks` back to `tasks`
> Run `backend-tasks` on `tasks`

- templates_jinja2/insights_details.html
Fix the `es` pluralization location for "Highest Scoring Match Overall"
#2769
Locally.  👀
> Fix pluralization on more than one "Highest Scoring Match Overall"

- templates_jinja2/index/index_competitionseason.html
Add Coronavirus warning to CompSeason template until we can get a sitevar for alerts placed in.
To avoid confusion and increase awareness, place a link to the Coronavirus status page on the FIRST website.
The overall styling has been tested using Inspect Element.
> Add Coronavirus warning to CompSeason template

- helpers/match/match_test_creator.py
- helpers/tbans_helper.py
- tests/helpers_tests/test_tbans_helper.py
During an event, we get several of these match schedule update events that get posted. I'm not entirely sure *why*, but part of the side effect is that we'll dispatch new upcoming match notifications for a new schedule.
This isn't really what we want. We want to send upcoming match notifications for (ex) semifinal matches when the match schedule gets updated. But if we get a match schedule update notification in the middle of qualifications, we shouldn't send out new upcoming match notifications, since they should be sent after scores get posted.
> Only send upcoming matches for new match schedules when the level changes

- templates_jinja2/index/index_competitionseason.html
We can try to iterate on the landing page to surface something besides an empty list - showing a list of events feels like counter to the information available right now.
> Update COVID-19 information on landing page, hide event list

- models/event.py
This should allow users to safely import `models.Event` globally without pulling in other code globally
> Move global imports on helper classes from Event to be JIT imports

- templates_jinja2/media_partials/instagram_partial.html
Firefox seems to have a bug rendering span background-image media objects when they also follow a 302 redirect.  Switching to a `background` media type and allowing FF to infer the source being an image seems to work though.
This would allow Firefox to display Instagram thumbnails on the carousel and homepage.
Inspect Element seems to both trigger the loading of it in Network monitor and rendering on the page when edited.  Doing the same in Chromium (80.0.3987.87) doesn't break either.
Before:
After:
> Update instagram partial to render thumbs correctly in Firefox.

- .gitignore
- .travis.yml
- ops/manage_deploy_keys.sh
- ops/travis/should-deploy.sh
- ops/travis/travis-deploy.sh
We should be able to leverage the same tooling to deploy to staging GAE instances of TBA. This should eliminate all the dependencies on the prod instance
> Generalize Continuous Deployment Tooling

- .travis.yml
- app.yaml
- ops/standalone/cron-empty.yaml
- ops/standalone/dispatch-empty.yaml
- ops/travis/travis-deploy.sh
- ops/travis/travis-install.sh
This will let you deploy a staging instance without cronjobs, and with only a single GAE instance, so that random people's staging instances can stay within the free tier usage
> Support single-instance deploy type

- database/district_query.py
- helpers/event_helper.py
The Indiana robotics organization, as well as as the Indiana district name, has changed.
https://frc-api.firstinspires.org/v2.0/2019/districts:
```
{
"code": "IN",
"name": "Indiana FIRST"
}
```
https://frc-api.firstinspires.org/v2.0/2020/districts:
```
{
"code": "FIN",
"name": "FIRST Indiana Robotics"
}
```
https://www.thebluealliance.com/events/in is returning a 500 error.
https://www.thebluealliance.com/events/fin is the new "correct" url
I lost my local setup with a recent format, so this is totally just YOLO'ed.  😅
Travis?  🙏 
👀
> Add IN to FIN district mapping

- models/api_auth_access.py
- models/award.py
- models/event.py
- models/insight.py
- models/match.py
- models/sitevar.py
- models/suggestion.py
- models/team.py
- models/typeahead_entry.py
`cloud-ndb` enforces that:
- [`StringProperty` is always indexed](https://googleapis.dev/python/python-ndb/latest/model.html#google.cloud.ndb.model.StringProperty)
- [`TextProperty` is never indexed](https://googleapis.dev/python/python-ndb/latest/model.html#google.cloud.ndb.model.TextProperty)
So codemod our models to make that so
```
$ find models/ -type f -name "*.py" -print0 | xargs -0 sed -i '' -e 's/StringProperty(indexed=False/TextProperty(indexed=False/g'
$ ack StringProperty . | grep "indexed=False"  | wc -l
0
```
Towards https://github.com/the-blue-alliance/the-blue-alliance/issues/2791
> Migrated non-indexed string model fields to TextProperty

- .travis.yml
- api.yaml
- app-backend-tasks-b2.yaml
- app-backend-tasks.yaml
- app.yaml
- appengine_config.py
- clientapi.yaml
- deploy_requirements.txt
- requirements.txt
Restart abstracting out ndb accesses to enable migrating to py3.
Break up the bits in https://github.com/the-blue-alliance/the-blue-alliance/pull/2789 into some smaller pieces so we can be more careful.
Also, I'm testing on my own GAE instance to make sure things aren't totally broken.
This particular diff is needed, because we're going to start depending on precompiled bits of `grpc` (when we later introduce the google cloud libraries to be vendored in). Which means we need to leverage the builtin version, not one we vendor ourselves.
> Take grpcio dependency from built-in

- src/.gcloudignore
- src/api/main.py
- src/api/tests/conftest.py
- src/api/tests/main_test.py
- src/common/middleware.py
- src/conftest.py
- src/pytest.ini
- src/web/main.py
- src/web/tests/conftest.py
- src/web/tests/main_test.py
We'll want to wrap each request in an ndb context, which we can do using a middleware.
There are a few fun things/dependencies:
- This needs some library stubs for `pyre` to be happy. These have been added already in 548b4d490571490b82d1c1a6c84c753f59e6c7a8 and 2e3d6931a4694835fd79a360521b0788ea8eeae2
- Added a base `pytest` fixture that'll monkeypath some env variables for cloud datastore to garbage values for now, just enough so the tests pass currently
- Moved API test client generation to `pytest` fixtures, because of the necessary monkeypatching of environment variables we'll need to do
Stubs generated using
```
$ stubgen -p google.cloud.ndb -o stubs/
$ stubgen -p pytest -o stubs/
$ stubgen -p _pytest -o stubs/
```
> [py3] Add flask middleware for ndb context

- Vagrantfile
- ops/dev/build-container-images.sh
- ops/dev/cloudbuild.yaml
- ops/dev/print-gae-logs.sh
- ops/dev/start-devserver.sh
By default, pull the container image from our Google project's container registry, which is faster htan building it locally.
Plus some other helpful scripts:
- to build+push a new container image (we could also integrate this with CI later)
- view GAE output from within container (by tailing the logfile)
> [py3] integrate dev container with cloud builds

- .github/workflows/update_wiki.yml
Removes updating the main repo on wiki submodule update.
This was nice to have/helpful in my test repo setup, but is both failing and unnecessary in our use case.
GitHub Action failure:
https://github.com/the-blue-alliance/the-blue-alliance/runs/737274894?check_suite_focus=true#step:4:13
Tested in my personal fork.
> [py3] [nodeploy] Remove main repo update on wiki update

- .github/workflows/update_wiki.yml
- .gitmodules
Update the self-updating wiki to not use a `git` submodule.
After I thought about my current implementation a bit more, I realized that we 100% don't actually need the wiki submodule at all.  Instead of having it in the repo, which has to then be cloned down, and changed for forks (if testing), we could just clone the wiki repo at the time the GitHub Action is run.  This cleans up the repo, and doesn't add any more time/complexity to the Action.
Passing build with this code:
https://github.com/dracco1993/the-blue-alliance/runs/738962512?check_suite_focus=true
Currently running at:
https://github.com/dracco1993/the-blue-alliance/tree/py3
https://github.com/dracco1993/the-blue-alliance/wiki
> [py3] [nodeploy] Update wiki auto-updating

- src/backend/common/queries/database_query.py
- src/backend/common/queries/tests/database_query_test.py
- src/backend/common/typed_future.py
This is the basis of a db query abstraction - it's a similar pattern to the old one with a few key differences:
- type hinted! (but uses `TypedFuture` as a wrapper for `ndb.Future` that supports type hinting)
- uses `abc` to make more clear the fact that subclasses need to implement `_query_async`
- passes args via `kwargs` rather than the `*args`, since it's more clear what arg means what and passes them through to `_query_async` by name
> [py3] Introduce Typed DatabaseQuery abstraction

- src/backend/common/tests/test_middleware.py
Weirdly tricky to test this one! Basically - create a fake request and ensure that our ndb context is available. This will throw an exception if the ndb context isn't available.
> Add middleware test to ensure ndb context provided via middleware

- src/backend/common/models/event_participation.py
- src/backend/web/handlers/team.py
- src/backend/web/handlers/tests/helpers.py
- src/backend/web/handlers/tests/team_canonical_test.py
- src/backend/web/handlers/tests/team_detail_test.py
- src/backend/web/main.py
- src/backend/web/templates/team_partials/team_year_dropdown.html
- implement the same distinction between the canonical/detail handlers as the existing site
- implement the year choice dropdown
- show stubs for event participation
- unit tests
> Py3 team detail events

- react/gameday2/components/TwitchChatEmbed.js
- react/gameday2/components/embeds/EmbedTwitch.js
- templates/gameday.html
- templates/webcast/twitch.html
Add `www.thebluealliance.com` as a parent for Twitch embeds
`GameDay` is kill.  Plz no kill `GameDay`.  🙏 
I manually changed the embeds in the source, and they worked.  👀
> Add www.thebluealliance.com as a parent for Twitch embeds
