the-blue-alliance/the-blue-alliance

- src/backend/api/handlers/event.py
- src/backend/api/handlers/team.py
- src/backend/common/models/event.py
- src/backend/common/models/event_team.py
- src/backend/common/models/keys.py
- src/backend/common/models/team.py
- src/backend/common/queries/event_query.py
- src/backend/common/queries/team_query.py
- src/backend/common/queries/tests/event_event_teams_query_test.py
- src/backend/common/queries/tests/event_teams_query_test.py
- src/backend/common/queries/tests/team_events_query_test.py
- src/backend/web/handlers/tests/helpers.py
- src/backend/web/local/bootstrap.py
- src/backend/web/local/tests/bootstrap_test.py
When passing around random `str` keys, we can leverage the typechecker to help us keep track of what's what. We could also in theory add validation to an overridden `__new__` to enforce data shape as well, but that can come later.
> Add type aliases for common key types

- src/backend/common/queries/award_query.py
- src/backend/common/queries/database_query.py
- src/backend/common/queries/district_query.py
- src/backend/common/queries/event_details_query.py
- src/backend/common/queries/event_query.py
- src/backend/common/queries/match_query.py
- src/backend/common/queries/media_query.py
- src/backend/common/queries/mobile_client_query.py
- src/backend/common/queries/robot_query.py
- src/backend/common/queries/team_query.py
- src/backend/common/tasklets.py
This can help us clean up how we typehint dbqueries, by formalizing `ndb.tasklet`'s typing contract in a wrapper.
This should let us define queries with a consistent return type, and remove the need to do stuff with unions/futures ourselves.
> Add a type hinted wrapper for ndb.tasklet

- src/backend/common/queries/award_query.py
- src/backend/common/queries/district_query.py
- src/backend/common/queries/event_details_query.py
- src/backend/common/queries/event_query.py
- src/backend/common/queries/match_query.py
- src/backend/common/queries/media_query.py
- src/backend/common/queries/mobile_client_query.py
- src/backend/common/queries/robot_query.py
- src/backend/common/queries/team_query.py
This lets the typechecker make sure we're setting the args correctly instead of letting the base class's `*args, **kwargs` consume everything and end up with runtime errors if you do it wrong.
> Create constructors for db queries

- controllers/admin/admin_match_controller.py
- models/match.py
A two part approach on this one - first, treat u'None' strings as `None` from the post. Second, do a JSON load *before* attempting to save the JSON to the model (we do this for other JSON from the form, just not this field)
> Add checks around saving 'None' match breakdown strings from admin console

- datafeeds/datafeed_first_elasticsearch.py
- datafeeds/parsers/first_elasticsearch/first_elasticsearch_team_details_parser.py
- helpers/team_manipulator.py
- tests/test_first_elasticsearch_team_parser.py
We should search by team number. Also, since we can trust `profile_year` now, we can remove the validation that tpid years only increase
> fix ES team detail

- src/backend/common/helpers/listify.py
- src/backend/common/manipulators/manipulator_base.py
- src/backend/common/manipulators/tests/base_manipulator_test.py
- src/backend/common/models/cached_model.py
- src/backend/common/queries/dict_converters/converter_base.py
This is an initial prototype for write path support of db models, with hooks for us to implement cache clearing later.
This is done in the same vein as the old manipulators (since we haven't come up with any fundamentally different/better ideas, I'll stick with what we've got in the nature of keeping progress moving).
However, there are two main improvements:
- what I hope will be better type hinting for the "pass either a `Thing` or a `List[Thing]` and we'll do the right thing" pattern we frequently have. This uses `@overload` (see [the PEP](https://www.python.org/dev/peps/pep-0484/#function-method-overloading)) to mark the return types
- Introduction of a `CachedModel` base class, which will contain first-class variables for the "magic" properties we often rely on here (eg `dirty` and …
> Initial Manipulator Support

- src/backend/common/queries/database_query.py
- src/backend/common/queries/team_query.py
- src/backend/common/queries/tests/event_event_teams_query_test.py
- src/backend/common/queries/tests/event_teams_query_test.py
- src/backend/common/queries/tests/team_list_query_test.py
- src/backend/common/queries/tests/team_list_year_query_test.py
- src/backend/common/queries/tests/team_participation_query_test.py
- src/backend/common/queries/tests/team_query_test.py
Adds a set of `_<model>_affected_queries` methods that returns the set of `DatabaseQueries` affected by the change.
Later, model manipulators will call all of the `_*_affected_queries` methods of all the `DatabaseQueries` whenever a model is updated to clear appropriate caches.
> [py3] Cache Clearing Base

- ops/dev/vagrant/bootstrap-dev-container.sh
- ops/dev/vagrant/dev_appserver.sh
Right now we're not installing dependencies to the Vagrant container from the setup script.
> Install Python deps to Vagrant container

- src/backend/web/redirect.py
- src/backend/web/tests/redirect_test.py
The `safe_next_redirect` method uses the `next` parameter for a request and ensures that the URL 1) matches the current host and 2) is a http/s link. This should be used when accepting user input for a redirect.
> Add safe redirect methods to web

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
- ops/build/run_buildweb.sh
Adds a `--env` flag to the `run_buildweb.sh` script to generate the `tba_secrets.js` using environment variables for CI
From Slack - [this PR](https://github.com/the-blue-alliance/the-blue-alliance/pull/3005) to generate `tba_secrets.js` on CI introduced a problem that when running `run_buildweb.sh` locally when re-building JS would overwrite your `tba_secrets.js` key with empty variables.
Tested locally - seems to work!
> Add --env to run_buildweb.sh to generate tba_secrets.js from environment variables

- templates/admin/base.html
- templates/base.html
- templates/datafeeds/base.html
- templates/gameday.html
- templates/gameday2.html
- templates_jinja2/base.html
TIL our Google Analytics tracking script is legacy. This upgrades all the old `ga.js` to `analytics.js`
Migration information here https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs
I removed all the Google Analytics tracking from the datafeed and admin pages - it doesn't feel particularly useful to include those in our Google Analytics data.
> Upgrade from ga.js to analytics.js

- templates/gameday.html
- templates/gameday2.html
Fix to https://github.com/the-blue-alliance/the-blue-alliance/pull/2754 - I was sending the GameDay time as the event value instead of the event label
> Fix sending GameDay tos as event instead of label

- ops/dev/vagrant/dev_appserver.sh
- src/backend/tasks_io/main.py
- src/backend/tasks_io/tests/main_test.py
- src/dispatch.yaml
- src/tasks_io.yaml
In an attempt to slim down the `zorr/py3/queues` branch, this adds the default `tasks-io` service to be run locally (not yet deployed)
> [py3] Add tasks-io service

- ops/dev/vagrant/dev_appserver.sh
- src/backend/common/environment.py
- src/backend/common/tests/environment_test.py
- tba_dev_config.json
Adds a `tasks_mode` field to `tba_dev_config.json` to allow users to use local Cloud Tasks, or to communicate with an upstream server to dispatch Cloud Tasks.
> [py3] Adds tasks_mode to tba_dev_config for local or remote Cloud Tasks

- Vagrantfile
- ops/dev/docker/Dockerfile
- ops/dev/vagrant/start-devserver.sh
- requirements.txt
We'll need this both for the memcache and task queue replacements.
For running with local docker changes, this also adds a `TBA_LOCAL_DOCKERFILE` env variable you can set to build docker locally. eg
```
$ TBA_LOCAL_DOCKERFILE=true vagrant up
```
> Add Locally Running Redis to Dev Container

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
CI is failing when calling the `setup-node` action due to GH Actions changes https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Bumping to setup-node@v2.1.2 should fix this issue for us https://github.com/actions/setup-node/releases/tag/v2.1.2
> Bump GH Actions setup-node to v2.1.2

- src/backend/web/renderers/team_renderer.py
This should fix the issue that is being raised around re-typing the `season_wlt` and `offseason_wlt` from a `None` to a `WLTRecord` when bumping `pyre-check` https://github.com/the-blue-alliance/the-blue-alliance/pull/3150
This change sets `season_wlt`/`offseason_wlt` to be optional, but then casts `season_wlt`/`offseason_wlt` to be `WLTRecord` objects so we can operate on them later on in the non-2015 flow
> Add cast from optional to non-optional for season_wlt and offseason_wlt for non-2015 years in team renderer

- ops/dev/vagrant/dev_appserver.sh
- src/backend/common/environment.py
- src/backend/common/tests/environment_test.py
- tba_dev_config.json
This reverts commit 61bbd2799e9ddc0ce72cf12b8d4bb72f9333ca67.
I'm going to pull this work out and do it as a whole later. But for now - this is going to be confusing for setup, so let's remove it altogether.
> Revert "Adds tasks_mode to tba_dev_config for local or remote Cloud Tasks"

- src/backend/common/environment/environment.py
- src/backend/common/environment/tasks/__init__.py
- src/backend/common/environment/tasks/tests/tasks_remote_config_test.py
- src/backend/common/environment/tests/environment_test.py
Pulling some code out of https://github.com/the-blue-alliance/the-blue-alliance/pull/3162 - this DRYs attempting to get the current service name, and otherwise returning "default" as the service name (used for the task queue stuff)
> Add Environment.service_for_current_service to get current service name with default fallback

- .pyre_configuration
- pytest.ini
- requirements.txt
- src/backend/common/environment/environment.py
- src/backend/common/memcache.py
- src/backend/common/middleware.py
- src/backend/common/redis.py
- src/backend/common/tests/memcache_test.py
This PR copies the legacy GAE memcache interface (ish, limited to the feature we currently use elsewhere in the code).
We add an interface so we can have multiple implementations. Namely, a noop one that will miss 100% of the time. This will be our default client for "raw" memcache, for cases where we can't/don't run redis locally.
~Still todo: write some tests, and refactor redis client creation so we can create a single one and share it with the ndb cache~
> Add Interface to Replace Legacy Memcache

- src/backend/common/memcache.py
- src/backend/common/tests/memcache_test.py
The previous iteration of just pickling everything will be a little too naive. For two main reasons:
1. In order to support `INCR` and `DECR` commands (which I missed yesterday), we'll need to write raw int values to redis. Obviously, this won't work if the data is pickled
2. For space efficiency reasons, we can more cheaply store primitive types if we avoid pickling them.
```
>>> len(pickle.dumps(True))
4
>>> len(pickle.dumps(255))
5
```
Instead, do a custom thing where we store a two byte header in front of the data, one byte for a version, and one byte for a type indicator, and then pack the data on after that.
This is actually similar to what the old ndb memcache library did transparently for us, see the [encoding](https://chromium.googlesource.com/external/googleappengine/python/+/mas …
> Implement custom serialization for memcache

- docs/Developing/Development-Runbook.md
- docs/Setup/Repo-Setup.md
- docs/Setup/Setup-Guide.md
I've been editing the Wiki online, which means the `docs/` folder in the codebase and the upstream Wiki have converged. This PR syncs the upstream Wiki docs to the codebase `docs/` folder so the latter stops overwriting the former when pushing changes.
> Update docs in codebase to match upstream docs

- src/backend/web/static/javascript/utils/client_detection.js
The client detection script tries to parse the macOS version that starts with ``10.`` but macOS Big Sur is ``11.`` - it throws an error that interferes with the rest of the JavsScript code so parts of the pages don't work.
This change should be merged with both ``master`` and ``py3``.
Testing UAs from different versions.
> Fix JavaScript on macOS Big Sur

- .github/workflows/push.yml
- .pyre_configuration
- docs/Deployment/CI-CD-Setup.md
- docs/Deployment/Prod-Setup.md
- docs/Developing/Redis.md
- ops/deploy/deploy_module.sh
- ops/deploy/postprocess_yaml.py
- requirements.txt
After defeating my own stupidity and fixing the incorrect port (h/t @fletch3555), let's get redis working in prod.
https://cloud.google.com/appengine/docs/standard/python/migrate-to-python3/migrate-to-cloud-ndb#caching is the guide of what we configured on the server side (I'll also add some wiki docs to this pull before merging)
In short, we need to configure two things:
- the `REDIS_CACHE_URL` environment variable for our application code to pick up the fact we want to use redis (this is the same way we get the url for the dev app)
- a VPC network connector to tell Google Cloud that our GAE instance is allowed to talk to the network containing the redis resources
Both of these things are to be configured in the service YAML files. The downside is, we don't really want anything tied to …
> Configure Redis in Prod

- .pyre_configuration
- src/backend/api/main.py
- src/backend/common/decorators.py
- src/backend/common/deferred/handlers/tests/test_defer_handler.py
- src/backend/common/flask_cache.py
- src/backend/common/tests/decorator_test.py
- src/backend/web/main.py
- src/requirements.txt
This uses the [flask-cache](https://pythonhosted.org/Flask-Cache/) library to plug into redis and cache the html outputs of rendered pages.
> Implement Response Caching

- consts/event_type.py
- datafeeds/parsers/fms_api/fms_api_event_list_parser.py
Verified all 2021 events show up in local dev.
> Add remote event type for 2021

- src/backend/common/models/event.py
- src/backend/common/models/tests/event_test.py
Currently the API is failing due to validation issues with `Event.validate_key_name`. This fixes that.
Will confirm this works in `py3` and then setup a PR for `master`
> Update Event.validate_key_name to support new 2021 participation event keys

- src/backend/common/queries/database_query.py
- src/backend/common/queries/tests/database_query_test.py
After https://github.com/the-blue-alliance/the-blue-alliance/pull/3234 we can now read `CachedQueryResult` items that were written by the legacy ndb library.
So this will let use CachedQueryResult, but in a read-only way.
I'll have to implement a bunch of protbuf code to get writes working, so that's a project for another day
> Support read only CachedQueryResult

- src/backend/common/cache_clearing/get_affected_queries.py
- src/backend/common/cache_clearing/tests/database_cache_clearer_test.py
- src/backend/common/deferred/__init__.py
- src/backend/common/deferred/clients/fake_client.py
- src/backend/common/deferred/clients/rq_client.py
- src/backend/common/deferred/queues/rq_queue.py
- src/backend/common/deferred/tests/deferred_test.py
- src/backend/common/manipulators/award_manipulator.py
- src/backend/common/manipulators/district_manipulator.py
- src/backend/common/manipulators/district_team_manipulator.py
- src/backend/common/manipulators/event_details_manipulator.py
- src/backend/common/manipulators/event_manipulator.py
- src/backend/common/manipulators/event_team_manipulator.py
- src/backend/common/manipulators/manipulator_base.py
- src/backend/common/manipulators/match_manipulator.py
- src/backend/common/manipulators/media_manipulator.py
- src/backend/common/manipulators/robot_manipulator.py
- src/backend/common/manipulators/team_manipulator.py
- src/backend/common/manipulators/tests/base_manipulator_test.py
- src/backend/common/models/cached_model.py
- src/backend/common/queries/database_query.py
- src/backend/common/queries/media_query.py
- src/backend/common/queries/team_query.py
- src/backend/common/queries/tests/event_event_teams_query_test.py
- src/backend/common/queries/tests/event_teams_query_test.py
- src/backend/common/queries/tests/team_list_query_test.py
- src/backend/common/queries/tests/team_list_year_query_test.py
- src/backend/common/queries/tests/team_participation_query_test.py
- src/backend/common/queries/tests/team_query_test.py
- src/backend/conftest.py
This ports `get_affected_queries` from the old app and hooks it into the manipulators.
The other half of `CacheClearer` was about clearing apiv2 caches, which we're not porting, so I skipped it all
> Port DB Query Cache Clearing

- controllers/datafeed_controller.py
- datafeeds/parsers/fms_api/fms_api_team_details_parser.py
- templates/datafeeds/usfirst_team_details_get.html
- tests/test_fms_api_team_parser.py
Part one of #3261 - we should stop creating Districts when fetching Teams. If we're relying on Events to be the indicator of Districts, then we need to stop creating Districts when fetching a Team details.
> Remove code to create districts when fetching teams - rely on Events for Districts

- docs/Developing/Queues-and-defer.md
- src/backend/common/deferred/clients/fake_client.py
- src/backend/common/deferred/clients/rq_client.py
- src/backend/common/deferred/queues/fake_queue.py
- src/backend/common/deferred/queues/rq_queue.py
- src/backend/common/manipulators/tests/base_manipulator_test.py
- src/backend/conftest.py
Note to Zach: We should try to see if we can make our fake client shared for all tests, as opposed to creating it in-memory during `_client_for_env`. It would allow us to remove that patch + allow for a better pattern for executing tasks in tests
> Remove InlineTaskClient, wrap code in FakeTaskClient

- src/backend/common/legacy_protobuf/legacy_gae_entity_model_decoder.py
- src/backend/common/queries/tests/cached_query_result_compatibility_test.py
Fixes https://github.com/the-blue-alliance/the-blue-alliance/issues/3291
This mainly works around the upstream NDB library bug about signed vs. unsigned integers (https://github.com/googleapis/python-ndb/issues/590) and adds in another case where the legacy library works around overflows ([here](https://github.com/GoogleCloudPlatform/python-compat-runtime/blob/743ade7e1350c790c4aaa48dd2c0893d06d80cee/appengine-compat/exported_appengine_sdk/google/appengine/api/datastore_types.py#L787-L806)), although I don't think we end up executing it.
This adds a round trip serialization compatibility unit test for one of the matches with far-in-the-past timestamps to make sure we have coverage for this, as well
> fix date overflows in protobuf deserialization

- src/backend/common/flask_cache.py
This way, we can store less data in redis. This also lets us get to
parity with the old app, which did compress responses it wrote to
memcache in `CacheableHandler`.
I'll probably need to drop all the data in redis when we land this, for push safety reasons.
> add compression for flask caching

- src/backend/api/main.py
- src/backend/common/deferred/handlers/defer_handler.py
- src/backend/common/deferred/handlers/tests/test_defer_handler.py
- src/backend/common/tests/url_converters_test.py
- src/backend/common/url_converters.py
- src/backend/tasks_io/main.py
- src/backend/web/main.py
I'll need this in order to port the district detail url handlers, and it
just seems like a good idea for us to have available everywhere
defer tests cover this + write some explicit ones
> Install RegexConverter on all handlers

- controllers/datafeed_controller.py
- templates_jinja2/team_details.html
Should fix a bug we're having with 2020 events (specifically https://www.thebluealliance.com/event/2020oncmp) where an `EventDetailsGet` is deleting `EventTeam` models for teams who are not listed as attending the event, but who won awards at the event
> Do not delete EventTeam models for teams who won awards at an Event if the team did not attend the Event

- old_py2/controllers/district_controller.py
- old_py2/controllers/event_controller.py
- old_py2/controllers/gameday_controller.py
- old_py2/controllers/mytba_controller.py
- old_py2/helpers/event_helper.py
- old_py2/helpers/firebase/firebase_pusher.py
- old_py2/helpers/insights_helper.py
- old_py2/tests/test_event_group_by_week.py
- src/backend/common/helpers/event_helper.py
- src/backend/common/helpers/tests/event_helper_test.py
- src/backend/web/handlers/account.py
- src/backend/web/handlers/district.py
- src/backend/web/handlers/event.py
- src/backend/web/handlers/index.py
- src/backend/web/handlers/tests/account_overview_test.py
- src/backend/web/renderers/team_renderer.py
The `EventHelper` methods have peev'd me for a while now, since they're named pretty poorly. I also added some tests, since it looked like these methods didn't have complete test coverage (but pretty good!)
> Rename EventHelper methods to be snake_case instead of camelCase, and to be less verbose. Add EventHelper.*_or_distant_future tests

- src/backend/common/legacy_protobuf/legacy_gae_entity_model_decoder.py
This was fixed upstream (https://github.com/googleapis/python-ndb/issues/590) and
https://github.com/the-blue-alliance/the-blue-alliance/commit/dcb033e78d45624be5665d51ac8816e4f7958091
bumps the version to include the fix
Existing tests still pass, so this means the fix is good
> Remove workaround for parsing negative numbers

- old_py2/main.py
Pretty boring but - removing the migrated routes will help us figure out which routes still need to be migrated moving forward.
> Remove migrated routes from old_py2/main.py

- ops/dev/vagrant/bootstrap-dev-container.sh
Noted in the comment but - this PR looks to speed up bootstrapping a development container but not installing the app dependencies. `dev_appserver` does an install of these for us, so we don't need to be installing them globally in the container.
> Do not install app requirements during container boostrap - will be installed by dev_appserver

- src/backend/common/models/subscription.py
- src/backend/common/models/tests/subscription_test.py
The `TYPE_NAMES` are not what we want, since we're using the `notification_names` method for display purposes (the myTBA page). We should use `RENDER_NAMES` instead.
> Use render names for Subscription.notification_names

- src/backend/web/models/mytba.py
- src/backend/web/models/tests/mytba_test.py
- src/backend/web/models/tests/user_test.py
- src/backend/web/models/user.py
This adds a `MyTBA` model to the `web` service to be used for the `/account/mytba` page. It pulls all of the business logic out of the controller that used to be querying the required models for the myTBA page in to a testable helper class. A `MyTBA` model can be created for a `User`'s `favorites` + `subscriptions` via `user.myTBA`
> Add MyTBA helper model on User model - for myTBA page

- models/cached_query_result.py
- tests/test_cached_query_result_compatibility.py
This is the py2 component of https://github.com/the-blue-alliance/the-blue-alliance/pull/3271
The diff will let the legacy py2 app successfully read pickled data in `CachedQueryResult` that was written by the py3 app. The only thing we should need to fix on this side is the import paths where we changed the directory of models.
I've tested this in the admin console, but I'll add some tests with serialized data pulled from the py3 version as well.
This will need https://github.com/the-blue-alliance/the-blue-alliance/pull/3340 on the py3 side
> Support unpickling CachedQueryResults created by py3

- src/backend/common/legacy_protobuf/legacy_gae_entity_pb_encoder.py
On the legacy NDB side, this field is required, so deserializing what we
construct here will fail. I'm not exactly sure what this type is, but
this is what the `EntityProto` file initializes it as.
Code ref: https://github.com/GoogleCloudPlatform/python-compat-runtime/blob/master/appengine-compat/exported_appengine_sdk/google/appengine/datastore/entity_pb.py#L2457-L2460
> Encode a dummy entity_group for back-compat

- old_py2/helpers/event_helper.py
A bit of a drive-by PR but - removes some already-migrated code from the old_py2/event_helper file so we can better keep track of what still needs to be migrated.
> Remove migrated code from old_py2/event_helper

- src/backend/web/handlers/account.py
- src/backend/web/handlers/tests/account_test.py
I don't want to set up *even more* state in this test, but our test coverage wasn't good enough to ensure that the myTBA method was using the return of `MatchHelper.natural_sort_matches` as opposed to just calling it. This fixes that bug, and adds tests to ensure we're using the returns of these helper methods as expected.
> Fix bug in myTBA render where matches were not sorting properly

- ops/dev/vagrant/bootstrap-dev-container.sh
I forgot this means we can't run pytest in the container 😅 Reverting this change
> Revert "Do not install app requirements during container boostrap - will be installed by dev_appserver (#3333)"

- src/backend/common/models/subscription.py
- src/backend/common/models/tests/subscription_test.py
These names not being in the same order makes the myTBA page a little wonky, since you get subscriptions with the same notification types next to each other but in a different order
> Return sorted render names for myTBA Subscription notification types

- src/backend/common/models/tests/subscription_test.py
- src/backend/common/queries/database_query.py
- src/backend/common/queries/event_details_query.py
- src/backend/common/queries/event_query.py
- src/backend/common/queries/match_query.py
- src/backend/common/queries/team_query.py
- src/backend/common/queries/tests/database_query_test.py
For example, if a DB Query just make a point query under the hood, then
there is no reason for us to double the datastore overhead by storing it
a second time. We may as well just always load the single model
regularly.
However, for the API, we want to continue caching the dict format of the
model, so leave that.
> Add way to skip CachedQueryResult for models

- src/backend/common/queries/district_query.py
When we added FIN<-->IN in
https://github.com/the-blue-alliance/the-blue-alliance/commit/5a73e405efd2159773b5ff50e2f5c31a00a79a79
we should have also bumped these, because it's possible we had poisoned
data stored from before the mapping where we're be returning `None`
without taking the mapping into consideration.
And indeed, this will fix #3316
> Bump cache versions relying on RenamedDistricts

- src/backend/common/helpers/tests/event_team_status_helper_test.py
- src/backend/common/legacy_protobuf/legacy_gae_entity_model_encoder.py
- src/backend/common/queries/database_query.py
- src/backend/common/queries/tests/cached_query_result_compatibility_test.py
- src/backend/common/queries/tests/last_season_event_test.py
We should be good to go on this.
https://github.com/the-blue-alliance/the-blue-alliance/commit/0f79f5ff1202bc1d9d45f3161334cd0ed211510e
should mean that py2 can read data written by py2, and the test suite
we've got here should be making sure that our serialization works round
trip. I can't think of any more testing we can do on this without
enabling it on prod, so here goes.
> Enable CachedQueryResult writes from py3

- docs/Maintainers/Maintainer-Runbook.md
- ops/shell/memorystore_shell.sh
This way, if/when we want to flush redis, this is a bit easier than enabling everything manually
> Add script to enter prod memorystore shell

- docs/Home.md
- docs/Services/Web.md
- docs/Services/common.md
This is a follow up from https://github.com/the-blue-alliance/the-blue-alliance/pull/3374 - this PR moves `User` and `current_user()` docs from `web` to a `common` page that outlines how to use the `current_user()` method. This PR also adds a note around using `login_user` in web for simplifying stubbing `current_user()`
> Update User and current_user docs for code move to common

- src/backend/common/deferred/clients/fake_client.py
- src/backend/common/manipulators/manipulator_base.py
- src/backend/common/manipulators/tests/base_manipulator_test.py
- src/backend/conftest.py
This will be the new pattern for porting post update/delete hooks.
I'm thinking that the decorator registration approach is best, and will allow us to support splitting the hooks into simpler functions (so we can have multiple).
> Add support for post update/delete hooks in ManipulatorBase

- dispatch.yaml
Seeing if we can revert our dispatch.yaml to support the off season event
> Revert dispatch.yaml to point to py2 site

- dispatch.yaml
This is needed so we can deploy a new homepage with updated code
> Point homepage back to py3

- src/backend/web/handlers/index.py
- src/backend/web/templates/index/index_competitionseason.html
- src/backend/web/templates/index/index_offseason.html
This shows the events at the bottom, and keeps the game/season data at the top. Once all scores for IRAH have been submitted, we can probably flip over to only showing events, as opposed to showing game/season info.
> Update competition season event page to be not-Covid. Update offseason event page to work for weird 2021ish season

- ops/dev/Dockerfile
The Docker image fails to build with the following error
```
#10 0.957 ERROR: This script does not work on Python 2.7 The minimum supported Python version is 3.6. Please use https://bootstrap.pypa.io/pip/2.7/get-pip.py instead.
#10 ERROR: executor failed running [/bin/sh -c curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py && python get-pip.py]: exit code: 1
```
We just need to specify the py2 pip URL to download
> Update Dockerfile to pull py2 pip

- src/backend/web/templates/event_details.html
- src/backend/web/templates/index/index_champs.html
In py3 the live event information is failing to load for live events
This is because we're failing to load the `liveevent.js` bundle in py3
Updating the routes to point at `py3_javascript/...` fixes this issue
> Fix py3 not loading liveevent JS

- pytest.ini
- src/backend/common/models/award.py
- src/backend/common/models/event.py
- src/backend/common/models/event_details.py
- src/backend/common/models/event_team.py
- src/backend/common/models/match.py
- src/backend/common/models/tests/global_cache_ttl_test.py
- src/backend/conftest.py
Until we can cutover writes to the new site fully, this should let us have live-updating content in py3.
It's dumb, but if the underlying events are live, then write to the NDB global cache with a short TTL, so if the data gets updated out from underneath us, it'll eventually expire here.
We can remove this once we cut all writes to be going through py3
> Configure Dynamic NDB Cache TTLs

- dispatch.yaml
- ops/standalone/dispatch-empty.yaml
With https://github.com/the-blue-alliance/the-blue-alliance/pull/3485 merged, I'm fairly confident we can point the Event and Team pages back at the py3 pages.
Should be good to merge once https://github.com/the-blue-alliance/the-blue-alliance/pull/3486 is merged
> Point production Event/Team/Match pages back at py3

- ops/dev/docker/Dockerfile
A partial cherry-pick of https://github.com/the-blue-alliance/the-blue-alliance/commit/1d05f3bb147b26e228efe40801f13a0692a97153
Drops pulling `cloud-sdk-xenial` to just pulling `cloud-sdk`, since the Ubuntu version the Docker container uses is set to `latest`, which is 20.04, not 16.04
> Small updates for Dockerfile around Python 2 + Google Cloud SDK

- src/backend/common/helpers/rankings_helper.py
Related to https://github.com/the-blue-alliance/the-blue-alliance/issues/3497 - the `rankings2` models for 2021 events were populated with `record` fields, which is causing records to show for 2021 events. After merging, we should re-scrape rankings for 2021 so we can get the models in a consistent state.
> Add 2021 to record-less years

- src/backend/web/renderers/team_renderer.py
Fixes https://github.com/the-blue-alliance/the-blue-alliance/issues/3499
> Remove district rankings/points information from team detail pages for 2021

- docs/Developing/Queues-and-defer.md
- src/backend/common/deferred/handlers/defer_handler.py
- src/backend/common/deferred/handlers/tests/defer_handler_test.py
- src/backend/common/tests/url_converters_test.py
- src/backend/common/url_converters.py
- src/backend/tasks_io/main.py
The `install_defer_routes` functionality got a little clobbered when we migrated installing regex routes via the `install_url_converters` method by requiring apps call `install_url_converters` before calling `install_defer_routes`. This PR automatically installs the regex converter in `install_defer_routes` if it is not already installed.
This PR also has the side-effect of fixing https://github.com/the-blue-alliance/the-blue-alliance/issues/3504
> Automatically install regex handler when installing defer routes

- src/backend/common/models/event_details.py
- src/backend/common/models/tests/event_details_test.py
Fixes a bug introduced in https://github.com/the-blue-alliance/the-blue-alliance/pull/3501
Before:
After:
> Fix missing Played/DQ information from rankings tables for non-2021 events

- docs/Developing/Queues-and-defer.md
- ops/dev/vagrant/start-devserver.sh
Right now the rq worker is only running the `default` queue, which isn't very helpful. This PR adds all other currently-used queues to the rq workers task load.
> Update rq worker to run currently-used queues

- src/backend/common/helpers/event_helper.py
- src/backend/common/helpers/tests/event_helper_test.py
- src/backend/common/models/event.py
- src/backend/common/models/tests/event_test.py
FINALLY - logical groupings for 2021 Events. The goal is to eventually remove the participation events altogether. But that'll happen in a follow-up PR.
> Group 2021 events by type

- src/backend/common/sitevars/fmsapi_secrets.py
- src/backend/common/sitevars/tests/fmsapi_secrets_test.py
Prepping for moving the FMS API datafeed to py3 - this PR adds the `fmsapi.secrets` sitevar
> Add fmsapi.secrets sitevar

- src/backend/common/sitevars/apiv3_key.py
- src/backend/common/sitevars/tests/apiv3_key_test.py
Fixing a bug that was introduced in https://github.com/the-blue-alliance/the-blue-alliance/pull/3518 - the apiv3 key sitevar is showing up as `None` in the web page if the API key is unset. This behavior is not desirable for this use case.
Before
After
> Fix 'None' v3 API Key in local/bootstrap

- docs/common/Sitevars.md
- src/backend/common/helpers/playoff_advancement_helper.py
- src/backend/common/helpers/youtube_video_helper.py
- src/backend/common/memcache.py
- src/backend/common/models/alliance.py
- src/backend/common/models/award_recipient.py
- src/backend/common/models/district_advancement.py
- src/backend/common/models/district_ranking.py
- src/backend/common/models/event_details.py
- src/backend/common/models/event_district_points.py
- src/backend/common/models/event_insights.py
- src/backend/common/models/event_matchstats.py
- src/backend/common/models/event_participation.py
- src/backend/common/models/event_predictions.py
- src/backend/common/models/event_ranking.py
- src/backend/common/models/event_team_status.py
- src/backend/common/models/match_video.py
- src/backend/common/models/ranking_sort_order_info.py
- src/backend/common/models/suggestion_dict.py
- src/backend/common/models/webcast.py
- src/backend/common/queries/tests/database_query_test.py
- src/backend/common/sitevars/apistatus.py
- src/backend/common/sitevars/apiv3_key.py
- src/backend/common/sitevars/flask_secrets.py
- src/backend/common/sitevars/fms_api_secrets.py
- src/backend/common/sitevars/google_analytics_id.py
- src/backend/common/sitevars/google_api_secret.py
- src/backend/common/sitevars/landing_config.py
- src/backend/common/sitevars/website_blacklist.py
Now that we're fully on Python 3.8, both `TypedDict` is available to us through `typing`. This PR drops the usage of `typing_extensions` for `TypedDict`.
`Literal` is left, since I can't seem to get `Literal[""]` working as a proper type
> Remove `typing_extensions` for `TypedDict` references

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
The build job is scripted in Python but we don't rely on any libraries, so we shouldn't need to install them.
> [py3] Don't install python requirements for build job

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
- .npmrc
- ops/dev/docker/Dockerfile
- ops/dev/vagrant/bootstrap-dev-container.sh
- ops/dev/vagrant/run_webpack.sh
- ops/dev/vagrant/start-devserver.sh
- package.json
- src/frontend/gameday2/selectors/index.js
This is the current LTS version. It appears dependabot can't manage this for us :(
Fixes:
- node 12 includes a change to `Array.sort`, the previous iteration we had was relying on the call order, which was unspecified
- get node 14 to run in CI
- update dev container to run node 14 too via `nvm` so it'll be easier for us to change in the future, I'll publish a new artifact as well
> update to nodejs 14

- src/backend/web/templates/team_partials/team_info.html
This adds a link to `https://frc-events.firstinspires.org/team/{{ team.team_number }}` on team pages.
Better UI parity with event pages, which already have equivalent firstinspires links.
Manually going to team pages.
> Add firstinspires link to team page

- src/backend/web/static/css/less_css/less/tba/tba_sidebar_nav.less
- src/backend/web/templates/base.html
- src/backend/web/templates/event_details.html
- src/backend/web/templates/team_details.html
Fix work done in #3625.
The ``footer-separator`` class sets the ``z-index`` to ``-1``, so the link isn't clickable.
Also, it fixes the design on mobile:
**Before:**
**After:**
> Fix the FRC API attribution link

- ops/dev/vagrant/dev_appserver.sh
- ops/dev/vagrant/run_datastore_emulator.sh
- ops/dev/vagrant/start-devserver.sh
- ops/shell/ipython_config.py
There were two things that needed fixing:
(1) the shell launcher needs to merge the local config file with the
default one to properly resolve when someone wants to use the local
datastore
(2) we need to run the datastore emulator bound to 0.0.0.0, so we can
access it outside the dev container. This diff changes the dev container
to run the emulator in a separate tmux window (always) instead as part
of dev_appserver. This is because dev_appserver's emulator launcher
alwys hardcodes `localhost`, and we need to specify the host ourselves.
After this lands, people will need to `vagrant rsync; vagrant halt; vagrant up` to recreate the container to launch TBA with the updated script
Test:
```
In [1]: import os
In [2]: os.environ["DATASTORE_EMULATOR_HOST"]
Out[2]: 'localhost:8089'
In [3]: with …
```
> Fix local shell connecting to local datastore

- docs/Setup/WSL-Guide.md
- ops/dev/vagrant/fix_wsl_rsync.sh
Adds docs about using a Vagrant plugin to improve rsync speeds on WSL.
On WSL2, I/O speed is a particular pain point, especially with rsync and vagrant (and more so when combined). This gives devs a workaround for local development.
Running commands locally, but only `vagrant up`, `vagrant destroy`, `vagrant halt`, and `ops/dev/host.sh`.
> Add docs about vagrant-gatling-rsync for WSL

- src/requirements.txt
I bork'd this from a manual conflict resolve from dependabot
> Fix busted google-cloud-storage version

- src/backend/common/deferred/handlers/defer_handler.py
- src/backend/common/deferred/handlers/tests/defer_handler_test.py
The regex for the deferred route was problematic, since it wasn't using a `?` for the wildcard match, which meant the `/_ah/queue/deferred` route wouldn't work. This PR allows support for just a `/_ah/queue/deferred` route.
> Add support for /_ah/queue/deferred route

- src/backend/web/templates/suggestions/suggest_offseason_event.html
FIRST is not issuing sync codes for the 2021 season.  This disables the form input so teams don't input it.
This mitigates teams submitting incorrect FIRST Sync codes for 2021 events.
This has only been tested via inspect element; the HTML is valid and renders correctly.  However we may encounter issues with form parsing, as I presently have no way to verify that in a dev environment.
> Disable FIRST Sync Code input box for 2021 season.

- ops/dev/docker/Dockerfile
- ops/dev/vagrant/bootstrap-dev-container.sh
The latest version of `grpcio` dropped the Python 2.7 binary wheel generations, which was causing our bootstrap [bootstrap-dev-container script](https://github.com/the-blue-alliance/the-blue-alliance/blob/37f9ea386bb876d032423f0fdf84ec107759f921/ops/dev/vagrant/bootstrap-dev-container.sh#L8) to fail when starting the development container.
This PR pins the `grpcio` version to the last known good version that supports py2
> Pin grpcio version for py2 bootstrap

- ops/dev/docker/Dockerfile
New M1 machines will use the native ARM image instead of the emulated x86 image of Ubuntu. This makes sure we always use the x86 version of Ubuntu (tooling will fail to install in weird ways if we use the ARM image)
> Ensure we use x86 Ubuntu image for Docker image

- ops/dev/docker/Dockerfile
This reverts commit 55026199b13cece8d9b8fd6fd2a33b95f8c48d64.
Reverting this change, since this DRAMATICALLY slows down the container on M1 machines. The tooling I'm running in to issues running has alternatives (like versions that can be installed via `npm`), which I'll try instead
> Revert "Ensure we use x86 Ubuntu image for Docker image (#3851)"

- src/backend/web/templates/event_details.html
Adds a link on official events, 2022 and later, to Covid 19 site info for events (e.g. [frc.link/e/c/CALA](http://frc.link/e/c/cala))
Don't know if there's a better way to handle year-specific stuff, or if this logic actually checks out, so let me know
> Add COVID-19 Site Information

- ops/dev/docker/Dockerfile
- ops/dev/vagrant/bootstrap-dev-container.sh
- ops/dev/vagrant/dev_appserver.sh
Use the [new Python 3 version of `dev_appserver`](https://cloud.google.com/appengine/docs/standard/python3/services/access#testing_and_deployment) locally for testing. This allows us to remove any Python 2 setup in our container.
> Use py3 dev_appserver and drop py2 from Vagrant install

- src/backend/api/main.py
- src/backend/tasks_io/main.py
- src/backend/web/handlers/tests/account_test.py
- src/backend/web/main.py
Right now it sounds like the `use_legacy_context_mode=True` is the only operating mode that works. We should keep an eye on this moving forward. But for now to get some of the bundled stuff working (`taskqueue` specifically), let's flip these to their default values.
> Use default use_legacy_context_mode option

- .flake8
- requirements.txt
Now that we can depend on some aspects of the legacy GAE runtime, we should ban importing `ndb` and `datastore` by default since we would prefer to use the google cloud libraries.
```
(venv) [phil@fedora-x1think the-blue-alliance-py3]$ git diff
diff --git a/src/backend/common/redis.py b/src/backend/common/redis.py
index 3a839b59..4208fa1e 100644
--- a/src/backend/common/redis.py
+++ b/src/backend/common/redis.py
@@ -1,6 +1,7 @@
from typing import Optional
import redis
+from google.appengine.ext import ndb
from pyre_extensions import none_throws
from backend.common.environment import Environment
(venv) [phil@fedora-x1think the-blue-alliance-py3]$ ./ops/lint_py3.sh 
All done! ✨ 🍰 ✨
517 files would be left unchanged.
./src/backend/common/redis.py:4:1: F401 'google.appengine.ext.ndb' imported …
```
> Add flake plugin to ban some builtin GAE libraries

- docs/Developing/Queues-and-defer.md
- src/backend/common/deferred/__init__.py
- src/backend/common/deferred/defer_handler.py
- src/backend/common/deferred/tests/defer_handler_test.py
- src/backend/tasks_io/main.py
The catch-all `/_ah/queue/deferred.*` routing was removed in #3999 - however, we still depend on it in production. This PR re-adds the catch-all routing using our old `install_deferred_routes` method.
> Re-add deferred catchall routing

- src/backend/common/models/event.py
- src/backend/common/models/tests/event_test.py
We've migrated away from using `EventDetails.rankings` and should be using `EventDetails.rankings2`
> Always return rankings2 for Event.rankings

- .github/workflows/push.yml
This is causing issues in production with failing to init the Firebase stuff
> Fix missing FIREBASE_APP_ID from buildweb env

- src/backend/web/main.py
We already set this up in the blueprint itself https://github.com/the-blue-alliance/the-blue-alliance/blob/8c49c185312db1d5dace186c970dc48e8dd91394/src/backend/web/handlers/account.py#L35
> Remove unnecessary url_prefix set from account_blueprint in web

- src/backend/common/decorators.py
- src/backend/common/flask_cache.py
- src/backend/common/tests/decorator_test.py
- src/backend/web/handlers/apidocs.py
- src/backend/web/handlers/district.py
- src/backend/web/handlers/event.py
- src/backend/web/handlers/gameday.py
- src/backend/web/handlers/index.py
- src/backend/web/handlers/match.py
- src/backend/web/handlers/team.py
- src/backend/web/handlers/tests/district_detail_test.py
- src/backend/web/handlers/tests/event_detail_test.py
- src/backend/web/handlers/tests/event_list_test.py
- src/backend/web/handlers/tests/match_detail_test.py
- src/backend/web/handlers/tests/team_canonical_test.py
- src/backend/web/handlers/tests/team_detail_test.py
- src/backend/web/handlers/tests/team_history_test.py
- src/backend/web/handlers/tests/team_list_test.py
- src/backend/web/renderers/team_renderer.py
We can cache data that isn't associated with an active event for longer.
This relies on using our forked version of `flask-caching`, but will maintain functionality from the old site. Timeouts were taken from the legacy controllers
> Add Dynamic View Cache TTLs

- src/backend/common/decorators.py
Worked in dev, should work in prod? I think this is dumb because it actually creates a cache depending on the *order* of the query strings, which isn't great. But let's see if it fixes our cache problem upstream and then write tests and figure out how to make it suck less later.
> Cache flask responses using query strings

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
`npm ci` works faster than `npm install`
> Use `npm ci` in GH Actions

- .github/workflows/comment_screenshots_on_pr.yml
- .github/workflows/pull_request.yml
- .gitignore
- .pyre_configuration
- ops/capture_screenshots.py
- ops/pr_screenshots/artifact_data.py
- ops/pr_screenshots/capture_screenshots.py
- ops/pr_screenshots/generate_screenshots_message.py
Handle uploading/commenting of screenshots in a separate action to safely deal with PRs from forks. See https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
> [CI] Properly handle screenshotting and commenting in PRs from forks

- .flake8
- flake8_plugins/api_authenticated_decorator_checker.py
- ops/problem_matchers/flake8_error.json
- ops/problem_matchers/flake8_warning.json
- src/backend/api/handlers/match.py
Example error:
```
Error: ./src/backend/api/handlers/match.py:20:1: ETBA1 'api_authenticated' must be the first decorator, but is after: validate_match_key, cached_public
```
> [lint] Add flake8 checker for api_authenticated decorator

- src/backend/common/manipulators/tests/base_manipulator_test.py
- src/backend/common/manipulators/tests/event_manipulator_test.py
- src/backend/tasks_io/datafeeds/datafeed_fms_api.py
- src/backend/tasks_io/handlers/tests/conftest.py
- src/requirements.txt
This pins us to a forked version of the GAE library, as a way to work around https://github.com/GoogleCloudPlatform/appengine-python-standard/issues/45
This package is running the changes from https://github.com/GoogleCloudPlatform/appengine-python-standard/pull/46 so we can base64 encode all the deferred payload before attempting to execute them.
This one was fun to track down...
> Pin NDB Library So Deferred Works on `dev_appserver`

- src/backend/common/queries/database_query.py
- src/backend/common/queries/tests/database_query_test.py
We might have some issues with caches that were written into the wrong field now returning None. We may have to increment cache keys for all dict converters :cry:
> Fix wrong cache field being written in CachedQueryResult

- src/backend/tasks_io/handlers/tasks.py
- src/backend/tasks_io/handlers/tests/tasks_test.py
- src/backend/tasks_io/main.py
The big difference here between the previous website blocklist is that we clear the team's website *before* doing a refetch. This allows us to handle the current situation where the FRC API is returning empty responses for websites
> Port website blocklist to py3

- .github/workflows/comment_screenshots_on_pr.yml
- .github/workflows/pull_request.yml
- .github/workflows/push.yml
- docs/Setup/Repo-Setup.md
- ops/dev/docker/Dockerfile
- ops/dev/vagrant/dev_appserver.sh
- src/api.yaml
- src/default.yaml
- src/tasks_io.yaml
- src/web.yaml
Base changelog: https://docs.python.org/3/whatsnew/3.9.html
This also changes the dev container to use `ubuntu:rolling`, which is the newest version, instead of the LTS. This means we have access to newer python versions sooner, so it's a benefit
> Update to python 3.9

- src/backend/web/templates/index/index_buildseason.html
- src/backend/web/templates/index/index_kickoff.html
Build season page -
The bits being removed from the kickoff page are mostly like, dead links for things that don't exist anymore
> Update build season template for 2022. Remove commented out bits from kickoff page

- src/backend/tasks_io/handlers/frc_api.py
- src/backend/tasks_io/templates/datafeeds/usfirst_events_details_enqueue.html
Just fixing some weirdness with the event_list enqueue template. Modified the template to reflect the new values that we get from this endpoint (no event count - only a list of years)
> Fix template bugs in event_list enqueue

- src/backend/api/handlers/tests/team_test.py
- src/backend/common/models/media.py
- src/backend/tasks_io/handlers/frc_api.py
`media.details()` is allowed to be None (e.g. for social media). Use `none_throws` only when it's expected to not be None.
> [Typing] Fix media typing

- src/backend/web/handlers/admin/blueprint.py
- src/backend/web/handlers/admin/team.py
- src/backend/web/templates/admin/team_details.html
Since FIRST no longer supports serving websites, we need a custom way to modify/add team websites if we get an email about this.
We should look to add this sort of stuff in the team mod dashboard to allow teams to update their websites themselves probably.
https://user-images.githubusercontent.com/516458/150724043-1025e44e-c2bd-4b4e-9aea-0ed8b6491cfd.mov
> Add website editing to admin page

- src/backend/web/templates/district_details.html
On the events page, wrap text on the District dropdown  menu.
Currently, when selecting a long district name (e.g. FIRST Indiana Robotics), the button expands, overlapping with other text on the page. The change will keep the width of the button fixed, and wrap text when it exceeds the space allotted.
Inspect Element 🙃
> Wrap text on district selector

- src/backend/common/helpers/tests/webcast_online_helper_test.py
- src/backend/common/helpers/webcast_online_helper.py
- src/backend/common/models/event.py
- src/backend/common/sitevars/twitch_secrets.py
This was fixed in py2 but never got ported to py3
d9a67c174bf09653f833fc7fd63adef37129e192
4445414c1be82e7d3f1570fe8eea212bb8300417
4445414c1be82e7d3f1570fe8eea212bb8300417
4d9f267502a49dadf8aa6dee2a24890edc580841
> [Webcast] Fix Twitch API auth & enable webcast status

- src/backend/web/context_processors.py
- src/backend/web/main.py
- src/backend/web/tests/context_processors_test.py
We support the `render_time` in the base templates, but we don't add the render time to the template. This PR adds the render time to web's template variables. This should make debugging caching easier.
> Add back in `render_time` to templates

- src/backend/common/consts/client_type.py
Going to disable sending notifications to Android until we can confirm Android is getting the proper payloads to not crash
> Disable sending push notifications to Android

- src/backend/common/consts/client_type.py
- src/backend/common/helpers/tbans_helper.py
- src/backend/common/helpers/tests/tbans_helper_test.py
- src/backend/common/models/notifications/requests/fcm_request.py
- src/backend/common/models/tests/match_test.py
Android phones expect the webhook formatted payloads
Fixes https://github.com/the-blue-alliance/the-blue-alliance/issues/4303
> Support android notifications with legacy data format

- src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_team_details_parser.py
Whitespace bad
Local fetch doesn't include trailing whitespace
Fixes https://github.com/the-blue-alliance/the-blue-alliance/issues/4331
> Strip whitespace from team names

- src/backend/common/manipulators/award_manipulator.py
Should fix #2485 but we'll need to keep an eye on it
> Wait 5m after fetching awards to recalculate district points so cache clearing can run

- src/backend/common/models/notifications/requests/tests/webhook_request_test.py
- src/backend/common/models/notifications/requests/webhook_request.py
The change in https://github.com/the-blue-alliance/the-blue-alliance/pull/4349 made it so we started emitting webhook errors. Now we should silence them so we don't get transient errors from other the services we're hitting not being up
> Silence webhook errors

- src/backend/common/frc_api/frc_api.py
- src/backend/common/frc_api/tests/frcapi_test.py
- src/backend/tasks_io/datafeeds/datafeed_fms_api.py
- src/backend/tasks_io/datafeeds/parsers/fms_api/simple_json_parser.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_matches_test.py
This will let us get right data to address #4301, because the the v2 hybrid endpoint seems to have broken showing the right values after replays (it only shows the first play).
And since the hybrid schedule endpoint doesn't exist in the v3, this diff will make us call all of the schedule, matches, and scores endpoints and merge all the results together. This is done in a slightly hacky way so we can still use the old hybrid parser, so we merge the data from the schedule/scores endpoint to build objects compatible with the old hybrid endpoint (thankfully the key names are all stable)
Fields missing from the matches endpoint, which meant we couldn't just use it as a drop-in:
- scheduled time for a match
-  surrogate status for teams
Closes …
> Call FRC API v3 for Matches

- ops/dev/vagrant/bootstrap-dev-container.sh
- ops/dev/vagrant/config.sh
- ops/dev/vagrant/dev_appserver.sh
- ops/dev/vagrant/run_firebase_emulator.sh
- src/backend/web/static/javascript/tba_js/tba_keys_template.js
If we attempt to build the container with no secrets file, the JS fails to build, and people cannot use any of the Firebase JS. This PR adds a default secrets file to the container to make sure we can compile the JS at least once.
> Fix building container with no secrets file

- src/backend/common/models/notifications/alliance_selection.py
- src/backend/common/models/notifications/awards.py
- src/backend/common/models/notifications/broadcast.py
- src/backend/common/models/notifications/district_points.py
- src/backend/common/models/notifications/event_level.py
- src/backend/common/models/notifications/event_schedule.py
- src/backend/common/models/notifications/match_score.py
- src/backend/common/models/notifications/match_upcoming.py
- src/backend/common/models/notifications/match_video.py
- src/backend/common/models/notifications/notification.py
- src/backend/common/models/notifications/verification.py
FCM requires a str/str key/value for payloads. We should make that clear in the typing for the notification models.
> Fix mistyped notification method returns

- src/backend/web/context_processors.py
- src/backend/web/tests/context_processors_test.py
The [JS code to convert from a UTC date to a local date](https://github.com/the-blue-alliance/the-blue-alliance/blob/b52f8bffb113bf22bf6023318a5d4d4ec2038427/src/backend/web/static/javascript/tba_js/tba.js#L133) to show the render time of the webpage in the user's local time does not currently work since the `render_time` coming from the server isn't timezone-aware, and the `Date` constructor will assume a timezone-less date is in the user's local time already.
This PR modifies the `render_time` datetime to be a timezone-aware (UTC specifically) datetime object. This allows for proper parsing by the JS `Date` class.
> Fix webpage render_time always being UTC

- src/backend/common/helpers/event_insights_helper.py
I noticed that the quintet success rates seemed suspiciously low at 2022orsal, but didn't question it too much. Looks like @arimb found the reason in #4366! This changes the quintet opportunities to use `opportunities_1x` (per-alliance) rather than `opportunities_3x` (per-robot).
Closes https://github.com/the-blue-alliance/the-blue-alliance/issues/4366
It's been a while since my last contribution so I don't have the testing environment fully setup, but this change seems to be relatively straight-forward. We may want to re-run the event stat calculation tasks for all completed 2022 events to update them, but probably not too big of a deal if that's a tedious job.
> Fix quintet opportunities

- src/backend/common/manipulators/event_details_manipulator.py
- src/backend/common/manipulators/match_manipulator.py
- src/backend/common/manipulators/tests/event_details_manipulator_test.py
This attempts to fix https://github.com/the-blue-alliance/the-blue-alliance/issues/4401 (and mirrors https://github.com/the-blue-alliance/the-blue-alliance/pull/4354) by waiting for the cache clear jobs to run before running our district point calculations
> Add 5m countdown to all district points calculations to allow cache clear jobs to run first

- src/backend/common/helpers/district_helper.py
- src/backend/common/helpers/tests/district_helper_test.py
Fixes #4396 - It looks like there was just a typo where we were taking max qual points instead of max alliance points. This looks to be the way district tiebreakers have been handled since at least 2017 (further back it's tough to find the details, since they're not in the manuals)
> Fix 4th district points tiebreaker to be highest alliance seed

- src/backend/common/helpers/district_helper.py
- src/backend/common/helpers/tests/data/2022on305_district_points.json
We're calculating district point totals for 3rd alliance members at single day events incorrectly. Currently with the equation `16 - (2 * (n + 4))` we're assigning totals backwards - ex: 3rd pick for 4th alliance (n = 3) gets 2 points, 3rd pick for 3rd (n = 2) alliance gets 4 points, etc.
```
4th alliance | n = 3 -> 16 - (2 * (3 + 4)) -> 16 - (2 * 7) -> 16 - 14 -> 2
3rd alliance | n = 2 -> 16 - (2 * (2 + 4)) -> 16 - (2 * 6) -> 16 - 12 -> 4
2nd alliance | n = 1 -> 16 - (2 * (1 + 4)) -> 16 - (2 * 5) -> 16 - 10 -> 6
1st alliance | n = 0 -> 16 - (2 * (0 + 4)) -> 16 - (2 * 4) -> 16 - 8 -> 8
```
The new equation `2 + (2 * n)` should give is the proper totals. 
```
4th alliance | n = 3 -> 2 + (2 * 3) -> 2 + (6) -> 8
3rd alliance | n = 2 -> 2 + (2 * 2) -> 2 + (4) -> 6
2nd alliance | n = 1 -> 2 + …
```
> Fix single day district point totals

- docs/Developing/Queues-and-defer.md
- src/backend/web/local/blueprint.py
- src/backend/web/local/bootstrap.py
- src/backend/web/local/tests/blueprint_test.py
- src/backend/web/local/tests/bootstrap_test.py
Doing a bootstrap for an entire year can be VERY expensive, and usually the request times out before finishing. This PR moves the year task to a `bootstrap` queue to happen in the background.
> Bootstrap event year data in queue

- ops/dev/docker/Dockerfile
From discussion in Slack - the Firebase emulator is currently broken, complaining about a bad Java version
Updating the JRE to the latest (11) seems to fix.
Will build a new version of the Docker container once this lands.
> Fix broken Firebase emulator by updating JRE to 11 in Docker container

- src/backend/common/helpers/tbans_helper.py
- src/backend/common/helpers/tests/tbans_helper_test.py
- src/backend/common/models/notifications/requests/webhook_request.py
- src/backend/web/handlers/apidocs.py
- src/backend/web/handlers/tests/apidocs_test.py
The return codes in these methods aren't used, and I'm attempting to limit the surface area to track down these multiple notification sends.
> Remove return values from TBANS sends - attempt to not retry tasks

- src/backend/web/templates/event_list.html
When there is one event in a category, say "1 Event" instead of "1 Events"
I guess this has been bothering me for a while, because I found this old issue #2779
It hasn't, and I probably did it wrong, but only time will tell!
> Flix plurals, closes #2779

- .pre-commit-config.yaml
- ops/check_venv_deps.py
- ops/check_venv_deps.sh
This will make it easier for people to catch when they have stale dependencies in their local checkout, and to make sure we run tests/lints/etc hermetically against what's in the repo
Example failure
```
(venv) [phil@fedora-x1think the-blue-alliance-py3]$ pre-commit run py3-deps
[py3] venv Dependencies..................................................Failed
- hook id: py3-deps
- exit code: 1
Missing requirements! ['black==22.6.0']
You have mismatched dependencies!
Try running using a venv: https://github.com/the-blue-alliance/the-blue-alliance/wiki/Repo-Setup#virtualenv-install
And make sure everything is up to date by running: pip install -r requirements.txt && pip install -r src/requirements.txt
```
> Validate requirements as a pre commit hook

- src/backend/web/handlers/conftest.py
- src/backend/web/handlers/hall_of_fame.py
- src/backend/web/handlers/tests/data/2021cmpaw.json
- src/backend/web/handlers/tests/data/2021cmpaw_awards.json
- src/backend/web/handlers/tests/data/2022cmptx.json
- src/backend/web/handlers/tests/data/2022cmptx_awards.json
- src/backend/web/handlers/tests/data/frc1629.json
- src/backend/web/handlers/tests/data/frc4613.json
- src/backend/web/handlers/tests/data/frc503.json
- src/backend/web/handlers/tests/hall_of_fame_test.py
- src/backend/web/handlers/tests/helpers.py
- src/backend/web/main.py
Add `/hall-of-fame` url, handler, and tests
More `py3`
Locally.
Added HOF tests (WIP)
Added test data for `2022cmptx`, `2022cmptx_awards`, `2021cmpaw`, and `2021cmpaw_awards`, which is enough data to make sure that the page correctly renders:
1) Years in the correct order (most recent first)
2) Single-winner years
3) Two champ years 
Note: I have no data locally, which is what the tests are for  🙂
> Add Hall of Fame page

- src/backend/tasks_io/datafeeds/datafeed_fms_api.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_test.py
Missed a case where we resolve the correct event code to use when querying FIRST
Also make the parameter for the `Event` required, to make this harder to happen in the future
> Resolve proper event code for team fetch

- src/backend/web/templates/team_details.html
Tried to fix the horizontal scroll issue in #4613. It was caused by this div extending too far to the right
Tested manually that you can no longer horizontally scroll, and the page otherwise looks the same on different screen sizes.
> Fix horizontal scroll issue

- src/backend/common/manipulators/tests/base_manipulator_test.py
- src/backend/common/manipulators/tests/event_manipulator_test.py
- src/requirements.txt
The issue that caused us to fork the library in the first place seems to
have been addressed in the `dev_appserver` implementation.
So I think that renders our fork unnecessary, so let's remove it and
bump ourselves to the latest version
https://github.com/GoogleCloudPlatform/appengine-python-standard/issues/45#issuecomment-1229537695
> Remove forked appengine-python-standard Dependency

- .gitignore
- src/backend/web/handlers/tests/webcast_list_test.py
- src/backend/web/handlers/webcasts.py
- src/backend/web/main.py
Add `/webcasts` url, handler, and tests
Old handler: https://github.com/the-blue-alliance/the-blue-alliance/blob/py3/old_py2/controllers/main_controller.py#L210
Port to py3
Added a basic test
- [x ] New feature (non-breaking change which adds functionality)
> Add /webcasts to py3

- src/backend/common/auth.py
- src/backend/common/middleware.py
- src/backend/common/tests/middleware_test.py
- src/backend/web/tests/main_test.py
`@before_first_request` was deprecated in Flask 2.2.0, and this is blocking a dependency update.
https://flask.palletsprojects.com/en/2.2.x/changes/#version-2-2-0
It's also pretty flaky. This just switches it to use `@before_request` which is hopefully better?
Although really we probably shouldn't use this pattern at all, but since we need to load the secret key from a sitevar, that requires an ndb context, which really can only come through a request
Maybe we should pull this from an env variable or tease out the right configuration to load an ndb context during the app configuration time, so we can make the query
> Stop using @before_first_request

- src/backend/api/api_trusted_parsers/json_matches_parser.py
- src/backend/api/handlers/trusted.py
- src/backend/common/models/match.py
- src/backend/web/handlers/admin/match.py
- src/backend/web/static/swagger/api_trusted_v1.json
- src/backend/web/templates/admin/match_details.html
- src/backend/web/templates/admin/match_edit.html
Towards https://github.com/the-blue-alliance/the-blue-alliance/issues/4716
In the current double elim bracket rendering, it looks weird because the rounds don't exactly line up with the comp level splits.
And so, we can allow Cheesy Arena to include what the match title should be, and use that to override `match.verbose_name`
> Store Display Name on Match Object

- src/requirements.txt
https://github.com/pallets-eco/flask-caching/pull/296 was merged and I missed it months ago, so we can now go back to upstream
> unpin flask-caching

- src/backend/common/decorators.py
- src/backend/common/tests/decorator_test.py
In addition to `etag` caching, we can also support `If-Modified-Since` based caching.
This diff teaches the `cached_public` decorator to detect when the content is unchanged and return a 304.
> Add support for If-Modified-Since based caching

- old_py2/controllers/ajax_controller.py
- old_py2/main.py
- src/backend/common/models/typeahead_entry.py
- src/backend/web/handlers/ajax.py
- src/backend/web/handlers/tests/ajax_test.py
- src/backend/web/main.py
This still 404s on every page load :stuck_out_tongue: so it's probably time to port it
(also it's one of the few things that'll loudly fail if we swap the default routing to py3)
> Port Typeahead Ajax Endpoint

- src/backend/common/consts/playoff_type.py
- src/backend/common/helpers/match_helper.py
- src/backend/common/helpers/playoff_advancement_helper.py
- src/backend/common/helpers/playoff_type_helper.py
- src/backend/common/helpers/tests/match_helper_test.py
Towards https://github.com/the-blue-alliance/the-blue-alliance/issues/4716
Since there are some actual changes we need to make to match ordering and bracket rendering (plus some existing data in the DB), I think we'll want to just keep separate playoff types in the code to separate old/new. This diff renames the existing double elim playoff type to `LEGACY` so the new style can be the "real" one
> Rename Legacy Double Elim Playoff Type

- src/backend/common/helpers/playoff_advancement_helper.py
- src/backend/web/handlers/tests/event_detail_test.py
- src/backend/web/static/css/less_css/less/tba/tba_double_elim_bracket_table.less
- src/backend/web/static/css/less_css/tba_style.main.less
- src/backend/web/templates/bracket_partials/double_elim_bracket_table.html
- src/backend/web/templates/event_details.html
Add support for displaying double elimination brackets on the event page. 
- Layout is done through HTML tables
- I created the `.inner` class since the behavior for drawing borders directly on `td`s was inconsistent between different browsers
- I put the team names in the tooltip, to prevent the bracket from being too wide
Feedback is welcome!
<hr/>
#4716
> Create double elimination bracket renderer

- src/queue.yaml
I'm seeing a lot of 502s coming from the `/_ah/queue/deferred_notification_send` endpoint - which might be the cause of our multiple push notification sends. I'm going to bump down the speed on our push notification sends to try to not overwhelm the instance to see if we can get more 200s here and then monitor if we're still seeing duplicate sends.
> Slow down push-notifications queue in an attempt to fix retried push notification tasks

- src/backend/common/helpers/tbans_helper.py
- src/backend/common/models/notifications/requests/fcm_request.py
Attempting to figure out what's taking so long with the FCM pushes - if it's iterating through our response objects/cleaning up tokens, or the actual sends.
> Add timestamp logging to debug 502s on task queue tasks

- dispatch.yaml
This pins the known-to-need py2 endpoints to the `default` service, and sets the default to py3.
It's time.
> Flip default routing to py3

- src/backend/api/api_trusted_parsers/json_zebra_motionworks_parser.py
- src/backend/api/api_trusted_parsers/tests/test_json_zebra_motion_parser.py
Respond with a more useful error message instead of returning 500 for malformatted data.
Ran into unhelpful 500 errors due to 
```
File "/workspace/backend/api/handlers/trusted.py", line 343, in add_match_zebra_motionworks_info
for zebra_data in JSONZebraMotionWorksParser.parse(request.data):
File "/workspace/backend/api/api_trusted_parsers/json_zebra_motionworks_parser.py", line 45, in parse
times = zebra_data.get("times", [])
AttributeError: 'str' object has no attribute 'get'
```
> Validate zebra json

- src/backend/web/handlers/event.py
- src/backend/web/main.py
Port RSS event feeds over to `py3`
It was mentioned in a couple issues (closes #4872, closes #4326), as well as in Slack.
I personally have used the RSS feeds in the past, and it was easy enough to port them over, so I figured why not?  🤷‍♂️ 
Tested locally, with `2022cmptx` (see below)
> Add RSS feeds to events

- src/backend/web/templates/bracket_partials/double_elim_bracket_table.html
Changes the double elim bracket display to display team numbers by default and alliance names on hover. There are several team number separators shown in screenshots. The PR (when opened) uses the ` - ` as a separator, but I'm not particularly attached to any single one.
Since alliance names are typically not on the same screen as the bracket display (due to page layout), it's difficult to remember which teams are on which alliance when looking at the bracket. Moving the mouse around to hover on each alliance in each match is frustrating. If alliance names are not set, the entire bracket shows as "Unknown", making it unreadable.
UI change only, ran locally.
https://i.imgur.com/xfNifAG.png
https://i.imgur.com/ZGjcUdl.png
https://i.imgur.com/CeSgKBq.png
https://i.imgur.com/DCWkl54.png
(the …
> Switch alliance name and alliance teams in double elim bracket display

- src/backend/common/decorators.py
- src/backend/common/models/media.py
- src/backend/common/sitevars/instagram_api_secret.py
- src/backend/common/suggestions/media_parser.py
- src/backend/web/handlers/admin/authkeys.py
- src/backend/web/handlers/embed.py
- src/backend/web/handlers/tests/embed_test.py
- src/backend/web/main.py
- src/backend/web/templates/admin/authkeys.html
- src/backend/web/templates/media_partials/instagram_partial.html
Use the new facebook [oembed API](https://developers.facebook.com/docs/graph-api/reference/instagram-oembed/) to get the thumbnail embeds and suggestion submission working again. 
- Since the image links returned by the API expire, I created a helper endpoint so the frontend can dynamically fetch the image urls
- This should fix #4779 and #3489
Slack thread: https://the-blue-alliance.slack.com/archives/C15SUFL92/p1667272352875539
Added a couple pytests
https://user-images.githubusercontent.com/6137845/199652637-7a39d9cd-9f9a-4ef9-8686-16e3bc61295b.mov
> Fix instagram embeds

- src/backend/common/queries/event_query.py
- src/backend/web/handlers/district.py
- src/backend/web/handlers/event.py
- src/backend/web/handlers/tests/district_detail_test.py
- src/backend/web/handlers/tests/helpers.py
- src/backend/web/handlers/tests/regional_detail_test.py
- src/backend/web/main.py
- src/backend/web/templates/regional_details.html
Similar to the district detail endpoint, show a page of regional events too.
This basically reserves the `regional` code to never be used as a district. Which ... why would it
> Add page to show regional events in a year

- src/backend/web/handlers/index.py
Fixes #4988
References can be empty if an avatar is deleted from a team (we don't delete the actual object, just remove the reference).
> Filter avatars with empty references

- src/backend/api/handlers/tests/trustedapi_auth_test.py
- src/backend/api/trusted_api_auth_helper.py
- src/backend/common/models/api_auth_access.py
This'll make it easier for us to support FIRST HQ's match video system, where we can easily grant them access to write videos to all events with official sync enabled
> Support granting trustedapi auth to all offiical events

- src/backend/web/static/css/less_css/less/tba/tba_match_table.less
- src/backend/web/templates/bracket_partials/double_elim_bracket_table.html
Adds some changed styling to double elim bracket to improve readability at a glance.
- Removes spaces in alliance member delimiters
- Inserts `<wbr>` between teams on 4-team alliances to suggest to the browser to wrap text after the hyphens
- Bolds the entire winning alliance, rather than their winning set score
- Adds column for alliance seed next to each alliance (if alliance names exist)
The bracket as is can be a little difficult to follow at a quick glance.
Locally. **This will be ugly if any double elimination brackets have named alliances, such as Einstein**, so an improvement to this would be appreciated. This is because it uses `alliance_name[-1]` to get the alliance seed.
2022cc before: 
2022cc after: 
2023week0 before: 
2023week0 after:
> Improve double elim bracket styling

- src/backend/web/handlers/event.py
- src/backend/web/templates/event_partials/event_copr_table.html
- src/backend/web/templates/event_partials/event_opr_table.html
- src/backend/web/templates/opr.html
Shows all OPRs by default on event insights tab.
The community has been asking (a lot) to show more than just the top 15 OPRs. These are available in the API anyhow.
Locally.
> Show all OPRs by default

- docs/Setup/Setup-Guide.md
- ops/dev/vagrant/bootstrap-dev-container.sh
- Add note about TBA_LOCAL_DOCKERFILE
- Add flag for puppeteer install to avoid this error: 
```
The chromium binary is not available for arm64.
If you are on Ubuntu, you can install with: 
sudo apt install chromium
sudo apt install chromium-browser
ERROR: Failed to set up Chromium r1095492! Set "PUPPETEER_SKIP_DOWNLOAD" env variable to skip download.
Error
at handleArm64 (/tba/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:137:11)
at BrowserFetcher.download (/tba/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserFetcher.js:284:13)
at fetchBinary (/tba/node_modules/puppeteer/lib/cjs/puppeteer/node/install.js:112:14)
at downloadBrowser (/tba/node_modules/puppeteer/lib/cjs/puppeteer/node/install.js:61:11)
at Object.<anonymous> …
```
> Improve setup for Apple Silicon mac

- src/backend/web/handlers/admin/authkeys.py
- src/backend/web/templates/admin/authkeys.html
Previously the local bootstrap page would direct you to `/admin/authkeys` to save your api key, but there was no field for the TBA key. 
Make development process easier. 
- [ x] Bug fix (non-breaking change which fixes an issue)
> Add TBA api key field to /admin/authkeys

- src/backend/common/models/match.py
- src/backend/common/models/tests/match_test.py
SF set number can go up to 13 now in double elims.
> Allow 2 digit semifinal set number in match validation

- src/backend/web/templates/event_details.html
Shows Covid-19 Site Information only if year = 2022.
Currently, site information populates for years > 2021, which includes 2023 and will include subsequent years. However, there are no Covid-19 site info summaries for events outside of 2022. Current links error on the FIRST website.
Hasn't
> Hide Covid information for events outside 2022

- src/backend/common/manipulators/event_details_manipulator.py
Sorry for the additional logging but - adding one piece of information for myself to attempt to troubleshoot multiple alliance selection push notification sends. I've run out of breadcrumbs to follow locally...
> Add event_key logging for EventDetails manipulator

- src/backend/web/static/javascript/tba_js/tba.js
On the https://www.thebluealliance.com/suggest/review page the links are nav-pills and this logic seems to not be needed, I'm not sure if this code is needed for any other page or if it should just be removed.
The links are .nav-pills but do not use hash routing so the previous version of the code resulted in links that only work when opened in a new tab.
Built and ran locally.
N/A
> Fix broken links on review pending suggestions page

- src/backend/common/helpers/playoff_advancement_helper.py
- src/backend/web/static/css/less_css/less/tba/tba_double_elim_bracket_table.less
- src/backend/web/templates/bracket_partials/double_elim_bracket_table.html
- Make bracket layout more compact
- In the match tables:
- Fix display of placeholder teams ("Winner of M1")
- Only show the score column if the match has been played 
- Remove the alliance name tooltips since we already display them in front of the team numbers
Fix bugs/improve the readability of the bracket
Checked locally
> Improve double elim bracket layout

- src/backend/web/templates/bracket_partials/double_elim_bracket_table.html
Fixed a typo in the double elimination bracket which had the winner of match 12 advancing to match 13 AND the finals while the winner of match 11 didn't go anywhere.
typo fix
> fixed double elimination bracket template

- src/backend/web/templates/suggestions/suggest_team_media.html
Remove Chief Delphi from instructions, add instructions about imgur.
Lots of confused emails when this doesn't work.
It hasn't, I don't have local auth working so can't load this page.
> Update media instructions for 2023.

- src/backend/web/templates/apidocs_partials/apidocs_webhooks_test.html
- src/backend/web/templates/apidocs_webhooks.html
For some reason the webhook test page is getting 400s with missing CSRF tokens. This PR just changes the form to hold the CSRF token, which seemed to work more reliably in my local instance. Should be an easy revert if it doesn't fix the issue.
> Change the webhook test form to use form CSRF instead of Javascript headers

- src/backend/common/consts/district_point_values.py
- src/backend/common/helpers/district_helper.py
Instead of awarding points to the loser of a match, we can award points to the winner of the previous match. This lets us award district points earlier, while an event is ongoing.
A website I help run, frclocks.com, uses the blue alliance for district points. That website tracks when a team clinches a spot to the district championship or to the world championship. We would like to mark when a team clinches a spot as soon as possible - while an event is ongoing. This change would allow frclocks to do that while still using the blue alliance api, rather than implementing our own points tracking system. It will also give TBA users accurate district points as an event is ongoing.
I've been having difficulties getting vagrant to run on my machine, so I have not been able to test this as well …
> Awards elim district points as matches are won

- src/backend/common/models/event.py
- src/backend/common/models/tests/event_test.py
- src/backend/tasks_io/datafeeds/datafeed_fms_api.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_awards_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_test.py
Fix firstinspires.org links for CMP divs.
Closes #5181
In addition, I moved the `EVENT_SHORT_EXCEPTIONS` and `EVENT_SHORT_EXCEPTIONS_2023` into the `Event` model, as that seemed like a better location as the "source of truth", if you will.
I'd like to move/unify the `FMSAPIEventListParser.EVENT_CODE_EXCEPTIONS` into this as well, but that will likely be a different PR with more refactoring.
Locally, as well as additional testing.
> Fix firstinspires.org links for CMP divs

- src/backend/common/helpers/matchstats_helper.py
- src/backend/common/helpers/score_breakdown_keys.py
- src/backend/web/static/swagger/api_v3.json
- src/backend/web/templates/match_partials/match_breakdown/match_breakdown_2023.html
`extraGamePieceCount` is separate from `teleopGamePieceCount` but `teleopGamePiecePoints` includes points for both
> Add supercharged node count

- src/backend/common/helpers/match_tiebreakers.py
- src/backend/common/helpers/tests/data/2023cmptx_sf12m1.json
- src/backend/common/helpers/tests/match_tiebreaker_test.py
This should fix the logic used to determine the winner of 2023 matches where the "tech foul" tiebreaker was used.
https://www.thebluealliance.com/match/2023cmptx_sf12m1 currently has the wrong winner assigned (blue, should be red) because the tiebreaker logic is awarding the win to the alliance with the larger `techFoulCount` (the number of tech fouls committed by the alliance, which award points to the opposing alliance).
This was probably overlooked when copying tiebreaker logic from 2022, where `foulPoints` (points earned from fouls committed by the opposing alliance) was the first tiebreaker.
Followup to #5005/#5007
Unit test added and appears to pass in CI.
I also verified that all existing ties broken by `techFoulCount` are showing the wrong winner on TBA (this was only the 4th …
> Fix inverted techFoulCount tiebreaker for 2023

- src/backend/common/helpers/event_helper.py
- src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_event_list_parser.py
There is special logic to make the two champs names correct that applied for 2023 when I believe it should not have. This makes 2023 look the same way as 2022.
Champs for 2023 is called `Einstein Field (Houston)` when last year it was called just `Einstein Field`.
I have only run the automated tests.
> Removes (Houston) from 2023 Champs to match 2022 Champs

- src/backend/web/templates/bracket_partials/double_elim_4_bracket_table.html
- src/backend/web/templates/bracket_partials/double_elim_bracket_table.html
Alliance names in the bracket in production currently show the last letter of the division name. This changes it to show the first 3 characters of the division name on Einstein, and the full name in Michigan.
There are definitely other ways to format this and I'm not tied to any format in particular!
Existing brackets at normal events are unchanged.
The existing bracket looks confusing! There's weird letters instead of showing which alliance is what.
I have ran this locally.
Einstein:
Michigan:
> Corrects alliance names in brackets on Einstein/MSC

- src/backend/web/static/css/less_css/less/tba/tba_double_elim_bracket_table.less
This change makes Einstein look better on mobile. The three character codes instead of the one character alliance number makes the boxes overlap each other. This stretches out the boxes by 20 pixels. This slightly affects non-Einstein double-elim brackets as well, but not by much.
I'm not very familiar with frontend changes. There might be a better way to implement this. One option I can think of would be to keep the width the same for non-Einstein brackets, and change the width only for Einstein.
The Einstein bracket does not look good on small mobile screens.
This has been run locally. It's only a cosmetic change.
These screenshots are on a standard-size (not XL) iPhone 13.
**Before:**
**After:**
> Makes Einstein bracket look better on mobile

- src/backend/common/models/match.py
- src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_match_parser.py
- src/backend/tasks_io/datafeeds/parsers/fms_api/tests/test_fms_api_match_tiebreaker.py
Reported because https://www.thebluealliance.com/match/2023ncash_sf12m1 shows the tie, but we never got the next match imported.
The bug was from an assumption about best-of-three, where we'd only replay third+ matches.
Added test coverage for the double elim case
> Fix Tiebreaker Match Generation For Double Elim Events

- ops/dev/pull-gae-logs.sh
- ops/test_ops.sh
- ops/tests/client_api_fullstack.test.js
- package-lock.json
- package.json
- src/backend/api/client_api_auth_helper.py
- src/backend/api/client_api_types.py
- src/backend/api/handlers/client_api.py
- src/backend/api/handlers/decorators.py
- src/backend/api/handlers/tests/client_api_registration_test.py
- src/backend/api/handlers/tests/clientapi_auth_test.py
- src/backend/api/handlers/tests/clientapi_test_helper.py
- src/backend/api/handlers/tests/conftest.py
- src/backend/api/main.py
- src/backend/common/auth.py
- src/backend/common/consts/client_type.py
- src/backend/common/firebase.py
- src/backend/common/tests/auth_test.py
- src/dispatch.yaml
Okay I think this is essentially what we'll need.
If I grab a id_token for my user, and put it over curl, then I can successfully register a client
```
[phil@fedora-x1think the-blue-alliance-py3]$ curl -H "Authorization: Bearer <snip>" -H "Content-Type: application/json" --data '{"name": "test device", "operating_system": "android", "mobile_id": "abc123", "device_uuid": "test"}' http://localhost:8080/clientapi/tbaClient/v9/register
{"code":200,"message":"Registration successful"}
```
This is how we get tokens in the android app, so I think this should be good:
https://github.com/the-blue-alliance/the-blue-alliance-android/blob/4313501d57594089ff01de2705bdc544a3d19eb9/android/src/main/java/com/thebluealliance/androidclient/auth/firebase/FirebaseAuthProvider.java#L64-L76
This PR also adds a …
> Port Basic Mobile API Registration Methods

- .github/workflows/pull_request.yml
- .github/workflows/push.yml
- ops/dev/docker/Dockerfile
- package.json
This seems like the better way to fix the current build failures: https://github.com/firebase/firebase-tools/issues/5041.
Especially since node 14 has been EOL (and I wish dependabot could manage this for us)
> Update to node 18

- src/backend/web/templates/index/index_offseason.html
Change 2021 game and season resources to 2023 game and season resources and remove the 2021 season details button
The years are wrong and the updated version is now consistent with the other index page templates
Current home page
Updated home page
> Update home page links

- src/backend/common/models/match.py
- src/backend/common/models/tests/match_test.py
Sometimes offseasons change up bracket structures and have more than 9 matches per round.
Changes the match key regex to support double digit set numbers.
> Support double digit set numbers in EF and QF matches

- old_py2/mobile_main.py
- ops/test_ops.sh
- ops/tests/client_api_fullstack.test.js
- src/backend/api/client_api_types.py
- src/backend/api/handlers/client_api.py
- src/backend/api/handlers/tests/client_api_ping_test.py
- src/backend/api/main.py
- src/backend/web/local/blueprint.py
This ports `ping` functionality in a way that we can test using the fullstack test framework. A few things:
- change the existing test to be a bit more idempotent to simplify local development
- add some jest arguments to run tests serially, so we can avoid tests conflicting state on the local devserver and bump the timeout 
- implement a basic webhook receiver on a the `local` blueprint, so we can fetch and validate the notifications we receive.
> Port clientapi ping to py3

- src/backend/common/auth.py
- src/backend/common/consts/suggestion_state.py
- src/backend/common/helpers/account_deletion.py
- src/backend/common/helpers/tests/account_deletion_helper_test.py
- src/backend/common/tests/auth_test.py
- src/backend/web/handlers/account.py
- src/backend/web/handlers/tests/account_overview_test.py
- src/backend/web/handlers/tests/account_test.py
- src/backend/web/templates/account_delete.html
- src/backend/web/templates/account_overview.html
Soon, Google Play will require us to provide links to a way to delete your account which can be deep-linked from the store metadata. Details: https://support.google.com/googleplay/android-developer/answer/13327111
This implements a basic version at `/account/delete`. The algorithm will be to:
- auto-reject all pending suggestions
- delete mobile clients, API keys, and myTBA favorite/subscription objects
- revoke the current session cookies
- delete the user in firebase and delete the `Account` object
> Add Account Deletion

- .github/workflows/push.yml
- ops/deploy/deploy_dispatch.sh
- ops/prod_dispatch.yaml
- src/dispatch.yaml
Towards https://github.com/the-blue-alliance/the-blue-alliance/issues/5388
GH Actions [dropped support for python2](https://www.github.com/actions/setup-python/issues/672); it's not worth investing in any more forward fixes.
For the time being, we need different dispatch rules for the local devserver and prod (for as long as we still have py2 serving endpoints), so we add a separate file which the CI knows how to handle at deploy-time. The contents were copied from the [`master` branch](https://github.com/the-blue-alliance/the-blue-alliance/blob/master/dispatch.yaml)
Once we remove the last few py2 URL rules, we can kill the service in GAE, and consolidate on a single dispatch file.
> deploy dispatch.yaml from py3 repo

- ops/prod_dispatch.yaml
Towards https://github.com/the-blue-alliance/the-blue-alliance/issues/5388
This will remove all the dispatch rules pointing to the `deafult` (py2) module, except for py2.thebluealliance.com (whose ordering was sus, since the dispatch rules will use the first match in the file, so the subdomain matchers should be at the top of the file).
The step after this is to remove the py2 subdomain and turn off the GAE services.
> remove py2 url routing rules

- src/backend/common/consts/insight_type.py
- src/backend/tasks_cpu/handlers/conftest.py
- src/backend/tasks_cpu/handlers/insights.py
- src/backend/tasks_cpu/handlers/tests/insights_test.py
- src/backend/tasks_io/handlers/math.py
- src/backend/tasks_io/handlers/tests/district_points_calc_test.py
- src/cron.yaml
Turns out we never updated the years in `cron.yaml` (I checked the console :stuck_out_tongue: )
So, add a version of the URLs here which don't take an explicit year parameter and instead default to the current season. And let's use that instead, so we don't have to remember to change the cronjobs in the future :smile:
> Support current-season computations in insights/district rankings

- src/backend/common/helpers/score_breakdown_keys.py
This allows adding `extraRp1` and `extraRp2` fields to score breakdowns through the write API. These are not used by the FRC API, so we could consider prefixing them with `tba_` as well (I brought this up as an option on Slack but we didn't reach a consensus).
Offseasons sometimes want to add extra ranking points for various things (e.g. the additional cargo threshold at 2022cc, rainbow link bonus at 2023mirr). Supporting breakdown fields for this purpose makes it easier to submit and retrieve data about these RPs, and also allows for disambiguation if multiple extra ranking points are used.
Submitted a couple matches through the write API on a local instance. Also verified that insights are unchanged with these fields added or removed from matches. (I would like to eventually support …
> Allow extra RP fields for 2023

- src/frontend/eventwizard/eventwizard.js
> Fix eventwizard crashing with no redux devtools

- src/backend/web/templates/match_partials/match_breakdown/match_breakdown_2023.html
Receiving null links instead of `[]` from Cheesy Arena.
This fixes match details page from 500-ing, but this means the score breakdown API is not following our swagger spec.
> Fix null links handling

- src/backend/api/api_trusted_parsers/json_awards_parser.py
`AwardRecipient` takes a string (including something like `"254B"`) or an int.
> Allow "B" teams in json awards parser

- src/backend/common/helpers/insights_helper.py
- src/backend/common/models/insight.py
- src/backend/web/templates/insights_details.html
Adds a new insight that tracks most matches played for each team per year. Does not include offseasons.
Been tracking this myself for a while now and would help to have this built in to TBA
Manually
This is from a few 2023/2019 events locally
> Add most matches played per year insight

- src/requirements.txt
Update the forked library to be based on 1.1.5. 
The patch we need remains https://github.com/GoogleCloudPlatform/appengine-python-standard/commit/0330577a2c44bee1f9fd4f64a02da75209e29d39
Full changelog:
```
0e6191b (HEAD -> tba-fork, origin/tba-fork) Merge tag 'v1.1.5' into tba-fork
ad688b7 (tag: v1.1.5, upstream/main, origin/main, origin/HEAD, main) v1.1.5
1142ecd Add Memcache support to fetch timestamps. (#106)
882b8fa (tag: v1.1.4) Version 1.1.4
ae33549 Loading imp module only for python2 versions. Python 3.12 has strictly (#101)
a900a13 (tag: v1.1.3) Version 1.1.3 (#95)
a186fbc Support an "all namespaces" option on ListIndexes in the Search SDK a… (#94)
31ceb17 add missing support for enabling search service stub in Testbed
dc77b80 Support python 3.11
db175aa (tag: v1.1.2) Version …
```
> Update App Engine Runtime to 1.1.5

- pytest.ini
- src/backend/api/main.py
- src/backend/common/environment/environment.py
- src/backend/common/helpers/tbans_helper.py
- src/backend/common/helpers/tests/tbans_helper_test.py
- src/backend/common/middleware.py
- src/backend/common/run_after_response.py
- src/backend/common/tests/fixture_loader.py
- src/backend/common/tests/google_analytics_test.py
- src/backend/conftest.py
- src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_match_parser.py
- src/backend/tasks_io/datafeeds/parsers/fms_api/tests/test_fms_api_match_tiebreaker.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_matches_test.py
- src/backend/tasks_io/handlers/tests/district_rankings_calc_test.py
- src/backend/tasks_io/handlers/tests/frc_api_event_details_test.py
- src/backend/tasks_io/handlers/tests/frc_api_event_list_test.py
- src/backend/tasks_io/handlers/tests/frc_api_event_matches_test.py
- src/backend/tasks_io/handlers/tests/frc_api_teams_test.py
Keeping warnings clean in tests is a good thing. Unfortunately, most of them come from third party libraries so they need to be suppressed, but there's at least a few things we should have fixed in our code.
> fail pytest on warnings

- src/backend/web/handlers/index.py
- src/backend/web/templates/index/index_buildseason.html
- src/backend/web/templates/index/index_kickoff.html
- src/backend/web/templates/index/index_offseason.html
- src/backend/web/templates/index_partials/index_lhc.html
- src/backend/web/templates/index_partials/index_lhc_offseason.html
- Change the donate button to link to `/donate`, which has more information instead of going directly to paypal
-  remove hardcoded years
- The covid-19 resource link hasn't been updated since 2021
> Update Homepage Templates for 2024

- src/backend/common/models/event.py
- src/backend/web/handlers/admin/team_media_mod.py
- src/backend/web/handlers/admin/tests/team_media_mod_test.py
When importing a year's worth of modcodes, this OOMs. I've been manually working around it for years, but no longer.
Also, write some tests for this handler.
> defer writes of team modcodes

- src/backend/common/helpers/tbans_helper.py
- src/backend/common/helpers/tests/tbans_helper_test.py
As title.
Currently, this 500s if you try to ping an Android client. That shouldn't be. Also adds new tests for the scenario.
> Support PING notifications with legacy FCM format

- src/backend/api/main.py
- src/backend/common/queries/dict_converters/event_details_converter.py
Adds `/event/{key}/coprs` API endpoint. This **does not** touch any Swagger stuff, so we will need to add that in a followup PR.
Note that all events from 2016-2022 should have their cOPRs generated at some point; these events are aggressively cached so they haven't ever actually run since cOPRs were introduced. An admin will need to do this.
COPRs are currently only available via web interface. This helps scouts a lot and prevents the need for web scraping.
Manually with 2 events - one with cOPRs generated, one without (returns `{}` for events without cOPRs).
> Add component opr api endpoint

- src/backend/web/templates/match_partials/match_breakdown/match_breakdown_2024.html
Fix match_breakdown_2024:
- red auto leave
- Foul/Tech foul points 
Copy/paste issue.  😅
Reported here:
https://www.chiefdelphi.com/t/tba-match-summaries-for-isr-district-event-1-correct/456162
Tested locally
> Fix match_breakdown_2024 red auto leave

- src/backend/common/models/event_details.py
https://www.thebluealliance.com/event/2024isde1#rankings is currently showing the pre-2017 "Ranking Score/Match" column, rather than the post-2017 "Total Ranking Points" column. This changes that behavior, and also changes the default behavior for future years so we hopefully don't run into the same issue every year (until rankings change).
https://www.chiefdelphi.com/t/tba-match-summaries-for-isr-district-event-1-correct/456162/10
Imported a 2016, 2017, and 2024 event locally. 2016 and 2017 showed no change. For 2024:
<details><summary>Before</summary>
</details> 
<details><summary>After</summary>
<p>
</p>
</details> 
Statically verified from 36a5b1db5d2f74eaa3b2e108a3c98b6488425f14 and 691592f097a6a17f5f6c0b0d26024c615d19738b that these should be the only necessary changes.
> Show "total ranking points" column in 2024 rankings

- src/backend/tasks_io/handlers/frc_api.py
- src/backend/tasks_io/handlers/tests/frc_api_teams_test.py
Right now, once a team is listed in a district, they will get new `DistrictTeam` records for every year after that.
The result of this is that we list teams who are no longer competing in current district listings, which is very confusing, and incorrect.
The biggest functional change here is that each time we update the `team_details` for a team, we're checking all `DistrictTeam`s for that team to make sure that each year the team has a corresponding `EventTeam` i.e. they went to at least one event.  2020/2021 was a question mark for me, but any team that actually competed has the "remote" events, so we're good there.
I've added a new spec, just to cover this specific case, as well as updated the other specs to including having a `EventTeam` for that year, since that's now required.
In …
> Automatically remove DistrictTeam for teams without an event in a given year

- src/queue.yaml
Set this in the web interface but a deploy overwrote this (expected). Going to add this to the ymal so it persists. Should help with push notification tasks timing out and then retrying.
> Set push notification retry limit to 0

- src/backend/common/models/notifications/requests/tests/webhook_request_test.py
- src/backend/common/models/notifications/requests/webhook_request.py
Removed the double quotes surrounding utf-8 in the HTTP header for Content-Type of the POST request sent to webhooks. 
The Content-Type header should now have the correct format for describing the UTF-8 character set of the payload. 
Both the implementation and the relevant test case have been changed to reflect the correct syntax for the HTTP header.  
The current webhook verification & ping process would result in a 500 error when sent to a Kafka cluster (hosted by Upstash) through their webhook API. The HTTP headers sent with the request were parsed by Upstash before the data is loaded into the Kafka topic stream, so that non-standard HTTP headers are converted to message headers in the stream. As such, standard HTTP headers with incorrect syntax would result in an error. 
Removing the …
> Minor fix: Removal of unnecessary double quotes around utf-8 in HTTP header for webhooks

- src/backend/common/helpers/tbans_helper.py
- src/backend/common/helpers/tests/tbans_helper_test.py
Adding the `match.push_sent = True` flag + check to the FCM code
> Set match.push_sent for match score notifications

- src/backend/tasks_io/datafeeds/datafeed_fms_api.py
- src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_match_parser.py
This week, FMS sync issues have led to schedules getting posted with no teams, which breaks lots of things...
This diff will try to work around it, for cases where match results are publishing (and to take the teams from the results API if none are present in the schedule response).
With this, I managed to load match results for `2024onbar` locally:
While prod looks like this:
> work around broken schedules in FRC API

- src/frontend/gameday2/components/VideoCellToolbar.js
Stop gameday from crashing the whole page on broken schedules
> [gameday] Skip match ticker if no teams

- src/backend/common/helpers/tbans_helper.py
- src/backend/common/helpers/tests/tbans_helper_test.py
- src/backend/common/manipulators/match_manipulator.py
- src/backend/common/manipulators/tests/match_manipulator_test.py
Avoids using the `match.put` which was rightly pointed out is probably an issue due to how our cache works for the models
> Check Match.push_sent in the match manipulator

- src/backend/api/handlers/decorators.py
Currently the `favorites/list` and `subscriptions/list` endpoints are throwing 500s because the POST data is empty and we're unable to load the JSON from the data (since it's empty). This provides a fallback for the data of an empty request if no POST data is supplied.
> Support empty requests for client api (list endpoints)

- src/backend/common/helpers/tbans_helper.py
- src/backend/common/helpers/tests/tbans_helper_test.py
- src/backend/common/manipulators/award_manipulator.py
- src/backend/common/manipulators/event_details_manipulator.py
- src/backend/common/manipulators/match_manipulator.py
- src/backend/common/manipulators/tests/award_manipulator_test.py
- src/backend/common/manipulators/tests/event_details_manipulator_test.py
- src/backend/common/manipulators/tests/match_manipulator_test.py
- src/backend/common/models/subscription.py
- src/backend/common/models/tests/subscription_test.py
More work on #5119 
First step is getting the notification dispatching out of the way of the post updates hook. The `TBANSHelper` calls are now deferred and will be run on the `push-notification` queue.
Next, we've setup the `Subscriptions` class methods to fetch subscriptions (changed from user IDs - more on this later) to be async. This will allow us to do several at a time and then wait for the response. Although I suspect fetching the subscriptions is not the problem - it's the previous `list(set([user.user_id for user in subscriptions]))` call.
The call above to get the user_id on a user object (despite the projection) is likely the problem for the long list of ndb queries that are timing out these calls. Instead of de-deduplicating the list of user IDs before sending the …
> Kickoff TBANS notifications via deferred. Batch subscription fetches

- src/backend/common/manipulators/award_manipulator.py
- src/backend/common/manipulators/event_details_manipulator.py
- src/backend/common/manipulators/match_manipulator.py
Adding named tasks in https://github.com/the-blue-alliance/the-blue-alliance/pull/5830 - we need to make sure we catch these tasks having already been added/run
> Add try/catch to TBANS defer adds - will catch TaskAlreadyExistsError or TombstonedTaskError

- src/backend/web/templates/event_details.html
Removes showing our geocoded location from the event pages and using the data we get from the frc-api instead.
Note: this does NOT remove geocoding altogether, as that powers setting the timezone for events as well as the lat/lng.
> Remove showing localized location from event pages

- src/backend/common/models/event.py
- src/backend/web/templates/event_details.html
Follow up from https://github.com/the-blue-alliance/the-blue-alliance/pull/5835 - did a closer read at the code and made this match the team info
Removing the `if not self._city_state_country and self.nl:` line should be no big deal - the only place that `event.city_state_country` is used is the [`mytba_live.html`](https://github.com/the-blue-alliance/the-blue-alliance/blob/c8992943722d95f27b36b06c912c38d9ad1dbad5/src/backend/web/templates/mytba_live.html#L59) and the [`event_table.html`](https://github.com/the-blue-alliance/the-blue-alliance/blob/c8992943722d95f27b36b06c912c38d9ad1dbad5/src/backend/web/templates/event_partials/event_table.html#L19) - both of which should match the location we show for the event on the details page (which no longer uses the `Event.normalized_location`)
> Use Event.city_state_country for event details location

- src/backend/web/templates/event_details.html
Partial revert of https://github.com/the-blue-alliance/the-blue-alliance/pull/5836 - forgot we'd drop the venue name by using that `city_state_country`.
A follow up would be to remove `city_state_country` altogether from the event and use `location` - unsure why that logic is duplicated
> Partial revert of 829637bcd4b5b51866e5ae6c9e24174a49d35ac3

- src/backend/common/helpers/tbans_helper.py
Push notifications are failing because the named tasks for scheduling upcoming matches can throw the usual named task errors. Catching should help these.
> Catch Tombstone'd task for scheduling upcoming matches in TBANS

- src/backend/tasks_io/handlers/math.py
- src/backend/tasks_io/handlers/tests/district_rankings_calc_test.py
- src/cron.yaml
We needed a handler to default the year when unset, as `cron.yaml` calls `/tasks/math/enqueue/district_rankings_calc`
> Fix calculating district rankings periodically

- src/backend/common/helpers/tbans_helper.py
From GAE yesterday - sometimes our team object when sending push notifications for teams can be nil. This PR introduces more logic to gracefully degrade if we cannot find a team
> Defend against missing team.key_name erroring notifications

- src/backend/common/auth.py
Fixing lots of errors in the logs for these clientapi token validation failing. They all seem to be around the token expiring
> Handle all errors from verifying clientapi tokens

- src/backend/common/helpers/matchstats_helper.py
Adds 2 more component OPRs - total game pieces and amplification rate. Amplification rate is the percentage of teleop speaker notes scored that are amplified.
Total GPs was not previously available. Amplification rate will become an increasingly important stat as the season progresses.
Locally on `2024mabos`.
> Add net total game pieces COPR, add amplification rate COPR

- src/backend/tasks_io/datafeeds/datafeed_fms_api.py
- src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_match_parser.py
- src/backend/web/handlers/event.py
- src/backend/web/templates/bracket_partials/double_elim_bracket_table.html
FMS seems to be publishing unplayed finals matches with the placeholder teams now (when teamNumber would be None previously).
So now, filter those out
Two currently broken events: 
`2024vafal`
Prod:
Local:
`2024nytr`
Prod:
Local:
> Work around matches with scheduled teams [1, 2,3]

- src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_event_list_parser.py
Added `johnson` and `milstein` to the event code exception list, matching the rest of the 2024 championship divisions.
Makes division names and codes consistent with each other and previous years
Tested in local instance of TBA by syncing with frc-events API and checking division names
> Fix event names for 2024 cmp divisions

- src/tasks_io.yaml
Tasks are timing out, bumping to F2 temporarily for champs
> Bump tasks-io instance to F2

- src/backend/common/helpers/score_breakdown_keys.py
Add missing `autoLineRobot1` field to 2024 score breakdown keys to fix the write API.
I was updating Cheesy Arena for 2024 and ran into this error while publishing match results:
```
{
"Error": "Invalid score breakdown fields for 2024: ['autoLineRobot1']. Valid keys are: ['adjustPoints', 'autoAmpNoteCount', 'autoAmpNotePoints', 'autoLeavePoints', 'autoLineRobot2', 'autoLineRobot3', 'autoPoints', 'autoSpeakerNoteCount', 'autoSpeakerNotePoints', 'autoTotalNotePoints', 'coopNotePlayed', 'coopertitionCriteriaMet', 'endGameHarmonyPoints', 'endGameNoteInTrapPoints', 'endGameOnStagePoints', 'endGameParkPoints', 'endGameRobot1', 'endGameRobot2', 'endGameRobot3', 'endGameSpotLightBonusPoints', 'endGameTotalStagePoints', 'ensembleBonusAchieved', 'foulCount', 'foulPoints', 'g206Penalty', …
```
> Add missing autoLineRobot1 field to 2024 score breakdown keys to fix the write API.

- src/backend/api/handlers/helpers/add_alliance_status.py
- src/backend/api/handlers/helpers/tests/add_alliance_status_test.py
- src/backend/common/consts/event_type.py
- src/backend/common/helpers/alliance_helper.py
- src/backend/common/helpers/event_team_status_helper.py
- src/backend/common/helpers/tests/alliance_helper_test.py
- src/backend/common/helpers/tests/event_team_status_helper_test.py
- src/backend/common/models/alliance.py
- src/backend/common/models/event_team_status.py
- src/backend/common/models/wlt.py
- src/backend/web/renderers/team_renderer.py
- src/backend/web/templates/team_details.html
This PR provides details about Alliance Selection and that Alliance's progression. 
I often find myself switching back and forth between event pages and alliance pages to determine an team's alliance, and find that the data should just be presented inline.
There seem to be no automated tests for the team renderer, so no automated tests were done. Manual tests were done with:
- District teams
- Regional teams
- Teams that were listed as backups, both in the backup field as well as a fake third pick
- Events that have specialized alliance names
> Add alliance details to team detail page

- src/backend/web/static/css/less_css/less/tba/tba_base.less
Properly centers the icon on the favorite button using flexbox.
It is currently uncentered on Safari Mobile.
> Fix favorite icon centering

- src/api.yaml
- src/tasks_cpu.yaml
- src/tasks_io.yaml
- src/web.yaml
App engine instances already handle timeouts in a cleaner way
> Disable gunicorn timeouts (experimental)

- src/backend/api/api_trusted_parsers/json_event_info_parser.py
- src/backend/api/handlers/tests/update_event_info_test.py
This allows requests to the write API to provide dates for webcasts.
Note: 
* unsure what documentation updates are necessary. The `webcasts` field was not fully described in the API docs to begin with.
* also unsure what validation is necessary here. Suggestions do not appear to perform any validation on the dates either.
Webcast suggestions can provide the `date` field, but write API requests cannot.
Local testing through write API, both with `url` and `type`+`channel` payloads.
> Allow passing webcast `date` field to trusted API

- src/backend/web/static/swagger/api_v3.json
- Adds score breakdown 2024
- Links score breakdown objects to score_breakdown field
- Adds null to possible values of fields that may be null
Code generators that use the spec generate incorrect types and leads to a lot of headache.
I don't know how to test this
> Add proper nullables, add score breakdown 2024 to API V3 Spec

- pwa/.eslintrc.cjs
- pwa/app/components/tba/matchResultsTable.tsx
- pwa/app/lib/utils.ts
- pwa/app/routes/event.$eventKey.tsx
- pwa/tailwind.config.ts
Adds new tailwind-based match table. Misses a lot of edge cases (e.g. round robins) but this gets the core UI implemented.
> Add match table component

- src/backend/web/static/swagger/api_v3.json
https://editor.swagger.io/ got angry with me about some invalid and duplicate properties. this fixes those errors. the generated typescript interface does not change (I regenerated it and there was no change)
> Fix openapi validation errors

- src/backend/api/api_trusted_parsers/json_matches_parser.py
- src/backend/common/helpers/tests/matchstats_helper_test.py
For some reason linting was failing? Not sure. `flake8` is also failing:
> Fix py3 formatting

- src/backend/web/static/css/less_css/less/tba/tba_api.less
- src/backend/web/static/css/less_css/tba_style.main.less
This has driven me crazy for years
> Fix white-on-white text in API docs for version numbers

- pwa/app/api/v3.ts
- src/backend/api/handlers/insights.py
- src/backend/api/main.py
- src/backend/common/helpers/insights_helper.py
- src/backend/common/models/insight.py
- src/backend/common/queries/dict_converters/insight_converter.py
- src/backend/common/queries/insight_query.py
- src/backend/web/static/swagger/api_v3.json
Upgrading the old insights felt like too brittle of a task, so I felt the best option was to create a couple of new insights that are guaranteed to be typed correctly. I chose `n=25` arbitrarily, this can be adjusted.
Screenshot with a limited number of local events:
> Add leaderboard insights to db && add insights API

- src/backend/common/models/media.py
- src/backend/common/queries/dict_converters/media_converter.py
Example old response:
```json
[
{
"details": {},
"direct_url": "https://i.imgur.com/BL6n8hLh.jpg",
"foreign_key": "BL6n8hL",
"preferred": false,
"type": "imgur",
"view_url": "https://imgur.com/BL6n8hL"
}
]
```
`https://i.imgur.com/BL6n8hLh.jpg` will resolve when displayed with `<img src="https://i.imgur.com/BL6n8hLh.jpg" />`. But the same URL 404s when viewed in the URL of the browser. Presumably something has changed routing-wise on imgur's end since this was implemented.
This causes a lot of frustration for users as the typical "right click to view image" just yields a 404.
> Change imgur direct url to no longer use h.jpg suffix, since that seems to 404 when outside of <img> tags

- src/backend/common/helpers/insights_helper.py
- src/backend/common/models/insight.py
yes this does create an all time highest match score for year=0, which i think is acceptable given how often i hear it as a trivia question:
(above data obviously small sample size of local events)
> Add highest clean & combined score per year leaderboard

- pwa/app/routes/insights.($year).tsx
not sure if the tooltip should have all teams or just the teams that are cut off. i went with all of them in case anyone wants to copy paste a full list its a bit easier?
> [pwa] minor styling on insights page

- pwa/.eslintrc.cjs
- pwa/package-lock.json
- pwa/package.json
- pwa/server.js
Issue: https://github.com/remix-run/remix/issues/9353
This will start becoming an issue with service workers / etc that we don't want cached indefinitely.
Used `eject-ras` [here](https://github.com/kiliman/rmx-cli#-eject-ras), with some additional changes.
Before:
After:
> [PWA] Custom express server configuration

- src/backend/common/models/event.py
- src/backend/common/models/tests/event_test.py
There's a small chance this breaks some really old events, but we will watch out for those and add them to unit tests.
This fixes gmaps links for events like https://www.thebluealliance.com/event/2024cabe
Maps link before: http://maps.google.com/maps?q=1980%20Allston%20Way
Maps link after: http://maps.google.com/maps?q=Berkeley%20High%20School%0A1980%20Allston%20Way%0ABerkeley%2C%20CA%2C%20USA
> Include venue and location in venue_address_safe

- pwa/app/api/v3.ts
- pwa/app/routes/event.$eventKey.tsx
- src/backend/web/static/swagger/api_v3.json
Some event details (e.g. rankings) can be null
e.g.
https://www.thebluealliance.com/api/v3/event/2024xxcha/rankings
```
null
```
vs.
https://www.thebluealliance.com/api/v3/event/2024cc/rankings
```
{
"extra_stats_info": [],
"rankings": [],
"sort_order_info": [
{
"name": "Ranking Score",
"precision": 2
},
{
"name": "Avg Coop",
"precision": 2
},
{
"name": "Avg Match",
"precision": 2
},
{
"name": "Avg Auto",
"precision": 2
},
{
"name": "Avg Stage",
"precision": 2
}
]
}
```
> Fix nullable event details

- pwa/app/api/v3.ts
- pwa/app/components/tba/matchResultsTable.tsx
- pwa/app/components/tba/teamEventAppearance.tsx
- pwa/app/routes/team.$teamNumber.tsx
- src/backend/web/static/swagger/api_v3.json
Statuses may be null for future events. Currently, `2024cc` is the best example of this.
<details>
</details>
Few known issues here, like quals still being in round 1, not displaying awards yet, etc, but its progress
> [PWA] Add basic event appearance to team page. Fix team-event-status nullability

- pwa/app/lib/api/EventType.ts
- pwa/app/lib/matchUtils.ts
- pwa/app/lib/utils.ts
- pwa/app/routes/team.$teamNumber.tsx
I plan to add to this in the future, with things like award count, playoff record, qual record, etc (which will be expandable and hidden by default).
Also need to figure out a better way to center shorter blocks like 368s.
<details>
</details>
> [PWA] Add stats block to team pages

- pwa/app/routes/insights.($year).tsx
<details>
<summary>Details</summary>
</details>
Moved the button up top and much smaller, adjusted some whitespace
> [pwa] Adjust insight leaderboard table styling

- pwa/app/lib/matchUtils.ts
- pwa/app/lib/utils.ts
- pwa/app/routes/team.$teamNumber.tsx
I expect in the future to add a toggle to include/exclude offseason data on the left side. For now its just official data (awards / matches / high score).
<details>
</details>
> [PWA] Add expandable team annual stats section

- .github/dependabot.yml
removes need for #6336 and #6338 in the future
> Link grouped pwa dependencies in dependabot

- src/backend/common/helpers/insights_helper.py
- src/backend/common/models/insight.py
Not extremely useful but I thought it'd be fun to see results.
<details>
<summary>Details</summary>
Overall:
Yearly:
</details>
> Add most unique teams played with/against insight

- ops/dev/vagrant/bootstrap-dev-container.sh
Fixes `ModuleNotFoundError: No module named 'pip._internal.cli.main'`
> Fix dev container

- ops/standalone/cron-skeleton.yaml
- src/cron.yaml
Sets notification (cron) tasks to 08:00 AM US Pacific Time (America/Los_Angeles).
Especially during off-seasons, and absent implementation of #1850, too many events submit webcasts at the last second, or day-of the event. This is especially true for Youtube live events that are not set up in advance, and compounded by the different channel per day required for YouTube.
The current cron time of 12:00 Pacific (3PM Eastern) leaves many events without a webcast listing for much of their competition day in many cases. My moving the suggestions nag post up a few hours, more mods will have an opportunity to see it earlier, enabling more paeople to view the streams. 8:00 AM Pacific was chosen as to try to avoid mods in the Pacific TZ to silence mod channel notifications in Slack because of an …
> Update Slack `nag-bot` notifications 4 hours earlier

- pwa/app/api/v3.ts
- src/backend/api/handlers/team.py
- src/backend/api/handlers/tests/team_test.py
- src/backend/api/main.py
- src/backend/common/models/history.py
- src/backend/web/static/swagger/api_v3.json
I'd like to add a total match record here but I'm not sure the best way to do that. Typically for WLT we just iterate over the matches but that seems highly dumb here. Likely best to do some sort of db count/groupby? But I don't know how.
I don't know why regenerating the api moved some types around but whatever.
> Create history API endpoint

- src/backend/web/static/javascript/tba_js/eventwizard_apiwrite.js
It seems like FMS Schedule Reports now have the match time as actual "date" objects in excel (previously it was just the string of the text)
This means we see data like:
With this diff, we get the correct version:
> Fix eventwizard parsing of schedule times

- src/backend/api/handlers/decorators.py
- src/backend/web/static/javascript/tba_js/eventwizard.js
- src/backend/web/static/javascript/tba_js/eventwizard_apiwrite.js
This was still calling APIv2 (!!!!!) and apparently we missed migrating it.
This diff will:
- call APIv3 instead
-  allow write endpoint API keys to use the read API
- support rankings
Rankings parsing:
Rankings rendering:
> Call APIv3 from eventwizard, support 2024 rankings

- pwa/app/components/tba/teamRobotPicsCarousel.tsx
- pwa/app/routes/event.$eventKey.tsx
Thins border and moves buttons closer together
The border is currently obnoxiously large (way larger than any other surface in the UI). I also changed the color to be the same as other borders, and moved buttons closer together (looks better to me).
Before:
After:
> [PWA] Clean up carousel styles

- pwa/app/routes/team.$teamNumber.($year).tsx
- pwa/app/routes/team.$teamNumber.history.tsx
* Fixed award history showing `Finalist ()` sometimes due to awardee being empty string instead of null
* Fixed history year selector being inverted
* Fixed offseasons missing on event sidebar due to empty string for short_name instead of null
> [pwa] various minor ui fixes

- .github/dependabot.yml
This puts them in here https://github.com/the-blue-alliance/the-blue-alliance/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen+label%3APWA
> Add PWA label to dependabot PRs in /pwa

- ops/dev/docker/Dockerfile
github copilot suggested this
removed distutils because of this error
```
#13 1.545 Fetched 15.3 MB in 1s (10.9 MB/s)
#13 1.545 Reading package lists...
#13 2.278 Reading package lists...
#13 2.981 Building dependency tree...
#13 3.129 Reading state information...
#13 3.176 E: Unable to locate package python3.12-distutils
#13 3.176 E: Couldn't find any package by glob 'python3.12-distutils'
#13 3.176 E: Couldn't find any package by regex 'python3.12-distutils'
#13 ERROR: process "/bin/sh -c apt-get update && apt-get install -y     \"$PYTHON_VERSION\"     \"$PYTHON_VERSION-venv\"     \"$PYTHON_VERSION-dev\"     \"$PYTHON_VERSION-distutils\"     python3-pip" did not complete successfully: exit code: 100
------
> [ 7/26] RUN apt-get update && apt-get install -y     "python3.12" …
```
> fix ops test failure by removing conflicting packages

- .github/dependabot.yml
should help prevent this in the future
> Add radix-ui group to dependabot

- pwa/app/api/v3.ts
- src/backend/api/handlers/district.py
- src/backend/api/handlers/tests/district_test.py
- src/backend/api/main.py
- src/backend/common/consts/renamed_districts.py
- src/backend/common/queries/district_query.py
- src/backend/web/static/swagger/api_v3.json
Currently the only way to get history for a district is to hit `/api/v3/districts/<year>` for each year 2009 to `current_year` which is pretty annoying. This endpoint can help reduce client wait times.
<details>
</details>
This can be used to implement districts in `/local/bootstrap` once it lands:
1. Check if the `/local/bootstrap` input key is solely alphabetical characters (eg `ne`).
2. If so, assume its a district (since it won't be of form `frc1234` or `2024abcd`).
3. Get district history
> Add /api/v3/district/<abbr>/history endpoint

- pwa/app/components/tba/links.tsx
- pwa/app/routes/insights.($year).tsx
- links to team history on overall insights
- replaces `-` with `, ` on notables
> [pwa] insights styling improvements

- src/backend/common/helpers/insights_helper.py
We should deprecate tba_video everywhere, we have it all transferred to youtube anyways.
> Remove tba_video from insights

- pwa/app/api/v3.ts
- src/backend/api/handlers/district.py
- src/backend/api/handlers/tests/district_test.py
- src/backend/api/main.py
- src/backend/web/static/swagger/api_v3.json
Currently the only way to get these is making a per-event request which is inefficient, especially at the size of something like Michigan.
Also renames getDistrict to getDistrictHistory, and clarifies that district rankings are nullable. (Example: `2025ne` rankings before 2025 has begun: https://www.thebluealliance.com/api/v3/district/2025ne/rankings)
> Add district/key/awards endpoint

- pwa/app/api/v3.ts
- pwa/app/lib/awardUtils.ts
- pwa/app/routes/events.($year).tsx
- pwa/app/routes/team.$teamNumber.($year).tsx
- pwa/generate-api.sh
- pwa/package.json
One problem we have is that we have to cast `event_type as EventType` in PWA, because eslint gets upset that the enum doesn't completely cover all `number` values (even though we know it should from the API).
Unfortunately every method of named, numeric enums in OpenAPI is janky and does not create a great developer experience.
This introduces a bash script that should be run to regenerate the API which:
1. Runs `oazapfts`
2. Replaces `award_type: number` with `award_type: AwardType`
3. Replaces `event_type: number` with `event_type: EventType`
4. Adds imports to the top of the file
5. Formats the file
<details>
<summary>Alternative solution</summary>
We can add this to the schema:
```json
{
// ...
"schemas": {
"EventType": {
"type": "integer",
"description": "Enumeration of event …
```
> Overwrite event_type/award_type types in generated api

- src/backend/common/frc_api/frc_api.py
- src/backend/common/frc_api/tests/frcapi_test.py
- src/backend/common/urlfetch.py
- src/backend/tasks_io/datafeeds/datafeed_fms_api.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_awards_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_distrct_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_alliances_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_matches_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_rankings_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_team_avatars_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_teams_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_teams_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_test.py
This setup is a vestige of when we originally tried to run things without the GAE standard library and used vanilla `requests`. However, since we have this available, we should use the async interface, which should allow the datafeed service to run more cheaply.
> Move FRC API calls to async NDB urlfetch

- src/backend/common/models/api_auth_access.py
- src/backend/web/handlers/admin/api_auth.py
- src/backend/web/templates/admin/api_add_auth.html
- src/backend/web/templates/admin/api_edit_auth.html
- src/backend/web/templates/admin/partials/api_write_table.html
This will make it easier for us to work with webcast managers for a district -- we'll resolve the list of events for the district at key creation/edit time, and include them in the valid events
> Support issuing write keys for an entire district

- src/backend/web/handlers/admin/api_auth.py
- src/backend/web/handlers/admin/blueprint.py
- src/backend/web/handlers/admin/users.py
- src/backend/web/templates/admin/api_manage_auth.html
- src/backend/web/templates/admin/user_details.html
This diff will simplify what has become a very expensive query...
We will:
- show issued API keys on the admin user view
- split the main "manage" page into separate ones for read/write/admin keys (so only "read" will remain super expensive, but we use that less)
- hide expired keys by default
> Improve querying of api keys in admin panel

- src/backend/tasks_io/datafeeds/datafeed_fms_api.py
- src/backend/tasks_io/datafeeds/parsers/fms_api/tests/test_fms_api_match_tiebreaker.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_awards_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_distrct_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_alliances_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_matches_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_rankings_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_team_avatars_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_teams_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_teams_test.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_test.py
- src/backend/tasks_io/handlers/frc_api.py
- src/backend/tasks_io/handlers/tests/district_rankings_calc_test.py
- src/backend/tasks_io/handlers/tests/frc_api_awards_test.py
- src/backend/tasks_io/handlers/tests/frc_api_event_alliances_test.py
- src/backend/tasks_io/handlers/tests/frc_api_event_details_test.py
- src/backend/tasks_io/handlers/tests/frc_api_event_district_test.py
- src/backend/tasks_io/handlers/tests/frc_api_event_list_test.py
- src/backend/tasks_io/handlers/tests/frc_api_event_matches_test.py
- src/backend/tasks_io/handlers/tests/frc_api_event_rankings_test.py
- src/backend/tasks_io/handlers/tests/frc_api_teams_test.py
This pushes the async-ification up one layer from 18fd3d6530aea860164f923212ee9b44367f9ac3, where we can now await requests in parallel for those endpoints which end up making multiple API calls
> Asyncify FRC API Datafeed

- src/backend/tasks_io/handlers/tasks.py
- src/backend/tasks_io/handlers/tests/tasks_test.py
- src/cron.yaml
This will prevent old keys for piling up and polluting the admin view (and if they're for old events, we don't need them anyway)
> Add cronjob to expire old API keys

- .github/workflows/pull_request.yml
This is blocking https://github.com/the-blue-alliance/the-blue-alliance/pull/6553, which requires at least 3.9 in the new release
> run coverage workflow on python 3.12

- src/backend/tasks_io/datafeeds/datafeed_fms_api.py
Not something we generally see, but we were error-ing when fetching a team via the `/backend-tasks/get/team_avatar/{team_key}` endpoint to get an avatar when the team did not have an avatar uploaded. This was just because our object was `None` and we couldn't unpack a `None` as a tuple
> Fix 500 when fetching team without avatar

- src/backend/web/handlers/admin/team.py
- src/backend/web/templates/admin/team_details.html
The current view is a bit confusing (because social media links show under "no year")
This diff will separate them out into their own listing
> clarify add/remove team social media on admin panel

- src/backend/common/helpers/event_short_name_helper.py
- src/backend/common/sitevars/turbo_mode.py
- src/backend/tasks_io/datafeeds/parsers/fms_api/tests/fms_api_team_avatar_parser_test.py
- src/backend/tasks_io/handlers/frc_api.py
- src/backend/tasks_io/handlers/math.py
- src/cron.yaml
This is an attempt to optimize usage/costs a bit.
We are currently slamming app engine every day, and it ends up scaling up to almost 40 instances at peak
And the initial requests for new instances are always slow:
For example, a trace like this:
We end up waiting almost 5 minutes before we actually get to executing the requests...
So my theory is - if we splay the daily work out over a few hours, we can run steady with a handful of warm instances, rather than big spikes. And we can maybe smooth out the cost cuve too (if we don't end up paying for dead instance time)
> Splay daily event/team datafeed requests

- src/backend/common/frc_api/frc_api.py
- src/backend/tasks_io/datafeeds/datafeed_fms_api.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_matches_test.py
FIRST has added back the hybrid schedule endpoint for us in v3 (same schema as the original v2 version).
Update the datafeed to call that instead, which will cut the number of API calls we make for matches by 1/3.
We need to keep the merging logic around for running the simulator against old events, but at least it's now not on the critical path anymore
> Fetch matches using v3 hybrid schedule

- src/backend/common/helpers/insights_helper.py
- src/backend/common/models/insight.py
Adds event played at insight. Only counts events the team played a match in. Tested locally.
Bugfix for unique teams played with/against to no longer make this an overall leaderboard. If you were to play with teams `{1, 2, 3}` in years 1 and 2, it would count you as having played with 6 overall unique teams, which isn't correct. This just makes it a single year only insight. **The existing overall insight will need to be manually deleted from the db.**
> Add events played at insight

- pwa/app/entry.server.tsx
- pwa/vite.config.ts
https://remix.run/docs/en/2.13.1/start/future-flags#v3_singleFetch
Required for RR7 upgrade.
>With this flag, Remix uses a single fetch for data requests during client-side navigations. This simplifies data loading by treating data requests the same as document requests, eliminating the need to handle headers and caching differently. For advanced use cases, you can still opt into fine-grained revalidations
> Enable remix.future.v3_singleFetch

- pwa/app/api/v3.ts
- pwa/app/components/tba/matchResultsTable.tsx
- pwa/app/components/tba/rpDot.tsx
- pwa/app/components/tba/teamEventAppearance.tsx
- pwa/app/lib/rankingPoints.test.ts
- pwa/app/lib/rankingPoints.ts
- src/backend/web/static/swagger/api_v3.json
<details>
</details>
---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/the-blue-alliance/the-blue-alliance/pull/6950).
* #7006
* __->__ #6950
> [pwa] add RP dots, team highlights to match table

- src/backend/tasks_io/datafeeds/datafeed_fms_api.py
- src/backend/tasks_io/handlers/frc_api.py
- src/backend/tasks_io/handlers/tests/frc_api_teams_test.py
Two parts to this pull request -
First - if we do a `get_team_details` and we don't get a team back for a particular year our parsing is failing. This seems like an oddity with how we're doing returns from our parsers (see also https://github.com/the-blue-alliance/the-blue-alliance/pull/6916 - which that parsing seems more right). This fixes the API return from our parsers in the case of an empty array.
The second part of this PR is to clean up `DistrictTeam`/`EventTeam` for teams that do not exist. Currently the code to cleanup these dangling teams is behind a check to make sure we get a `Team` model back from the API. In the case that we stop getting a Team back from the API, existing `DistrictTeam` and `EventTeam` models will not be cleaned up.
This data deletion *feels* safe in this …
> Do cleanup for district keys and event keys for teams with empty responses

- src/backend/web/static/swagger/api_v3.json
Update swagger specs:
* Set `playoff_average` to use the `double` format
* Set `sort_orders` to use the `float` format
I've been working on updating the the API models for the Android app, and ran into a few unexpected types in the team event status models. I'm sure I'll find more as I keep going, but this was a good starting point.
I ran the JSON file through https://editor.swagger.io/ and it checked out, fields now display as expected.
This could be a breaking change if others are generating API models based on the Swagger specs, but the newly specific types align with the underlying Python types. The actual behavior of these APIs is also not changing.
> Update swagger types for team event status objects

- pwa/app/routes/event.$eventKey.tsx
It is currently not possible to get to a team page from a 2025 event (that hasn't been played). This fixes that
> Add link to team page from team@event credenza on event pages

- pwa/app/api/v3.ts
- pwa/app/lib/rankingPoints.ts
- pwa/app/root.tsx
- src/backend/web/static/swagger/api_v3.json
This fixes three issues I found.
1. TeamEventStatus did not properly have several fields set to nullable.
2. Going to `/team/<num>/2021` for teams that attended 2021 Chezy would 500. This is because it was attempting to read `RANKING_POINT_LABELS[event.year]` which did not have a value for `event.year == 2021`. It attempted to read this because the `score_breakdown` field was properly set by Cheesy Arena.
3. The server 500ing did not always show the actual error. Now, it will log it to console.
> Fix team event status missing nullables. Fix [PWA] 2021 missing RP descriptors

- src/backend/common/models/notifications/requests/fcm_request.py
- src/backend/common/models/notifications/requests/tests/fcm_request_test.py
We're getting 404's from using the deprecated batch APIs for FCM (see https://github.com/firebase/firebase-admin-python/issues/849)
This PR updates our calls to the deprecated `send_multicast` to calling `send_each_for_multicast`, which should be a drop in replacement.
> Replace deprecated FCM send

- src/backend/web/templates/match_details.html
- src/backend/web/templates/match_partials/match_breakdown/match_breakdown_2025.html
First pass at this does not show scoring locations (which is less than ideal), but this will fix our match details pages 500-ing
This also adds `ignore missing` for the template include to prevent our pages from 500-ing if we haven't added support for the match breakdown yet https://jinja.palletsprojects.com/en/stable/templates/#include
> Adds 2025 match breakdown for scoring

- src/backend/web/static/swagger/api_trusted_v1.json
I [realized today](https://www.chiefdelphi.com/t/tba-unable-to-generate-event-write-tokens-or-email-support/484964/17?u=plnyyanks) we were missing this :stuck_out_tongue:
> [apidocs] Include reference of remap_teams in trusted event info

- src/backend/common/cache_clearing/get_affected_queries.py
- src/backend/common/consts/district_point_values.py
- src/backend/common/helpers/district_helper.py
- src/backend/common/helpers/regional_champs_pool_helper.py
- src/backend/common/helpers/season_helper.py
- src/backend/common/manipulators/regional_champs_pool_manipulator.py
- src/backend/common/manipulators/regional_pool_team_manipulator.py
- src/backend/common/models/event.py
- src/backend/common/models/event_details.py
- src/backend/common/models/keys.py
- src/backend/common/models/regional_champs_pool.py
- src/backend/common/models/regional_pool_advancement.py
- src/backend/common/models/regional_pool_ranking.py
- src/backend/common/models/regional_pool_team.py
- src/backend/common/queries/team_query.py
- src/backend/tasks_io/handlers/frc_api.py
- src/backend/tasks_io/handlers/math.py
- src/backend/tasks_io/handlers/tests/district_points_calc_test.py
- src/backend/tasks_io/templates/datafeeds/usfirst_event_details_get.html
- src/backend/tasks_io/templates/datafeeds/usfirst_team_details_get.html
- src/backend/web/handlers/admin/blueprint.py
- src/backend/web/handlers/admin/districts.py
- src/backend/web/handlers/admin/team.py
- src/backend/web/templates/admin/district_details.html
- src/backend/web/templates/admin/district_list.html
- src/backend/web/templates/admin/event_details.html
- src/backend/web/templates/admin/team_details.html
This is new for this year!
We now need to track the leaderboard in the "regional pool" (where points are similar, but not exactly equivalent to district points). 
We will implement this with an analogue of the `DistrictTeam` model for regional teams.
This PR contains a few commits:
- introduce the models / manipulator plumbing
- update the API datafeed to write a `RegionalPoolTeam` when we do not have a district team (we are assuming that event team not in a district is a regional team) + display them naively in the admin panel / datafeed output
- the annual rankings are stored in the `RegionalPool` model 
- update the "calculate district points" hooks to trigger regional points for relevant events
Still TODO:
- implement the differing tiebreakers
- add API endpoint for regional pool …
> Implement 2025+ Regional to CMP Advancement

- src/backend/common/consts/client_type.py
- src/backend/common/helpers/tbans_helper.py
- src/backend/common/helpers/tests/tbans_helper_test.py
- src/backend/common/models/notifications/requests/fcm_request.py
Android notifications are too large currently by passing in the entire webhook data payload. This removes the legacy data payload flow (and thus sending to Android devices for now)
Mostly a revert of https://github.com/the-blue-alliance/the-blue-alliance/pull/4311
Tests will fail to begin with, I didn't get all the removal of the expected calls with the True/False flag for legacy payloads I imagine
> Remove sending to Android via legacy data payload flow

- ops/dev/vagrant/dev_appserver.sh
Just bumping this - the `python312` seems like it picks up the proper Python runtime now
> Update runtime version to python312 in dev_appserver launch

- docs/Maintainers/New-Season.md
- src/backend/web/templates/avatars.html
We really ought to have some year <-> game name dictionary somewhere to do this dynamically. But until then - adds the few missing game names from recent years and adds docs letting people what to do for avatars during the build season.
> Add game name information to avatars page. Add avatars docs to season runbook

- docs/common/Current-User.md
- src/backend/common/helpers/mytba.py
- src/backend/common/models/keys.py
- src/backend/web/handlers/account.py
- src/backend/web/handlers/tests/account_overview_test.py
- src/backend/web/handlers/tests/account_test.py
- src/backend/web/templates/mytba.html
- src/backend/web/templates/mytba_eventteam.html
- src/backend/web/templates/mytba_partials/my_eventteams.html
<details>
</details>
You can only navigate to this via url currently, it's not linked in the UI. The idea here is that you can keep a running track of all the events you have personally competed at, and view stats about your teams. This is implemented by favoriting EventTeam models.
This is hidden by default because it's largely a proof of concept and something I'd rather only implement once between py3 vs PWA.
> Add ability to favorite eventteams

- src/backend/common/models/match.py
- src/backend/common/models/tests/match_test.py
- src/backend/web/static/swagger/api_v3.json
Also adds tests for some of the match breakdown logic
> Adds `tba_botRowCount`, `tba_midRowCount`, `tba_topRowCount` to `autoReef` and `teleopReef` for `red`/`blue` 2025 match breakdowns

- src/backend/web/handlers/admin/blueprint.py
- src/backend/web/handlers/admin/sitevars.py
- src/backend/web/templates/admin/sitevar_create.html
Sitevar creation via the admin panel wasn't working - probably just due to something with the upgrade to py3, since it was still even missing a csrf token. This PR updates that flow to work again.
> Fix broken sitevar creation flow

- src/backend/common/helpers/deferred.py
- src/backend/common/helpers/tests/deferred_test.py
Fixes a bug from https://github.com/the-blue-alliance/the-blue-alliance/pull/7121 that doesn't really repro in tests.
The GAE middleware will slurp up anything with the default deferred URL, so if we want to make requests using a custom payload format, we need to make sure it's run on a distinct URL that can trigger our custom handler.
https://github.com/GoogleCloudPlatform/appengine-python-standard/blob/99f33792c00ecee37ef081d41582c7c4eaa673aa/src/google/appengine/runtime/middlewares.py#L381-L397
Since we already accept a regex:
https://github.com/the-blue-alliance/the-blue-alliance/blob/f05a3db0b0cc05000dae6f8cab0b04158cddc2d1/src/backend/common/deferred/defer_handler.py#L37-L41
anything should do
> Run safe deferred on own URL

- src/backend/common/helpers/tests/tbans_helper_test.py
Just an oversight from https://github.com/the-blue-alliance/the-blue-alliance/commit/bcb8f92ae2b950dac33b71e066802b28dbb23ff7#diff-0ee31cd80d94496fba41420991ecb2d315e73a716cf51d2400bc141ec9251918R180 - the call should've gotten moved before the patch and the call inside the patch should've gotten removed.
> Remove double call in alliance_selection test

- src/backend/common/tasklets.py
- src/backend/tasks_io/handlers/frc_api.py
doh
```
AttributeError: type object 'RegionalPoolTeam' has no attribute 'advancemnet'
at ._set_attributes ( /layers/google.python.pip/pip/lib/python3.12/site-packages/google/appengine/ext/ndb/model.py:3078 )
at .__init__ ( /layers/google.python.pip/pip/lib/python3.12/site-packages/google/appengine/ext/ndb/model.py:3026 )
at .__init__ ( /workspace/backend/common/models/cached_model.py:41 )
at .__init__ ( /workspace/backend/common/models/regional_pool_team.py:27 )
at .event_details ( /workspace/backend/tasks_io/handlers/frc_api.py:404 )
at .dispatch_request ( /layers/google.python.pip/pip/lib/python3.12/site-packages/flask/app.py:902 )
at .full_dispatch_request ( /layers/google.python.pip/pip/lib/python3.12/site-packages/flask/app.py:917 )
at .full_dispatch_request ( …
```
> Fix Invalid RegionalPoolTeam property

- src/frontend/eventwizard/components/infoTab/AddRemoveWebcast.js
- src/frontend/eventwizard/components/infoTab/EventInfoTab.js
- src/frontend/eventwizard/components/infoTab/WebcastItem.js
- src/frontend/eventwizard/constants/ApiWebcast.js
This PR adds an optional field to the event info tab of eventwizard2 to allow for specifying a date for a webcast.
This change is to support a subset of FIRST in Michigan events, who have streams which are only active on certain days. This functionality was already available in the trusted API, but not surfaced in the event wizard.
In local environment, adding and removing webcasts via the event wizard both with and without dates, confirming changes are as expected by using the read API. Local environment is set up using the docker compose method.
Node tests and lints have been run locally and passed.
> Add webcast date field to eventwizard2 UI

- src/backend/common/helpers/matchstats_helper.py
https://www.chiefdelphi.com/t/2025-high-scores/492943/14?u=jtrv
The `tba_<level>RowCount` teleop fields are based on the state at the end of the match. Here is an example score breakdown from `2025isde1_f1m1`:
```
'red': {'adjustPoints': 0,
'algaePoints': 12,
'autoBonusAchieved': False,
'autoCoralCount': 6,
'autoCoralPoints': 42,
'autoLineRobot1': 'Yes',
'autoLineRobot2': 'Yes',
'autoLineRobot3': 'Yes',
'autoMobilityPoints': 9,
'autoPoints': 51,
'autoReef': {'botRow': {'nodeA': False,
'nodeB': False,
'nodeC': False,
'nodeD': False,
'nodeE': False,
'nodeF': False,
'nodeG': False,
'nodeH': False,
'nodeI': False,
'nodeJ': False,
'nodeK': False,
'nodeL': False},
'midRow': {'nodeA': False,
'nodeB': False,
'nodeC': False,
'nodeD': False,
'nodeE': False,
'nodeF': False,
'nodeG': False,
'nodeH': …
```
> Fix cOPRs for L2-L4 coral

- pwa/app/components/tba/allianceSelectionTable.tsx
Fixes issue #6378 
This PR addresses an issue where a RangeError (#6378): Invalid array length occurs when rendering table headers based on the allianceSize. The error arises if allianceSize is not defined or less than 2. The implementation now includes validation to ensure allianceSize is a valid positive integer before creating the array, preventing the error from occurring.
> Fixed #6378

- src/backend/web/templates/match_partials/match_breakdown/match_breakdown_2025.html
Fixes https://github.com/the-blue-alliance/the-blue-alliance/issues/7155
> Show correct foul points for red/blue for 2025 breakdowns

- pwa/public/robots.txt
We're getting a lot of 500s on the backend from robots crawling the PWA pages. Going to add a `robots.txt` for now in order to disallow crawling these pages until we've got them fixed up.
> Add robots.txt to pwa

- src/backend/web/templates/match_partials/match_breakdown/match_breakdown_2025.html
> Fix coral and barge RP dots in 2025 match breakdowns overlapping

- docs/Deployment/GAE-Firebase-Setup.md
- src/backend/web/static/javascript/tba_js/tba_auth.js
- src/backend/web/static/javascript/tba_js/tba_firebase.js
- src/backend/web/static/javascript/tba_js/tba_keys_template.js
- src/backend/web/templates/account_login_required.html
- src/backend/web/templates/admin/base.html
- src/backend/web/templates/base.html
Figured out some of the wonkiness with getting Firebase Auth setup locally. The user emulator should work out of the box now.
Additionally - moves our Firebase performance call back to the standalone (for now) because our performance was only getting setup on our login page (where we pull in the Firebase JS). Reverts https://github.com/the-blue-alliance/the-blue-alliance/pull/3237
> Fix Firebase Auth setup to require less messing with locally

- .github/workflows/push.yml
- docs/Setup/Repo-Setup.md
Bumping the GitHub Actions to use Python 3.12 for deploys - should be alright, but we'll see
> Switch GH Actions to using Python 3.12 for setup

- ops/deploy/deploy_module.sh
- src/default.yaml
A few small app engine deployment fixes while I'm looking at them
> Move gcloud deploy off beta deploy. Add app_engine_apis flag to default.yaml

- src/backend/web/handlers/admin/blueprint.py
- src/backend/web/handlers/admin/cache.py
- src/backend/web/templates/admin/cached_query_detail.html
- src/backend/web/templates/admin/cached_query_info.html
API dictionaries fail to load with the current cache clearing system. This PR modifies the cache versions to allow for the dictionary cache key versions.
This also surfaces what the cached data is for introspection, and gives some detail about what keys to enter for the inputs when querying cache keys
> Allow for cache clearing to clear API dictionaries

- pwa/README.md
- pwa/app/components/tba/allianceSelectionTable.tsx
- pwa/app/routes/event.$eventKey.tsx
I think I bork'd this when merging https://github.com/the-blue-alliance/the-blue-alliance/pull/6623
This PR fixes the alliances table showing double headers, as well as only shows the alliances table if we have some non-empty alliances array
> Fix double alliances in alliances table. Only show alliances table if we have non-empty alliances

- src/backend/web/templates/admin/api_delete_auth.html
Got VERY scared when I clicked this button
> Change delete auth button to be named Delete Auth (not Delete Event)

- src/backend/common/models/regional_champs_pool.py
- src/backend/common/models/regional_pool_advancement.py
- src/backend/tasks_io/handlers/frc_api.py
This will set the "qualified for CMP" flag when we get a confirmed `EventTeam` back for a CMP division/finals event
> Calculate regional champs advancement in datafeed

- src/backend/common/queries/team_query.py
- src/backend/tasks_io/handlers/math.py
For the list of regional pool teams, store the keys, not the full team models (since I think this was too large).
Also filter out entries where the teams have no points.
Fixes https://github.com/the-blue-alliance/the-blue-alliance/issues/7220
> Reduce size of regional pool db quueries

- src/backend/common/helpers/district_helper.py
- src/backend/common/helpers/regional_champs_pool_helper.py
This will do the ones based on event points.
While investigating this, it actually looks like our district point tiebreakres have been wrong for ages (we look at highest _qual_ match, while the manual says _any_ match for like the last decade). I will clean this up separately (and also backport this named tuple type hinting setup to make it more robust as well)
> Implement basic regional advancement tiebreakers

- src/backend/common/helpers/district_helper.py
- src/backend/common/helpers/regional_champs_pool_helper.py
- src/backend/common/helpers/tests/district_helper_test.py
- src/backend/web/templates/admin/district_details.html
This updates district rankings to use a similar typing scheme as the regional one; which allows us to use a `NamedTuple` instead of direct indexing "magic" bits into a list.
This also cleans up a bug where we were tracking qual wins, instead of qual performance district points.
> More strongly type district ranking tiebreakers

- src/backend/common/helpers/district_helper.py
- src/backend/common/helpers/district_point_tiebreakers_sorting_helper.py
- src/backend/common/helpers/regional_champs_pool_helper.py
- src/backend/web/handlers/admin/event.py
- src/backend/web/handlers/event.py
- src/backend/web/templates/admin/event_details.html
This implements most of the sorting (and also makes sure the UI takes tiebreakers into account as well).
This still isn't perfect, because we are still looking at the highest _qual_ match as the bottom tiebreakers (instead of _all_ matches). But untangling this is going to be a bit tricky to do safely with historical data being written differently, so leave it for now.
> Implement sorting for regional champs pool

- src/backend/api/handlers/event.py
- src/backend/api/main.py
- src/backend/common/queries/dict_converters/event_details_converter.py
- src/backend/web/static/swagger/api_v3.json
This adds an API endpoint, shaped the same as the district point one, for regional CMP pool points. There is also a "hybrid" endpoint, for `advancement_points`, which will return either district points or the regional points, whichever is applicable for that event.
> Add APIv3 endpoint for regional champs pool points

- src/backend/common/manipulators/manipulator_base.py
- src/backend/web/handlers/admin/blueprint.py
- src/backend/web/handlers/admin/cache.py
- src/backend/web/templates/admin/event_details.html
- src/backend/web/templates/admin/match_details.html
- src/backend/web/templates/admin/team_details.html
This makes the "clear cache" button on the admin panel do something again :stuck_out_tongue: 
Mainly, it'll defer through the model manipulator to get the necessary affected DB queries and delete those
> Hook up 'clear cache' admin panel button

- subtrees/bootstrap/less/navs.less
Moves the bottom border to account for two lines. Uses line height x2 + a border.
The new "Champs Qual Points" tab spans two lines and the border doesn't like right (see #7225).
Locally.
> Add nav bar padding; Fixes #7225

- pwa/app/entry.client.tsx
- pwa/app/entry.server.tsx
Gives us some nice data on which functions are taking the longest to run, which we can use to improve performance once enough data comes in.
Followed these steps: https://docs.sentry.io/platforms/javascript/profiling/browser-profiling/
> [pwa] Enable Sentry profiling for code performance analysis

- pwa/app/routes/event.$eventKey.tsx
> [pwa] fix div escaping its parent

- pwa/app/lib/search/fuzzysortFilterer.ts
This improves the event search results by ordering more recent events first. A reminder that in fuzzysort, a 1.0 score is a perfect match, a 0.5 score is a good match, and a 0.0 score is no match.
Example from documentation: https://github.com/farzher/fuzzysort?tab=readme-ov-file#advanced-usage
Tested locally.
> [PWA] Improve event search results

- pwa/app/lib/matchUtils.ts
- pwa/app/routes/event.$eventKey.tsx
2025nysu insights tab is currently 500ing because its trying to get a high score for elim matches that haven't been played.
> [pwa] Fix 500 for schedule-released events insights tab

- pwa/app/components/ui/tabs.tsx
> [pwa] Add pointer cursor to clickable tabs

- pwa/app/components/tba/allianceSelectionTable.tsx
> [pwa] center table headers on alliance selection table

- pwa/app/lib/matchUtils.ts
- pwa/app/routes/event.$eventKey.tsx
The RP percentages are wrong because they include unplayed matches. This removes an unnecessary filter from high score calculations as well, now that we are filtering before the data reaches the component.
> [pwa] only include played matches on frontend insight tab

- pwa/app/routes/event.$eventKey.tsx
old events (pre RPs) 500 on the insights tab due to missing RP names
> [PWA] fix event/insights 500 on old, pre-RP events

- src/backend/common/logging.py
Tested this on a local instance and this fixed the threading errors. Should be good until we get a new version of Google Cloud Logging.
> Patch threading not to throw an error from upstream Google Cloud Logging exception

- src/backend/common/models/event.py
- src/backend/web/handlers/event.py
- src/backend/web/main.py
- src/backend/web/templates/event_details.html
This one is a little selfish, but getting links to event agendas is always kinda annoying. This adds a link to the event page for current + future events, and also adds `/event/<event key>/agenda` as a redirect helper.
> Add links to event public agendas

- src/backend/common/cache_clearing/get_affected_queries.py
- src/backend/common/cache_clearing/tests/database_cache_clearer_test.py
- src/backend/common/models/championship_qualification_method.py
- src/backend/common/queries/event_query.py
- src/backend/tasks_io/handlers/math.py
- src/backend/tasks_io/handlers/tests/regional_champs_pool_rankings_calc_test.py
This uses the presence of an `EventTeam` for a CMP event. I'd also like this to eventually link to which division, as well has provide a tooltip for how they qualified (by means of winning an event/award/etc)
> Populate Regional --> CMP Advancement Checks

- .github/dependabot.yml
Replaces remix-run group with react-router group
> Add react-router group to dependabot

- pwa/app/components/tba/teamAvatar.tsx
- pwa/app/components/tba/teamPageTeamInfo.tsx
- pwa/app/components/ui/avatar.tsx
- pwa/app/components/ui/dialog.tsx
- pwa/app/lib/utils.test.ts
- pwa/app/lib/utils.tsx
- pwa/app/routes/event.$eventKey.tsx
- pwa/package-lock.json
- pwa/package.json
This gets rid of the team-schedule popup for now. I believe a better UX is:
1. When clicking on a team in the teams tab, you are brought to the team page
2. When clicking on a team in the schedule tab, you are given a dialog of the team's schedule
This PR is a step towards that. Still need to implement the dialog on the schedule.
> [PWA] overhaul teams tab to add avatars and be more compact

- src/backend/common/cache_clearing/get_affected_queries.py
- src/backend/common/cache_clearing/tests/database_cache_clearer_test.py
- src/backend/common/models/regional_pool_advancement.py
- src/backend/common/queries/event_query.py
- src/backend/tasks_io/handlers/frc_api.py
- src/backend/tasks_io/handlers/math.py
- src/backend/tasks_io/handlers/tests/frc_api_event_details_test.py
- src/backend/tasks_io/handlers/tests/regional_champs_pool_rankings_calc_test.py
- src/backend/web/templates/admin/regional_champs_pool_list.html
We need to compute this entirely when we fetch team registration. We also need to store/update the event from which we're considering the team "qualified", so we can ignore updates to other events. That way we don't clobber the advancement after fetching teams for a regional.
> Fix Regional --> CMP Advancement Calculation

- src/backend/common/helpers/insights_helper_utils.py
- src/backend/common/helpers/insights_leaderboard_event_helper.py
- src/backend/common/helpers/insights_leaderboard_match_helper.py
- src/backend/common/helpers/insights_leaderboard_team_helper.py
- src/backend/common/helpers/insights_notable_helper.py
- src/backend/common/helpers/tests/insights_helper_utils_test.py
- src/backend/common/helpers/tests/insights_leaderboard_event_helper_test.py
- src/backend/common/helpers/tests/insights_leaderboard_match_helper_test.py
- src/backend/common/helpers/tests/insights_leaderboard_team_helper_test.py
- src/backend/common/helpers/tests/insights_notable_helper_test.py
- src/backend/tasks_cpu/handlers/insights.py
Previously leaderboard calculations would store all matches `len(valid_years)` times, since for each one it was calculating the given year and also overall. Now, overall is a separate year (0) and matches are retrieved via generator given a list of events, rather than stored in `arguments`.
> Fix leaderboards OOMing

- pwa/app/lib/utils.tsx
- pwa/app/root.tsx
- pwa/app/routes/event.$eventKey.tsx
- pwa/package-lock.json
- pwa/package.json
Adds client-side requests for data to the event page via react-query. The `shouldPreviewXYZ` fields are to minimize how often the UI "jumps" around when something is rendered. The only jumping that occurs as a result of this PR is offseason pages with awards (e.g. 2024cc), and the team count badge going from `-` to `40` (or whatever the team count is).
> [PWA] Add react query, client-side load awards

- src/backend/web/renderers/team_renderer.py
- src/backend/web/templates/team_history.html
- src/backend/web/templates/team_partials/team_info.html
This way, if a team is competing at multiple events, it's easier to see at a quick glance on the page
> Show pit location in team info pane

- src/backend/common/consts/nexus_match_status.py
- src/backend/common/helpers/firebase_pusher.py
- src/backend/common/helpers/tests/firebase_pusher_test.py
- src/backend/common/helpers/webcast_online_helper.py
- src/backend/common/manipulators/match_manipulator.py
- src/backend/common/manipulators/tests/match_manipulator_test.py
- src/backend/common/memcache_models/event_nexus_queue_status_memcache.py
- src/backend/common/memcache_models/memcache_model.py
- src/backend/common/models/event_queue_status.py
- src/backend/common/tasklets.py
- src/backend/tasks_io/datafeeds/datafeed_nexus.py
- src/backend/tasks_io/datafeeds/nexus_api.py
- src/backend/tasks_io/datafeeds/parsers/nexus_api/queue_status_parser.py
- src/backend/tasks_io/handlers/live_events.py
- src/backend/tasks_io/handlers/nexus_api.py
- src/cron.yaml
This will add a cronjob that fetches the queue data from nexus.
We also get it updated in firebase, in both the live event status, and the per-match objects.
> Ingest Event Queue Status / Predicted Times from Nexus

- src/backend/common/queries/insight_query.py
Some stale leaderboards are showing up in API responses and I think this may resolve it
> Bump leaderboard insight query cache version

- src/backend/common/helpers/firebase_pusher.py
- src/backend/common/helpers/tests/firebase_pusher_test.py
- src/backend/common/manipulators/match_manipulator.py
- src/backend/common/manipulators/tests/match_manipulator_test.py
- src/backend/tasks_io/handlers/live_events.py
- src/backend/tasks_io/handlers/nexus_api.py
This didn't make sense to hang off of `MatchManipulator`, because the two data sources are updated independently. Instead, use Firebase's ability to merge specific dict keys and update it as part of the nexus fetch
> [nexus] Patch queue status into firebase outside of Match Manipulator

- src/backend/common/cache/cache_if.py
- src/backend/common/cache/gae_builtin_cache.py
- src/backend/common/cache/noop_cache.py
- src/backend/common/cache/tests/test_gae_builtin_cache.py
- src/backend/common/helpers/firebase_pusher.py
- src/backend/common/helpers/tests/webcast_online_helper_test.py
- src/backend/common/helpers/webcast_online_helper.py
- src/backend/common/memcache_models/memcache_model.py
- src/backend/common/memcache_models/webcast_online_status_memcache.py
- src/backend/tasks_io/handlers/live_events.py
- src/backend/web/handlers/admin/authkeys.py
- src/backend/web/handlers/admin/event.py
- src/backend/web/handlers/admin/tests/authkeys_test.py
- src/backend/web/templates/admin/authkeys.html
- src/backend/web/templates/admin/event_details.html
A series of things I noticed while working in this code:
- move the webcast status to be backed by a `MemcacheModel`, to leverage the abstraction here
- support async get/set in `MemcacheModel`
- clean up the async-ificatoin of all the webcast status fetching, which should hopefully increase the parallelism here
- show webast online status from memcache in the admin panel + a way to refresh it (since it has a pretty short TTL)
> Clean up webcast status fetching

- src/backend/common/helpers/match_time_prediction_helper.py
- src/backend/common/helpers/tests/match_time_prediction_helper_test.py
- src/backend/tasks_io/handlers/live_events.py
- src/backend/web/handlers/admin/event.py
- src/backend/web/jinja2_filters.py
- src/backend/web/templates/admin/event_details.html
In situations where we have an estimated match start time from nexus, use that as the match "predicted time". This should help minimize confusion with different sources showing conflicting information.
If the data isn't available, or is stale, then we can fall back to the existing time predictions.
> [nexus] Use predicted times where available 

- src/backend/common/helpers/tests/youtube_video_helper_test.py
- src/backend/common/helpers/youtube_video_helper.py
this was never updated to support `sf\d\dm\d` formats
> update youtube playist parser for double elim keys

- src/backend/tasks_io/handlers/frc_api.py
- src/backend/tasks_io/handlers/tests/frc_api_awards_test.py
- src/cron.yaml
Instead of waiting an hour before looking for awards, this PR fetches them every 10 minutes only on the last day of an event.
For FRCLocks.com we'd like to get award information from the TBA API sooner. It currently can take up to an hour after awards are updated for them to appear. This means that teams who want to see if they qualify for the district championship can't see that until well after an event is over and they are on their way home.
This year we've also seen some events upload certain awards while the playoffs are still progressing, and we'd like to see those reflected on API sooner too.
The unit tests here are based off of the ones for getting alliance selection data on the day of the event.
> Schedules award scrapes more frequently on the last day of events

- src/backend/common/helpers/firebase_pusher.py
- src/backend/common/tasklets.py
- src/backend/tasks_io/handlers/regional_advancement_api.py
This updates the `typed_tasklet` decorator to use modern python's `ParamSpec` (instead of the original experimental pyre one), and fixes some bugs along the way
> fix typed_tasklet type hints

- src/backend/api/handlers/tests/update_event_info_test.py
- src/backend/common/helpers/tests/webcast_helper_test.py
- src/backend/common/helpers/webcast_helper.py
Updates the regex for parsing YouTube webcasts to support the alternative `https://youtube.com/live/video-id?si=tracking-id` URL
This is the format that YouTube gives you when you share a livestream, currently to add a YouTube webcast you have to modify the URL to match one of the expected formats
Tested with regexr
> Add additional URL formats to YouTube webcast parser

- src/backend/common/helpers/event_short_name_helper.py
- src/backend/common/helpers/tests/event_short_name_helper_test.py
Currently the "presented by" is in the short name for New England DCMP Divisions.
This makes the short names match how they look for other years, and aligns removing the "presented by" text like is done for regionals or other events.
A unit test was added for this case
This is how it looks right now:
And this is how it looked in 2024:
> Updates short names for 2025 DCMP divisions

- src/frontend/liveevent/components/UpcomingMatchesTable.js
If a match is predicted to happen immanently, and we have queuing status from nexus, display that
eg:
> show queue status from nexus in upcoming match table

- src/backend/common/helpers/event_insights_helper.py
- src/backend/web/templates/event_partials/event_insights_2025.html
Corrects the 6RP statistic to count only for the winning alliance, adds a 9RP statistic to show the number of matches where all 9RP were achieved
Resolves #7441
Local TBA instance with 2025pncmp data.
> Fix 2025 ranking point statistics

- src/frontend/gameday2/components/PlatformIcon.js
- src/frontend/gameday2/components/WebcastSelectionDialog.js
- src/frontend/gameday2/components/WebcastSelectionDialogItem.js
- src/frontend/gameday2/components/icons/TwitchIcon.js
- src/frontend/gameday2/components/icons/YouTubeIcon.js
Adds icons for YouTube and Twitch streams to the webcast selector in GameDay. Other live streaming platforms will not show an icon but still be aligned with other streams that do have one.
Implements a suggestion [discussed in Slack](https://the-blue-alliance.slack.com/archives/C15SUFL92/p1744167915448729?thread_ts=1744167594.938749&cid=C15SUFL92), this allows users to see at a glance which streaming platform a webcast is using.
Tested locally using a local version of Firebase. Would definitely appreciate a maintainer taking a good look at this since I had to stub out some of the Twitch/YouTube online status stuff to get it running!
> Add YT and Twitch icons to GameDay

- src/backend/tasks_cpu/handlers/insights.py
Adds an endpoint that can be used to delete insights, as currently there's no way to do it besides going into GAE console and manually doing it.
This does it by name, so all years attached to a name will be deleted.
> Add insight delete task endpoint

- pwa/app/api/v3.ts
- pwa/app/lib/utils.tsx
- pwa/generate-api.sh
- src/backend/web/static/swagger/api_v3.json
Not all events have timezone information. Additionally, the District model is named `District_List` which is a little wonky.
> Mark APIv3 Event.timezone as nullable. Rename District_List to District

- src/frontend/gameday2/selectors/index.js
- src/frontend/liveevent/components/LiveEventPanel.js
2025cur still has f1m3 in Firebase (unsure why - possibly because sf3m2 happened). This is missing the comp_level/set_number/match_number fields (c/s/m in Firebase), so this match's sort order on the frontend gets calculated as `NaN`, which breaks the sorting of everything. Because matches are returned from Firebase in alphabetical order, in practice this means that semifinals end up displayed last.
This does not fix the issue of sf3m2 sorting after sf13m1 (a remnant of the old single-elim bracket) - that is a separate (maaaybe related) issue that likely warrants a bit more discussion.
Local with `2025cur`. Also confirmed no regressions on `2025dal`.
Before:
<details>
</details>
After:
<details>
</details>
> LiveEventPanel/gameday: fix issue where lingering unplayed matches could break sort order

- src/backend/api/handlers/decorators.py
- src/backend/api/handlers/tests/add_event_media_test.py
- src/backend/api/handlers/tests/add_match_video_test.py
- src/backend/api/handlers/tests/trustedapi_auth_test.py
- src/backend/api/handlers/trusted.py
- src/backend/api/trusted_api_auth_helper.py
- src/backend/common/consts/event_code_exceptions.py
- src/backend/common/models/event.py
- src/backend/tasks_io/datafeeds/parsers/fms_api/fms_api_event_list_parser.py
This will take away an annual headache we have to do; this will allow FIRST to post videos using the full division name keys (which match frc-events) and not need to maintain their own list of overrides.
> Resolve CMP division overrides in truted API

- pwa/app/routes/event.$eventKey.tsx
Awards and Insights tabs were showing up on future events. This fixes that
> [pwa] fix awards and insights tab buttons showing up on not-yet-started events

- src/backend/common/helpers/insights_leaderboard_team_helper.py
- src/backend/common/models/insight.py
Adds longest qualifying event win streak insight. Qualifying events are districts or regionals.  It excludes DCMP and CMP.
> Add longest qualifying event win streak insight

- src/backend/api/handlers/client_api.py
- src/backend/api/handlers/tests/client_api_ping_test.py
- src/backend/common/helpers/tbans_helper.py
- src/backend/common/helpers/tests/tbans_helper_test.py
- src/backend/common/models/notifications/requests/tests/webhook_request_test.py
- src/backend/common/models/notifications/requests/webhook_request.py
- src/backend/web/handlers/account.py
- src/backend/web/handlers/tests/account_test.py
- src/backend/web/templates/apidocs_webhooks.html
Two changes here -
First one is part of the arc of work to increase reliability of our webhooks. No idea why, but I was treating webhooks similarly to FCM clients where we'd pass an array and process them all in one go. This obviously doesn't scale if we're trying to process data to all our webhooks within a single 30s GAE request. This now breaks each webhook request into it's own task. The urlfetch (moved back to urlfetch from requests - possibly to tie into the ndb context in the future for all this work - we'll see) has a default timeout of 10s. This has been updated in the webhook docs.
Second - the `ping` endpoint now has two response values - a `success` (did we throw an error) and a `valid` (which covers whatever our logic will be for a valid/invalid response). A single boolean …
> Dispatch webhooks individually. Update ping to have success and valid booleans.

- src/backend/api/handlers/district.py
- src/backend/api/handlers/tests/district_test.py
Some of the district API endpoints were missing validation. This adds them + adds a little test for validating them.
> Add validation to some District API endpoints

- .github/dependabot.yml
Should reduce the number of separate dependabot PRs we get and also reduce some merge conflicts by updating things together.
> Update pwa dependabot groups

- pwa/app/api/v3.ts
- src/backend/api/handlers/district.py
- src/backend/api/main.py
- src/backend/web/static/swagger/api_v3.json
This is useful for an upcoming PWA page and saves a great deal of unnecessary requests when trying to get a historical view of DCMP.
Returns an array of objects, where each object has an event and an array of awards. Each object represents a DCMP event or DCMP division.
> Add new DCMP event/awards history endpoint

- pwa/app/api/tba/@tanstack/react-query.gen.ts
- pwa/app/api/tba/sdk.gen.ts
- pwa/app/api/tba/types.gen.ts
- pwa/app/api/tba/zod.gen.ts
- src/backend/api/handlers/district.py
- src/backend/api/main.py
- src/backend/common/consts/insight_type.py
- src/backend/common/consts/renamed_districts.py
- src/backend/common/helpers/insights_districts_helper.py
- src/backend/common/helpers/insights_helper.py
- src/backend/common/helpers/insights_helper_utils.py
- src/backend/common/models/insight.py
- src/backend/common/queries/insight_query.py
- src/backend/tasks_cpu/handlers/insights.py
- src/backend/tasks_cpu/templates/math/year_insights_do.html
- src/backend/web/static/swagger/api_v3.json
Adds district-specific insights.
There are a handful of district-specific spreadsheets floating around that all basically do the same thing - a generic overview of their district's stats, all pulled from TBA and compiled. It would make sense to simply integrate these into TBA; this does that.
Because of json field size constraints, district insights are split into 2 insights: team data and district data. Team info contains team-specific info like average district points earned by a given team. District info contains info like retention, growth, event count, etc.
These are not added to cron here; they will be in a future PR once these insights are known to function on prod.
> Add district-specific insights

- .github/workflows/pull_request.yml
Fails if the PWA API needs to be regenerated
Example failure: https://github.com/the-blue-alliance/the-blue-alliance/actions/runs/15469172612/job/43548776238?pr=7781
Example success: https://github.com/the-blue-alliance/the-blue-alliance/actions/runs/15469256923/job/43549064131?pr=7781
> Add PWA API regeneration CI

- .github/workflows/pull_request.yml
Linting is erroring on API regeneration because it can't find the (not generated) react router types
> Fix PWA linting on CI

- pwa/app/api/tba/read/types.gen.ts
- pwa/app/api/tba/read/zod.gen.ts
- src/backend/web/static/swagger/api_v3.json
Apparently on social media, `details` can also just be an empty object (`{}`)
> Fix media details in api spec

- .github/workflows/pull_request.yml
- .github/workflows/pull_request_target.yml
- .github/workflows/push.yml
Dependabot can't access secrets on `pull_request`, only `pull_request_target`.
https://github.com/dependabot/dependabot-core/issues/3253
> Add PWA E2E dependabot version

- .github/workflows/push.yml
- ops/dev/vagrant/dev_appserver.sh
- ops/test_vagrant_startup.py
- src/backend/tasks_cpu/handlers/insights.py
- src/backend/tasks_cpu/handlers/tests/insights_test.py
- src/backend/tasks_cpu/handlers/typeahead.py
- src/backend/web/templates/admin/tasks.html
- src/cron.yaml
- src/dispatch.yaml
- src/tasks_cpu_enqueue.yaml
Handle `/backend-tasks-b2/enqueue/*` and `/backend-tasks-b2/do/*` on separate instance types since `tasks-cpu` doesn't autoscale.
Replaces #7891
> Separate enqueue/do handlers for CPU tasks

- src/backend/common/helpers/insights_leaderboard_team_helper.py
Semi-experimental. Calling `prep_awards_matches_teams()` on all events within a year before processing shouldn't significantly allocate memory.
> Prefetch event data when processing insights

- src/backend/common/helpers/insights_districts_helper.py
These break an upcoming PWA feature that shows district growth by region. Teams such as 8393 are shown as being a part of FIM, but being in PA (their current location). This PR omits them from growth data entirely
> Add exceptions for district insight calculations

- src/cron.yaml
New enqueue logic & backend task queue makes spreading out start times unnecessary.
> Condense cron start times

- src/backend/api/api_trusted_parsers/json_event_info_parser.py
- src/backend/api/handlers/tests/update_event_info_test.py
- src/backend/api/handlers/tests/update_event_rankings_test.py
- src/backend/api/handlers/trusted.py
- src/backend/web/static/swagger/api_trusted_v1.json
Two things:
- Support setting the event timezone via the trusted API
- add test coverage specifically for posting rankings with `sortN` key names (which is how FMS stores them)
> Support Event Timezone in trusted API

- src/backend/api/api_trusted_parsers/json_matches_parser.py
- src/backend/api/handlers/tests/update_event_matches_test.py
- src/backend/api/handlers/trusted.py
- src/backend/web/static/swagger/api_trusted_v1.json
Supports `actual_start_time` and `post_result_time` being set
> Support additional match timestamps in trusted API

- pwa/app/components/ui/tooltip.tsx
Tailwind primary color changed to blue which made tool tips pretty unreadable.
- Updated colors for component
- Added a scroll bar for tool tips that are above a certain size for massive lists of teams for insights page that made things unreadable
- Fixed some weird text centering + better dropshadow
Reading tool tips is good
Looks actually readable on insights page, checked a bunch of different usages and seems to work fine.
> [PWA] Visual fixes for tool tips

- src/backend/api/api_trusted_parsers/json_event_info_parser.py
- src/backend/api/handlers/tests/update_event_info_test.py
- src/backend/api/handlers/trusted.py
- src/backend/common/consts/event_sync_type.py
- src/backend/common/models/event.py
- src/backend/common/models/tests/event_test.py
- src/backend/tasks_io/datafeeds/datafeed_fms_api.py
- src/backend/tasks_io/datafeeds/parsers/fms_api/tests/test_fms_api_match_tiebreaker.py
- src/backend/tasks_io/datafeeds/tests/datafeed_fms_api_event_matches_test.py
- src/backend/tasks_io/handlers/frc_api.py
- src/backend/tasks_io/handlers/tests/frc_api_awards_test.py
- src/backend/tasks_io/handlers/tests/frc_api_event_alliances_test.py
- src/backend/tasks_io/handlers/tests/frc_api_event_rankings_test.py
- src/backend/web/handlers/admin/event.py
- src/backend/web/static/swagger/api_trusted_v1.json
- src/backend/web/templates/admin/event_details.html
- src/backend/web/templates/admin/event_edit.html
This is a feature we'll want to be controlled by the TBA companion, so for example, if they run custom playoffs, they can turn off pulling from the API to avoid the test-match results getting clobbered.
> Support disabling indivdual parts of sync

- src/backend/common/helpers/season_helper.py
- src/backend/common/helpers/tests/season_helper_test.py
Updates the `kickoff_datetime_est` for 2026 and onward to have kickoff occur on the *second* Saturday after January 2nd.
> Update `kickoff_datetime_est` for 2026 (and onward?)
